### ISSUE TITLE
add_int() error: integer out of range for 'I' format code

### ISSUE THREAD

**Issue by int-0** [paramiko/paramiko#1005]
Hi,
I've written a simple sshv2 server proxy and I have a code like:
```python
status = ep1.recv_exit_status()
ep2.send_exit_status(status)
```
Where _ep1_ and _ep2_ are _Channel()_ objects. Sometimes (with X11 channels, after closing remote app like _xeyes_ or something, it happens often) _recv_exit_status()_ returns a **-1** value. This status code is sended with _send_exit_status()_ and it fails because _add_int()_ (at _messages.py_) method causes a _struct.error_ exception. This exception is raised because **-1** cannot be packed with **">I"**. I've changed **">I"** and **">Q"** by **"i>"** and **">q"** at _messages.py_ and the error seems doesn't occurs anymore, also connections with open-ssh servers still working fine (tty channels, X11 channels, scp, etc.). I've checked the open-ssh code and they uses _uint_ so my question is: how it's possible to get a **-1** value with _recv_exits_status()_ function?, if I get a negative value, should I convert to _uint_ before call _send_exit_status()_?.

Thank you!

**Comment by ploxiln** [comment]
`-1` does not really make sense for an exit status. I'm not sure what it means for `recv_exit_status()`, I'd have to do some research to find out.

https://docs.python.org/2/library/sys.html?highlight=sys.exit#sys.exit says
> Most systems require it to be in the range 0–127, and produce undefined results otherwise.

If you look up `man waitpid` on macOS or Linux you'll see some macros to interpret the exit status of processes, including:
> WEXITSTATUS(status): If WIFEXITED(status) is true, evaluates to the low-order 8 bits of the argument passed to _exit(2) or exit(3) by the child.

(that would imply a value between 0 and 255, which is what I previously thought was the typical constraint)

There is a separate way that a "signal which caused termination" can be encoded:
> WTERMSIG(status): If WIFSIGNALED(status) is true, evaluates to the number of the signal that caused the termination of the process.

I'm not sure how that is encoded. But python's subprocess docs say https://docs.python.org/2/library/subprocess.html?highlight=subprocess#subprocess.Popen.returncode
> A negative value -N indicates that the child was terminated by signal N (Unix only).

Signal 1 is SIGHUP, I guess that's plausible ... but I still suspect `-1` might stand for a more generic failure of some sort in this remote-process-over-ssh case.

**Comment by int-0** [comment]
I can reproduce the error opening a "ssh -Y" connection through my proxy and running xeyes. When I close the window most of the times it fails (yep, not always!).

Thank you!

**Comment by ploxiln** [comment]
For your purposes, I'd suggest `ep2.send_exit_status(status % 256)` - that will turn -1 into 255 (and all other values will be translated into the range 0 - 255).

**Comment by ploxiln** [comment]
Ah - note that `Channel.recv_exit_status()` docs say
> If no exit status is provided by the server, -1 is returned

and the Channel.exit_status attribute defaults to -1. So, to be as "faithful" a proxy as possible, if you get "-1", you could try just not sending an exit status at all, before closing the channel.

**Comment by int-0** [comment]
Oh man... so probably if I get -1 I can ignore the value and don't send anything...

Sorry for the spam!

**Comment by ploxiln** [comment]
No problem, it was a tricky and interesting question!
