### ISSUE TITLE
paramiko.transport: Exception: Error reading SSH protocol banner[Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by AlfredChenxf** [paramiko/paramiko#1006]
Test Env:
Python 2.7.13
Paramiki 2.2.1
Mac OS X 10.12.5

`66618 DEB [20170626-10:06:55.200] thr=44  paramiko.transport: starting thread (client mode): 0x7e72290L
66619 DEB [20170626-10:06:55.200] thr=44  paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.2.1
66620 ERR [20170626-10:06:55.200] thr=44  paramiko.transport: Exception: Error reading SSH protocol banner[Errno 54] Connection reset by peer
66621 ERR [20170626-10:06:55.203] thr=44  paramiko.transport: Traceback (most recent call last):
66622 ERR [20170626-10:06:55.203] thr=44  paramiko.transport:   File "/tmp/virtualenv/hypersonic/lib/python2.7/site-packages/paramiko/transport.py", line 1805, in run
66623 ERR [20170626-10:06:55.204] thr=44  paramiko.transport:     self._check_banner()
66624 ERR [20170626-10:06:55.204] thr=44  paramiko.transport:   File "/tmp/virtualenv/hypersonic/lib/python2.7/site-packages/paramiko/transport.py", line 1957, in _check_banner
66625 ERR [20170626-10:06:55.204] thr=44  paramiko.transport:     'Error reading SSH protocol banner' + str(e)
66626 ERR [20170626-10:06:55.204] thr=44  paramiko.transport: SSHException: Error reading SSH protocol banner[Errno 54] Connection reset by peer
66627 ERR [20170626-10:06:55.204] thr=44  paramiko.transport:`

**Comment by bebee** [comment]
i have same issues

**Comment by AlfredChenxf** [comment]
This issue is caused by the limitation of concurrent ssh users on Mac, the default value is 42.
Increase the value can fix this issue.

**Comment by iamaziz** [comment]
Hey @AlfredChenxf where/how did you increase the value to solve the issue?

**Comment by AkashAgr1910** [comment]
Use this command 

/usr/bin/sudo /usr/bin/sed -i.bak 's/^[\#]*MaxSessions.*/MaxSessions 20/' /etc/ssh/sshd_config
