### ISSUE TITLE
AttributeError: 'EllipticCurvePublicNumbers' object has no attribute 'encode_point'

### ISSUE THREAD

**Issue by tkyang99** [paramiko/paramiko#1007]
File "/home/ubuntu/.local/lib/python2.7/site-packages/pysftp/__init__.py", line 143, in __init__
    self._transport.connect(**self._tconnect)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/transport.py", line 1123, in connect
    self.start_client()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/transport.py", line 510, in start_client
    raise e
AttributeError: 'EllipticCurvePublicNumbers' object has no attribute 'encode_point'

**Comment by ploxiln** [comment]
It looks like `EllipticCurvePublicNumbers.encode_point()` was added in Cryptography 1.1 - https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#11---2015-10-28

Can you confirm that you have an older version of python module "cryptography" installed?

**Comment by ploxiln** [comment]
Can you also confirm the version of paramiko you are running?

**Comment by ploxiln** [comment]
... it looks like paramiko 2.x has always explicitly required cryptography>=1.1 in setup.py

**Comment by tkyang99** [comment]
Running "sudo pip install cryptography --upgrade" seems to have solved the problem for me.
Thank you!!
