### ISSUE TITLE
How to deal with New line Character windows vs Unix

### ISSUE THREAD

**Issue by just10minutes** [paramiko/paramiko#1010]
Hi,

I did read the [disclaimer about Windows support,](http://www.paramiko.org/faq.html) but this might be an problem only at my end, so just to be sure i am posting this.

Currently I am doing below task.

Create a small File in Windows using python
Transfer this file to Remote Unix environment using Paramiko python library SFTP module
Problem faced:

Newline created on Windows is not properly converted to unix new line character during the transfer. I see ^M character inside the file on my remote host.

Any idea or suggestion how can i get rid of this behaviour.

When I do the transfer of the same file using WinScp i do not face this problem. I guess winscp has built in capability to handle this.

python version used 3.5

Step1:

```
with open(myNewFile.txt,'w') as fileToUpload:
    fileToUpload.write('MyOwnTxt'+'\n')
```
Step2:

    COMP = remoteServerHost
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(COMP, username=user, password=password, allow_agent = False)
    src = myNewFile.txt
    dst = "/remotePath/myNewFile.txt"
    ftp = ssh.open_sftp()
    ftp.put(src , dst)
    ftp.close()
    ssh.close()
I am little surprised because no one has specified this problem in any other forum. So it makes me feel is there something wrong on my Windows Machine :(

**Comment by bitprophet** [comment]
There's nothing about SFTP (the transfer method used here) or Paramiko itself that would perform line-ending transformations automatically, it just uploads the bytes directly.

So I'd guess you're right that WinSCP might be performing that on your behalf, which is leading to this confusion.

Re: solution: a quick Google finds [this StackOverflow thread](https://stackoverflow.com/questions/2536545/how-to-write-unix-end-of-line-characters-in-windows-using-python) noting multiple ways you can force Python-on-Windows to _not_ write out "Windows style" newlines. So this would let you get a file with Unix-style newlines which would then work correctly post-transfer.

**Comment by just10minutes** [comment]
@bitprophet  Thanks a lot for your suggestion. Looks like I need to follow this, I do not have any other option.

But In order to use any existing Unix file on Windows after transfer or vice versa  I might have to create a small script which can perform New line replacement based on system. This snippet has to run after the transfer.

Thanks

**Comment by ploxiln** [comment]
"text transfer mode" which does this conversion was a very common feature in FTP clients, which I think inspired this functionality in WinSCP (along with "binary transfer mode" which does no conversion and is usually the better way to go). openssh scp, rsync, etc do not have this feature. I think paramiko would not be a good place to put this functionality.

You may also be interested in the "dos2unix" utility, available in most linux package managers and homebrew for macOS.

**Comment by just10minutes** [comment]
@ploxiln  Thank you for your valuable feedback. I understand the concept now why Winscp does this.

I read somewhere someone has developed a scp module using Paramiko as base, I will just have to test it if that has the facility built in to convert to text.

Thank you.
