### ISSUE TITLE
demo.py issues a false positive warning about an unknown host key

### ISSUE THREAD

**Issue by CrazyPython** [paramiko/paramiko#1017]
In Terminal: (note that there is no known_hosts warning)
```zsh
$ ssh 52.233.XXX.XX
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-78-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
```

in `~/.ssh.known_hosts`:
```
52.233.XX.XX ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBI23aBpnzlKz96Q80qpVO8JDxpBvoNxT+KhiFf6zcf4Q+6TDtCue2zLOZZEyRJ7iQHC7zd2lXe2lOCOc1CczKGk=
```

But invoking demo.py results in `*** WARNING: Unknown host key!`.

Preliminary investigation shows that paramiko successfully finds the `known_hosts` file.

(last five digits of IP address changed to Xes to maintain firewall)

--- 

macOS Sierra 10.12.5
Python 3.6.1

**Comment by ploxiln** [comment]
The issue is here: https://github.com/paramiko/paramiko/blob/2.2.1/demos/demo.py#L122

because the demo uses Transport directly but does not negotiate for the key type present in `known_hosts` like SSHClient does for you here: https://github.com/paramiko/paramiko/blob/2.2.1/paramiko/client.py#L361

**Comment by ploxiln** [comment]
It would be nice to update `demo.py` to show better use of the APIs ... pull requests welcome I presume ;)

**Comment by bitprophet** [comment]
I almost want to just remove all demos with links to Fabric (2), honestly... 😭
