### ISSUE TITLE
SSHException: Server not found in known_hosts and PasswordRequiredException: Private key file is encrypted

### ISSUE THREAD

**Issue by tsando** [paramiko/paramiko#1019]
Hi,

I am getting this error:

```
---------------------------------------------------------------------------
SSHException                              Traceback (most recent call last)
<ipython-input-1-40609d5a064d> in <module>()
      3 ssh = SSHClient()
      4 ssh.load_system_host_keys()
----> 5 ssh.connect('XX.XXX.XX.XXX')

C:\Apps\Anaconda3\lib\site-packages\paramiko\client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_
agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout)
    371                 # will raise exception if the key is rejected
    372                 self._policy.missing_host_key(
--> 373                     self, server_hostkey_name, server_key
    374                 )
    375             else:

C:\Apps\Anaconda3\lib\site-packages\paramiko\client.py in missing_host_key(self, client, hostname, key)
    698         client._log(DEBUG, 'Rejecting %s host key for %s: %s' %
    699                     (key.get_name(), hostname, hexlify(key.get_fingerprint())))
--> 700         raise SSHException('Server %r not found in known_hosts' % hostname)
    701
    702

SSHException: Server 'XX.XXX.XX.XXX' not found in known_hosts
```

when I run:

```
import paramiko
from scp import SCPClient

ssh = paramiko.SSHClient()
ssh.load_system_host_keys()
ssh.connect('XX.XXX.XX.XXX')
```

And even if I add `ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())`, I get a different type of error:

`PasswordRequiredException: Private key file is encrypted`

yet my key doesn't have a password, so I can't provide a password as argument to `ssh.connect`.

Any ideas of what could be wrong? I thought `ssh.load_system_host_keys()` would solve this problem...

Btw, I'm using version `paramiko==2.2.1`
 
Thanks for your help.

**Comment by bitprophet** [comment]
The two errors are not related, FWIW, the first one you'll always get unless you use the policy that you ended up using, or if your `~/.ssh/known_hosts` actually contains the target host's key already (which presumably it doesn't.)

The second error may mean your key type isn't supported yet (it's currently hard for Paramiko to tell the difference between an unsupported or invalid key format and an encrypted key), what type of key is it exactly?

**Comment by Addvilz** [comment]
I can confirm there is some sort of devious issue at works here.

paramiko 2.2.1 on fresh 16.04.

What I did:

- Created a new remote machine
- Tried to connect without auto add policy
- Got `paramiko.ssh_exception.SSHException: Server 'xxx' not found in known_hosts`
- Added auto add policy
- Tried to connect again, but got `PasswordRequiredException`

Here's the fun part:

- Everything worked just fine yesterday, however, I did in fact add yesterdays test host I used to known_hosts by ssh-client, so this clearly changed things
- I later removed known_hosts from ~/.ssh to see what happens, and with auto add policy, the host file is not created
- I created empty known hosts, it is not modified with auto add policy
- Permissions on .ssh and all files within are 0700, as usual
- ssh-agent is up and running

```
Traceback (most recent call last):
  [...]
    client.connect(host, username='root')
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 394, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 649, in _auth
    raise saved_exception
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted
```
Fresh install 16.04 LTS.

**Comment by Addvilz** [comment]
I figured what the issue is. I forgot to add my pubkey to the machine on deployment, and did not log in to it using ssh-client this time, just tried to add the key ssh-keyscan which clearly succeeded, but paramiko failed because no password was set, just user keys.

This is still a small issue, as the exception being thrown is misleading at best.

**Comment by bitprophet** [comment]
Thanks for reporting back.

Re: exception misleading: yes, we're aware, very long standing issue - I even alluded to it above :)

> (it's currently hard for Paramiko to tell the difference between an unsupported or invalid key format and an encrypted key)

Work's in the pipe for this though.

**Comment by Addvilz** [comment]
Well, it's misleading to say the least, key has nothing to do with this at all. Paramiko should probably parse supported authentication methods and report back if no password is set and pubkey auth is not supported. 

So this is not really the same issue.
