### ISSUE TITLE
import return a ValueError:'ciphers' in __slots__ conflicts with class variable

### ISSUE THREAD

**Issue by hamilton-z** [paramiko/paramiko#103]
I downloaded paramiko1.8.0, running 2to3.py convert all py files and run python setup.py install .after the installation was successful, but get the following error when import:

> > > Import paramiko
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File ". \ Paramiko \ **init**.py", line 69, in <module>
> > >     from. transport import SecurityOptions, Transport
> > >   File ". \ Paramiko \ transport.py", line 66, in <module>
> > >     class SecurityOptions (object):
> > > ValueError: 'ciphers' in __ slots__ conflicts with class variable

how can i solve it? my python is 3.3

**Comment by ankitpatnaik** [comment]
Was there a fix to this issue??

**Comment by ploxiln** [comment]
> I downloaded paramiko1.8.0, running 2to3.py convert all py files

All currently supported branches of paramiko support python3 without any changes. This issue is no longer relevant.
