### ISSUE TITLE
DeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.

### ISSUE THREAD

**Issue by singhaniashrinkhala** [paramiko/paramiko#1030]
Hi,

I have paramiko version 2.2.1 on CentOs6.5

On running a python script, which tries to connect to a network device using paramiko, I get the following error:

```
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
/usr/lib/python2.6/site-packages/paramiko/rsakey.py:128: DeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  algorithm=hashes.SHA1(),
```

Could someone explain to me what "Please use sign and verify instead" means?

**Comment by ploxiln** [comment]
it's a warning for the authors of paramiko, not for you
see #979

**Comment by singhaniashrinkhala** [comment]
@ploxiln :right, but it doesn't connect to the device. I am trying to ssh to a Cisco Nexus box, which is now failing. On paramiko version 1.7.5, I was getting this error on the client: 
```
paramiko.SSHException: Incompatible ssh peer (no acceptable kex algorithm)
```
On the device end, 

```
2017 Aug  1 22:30:56.997 nexys %DAEMON-2-SYSTEM_MSG: fatal: Unable to negotiate with 10.10.10.1 port 37211: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1 - dcos_sshd[27357]
```

So, I upgraded the paramiko. After upgrading, I only get the warning as stated in the issue.

**Comment by ploxiln** [comment]
If it did not work, the `DeprecationWarning` is not why it did not work. You'll want to enable debug logging for paramiko to help you figure out what's happening.

You should also know that paramiko methods like `exec_command()` usually don't work for things like cisco switches. http://www.paramiko.org/faq.html

**Comment by singhaniashrinkhala** [comment]
@ploxiln : Thanks for pointing that out. I will probably switch to a different package then.

**Comment by nkfilis** [comment]
is the DeprecationWarning fixed or will it be?
