### ISSUE TITLE
Fix example for forwarding agent

### ISSUE THREAD

**Issue by fedordikarev** [paramiko/paramiko#1034]
`Client` should be used for `exec_command`, not `session`.

> diff --git a/paramiko/agent.py b/paramiko/agent.py
> index bc857ef..c8fa4f0 100644
> --- a/paramiko/agent.py
> +++ b/paramiko/agent.py
> @@ -317,7 +317,7 @@ class AgentRequestHandler(object):
>          AgentRequestHandler(session)
>          # Commands executed after this point will see the forwarded agent on
>          # the remote end.
> \-        session.exec_command("git clone https://my.git.repository/")
> \+        client.exec_command("git clone https://my.git.repository/")
>      """
>      def __init__(self, chanClient):
>          self._conn = None

**Comment by ploxiln** [comment]
please open a pull request

**Comment by fedordikarev** [comment]
#1036
