### ISSUE TITLE
Server/Client key pair

### ISSUE THREAD

**Issue by masoudr** [paramiko/paramiko#1035]
Hi,
I created a simple server/client example with `paramiko `and `python3`. I want to authorize client with server key. I used the `demo_server `example. I successfully run the server but in my client, I can't authorize with the server. I generated the server's public key (key in the code) with `puttygen `and saved the private key file as `server_private_keyfile`. My problem is I don't know which key must be used in the client? Here is the procedure I used:

Server.py:
```
class paramiko_Server (paramiko.ServerInterface):
    key=b'AAAA....'
    data=base64.b64encode(key)
    good_pub_key = paramiko.RSAKey(data=decodebytes(key))

    def __init__(self):
        self.event = threading.Event()

    def check_auth_publickey(self, username, key):
        print('Auth attempt with key: ' + u(hexlify(key.get_fingerprint())))
        if (username == 'root') and (key == self.good_pub_key):
            return paramiko.AUTH_SUCCESSFUL
        return paramiko.AUTH_FAILED
        return paramiko.AUTH_SUCCESSFUL
    def main():
    ....
    keyfile='server_private_keyfile'
    host_key = paramiko.RSAKey.from_private_key_file(keyfile)
    transport.add_server_key(host_key)
```

Client.py
```
host_key = paramiko.RSAKey.from_private_key_file('client_private_keyfile')
ss = paramiko.SSHClient()
ss.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ss.connect('localhost',22,username='root',pkey = host_key,timeout=4)
...
```
Edit:
I test the client with `server_private_keyfile` and I can successfully connect to the server. But I think it is not a good idea to give client the server private key file, am I right? Is there any way to generate private key file in client?
Thanks.

**Comment by ploxiln** [comment]
"Host keys" and "Auth keys" are separate keys.

For the "Host key", the server has the private and public key, and the client just has the public key. It typically just gets the public key from the server, the first time it contacts that server, in a simple scheme referred to as "trust on first use" or "TOFU". After that, the client requires the server to have the private key corresponding to the public key the client has for that hostname.

For the "Auth key", the client has the private key, and the server has the public key. They must both be in place ahead of time. The server requires the client to have the private key corresponding to the public key the server has for that user.

Two separate keys.

**Comment by masoudr** [comment]
Thanks for the answer, I got that, but how can I implement this?
In the above example, I can only use `server private key` file for the client to authorize with the server.
In the above example, I only use a key pair, the public key used for the server (`good_pub_key `file) and a private key which generated from that public key and it used in server and client. So you mean this key pair is only `host key` right? and it doesn't require to give `Auth key` in my code?

**Comment by ploxiln** [comment]
You need two key pairs. Only the server has the private part of the host key pair. Only the client has the private part of the auth key. In `check_auth_publickey()` the server checks with the public part of the client's auth key pair. For `add_server_key()` it specifies the private part of the host key pair.

With `AutoAddPolicy` all the client needs is the private part of the auth key.

**Comment by masoudr** [comment]
Thank you very much, I followed your procedure and my problem solved.
