### ISSUE TITLE
Exception: Error reading SSH protocol banner

### ISSUE THREAD

**Issue by hellorocky** [paramiko/paramiko#1038]
I used paramiko as a ssh server, sometimes meet this error, and my users hang up in the terminal.

ERROR|2017-08-08 20:49:50|15292|transport.py:1636|Exception: Error reading SSH protocol banner
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|Traceback (most recent call last):
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/transport.py",
 line 1952, in _check_banner
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|    buf = self.packetizer.readline(timeout)
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/packet.py", li
ne 353, in readline
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|    buf += self._read_timeout(timeout)
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/packet.py", li
ne 546, in _read_timeout
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|    raise socket.timeout()
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|socket.timeout
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|During handling of the above exception, another exception occurred:
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|Traceback (most recent call last):
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/transport.py",
 line 1805, in run
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|    self._check_banner()
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|  File "/home/jumpserver/python3/lib/python3.6/site-packages/paramiko/transport.py",
 line 1957, in _check_banner
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|    'Error reading SSH protocol banner' + str(e)
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
ERROR|2017-08-08 20:49:50|15292|transport.py:1634|
WARNING|2017-08-08 20:49:50|15292|app.py:123|SSH negotiation failed.

**Comment by ploxiln** [comment]
The remote server did not respond within a reasonable time, and `raise socket.timeout()` happened. Nothing else can really be determined from this backtrace.

**Comment by zhaowei1109** [comment]
hey,brother. Have you solved this problem yet?
