### ISSUE TITLE
python3: NoValidConnectionsError.__init__ fails with TypeError

### ISSUE THREAD

**Issue by blackboxsw** [paramiko/paramiko#1040]
I get a TypeError on Ubuntu using python3 when hitting a NoValidConnectionsError exception using paramiko client.

The issue is in NoValidConnectionsError.__init__  because dist_keys object is not array subscriptable.

 The fix would be to simply to make errors.keys() a list when declaring addrs on line 165 of /usr/lib/python3/dist-packages/paramiko/ssh_exception.py. Then array subscripting used to create the exception message body would work.

Details:
paramiko verison: 1.16.0-1
OS: Ubuntu Xenial 
Platform: x86_64
Python: 3.5.2

**Comment by bitprophet** [comment]
You're on quite an old version of Paramiko there, I believe this has already bee fixed for some time! There are multiple changes to that line since 1.16 which wrap in `list` and then `sorted`; and our tests are instantiating it without issue under Python 3. Please try upgrading! Thanks :)
