### ISSUE TITLE
Support the `Include` directive in ssh config

### ISSUE THREAD

**Issue by brycefisher** [paramiko/paramiko#1044]
Using paramiko 1.15.2, I'm unable to use `Host` blocks defined in a file included from my main `~/.ssh/config`. From the man page for the default OpenSSH client config (man ssh_config) on MacOS 10.12:

>  Include
>             Include the specified configuration file(s).  Multiple pathnames may be specified and each pathname may contain glob(3) wildcards and, for user configurations, shell-like `~'  included in a user configuration file or /etc/ssh if included from the system configuration file.  Include directive may appear inside a Match or Host block to perform conditional inclusion.

A quick grep of the codebase (and my experience of fabric not being able to find those hosts when in a separate include VS being in the main config file) leads me to believe that this directive is not implemented in paramiko.

Personally, I'd be really happy just supporting an Include directive standalone sufficient rather than doing the entire spec of support `Include` from inside a Host or Match block.

If I were willing to contribute a PR which added this feature, would the maintainers be interested in accepting it, given sufficient code quality and response to feedback in code review?

**Comment by ploxiln** [comment]
see #872

**Comment by brycefisher** [comment]
Excellent!!!
