### ISSUE TITLE
Received some messy codes when using channel.recv() in paramiko

### ISSUE THREAD

**Issue by qijianan** [paramiko/paramiko#1050]
When I use paramiko to login remote SUSE 11 SP3 Linux host and switch user to root , I want to receive the messages to konw the switch is successful or not.But I meet some messy codes as below,so I can not match the ‘#‘ at end.
![image](https://user-images.githubusercontent.com/24307632/30001129-987a4d4c-90b6-11e7-8027-0de897fde8d4.png)
When i change LINUX OS to centos , and do not have this problem.
So how can I solve this problem? If I want to login to host and switch to root,except for this method below,is there any other way?
```
import paramiko
import time
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname='', port=22, username='sshusr', password='')
stdin, stdout, stderr = ssh.exec_command('ls')
channel = ssh.invoke_shell()
rootpass=""
try:
    channel.send("su - root\n")
    while not channel.recv_ready():
        print "Working..."
        time.sleep(2)
    print channel.recv(1024)
    channel.send("%s\n" % rootpass)
    while not channel.recv_ready():
        print "Authenticating..."
        time.sleep(2)
    buff=channel.recv(1024)
    print type(buff)

    if buff.find('Password') != -1:
        print buff
except Exception, e:
    print e
```

**Comment by ploxiln** [comment]
The difference is in the `PS1` variable which sets the command prompt. It is configured differently in SUSE than it is in CentOS. It might be configured on `/etc/profile`, or `/etc/bash.profile`, or `/etc/profile.d/*.sh`, or `/root/.bashrc`, etc ... in any case, it is not related to paramiko.

You might try using "sudo" to run a single command as root, in a more automation-friendly way. Configuring and using sudo is also not related to paramiko.
