### ISSUE TITLE
Unclosed socket on connection failure

### ISSUE THREAD

**Issue by maggyero** [paramiko/paramiko#1126]
With Python 3.6.3 and Paramiko 2.4.0, connecting with an invalid *host* or *port* causes a `ResourceWarning` (noticeable when the interpreter warnings are activated with the `-Wall` flag) as the underlying socket is not closed in such a case:

Input (example with an invalid port):

```bash
$ python3 -Wall <<EOF
import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy)
with client.connect(hostname="localhost", port=0): pass
EOF
```

Output:

> /home/master/.local/lib/python3.6/site-packages/paramiko/client.py:332: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::', 49626, 0, 0)>
>   sock = socket.socket(af, socket.SOCK_STREAM)
> /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
> Traceback (most recent call last):
>   File "<stdin>", line 4, in <module>
>   File "/home/master/.local/lib/python3.6/site-packages/paramiko/client.py", line 357, in connect
>     raise NoValidConnectionsError(errors)
> paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 0 on 127.0.0.1 or ::1
> sys:1: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 58766)>

**Comment by pkittenis** [comment]
Not just on invalid host/port, sockets are not closed in general. #1127

**Comment by maludwig** [comment]
I just spent a bunch of time hunting down this error, sad that it's in Paramiko itself.

**Comment by andschwa** [comment]
As of today, this is still the case.

**Comment by bitprophet** [comment]
Rolling into #1822
