### ISSUE TITLE
Auth Failed on SSH to Adva NID Device

### ISSUE THREAD

**Issue by degroat-c** [paramiko/paramiko#1177]
So I'm trying to use paramiko to ssh to an adva nid and I am getting authentication failures for some reason.  I can SSH normally via CLI with username and password but for some reason I can't via paramiko.  I've also tried the 'load_host_keys=False' with no change.  If there's any other info needed please let me know.  Thanks!

Script: 

def main_ADVA(HOST):
    paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
    print ("Attempting to login to " + HOST + " via root \n")
    ssh_client = paramiko.SSHClient()
    ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh_client.connect(hostname=HOST, username='root', password='XXXX')
    rem_conn = ssh_client.invoke_shell()

**Debug output:** 
DEBUG:paramiko.transport:starting thread (client mode): 0x9a9d5cf8
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.4.0
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.2
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.2)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: ecdh-sha2-nistp256
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 10.193.237.204: b'5d450de01b7ac23b7d4816a6b6ff21e7'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) failed.

**Comment by bitprophet** [comment]
If this never found a workaround, it'll be worth trying with Paramiko 2.9 (out soon) which adds RSA-SHA2 support - possible this was the issue here.

**Comment by avatarofhope2** [comment]
I am seeing the same issue. would love a fix or workaround. I'll keep digging as well.

**Comment by bskinn** [comment]
@avatarofhope2 -- bitprophet has been working on improving the flexibility of the key/auth tooling lately, per #387 and #23. Please check out the **experimental** new features described in the [3.2.0 paramiko CHANGELOG] (including the new `OpenSSHAuthStrategy` implementation in [Fabric 3.1.0]) -- it's possible that they may let you do what you need here on the user side, and not require augmentation of `paramiko` itself.

I'm not deeply familiar with what the current features enable, so I can't say for sure whether they address this use case. We would greatly appreciate any investigation you might be able to do and report back here, though. The new features will be fully added and finalized over the next few minor versions, so now is a great time to make sure your needs are factored into the functionality.

[3.2.0 paramiko changelog]: https://www.paramiko.org/changelog.html#3.2.0
[fabric 3.1.0]: https://www.fabfile.org/changelog.html#3.1.0

**Comment by avatarofhope2** [comment]
Thanks. I'll try out 3.2 and see if I can come up with something.

**Comment by avatarofhope2** [comment]
I've been trying to get login working in an imperative way before trying to place it where it needs to be, like in an implementation of an auth_strategy, but I'm struggling. Continuing from what I had above:
```python
import select

channel = client.invoke_shell()
elapsed_time = 0
buffer = b''
lines = []
eol = re.compile(b'\r*\n\r*')
poller = select.poll()
poller.register(channel)
while elapsed_time < 15000 and not channel.closed:
    events = poller.poll(1000)
    for fd, event in events:
        if event == select.POLLIN:
            while channel.recv_ready():
                received = channel.recv(1024)
                if len(received) > 0:
                    buffer += received
                    buff_lines = re.split(eol, buffer)
                    lines += buff_lines[:-1]
                    buffer = buff_lines[-1]
                    elapsed_time = 0
                    # check for prompt:
            if re.search(b'password:\s*$', buffer):
                print('sent: {}'.format(channel.sendall('my_password\n'.encode('utf-8'))))
                buffer = b''
            break  # out of the for loop
    else: # we didn't break. i.e. we didn't get pollin event
        elapsed_time += 1000
```
The send call returns a non-zero integer, but it doesn't ever get a response prompt afterwards. Something isn't right, but I don't know enough to know what.

**Comment by avatarofhope2** [comment]
I tried using Fabric's OpenSSHAuthStrategy class with as few changes as I could, but it failed. It is possible that it failed because I am mocking the config arguments. I'm not sure how to instantiate those, but the end result was that it requested the password in the terminal, and after entering it, received:
```
DEBUG:paramiko.auth_strategy:Trying Password(user='my_user')
my_user's password: 
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) failed.
INFO:paramiko.auth_strategy:Authentication via Password(user='my_user') failed with AuthenticationException
Traceback (most recent call last):
  File "path/scripts/test_adva_ssh.py", line 290, in <module>
    result = client.connect('192.168.1.1', username=username, look_for_keys=False, timeout=15, auth_strategy=OpenSSHAuthStrategy(ssh_config, fabric_config, username))
  File "/home/my_user/my_py_env/lib/python3.9/site-packages/paramiko/client.py", line 475, in connect
    return auth_strategy.authenticate(transport=t)
  File "/path/scripts/test_adva_ssh.py", line 201, in authenticate
    return super().authenticate(*args, **kwargs)
  File "/home/my_user/my_py_env/lib/python3.9/site-packages/paramiko/auth_strategy.py", line 301, in authenticate
    raise AuthFailure(result=overall_result)
paramiko.auth_strategy.AuthFailure: 
Password(user='my_user') -> Authentication failed.
```

**Comment by bskinn** [comment]
Reopening this since it's still a problem.

**Comment by jun66j5** [comment]
I don't think we should reopen this. This issue is about rsa-sha2 signature algorithm. It has been fixed in paramiko 2.9.

avatarofhope2 is trying to authenticating with password (not publickey). I believe that avatarofhope2's issue is _not_ the same issue.

**Comment by bskinn** [comment]
Ah, good point, @jun66j5.

Sounds like you'd recommend @avatarofhope2 open a new issue for this?

**Comment by avatarofhope2** [comment]
My actual issue is close to the 1476 issue mentioned previously, but I've been commenting here because bskinn's idea of implementing an auth strategy.

**Comment by avatarofhope2** [comment]
```python
import re
import select

import paramiko
from paramiko.auth_strategy import Password, AuthStrategy
from paramiko.ssh_exception import AuthenticationException
from paramiko.config import SSHConfig

# custom
from config import read_passwords
import util


def main():
    client = paramiko.SSHClient()
    module_kwargs = util.get_module_kwargs(data={'custom': {}})
    ssh_config = SSHConfig()
    ssh_config.parse(open("/etc/ssh/ssh_config"))
    try:
        client.load_host_keys('/home/my_user/.ssh/known_hosts')
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        paramiko.common.logging.basicConfig(level=paramiko.common.DEBUG)
        # need a container to hold the authenticated channel so it isn't deleted in the scope of the AuthSource.authenticate() call
        # if the channel is closed or deleted, you will need to log in again.
        container = Container()
        client.connect('192.168.1.1', look_for_keys=False, timeout=15,
                       auth_strategy=MySshStrategy(ssh_config, module_kwargs['config'], container))
        channel = container.channel
        try:
            channel.send(b'show system\r\n')
            # get_response_ssh(channel, 15)
            print(b'\n'.join(get_response_poll(channel, None)).decode('utf-8'))
        finally:
            channel.close()
    finally:
        client.close()


class AdvaAuth(Password):
    """
    Implementation of Password AuthSource, but with auth_none as a base
    """

    def __init__(self, username, password_getter, shell_channel_container):
        super().__init__(username, password_getter)
        self.shell_channel_container = shell_channel_container

    def authenticate(self, transport):
        next_auth_types = transport.auth_none(self.username)
        # should raise an exception for all non-Adva devices or devices that cannot authenticate with none approach

        channel = transport.open_session()
        try:
            # use default values from SSHClient.invoke_shell()
            channel.get_pty("vt100", 80, 24, 0, 0)
            channel.invoke_shell()
            password = self.password_getter()
            get_response_poll(channel, password)
        finally:
            self.shell_channel_container.channel = channel

        return next_auth_types


class MySshStrategy(AuthStrategy):
    """
    Implementation of an AuthStrategy using a custom AuthSource
    """

    def __init__(self, ssh_config, my_config, shell_channel_container):
        super().__init__(ssh_config)
        self.my_config = my_config
        self.shell_channel_container = shell_channel_container

    def get_sources(self):
        credentials = read_passwords(self.my_config.get('authentication', 'password_file'))

        def get_password():
            return credentials[1]

        yield AdvaAuth(credentials[0], get_password, self.shell_channel_container)
        yield Password(credentials[0], get_password)
        # any other AuthSource implementations can be used here


class Container:
    def __init__(self):
        self.channel = None


def get_response_poll(channel, password):
    elapsed_time = 0
    buffer = b''
    lines = []
    eol = re.compile(b'\r*\n\r*')
    poller = select.poll()
    poller.register(channel)
    password_detail = ' for password'
    while elapsed_time < 15000 and not channel.closed:
        events = poller.poll(1000)
        for fd, event in events:
            if event == select.POLLIN:
                # if we get any POLLIN event, just consume everything, until everything is consumed
                # there may be a better way to do this, but I wasn't sure that the POLLIN event
                # always had the same amount of data behind it to receive.
                while channel.recv_ready():
                    received = channel.recv(1024)
                    if len(received) > 0:
                        buffer += received
                        buff_lines = re.split(eol, buffer)
                        lines += buff_lines[:-1]
                        buffer = buff_lines[-1]
                        elapsed_time = 0
                # check for prompt:
                if re.search(b'password:\s*$', buffer):
                    if channel.send((password + '\r\n').encode('utf-8')):
                        password_detail = ' after sending password'
                        buffer = b''
                if re.search(b'ADVA-->\s*$', buffer):  # todo: need to handle all possible ADVA prompts here
                    return lines
                break  # out of the for loop
        else:  # we didn't break. i.e. we didn't get pollin event
            elapsed_time += 1000
    raise AuthenticationException('timed out waiting for a prompt{}'.format(password_detail))


if __name__ == '__main__':
    main()
```

Here is my working solution. I don't really like what I need to do to keep the channel alive, but it works.

**Comment by bskinn** [comment]
Ok, since you've found a working solution that you can refine toward a final state, @avatarofhope2, I'm going to go ahead and close this issue as resolved, assuming that a similar approach will work for OP, if this is still a problem.

@degroat-c, if you still need assistance with this problem, feel free to comment and re-open.
