### ISSUE TITLE
Translation from Py2 to Py3

### ISSUE THREAD

**Issue by kuzeyron** [paramiko/paramiko#1179]
Hello!
I can't translate [my project](https://github.com/kuzeyron/Kivy-SSH_Server) for Python3.

`  File "server.py", line 117, in ask_for_prompt
    inp = message.makefile('rU', None)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 864, in makefile
    return ChannelFile(*([self] + list(params)))
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 1323, in __init__
    self._set_mode(mode, bufsize)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/file.py", line 481, in _set_mode
    if bufsize < 0:
`

I have been working on this for a very long time and I get nowhere with this.
It runs well on Python2 but not at all with Python3.
I hope anyone can help me with this one!

**Comment by bitprophet** [comment]
What version of Paramiko are you using? It should be Python 3 compatible since version 1.13 or so.

Also I think you are missing part of your traceback! Cannot tell what the actual error is 😂

**Comment by kuzeyron** [comment]
Hey @bitprophet !
I have installed Paramiko with Pip2 and Pip3. I have set Python3 to be the default Python. 

The traceback is all I get!
But I'll make a new traceback.

**Comment by kuzeyron** [comment]
@bitprophet I found the problem. It's weird. But it seems to go to Paramiko's source code!
```python3
def check_channel_exec_request(self, channel, command):
		'''
			Determine which command interface to use.
		'''
		if command == 'terminal':
			print(("[*] Incoming call from [{}] which is using the client: [{}]".format(self.remote, command)))
		#else:
			#channel.close()
		return True
```

'command' is broken on Python3 but is fully working on Python2!
