### ISSUE TITLE
paramiko can't handle `eow@openssh.com` request

### ISSUE THREAD

**Issue by xuedipiaofei** [paramiko/paramiko#118]
The channel is died after receiving this request `eow@openssh.com`. It is a extension of openssh rfc.

The log:
DEB [20121129-16:44:10.944] thr=3   paramiko.transport: [chan 1] Unhandled channel request "eow@openssh.com"
DEB [20121129-16:44:10.944] thr=3   paramiko.transport: [chan 1] Simon catch this exception!!!
DEB [20121129-16:44:10.945] thr=3   paramiko.transport: [chan 1] EOF received (1)
DEB [20121129-16:44:10.945] thr=3   paramiko.transport: [chan 1] EOF sent (1)
DEB [20121129-16:44:10.952] thr=34  paramiko.transport: [chan 1] Unhandled channel request "eow@openssh.com"
DEB [20121129-16:44:10.953] thr=34  paramiko.transport: [chan 1] Simon catch this exception!!!
DEB [20121129-16:44:10.953] thr=34  paramiko.transport: [chan 1] EOF received (1)
DEB [20121129-16:44:10.953] thr=34  paramiko.transport: [chan 1] EOF sent (1)
DEB [20121129-16:44:10.957] thr=5   paramiko.transport: [chan 1] EOF received (1)
DEB [20121129-16:44:10.957] thr=5   paramiko.transport: [chan 1] EOF sent (1)
DEB [20121129-16:44:10.959] thr=5   paramiko.transport: [chan 1] Unhandled channel request "eow@openssh.com"

**Comment by bitprophet** [comment]
Closing for timeout.
