### ISSUE TITLE
Update documentation with non-optional dependencies

### ISSUE THREAD

**Issue by stevenwinfield** [paramiko/paramiko#1191]
Hi,

On [the installation page](http://www.paramiko.org/installing.html) at paramiko.org it says:
> Paramiko has only one direct hard dependency: the Cryptography library

...but in setup.py:
```    
install_requires=[
        'bcrypt>=3.1.3',
        'cryptography>=1.5',
        'pynacl>=1.0.1',
        'pyasn1>=0.1.7',
```

...which was a bit of a surprise!

Could the docs be updated, please?

**Comment by bitprophet** [comment]
Pondering whether we can/should remove `pyasn1` on older versions; even though it is _removing_ something, not adding, it still worries me that it'll goof somebody up somewhere (esp eg downstream packagers whose scripts, etc might suddenly break.)

Think I'll just make the changes on master for now?

**Comment by bitprophet** [comment]
Seems all right, updated the pyasn1 imports in the gssapi module (`paramiko.ssh_gss`) to all be inlined, and now I can import paramiko in a virtualenv without that module present. Tests all still pass etc.

So, Paramiko 2.5.x, when it comes out, will have this change in its code, and the docs will have the change as soon as I push. Thanks again! 👍
