### ISSUE TITLE
AttributeError: module 'paramiko' has no attribute 'util

### ISSUE THREAD

**Issue by adrianlaraperez88** [paramiko/paramiko#1200]
Ubuntu 16.04
python 3.5
web2py

 import paramiko.util as util
AttributeError: module 'paramiko' has no attribute 'util'

**Comment by adrianlaraperez88** [comment]
File "/usr/lib/python3/dist-packages/paramiko/ber.py", line 21, in <module>
    import paramiko.util as util
AttributeError: module 'paramiko' has no attribute 'util'

**Comment by ChrisYeGX** [comment]
I has has this probelm. Can anyone can help me???

**Comment by slivingston** [comment]
can you give more detail? what version of paramiko do you have? (`python -c 'import paramiko; print(paramiko.__version__)'`)

**Comment by adrianlaraperez88** [comment]
I use another wait so many time for replay lol, but is good library.

**Comment by adrianlaraperez88** [comment]
This project is finish I take another way.
