### ISSUE TITLE
No socket timeout in transport

### ISSUE THREAD

**Issue by jetchirag** [paramiko/paramiko#1231]
Code:
```
transport = paramiko.Transport((hostname, port ))
transport.connect( username=username, password=password)
```
transport.py: 361
```
try:
    retry_on_signal(lambda: sock.connect((hostname, port)))
except socket.error as e:
    reason = str(e)
else:
    break
```

There's no possible attribute in initial connection in transport to specify timeout. If the application is unable to connect to remote server, it takes forever for it return timeout.

**Comment by APCBoston** [comment]
`transport.connect()` gives the following in its documentation:

"This is a shortcut for `start_client`, `get_remote_server_key`, and `Transport.auth_password` or `Transport.auth_publickey`.  Use those methods if you want more control."

And in fact, `start_client()` takes a timeout, should you wish to provide one.

**Comment by bskinn** [comment]
Closing given the age of the ticket. If this is still a live issue, please comment and reopen.
