### ISSUE TITLE
Problem when importing modules like pandas. 

### ISSUE THREAD

**Issue by aseem-hegshetye** [paramiko/paramiko#1236]
Even a simple code like following wont work.

`import sys
import numpy
import pandas
file=open('/home/ubuntu/caling_ec2_from_ec2.txt','w')
file.close()
`

**Comment by bitprophet** [comment]
I'm not sure how this is relevant to this repository, can you clarify?

**Comment by ploxiln** [comment]
It sounds like you used `exec_command()` for each command separately. The first one does not affect the second (but you need it to). You need to have a single shell process run both of those commands. It may be sufficient to join them with "&&".

In general you should provide more detailed information when asking for help. In particular, your code which calls paramiko. And it helps to learn how to quote and format multiple lines of code or terminal output in a github issue/comment.

**Comment by bitprophet** [comment]
Yup, @ploxiln has it. For example, Fabric (a layer above Paramiko) explicitly has this in its FAQ: http://www.fabfile.org/faq.html#my-cd-workon-export-etc-calls-don-t-seem-to-work

**Comment by aseem-hegshetye** [comment]
Yes **&&** works or even semicolon (**;**) works.
eg:
`source activate py36 ; ls ; exit;`
But my actual error was that py36 is a conda environment. its path is  /home/ubuntu/anaconda3/bin/. This path is stored in my system so when i just write `source activate py36` it works. But when i ssh from remote server, somehow this path is not available. so i had to replace it with 
`source /home/ubuntu/anaconda3/bin/activate py36`

Now **Paramiko** works like a charm:
```
user_name='ubuntu'
instance_id='i-08h873123123' #just an example
pem_addr='/Users/folder1/.ssh/jack-aws.pem' # folder path to aws instance key
aws_region='us-east-1' 


instances = ec2.instances.filter(Filters=[{'Name': 'instance-state-name', 'Values': ['running']}])
    for instance in instances:
        if (instance.id==instance_id):
            p2_instance=instance
            break;

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    privkey = paramiko.RSAKey.from_private_key_file(pem_addr)
    ssh.connect(p2_instance.public_dns_name,username=user_name,pkey=privkey)


cmd_to_run='dropbox start && source /home/ubuntu/anaconda3/bin/activate py36 && cd /home/ubuntu/xx/yy/ && python3 func1.py'
stdin4, stdout4, stderr4 = ssh.exec_command(cmd_to_run,timeout=None, get_pty=False)

```
