### ISSUE TITLE
ssh.exec_command('chroot /path/to/your/root;ls -la') stuck

### ISSUE THREAD

**Issue by chncpla** [paramiko/paramiko#1238]
other multi commands in single session work well,like 
'cd /var;ls -la'

**Comment by ploxiln** [comment]
`chroot` does not work like `cd` - you give it a command to run in the new root (as additional arguments to chroot), it does not change the root for later commands after chroot finishes. If you do not give it a command, it runs an interactive shell.

This is really not a paramiko related topic ;)

**Comment by bitprophet** [comment]
Thanks for handling tickets like this so often, @ploxiln - super appreciate it as always! ❤️
