### ISSUE TITLE
Exception list doesn't match the current API (ECDSAKey._decode_key(self, data))

### ISSUE THREAD

**Issue by iksemyonov** [paramiko/paramiko#1257]
https://github.com/paramiko/paramiko/blob/6f0e7c58d0296d157d33194a30de1789da167480/paramiko/ecdsakey.py#L290

Compare to:

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/?highlight=load_der_private_key#cryptography.hazmat.primitives.serialization.load_der_private_key

> Raises:
>
> - `ValueError` -  If the DER data could not be decrypted or if its structure could not be decoded successfully.
> - `TypeError` - If a password was given and the private key was not encrypted. Or if the key was encrypted but no password was supplied.
> - `cryptography.exceptions.UnsupportedAlgorithm` - If the serialized key is of a type that is not supported by the backend or if the key is encrypted with a symmetric cipher that is not supported by the backend.

This appears to be a mismatch. `TypeError` is a sibling to `AssertionError` and thus will not be caught. The library-specific exception is not being caught at all.

Proposed fix: update the exception list to match that of the cryptography.io API.

**Comment by bitprophet** [comment]
Thanks, I suspect this may just represent us not being up to date with more recent cryptography API changes? Either way I agree it should get tweaked if possible. My only worry is whether the changes are technically backwards incompatible with the older crypto releases we support (IIRC, 1.1+). Will have to look.
