### ISSUE TITLE
Allow using HashKnownHosts for hashed hostnames in hosts_allow

### ISSUE THREAD

**Issue by mallniya** [paramiko/paramiko#1263]
Hello,
I see some controversy about hashed hostnames in hosts_allow:
https://github.com/paramiko/paramiko/issues/437
https://github.com/paramiko/paramiko/pull/166
Having Ubuntu, which ssh_config states the following:
```
Note that the Debian openssh-client package sets several options as standard in /etc/ssh/ssh_config which are not the default in ssh(1):

           ·   SendEnv LANG LC_*
           ·   HashKnownHosts yes
           ·   GSSAPIAuthentication yes
```
and 700 lines-long `.ssh/known_hosts` with hashed hostnames, which I want to get working, I haven't found more clean way to use paramiko than:
```
class SilentAccept(paramiko.client.MissingHostKeyPolicy):
    def missing_host_key(client, hostname, key):
        return

client.set_missing_host_key_policy(SilentAccept)
```
Googling around all I found is scary workarounds like this: https://gist.github.com/maxtaco/5080023
So my question or feature request is comes from man of Ubuntu's ssh_config:
>Note that existing names and addresses in known hosts files will not be converted automatically, but may be manually hashed using ssh-keygen(1).

Could paramiko have an option to _manually hash_ hostname to support hosts_allow under HashKnownHosts?
Thanks.

**Comment by ploxiln** [comment]
paramiko *should* support hashed hostnames in `known_hosts`: https://github.com/paramiko/paramiko/blob/master/paramiko/hostkeys.py#L205

**Comment by mallniya** [comment]
@ploxiln it definitely do -- after upgrading from default Ubuntu's 2.0.0 to pip's 2.4.1.
Sorry for inconvenience.
