### ISSUE TITLE
How to not print ssh banner

### ISSUE THREAD

**Issue by fixlensmith** [paramiko/paramiko#1281]
def connect(HOST, command):
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(hostname=HOST, username= USERNAME, password = PASSWORD)
    myshell = client.invoke_shell()
    myshell.send(command + '\n')
    time.sleep(2)
    output = myshell.recv(65535)
    print(output.decode(encoding='UTF-8'))

when i execute this script, it also print the banner..
how to not print this banner?

**Comment by bitprophet** [comment]
Which exact banner are you seeing? You might be mixing up your remote system's MOTD with the SSH banner or something. Typically the banner doesn't get printed to stdout (though it's possible `invoke_shell` is changing this, but I don't think so).

Also, you should definitely try using https://www.fabfile.org for things this high level as it'll remove a lot of this kind of possible error. Thanks!
