### ISSUE TITLE
please update interactive.py example to not use "hardcoded" u(chan.recv(1024))

### ISSUE THREAD

**Issue by yarikoptic** [paramiko/paramiko#1282]
as discussed (I think) in https://github.com/paramiko/paramiko/issues/302#issuecomment-290192663 it is not "proper" to read prespecified number of bytes (1024).  In our case e.g. it just leads to a crash since the 1024th byte is the first byte of the unicode character so decode blows.

**Comment by bitprophet** [comment]
Gonna consider this another reason to just nuke the examples (#1245), they're frequently bogus and certainly should not be causing support tickets for stuff users tend to handle themselves anyways :( thanks for bringing it up!
