### ISSUE TITLE
echo $PATH is different in client.exec_command function

### ISSUE THREAD

**Issue by makeforever** [paramiko/paramiko#1284]
client = SSHClient()
client.exec_command('echo $PATH')
#result == /user/lib64/qt-3.3

in putty client
#result == /usr/lib64/qt-3.3:/~/python:/~~~~~~~something

why is different?

**Comment by bitprophet** [comment]
See http://www.fabfile.org/faq.html#the-remote-shell-environment-doesn-t-match-interactive-shells, which is for a higher level library but applies to Paramiko itself as well. Thanks!
