### ISSUE TITLE
client.set_missing_host_key_policy always get error

### ISSUE THREAD

**Issue by beterhans** [paramiko/paramiko#1286]
paramiko v 2.4.1
python 3.7
mac 10.13.6

    client = paramiko.SSHClient
    client.set_missing_host_key_policy(paramiko.WarningPolicy())

or
    client = paramiko.SSHClient
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy)

always get errors

e 12, in connect_ssh_server
    client.set_missing_host_key_policy(paramiko.WarningPolicy())
TypeError: set_missing_host_key_policy() missing 1 required positional argument: 'policy'

e 11, in connect_ssh_server
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy)
TypeError: set_missing_host_key_policy() missing 1 required positional argument: 'policy'

**Comment by ploxiln** [comment]
This is because you need to call `paramiko.SSHClient()` with parentheses, to create a `SSHClient` instance, to call the method `set_missing_host_key_policy()` on.
