### ISSUE TITLE
Error importing package paramiko

### ISSUE THREAD

**Issue by ReenaAcharya** [paramiko/paramiko#1288]
Hi,

I installed paramiko using "pip install paramiko".
When I am trying to import paramiko "import paramiko" I am getting following error:-
"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/transport.py", line 57, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nacl/signing.py", line 19, in <module>
    import nacl.bindings
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_box import (
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nacl/bindings/crypto_box.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nacl/_sodium.so, 2): Symbol not found: _crypto_box
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nacl/_sodium.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nacl/_sodium.so"

I have checked the pramiko directory and all files are present including transport.py.
I am using MacOS.

Any help here would be appreciated.

Thanks & Regards,
Reena Acharya

**Comment by ploxiln** [comment]
This is a problem importing a dependency of paramiko, "nacl", a different python module. You could try to uninstall nacl and re-install it.

**Comment by ReenaAcharya** [comment]
Hi,

Thanks for reply. I installed nacl using "brew install nacl".
When I do "import paramiko" still I am getting above errors.

Thanks & Regards,
Reena Acharya

**Comment by ploxiln** [comment]
Ah, right, sorry, I mean "pynacl" https://pypi.org/project/PyNaCl/

**Comment by ReenaAcharya** [comment]
Hi,

I have pynacl  already installed.

Thanks & Regards,
Reena Acharya

**Comment by ploxiln** [comment]
Yes, you have pynacl installed, but it's apparently broken somehow and fails to import. So the original suggestion was to uninstall it and reinstall it.

Your original problem is with pynacl, not with paramiko.

**Comment by ReenaAcharya** [comment]
Hi,

I tried uninstalling and installing pynacl. When I did "import paramiko" I am getting errors.
I used the below commands for pynacl:-
1. pip uninstall pynacl
2. pip install pynacl
After doing this I got error for paramiko, so I followed a link which had a link download the tar file got pynacl and install it.I tried that also but still getting importing error for paramiko.
Do you have any link or any other command I can use to fix pynacl stuff.

Thanks & Regards,
Reena Acharya

**Comment by ploxiln** [comment]
You could provide verbose terminal output from installing pynacl (`pip install --verbose pynacl`). You may get better help from https://github.com/pyca/pynacl

**Comment by ReenaAcharya** [comment]
Hi,

Attaching output of command pip install --verbose pynacl

Thanks & Regards,
Reena Acharya

[output.txt](https://github.com/paramiko/paramiko/files/2376062/output.txt)

**Comment by bitprophet** [comment]
That seems to be getting you PyNacl 1.2.1 which is the same version I have locally, and it works on my end. This makes me suspect perhaps your underlying libnacl or libffi versions are incompatible with whatever PyNaCl requires. Normally the Python wrapper for a low level library should notice such things at install time, but there are always issues...

You may want to try completely uninstalling and reinstalling your Paramiko environment, or try using a separate Python environment besides the macOS default (which can sometimes have issues) - for example [pyenv](https://github.com/pyenv/pyenv).

Otherwise, I would go check the install documentation and FAQs for https://cryptography.io as they are the intermediate dependency here; this is not something Paramiko itself has any control over :( good luck! I am closing the issue as not-actionable but discussion is not locked.
