### ISSUE TITLE
"Invalid key" error when an Ed25519Key is used with an incorrect passphrase

### ISSUE THREAD

**Issue by parke** [paramiko/paramiko#1305]
When I call either of the following ...

    paramiko.ed25519key.Ed25519Key.from_private_key_file
    paramiko.SSHClient.connect

... with an incorrect key decryption passphrase, I get the following error:

    paramiko.ssh_exception.SSHException: Invalid key

Instead of the above error, I would expect an error telling me that the passphrase failed to decrypt the key.  I would recommend that the error message also include the path of the file that contained the key.

The "Invalid key" error can be very misleading.  For example, consider the following scenario with two key files:

    /tmp/key_ed25519     # this key is encrypted with passphrase "foo"
    ~/.ssh/id_ed25519    # this key has some other passphrase

Now consider the following series of events:

1 ) You call the following:

    paramiko.SSHClient.connect (
      key_filename='/tmp/key_ed25519'
      passphrase='foo' )    # other parameters omitted for purposes of illustration

2 ) paramiko will successfully decrypt the key and use it to attempt to connect to the remote host.

3 ) Let's say the key is not in `~/.ssh/authorized_keys` on the remote host.  So, the attempt to connect with the key will fail.

4 ) At this point, I would expect to receive an authentication failed exception.  However, no such exception is raised.  Instead...

5 ) paramiko will continue, and will now look for a key in `~/.ssh/id_ed25519`.  paramiko will attempt to decrypt this key, again using `passphrase='foo'`.  This key decryption will fail, and (confusingly) raise an `Invalid key` exception.  (There is nothing invalid about either key.  Paramiko is simply silently trying to use passphrase on a mismatched key file.)

Aside:  It seems entirely reasonable to me that different key files would be encrypted with different passphrases.  Yet paramiko is not designed to accommodate this configuration.  Paramiko will attempt to decrypt different key files with the same passphrase.  Error messages do not describe which key file caused any errors that occur.  So the error message is doubly confusing.  If it were my choice, I would either redesign paramiko so that passphrases are specified on a per key file basis, or so that if a key is explicitly provided the paramiko does not look for additional keys in `~/.ssh` .

Here is code to reproduce the bug:

    import  os
    import  paramiko

    os.system ( 'rm -f /tmp/key_ed25519' )
    os.system (
      'ssh-keygen -t ed25519 -N foo -f /tmp/key_ed25519 > /dev/null' )

    hostname      =  'localhost'
    username      =  'nobody'
    key_filename  =  '/tmp/key_ed25519'

    passphrase    =  'bar'
    #  passphrase   =  'foo'    # uncomment to search for keys in ~/.ssh        

    client  =  paramiko .SSHClient()
    client .set_missing_host_key_policy ( paramiko .AutoAddPolicy() )

    client .connect ( hostname=hostname,  username=username,
                      key_filename=key_filename, passphrase=passphrase )

**Comment by bitprophet** [comment]
Let's file this under #387 - a lot of key handling stuff is going to get cleaned up and more specific errors (when possible – they are not always possible without leaking security-sensitive metadata) should come out of that. Thanks!
