### ISSUE TITLE
"Private key file is encrypted" incorrect raised for (all?) auth failures where keys are provided?

### ISSUE THREAD

**Issue by twirrim** [paramiko/paramiko#1317]
This took a little digging.  I was being dumb, and put entirely the wrong username in for the tool to use, on an instance where I provided an SSH Key for authentication.   Paramiko incorrectly complained that I'd passed in an encrypted private key file, which I hadn't.  So far as I could gather by stepping through the code using pdb, It had been able to decrypt the key, it just couldn't use it to authenticate with.

Easy to replicate:
```
#!/usr/bin/env python

import paramiko

ip = some_ip_address

client = paramiko.SSHClient()
client.load_system_host_keys()
client.connect(ip, username="bad_username", key_filename="/path/to/ssh/key")
client.exec_command("ls -l /")
```

```
$ python quick.py
Traceback (most recent call last):
  File "quick.py", line 11, in <module>
    client.connect(ip, username="foo", key_filename="../keys/ssh/id_rsa")
  File "/Users/pgraydon/Envs/tools/lib/python2.7/site-packages/paramiko/client.py", line 437, in connect
    passphrase,
  File "/Users/pgraydon/Envs/tools/lib/python2.7/site-packages/paramiko/client.py", line 749, in _auth
    raise saved_exception
paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted
```

A straight authentication failure would probably have got me revisiting stuff, but saying "Private key file is encrypted" meant I went down totally the wrong investigative path!

**Comment by twirrim** [comment]
I guess this is a dupe of https://github.com/paramiko/paramiko/issues/387 ?

**Comment by bitprophet** [comment]
Yea, it is. You're seeing some other, later password-protected key exception. (See for example a similar-ish scenario I just posted in comments on #387.)

**Comment by chrisconlan** [comment]
Can confirm. If I pass the wrong username for the server, I get `aramiko.ssh_exception.PasswordRequiredException: private key file is encrypted`, and Paramiko makes a request to `gnome-keyring`, which is just really confusing.

**Comment by ambv** [comment]
For people searching for this error message (like me!), I just need to share a weird discovery that the error goes away if you actually go through the motions of logging into the affected box manually. Somehow by some ssh-agent magic the next run of Paramiko works fine.

**Comment by kikoreis** [comment]
I ran into the same problem; I didn't have the right key in authorized_users, so when SSHing I got prompted for a password. The error message "Private key file is encrypted" didn't actually make any sense (as yes, it is encrypted but that works just fine) but a manual ssh helped me figure it out.
