### ISSUE TITLE
paramiko paramiko.ssh_exception.SSHException:  using  keyfile

### ISSUE THREAD

**Issue by ravinderthakuraltus** [paramiko/paramiko#1358]
Hi,

I am trying to use paramiko to login into the remote server but getting below error when running the code on aws lambda function , it really wired that the same code was working yesterday fine for me not sure what went wrong.

    raise SSHException("not a valid " + tag + " private key file")
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file

def copy():
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(hostname, username='ubuntu', key_filename = '/tmp/id_rsa.pem')
        stdin, stdout, stderr = ssh.exec_command('ls -l /tmp')
#        print(stdout.readlines())
        ssh.close()

I also tried below code but still the error is coming:

        import paramiko
        k = paramiko.RSAKey.from_private_key_file("/tmp/id_rsa.pem")
        c = paramiko.SSHClient()
        c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        print("connecting")
        c.connect( hostname = 172.1.1.2, username = "ubuntu", pkey = k )
        print("connected")
        commands = [ "ls -l /tmp" ]
        for command in commands:
                print("Executing {}".format( command ))
                stdin , stdout, stderr = c.exec_command(command)
                print(stdout.read())
                print( "Errors")
                print(stderr.read())
                c.close()

   return self.auth_handler.wait_for_response(my_event)
  File "paramiko/paramiko/auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

**Comment by xuerhaha** [comment]
I have the same mistake. do you have resolved? how to resolve it?

**Comment by ploxiln** [comment]
see #1313 #1343
