### ISSUE TITLE
Support for the new OpenSSH format

### ISSUE THREAD

**Issue by thomasd3** [paramiko/paramiko#1382]
I've seen a few issues discussing the problem, but there seems to be no clear timeline, or even any information if this will be implemented.

What is the status regarding support of these keys?

**Comment by dmhalejr** [comment]
Signpost:

How to generate keys in the old/trusted RSA style from existing keygen:
```
ssh-keygen -p -m PEM -f <path_to_key>
```

**Comment by XVilka** [comment]
Any updates on this issue? There seems to be a pull request adding support for this: https://github.com/paramiko/paramiko/pull/1343

**Comment by bitprophet** [comment]
See #1343, this is now done.

**Comment by bitprophet** [comment]
Also, I am perplexed by the notion that if someone is too busy to implement something, how opening yet another issue for them to be bothered by is going to help the situation 🙃
