### ISSUE TITLE
Warning: CryptographyDeprecationWarning:

### ISSUE THREAD

**Issue by 1605200517** [paramiko/paramiko#1386]
Hi,

there are warnings in latest paramiko 2.4.2:

lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
    hm.add_string(self.Q_C.public_numbers().encode_point())

same for lines 39 and 96 in same script, kex_ecdh_nist.py.

Though I can't recognize how I trigger them with this boilerplate code:

```
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(ip, username=username, password=password, timeout=t, auth_timeout=t)

```

How to get rid of these warnings?

**Comment by ploxiln** [comment]
fixed in #1379

**Comment by skebanga** [comment]
Do you plan on releasing a new version with this fix please?

Currently I see the [latest release](https://github.com/paramiko/paramiko/releases) is [2.4.2](https://github.com/paramiko/paramiko/releases/tag/2.4.2), released on 18 Sep 2018.

What does your release schedule look like?

Thanks in advance

**Comment by cowlinator** [comment]
It's not really fixed until it's merged and released

**Comment by chrisranderson** [comment]
Is paramiko safe to use with these warnings? I don't know how serious the deprecation warnings are.

**Comment by johnnybubonic** [comment]
@chrisranderson should be safe, yes; it's just an interface deprecation from what i can tell, not an algo deprecation or anything of the sort.

**Comment by cowlinator** [comment]
I asked someone on #cryptography-dev on Freenode about this... unfortunately I lost my copy of what they said.  It was something about the depreciated function could generate a point which is not on the elliptic curve unless you called `PublicKey()` on it.  Or something; my memory isn't great.  Or, hey, just hop on #cryptography-dev on Freenode and ask.

**Comment by skebanga** [comment]
Any news on the release schedule please?

**Comment by tomazas** [comment]
If anyone wants a workaround without updating, then include:

`import warnings`
`warnings.filterwarnings(action='ignore',module='.*paramiko.*')`

**Comment by ssbarnea** [comment]
I am looking forward for a release as this hack is useless if you encounter it on code that run on remove machines, like one that is run by ansible.

**Comment by newAM** [comment]
I would like to echo the requests for a release - suppressing warnings always makes me feel uneasey.

**Comment by AInteriorB** [comment]
It would be great to hear from you. We use duplicity for backups. There, warnings are important for us as an indication for a failed or incomplete backup.

**Comment by ratskin** [comment]
Have a look at https://stackoverflow.com/a/54861527/7304372

**Comment by bitprophet** [comment]
As noted earlier this should be handled by #1379, closing!
