### ISSUE TITLE
Two-factor not working

### ISSUE THREAD

**Issue by nevins-b** [paramiko/paramiko#139]
Hi there, 
It appears that Paramiko does not work with "RequiredAuthentications2 publickey,password"  option in OpenSSH_5.3p1 on Centos 6.3.

Looking at the logs it appears that it sends on authentication type but never sends the other:

sshd[16481]: Accepted password for test from 1.1.1.1 port 57946 ssh2
sshd[16482]: dispatch_protocol_error: type 90 seq 5

**Comment by bitprophet** [comment]
Rolling this into #467
