### ISSUE TITLE
Add support for aes256-gcm@openssh and aes128-gcm@openssh ciphers

### ISSUE THREAD

**Issue by shradhagautam15** [paramiko/paramiko#1394]

**Comment by bofh16** [comment]
Such development could lower the priority of introducing any explicit etm-MAC algorithm support. It would also pave the way for dropping support of des/3des/md5. And in the further down the road - cbc...

**Comment by gsuyashs** [comment]
What's the plan on this ticket. Can we expect these ciphers in upcoming release? It should be supported by Paramiko since these ciphers are most preferred over other ciphers.

**Comment by Rajalaxmi-web** [comment]
Yes i agree gsuyashs comment . Please let me know when this update happend for Paramiko to use **"aes128-gcm@openssh.com and aes256-gcm@openssh.com"**...WHich is more encrypted way of connecting. In mean while please anyone help me how to connect ssh using these ciphers using python.....Is there any alternative way....

**Comment by adiroiban** [comment]
This looks like a duplicate for #982

**Comment by bitprophet** [comment]
It does, thanks @adiroiban !

**Comment by bitprophet** [comment]
GitHub why does your dropdown list things like "duplicate" but then not let me _choose 'duplicate'_? eesh.
