### ISSUE TITLE
Raises 'Invalid key' on valid OPENSSH private key 

### ISSUE THREAD

**Issue by eepstein** [paramiko/paramiko#1430]
Context: 
- no passphrase.
- keyfile works flawlessly with `ssh -i ...`
- Paramiko throws `Invalid key` during the public key checking phase when using a file containing the private key. 

https://github.com/paramiko/paramiko/blob/cf7d49d66f3b1fbc8b0853518a54050182b3b5eb/paramiko/ed25519key.py#L130

keyfile is 2048 bit RSA:
 
```
$ ssh-keygen -l -f ~/.ssh/the_key.pem 
2048 SHA256:VfQdzkeQp31B2XgUEAhznNfJ5Wxt8x9KiD8PGsd3uSQ foo (RSA)
```

file starts with:

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

Both `class RSAKey(PKey)` and `class Ed25519Key(PKey)` fail to support this valid key file format.

**Comment by ploxiln** [comment]
see #1313 #1343
