### ISSUE TITLE
ImportError GLIBC_2.25 not found when importing on Raspberry PI

### ISSUE THREAD

**Issue by disaacs** [paramiko/paramiko#1435]
I have pip installed paramiko on my Raspberry PI, running the latest Raspbian Stretch version.
When I try to import it in python3.6, however, I get an ImportError

```
# python3.6
Python 3.6.3 (default, Apr 22 2019, 11:20:48)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/local/lib/python3.6/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/usr/local/lib/python3.6/site-packages/nacl/signing.py", line 17, in <module>
    import nacl.bindings
  File "/usr/local/lib/python3.6/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/usr/local/lib/python3.6/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/lib/python3.6/site-packages/nacl/_sodium.abi3.so)
```
The python3.6 that is installed was compiled from source on the PI.

**Comment by disaacs** [comment]
Looks like the latest GLIBC version that ships with Debian Stretch (and therefore Raspbian Stretch) is 2.24

```
$ ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
```
A later versions (2.28-8) is still in testing.

Do I need to downgrade paramiko?

**Comment by ploxiln** [comment]
The problem is specifically with `pynacl`. You could try an older version of `pynacl`, or you could make sure that builds from source with `pip install --no-binary :all: pynacl` (but it will have other requirements when building from source).

**Comment by disaacs** [comment]
OK, the problem isn't Paramiko. It is the PyNaCl module that Paramiko installs. 

The PyNaCl module packages it's own version of of the libsodium library, which is incompatible with my target OS. It should be possible, according to PyNaCl's Readme, to install the PyNaCl library using the libsodium provided by the OS. But for some reason that option is not working. 

Anyway, it's not strictly a Paramiko issue.

**Comment by disaacs** [comment]
> The problem is specifically with `pynacl`. You could try an older version of `pynacl`, or you could make sure that builds from source with `pip install --no-binary :all: pynacl` (but it will have other requirements when building from source).

Thanks for the building suggestion, and I did try that by cloning the pynacl repo and compiling using `SODIUM_INSTALL=system python3 setup.py install`. Unfortunately, once successfully compiled, this just led me to another error
```
ImportError: /usr/local/lib/python3.6/site-packages/PyNaCl-1.4.0.dev1-py3.6-linux-armv7l.egg/nacl/_sodium.abi3.so: undefined symbol: crypto_pwhash_argon2id_opslimit_moderate
```
I figure I've gone far enough down this rabbit hole and am calling it a day ;)

**Comment by Swimmerhair** [comment]
I would just like to say I'm glad I'm not the only one having this issue. After digging through my code and the error logs, and doing some searching online I found this post and have decided to call it a day as well. 

I was trying to run a library that is dependent on `paramiko` (and by extension the PyNaCl module) hence why I was having this exact same issue. Alas, I will wait for another day to tackle this issue.

**Comment by ploxiln** [comment]
I maintain a fork of paramiko for which PyNaCl is an *optional* requirement, only needed for ed25519 keys. You could try something like the following:

```
pip uninstall paramiko
pip uninstall PyNaCl
PARAMIKO_REPLACE=1 pip install https://github.com/ploxiln/paramiko-ng/archive/2.7.0.tar.gz#egg=paramiko
```

(or, if you don't have another python package you are trying to get working, which explicitly depends on paramiko, you could replace that last line with just `pip install paramiko-ng` (and then `import paramiko` as usual))

**Comment by Swimmerhair** [comment]
You just saved my project! Everything is running smoothly (for now). Thank you!

**Comment by ms7m** [comment]
If anyone ever stumbles upon this while Googling for 30 hours and hit a dead end, and none of the solutions help you out.  Here is what works for me.

I installed Ubuntu Mate on my Pi which came with glibc 2.27. Even though PyNaCl requires 2.27.

The repos on Ubuntu show that 2.27 is the latest. But you can find a deb from debian with a compiled version for armhf on their repos.

You can download [here](http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6_2.28-10_armhf.deb). 

If it nags you about a dependency called "bison", you can download it [here](http://ftp.us.debian.org/debian/pool/main/b/bison/bison_3.3.2.dfsg-1_armhf.deb)

After installing the libc6, you need to do ``apt-get update`` and ``apt-get upgrade``. 
Ubuntu might tell you that stuff will break. Namely the ``locale`` package, but I ignored it.

After doing all that, you can see if your app works. 
If you gives you an error about something that it can't Import something about copyable regex, just uninstall and reinstall paramiko/netmiko from pip.
