### ISSUE TITLE
2019-06: make new release or pre-release

### ISSUE THREAD

**Issue by ssbarnea** [paramiko/paramiko#1446]
A new release is really needed as the current one is ancient and raises a huge amount of deprecation warnings related to cryptography. Current master already includes fixes but packages depending on paramiko cannot consume unreleased versions.

Example of issues waiting for release:
* https://github.com/paramiko/paramiko/issues/1386

**Comment by bitprophet** [comment]
This is not helpful feedback unfortunately.
