### ISSUE TITLE
Dependency problem with cryprograhpy

### ISSUE THREAD

**Issue by 1605200517** [paramiko/paramiko#1454]
After upgrading to paramiko 2.5.0, - thanks for the new release - I had a broken pipeline using a standard cryptgraphy 1.7 distributed with my Python version. After moving to cryptography 2.7 it was ok again. The missing module was cryptography.hazmat.primitives.asymmetric.x25519.

**Comment by ploxiln** [comment]
the tool that was used to install/upgrade paramiko should have noticed that it now requires cryptography-2.5 or later:
https://github.com/paramiko/paramiko/blob/2.5.0/setup.py#L76

**Comment by pmury** [comment]
Thanks - reduced test ok:
```

docker run -it python:latest bash -c "pip3 install paramiko && pip3 list"

Package      Version
------------ -------
asn1crypto   0.24.0 
bcrypt       3.1.6  
cffi         1.12.3 
cryptography 2.7    
paramiko     2.5.0  
pip          19.0.3 
pycparser    2.19   
PyNaCl       1.3.0  
setuptools   40.8.0 
six          1.12.0 
wheel        0.33.1 

```

**Comment by mysuf** [comment]
I can confirm issues with this module too. Running in docker. It does not work on debian stretch (python 3.7.2), but works on buster(python 3.8.0).

**Comment by bitprophet** [comment]
@mysuf Can you file a new ticket with the exact error you're getting? It's probably unrelated to the original issue here as that was a Cryptography <2.5 issue and you're on Cryptography 2.7.
