### ISSUE TITLE
Some ssh cmd commands with &  sent by paramiko to guest8.1 (& kernel 4.18.0-107.el8.x86_64) hang.

### ISSUE THREAD

**Issue by polinaag** [paramiko/paramiko#1473]
Running automation regression set with guest based on Red Hat Enterprise Linux release 8.1 Beta (Ootpa), we see some tests are hanging on the execution of ssh cmd command on VM, like for example

    cmd = "dd if=/dev/urandom of=/dev/null &"
    rc = vm_resource.run_command(command=shlex.split(cmd))[0]
or 

    cmd = 'cat /dev/zero > /dev/null &'
    rc, _, error = vm_executor.run_cmd(cmd=shlex.split(cmd))

The same command successfully passes on:
guest RHEL-8.1.0-20190508.0 & kernel 4.18.0-83.el8.x86_64
Also good for RHEL-8.1.0-20190508.0 & kernel 4.18.0-107.el8.x86_64

Hangs on RHEL-8.1.0-20190619 & kernel 4.18.0-107.el8.x86_64 (paramiko 2.3.1 and 2.6.0)
Manually entering the guest and running the command succeeds.

Version-Release number of selected component (if applicable):
RHEL-8.1.0-20190619 & kernel 4.18.0-107.el8.x86_64

How reproducible: 100%

Steps to Reproduce:
For reproduce the following python script must be run on Ovirt VM (after git clone of https://github.com/lukas-bednar/python-rrmngmnt/tree/master/rrmngmnt):

import shlex
from rrmngmnt import Host, RootUser

h = Host("10.35.30.57")
h.users.append(RootUser('qum5net'))
cmd = "dd if=/dev/urandom of=/dev/null &"
print h.executor().run_cmd(cmd=shlex.split(cmd))[0]

Actual results: the command just hangs, doesn't return prompt.
Expected results: the command must be completed with the return code
Additional info: we could provide the environment for testing if needed.

**Comment by ploxiln** [comment]
It's unclear what this was doing before, but it is very strange:

```
cmd = 'cat /dev/zero > /dev/null &'
rc, _, error = vm_executor.run_cmd(cmd=shlex.split(cmd))
```

`shlex.split()` is presumably so that you could run the command directly, without a shell. But `> /dev/null` and `&` are special shell operators, you really need a shell to interpret the whole line.

If you ssh in, the thing with `&` will work fine as your shell will persist. But for running a single command with paramiko, using `&` is tricky, and won't work on its own in the simple way you use it.

But then again, `run_command()` and `run_cmd()` are not paramiko methods. This all really depends on what your intermediate library is doing. (Maybe it's ignoring the `&`?)  But it seems what changed is the RHEL ssh server or shell or configuration? And these are just "regression tests" doing very odd things, the expected behavior of which does not seem well defined ...

To have any hope of a change which can benefit your use case, I suggest posting a pure-paramiko example which shows a behavior which you can argue not correct.

**Comment by polinaag** [comment]
It could be not the paramiko issue but platform on the VM side. we are investigating this. I'd like to narrow the scope of the investigation and make sure that nothing is suspicious from the point of paramiko.
If we could be sure giving this description and the output, that this is not the paramiko issue , the issue could be closed.

The test is sending the linux command to a virtual machine with ssh. 
let's concentrace on one example:
    cmd = "dd if=/dev/urandom of=/dev/null &"
    rc = vm_resource.run_command(command=shlex.split(cmd))[0]
run_command is a method of https://github.com/lukas-bednar/python-rrmngmnt/tree/master/rrmngmnt which uses paramiko library.
I reproduce the hanging problem with a small script:
    import shlex
    from rrmngmnt import Host, RootUser
    
    h = Host("VM_IP")
    h.users.append(RootUser('passwd'))
    cmd = "dd if=/dev/urandom of=/dev/null &"
    print h.executor().run_cmd(shlex.split(cmd))[0]

adding some additional printing I get this output for 

successful case: 
<paramiko.ChannelFile from <paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x674bda90L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, <paramiko.ChannelFile from <paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x674bda90L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, <paramiko.ChannelFile from <paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x674bda90L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, dd if=/dev/urandom of=/dev/null &

<paramiko.ChannelFile from <paramiko.Channel 0 (EOF received) (open) window=2097152 -> <paramiko.Transport at 0x674bda90L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, <paramiko.ChannelFile from <paramiko.Channel 0 (EOF received) (open) window=2097152 -> <paramiko.Transport at 0x674bda90L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, <paramiko.ChannelFile from <paramiko.Channel 0 (EOF received) (open) window=2097152 -> <paramiko.Transport at 0x674bda90L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>

0

failed case:
<paramiko.ChannelFile from <paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x8ae46cd0L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, <paramiko.ChannelFile from <paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x8ae46cd0L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, <paramiko.ChannelFile from <paramiko.Channel 0 (open) window=2097152 -> <paramiko.Transport at 0x8ae46cd0L (cipher aes128-ctr, 128 bits) (active; 1 open channel(s))>>>, dd if=/dev/urandom of=/dev/null &

**Comment by polinaag** [comment]
I close the issue. have now manual reproduce sending the ssh command. no paramiko issue here.
