### ISSUE TITLE
docs.paramiko.org version selector doesn't actually do anything

### ISSUE THREAD

**Issue by eichin** [paramiko/paramiko#1486]
At least from chrome on linux, although it *does* get you the pink "_Note
You are not reading the most recent version of this documentation. 2.6 is the latest version available_."  banner, the *content* is all from the latest version.  (Particular example that came up was `channel.set_environment_variable` which is new in 1.18 according to the excellent changelog page, but ubuntu xenial has 1.16 which doesn't have it (and the pydoc is correct), http://docs.paramiko.org/en/1.16/api/client.html still talks extensively about it.)

Knowing this, I just went with the local pydoc, and I know very little about sphinx and readthedocs so I don't know what other observations I could make.

**Comment by bitprophet** [comment]
Took me a few reads to realize what you meant. The selector definitely "does things" in that it changes the URL to e.g. /en/1.16/ but I see what you mean about the API contents appearing to be 'modern'. That's distressing and makes me wonder if there's an unknown bug lurking in RTD somewhere.

That particular set of branches (1.16-1.17) are old enough that they've been deleted upstream, which makes it hard for RTD to honor my "uh please rebuild this, wtf" request. (Wondering if that is somehow related, though again, it would be very worrisome.)

But I had the branch locally so I've pushed it back to Github, we'll see if RTD can rebuild it, and then we'll see if that somehow refreshes the contents of the publicly visible site.

While that runs I did another sanity check: Paramiko 2.6 added `Client.connect(disabled_algorithms=xxx)`. So this is a very fast way to check which versions got stomped. 2.5 docs lack it, so they're good. Ditto 2.0. So this may only impact the pre-2.0 branches (which to be fair are wholly unsupported at this point in time).

I then checked 1.17 for `Channel.set_environment_variable`, and it's not there. So this entire issue may be limited to 1.16 only. Still mysterious tho.

**Comment by bitprophet** [comment]
1.16 docs rebuilt and now they're lacking that too-new member. So I think this is fixed enough now, even though I wonder how it occurred. Thanks for the report!
