### ISSUE TITLE
type object 'EllipticCurvePublicKey' has no attribute 'from_encoded_point'

### ISSUE THREAD

**Issue by holic-cl** [paramiko/paramiko#1498]
Hi, i am having problems to execute the following code on a web application:
```
            client = SSHClient()
            client.load_system_host_keys()
            client.set_missing_host_key_policy(MissingHostKeyPolicy())
            client.connect(
                credentials.get('host'),
                username=credentials.get('username'),
                password=credentials.get('password'))

            stdin, stdout, stderr = client.exec_command('ls -l')
            print("stdout")
            for line in stdout:
                print('... ' + line.strip('\n'))
            print("stderr")
            print(stderr)
            client.close()
```
I get this message:
```
type object 'EllipticCurvePublicKey' has no attribute 'from_encoded_point'
```

But when i try the same code in the python console, it works well.

I am using:
- python 3.7
- debian sid
- openssh-client 1:8.0p1-4

Anyone have any suggestion?. Thanks

**Comment by ploxiln** [comment]
This is caused by using paramiko >= 2.5 with cryptography (library) < 2.5 (and using ecdh keys). If you're importing different versions of the cryptography library depending on how you start python, or if you end up using different ssh host key or key exchange algo (different server?), that would explain it.

**Comment by holic-cl** [comment]
Hi @ploxiln thanks for fast answer.

I am using `cryptography 2.3.1` so it must be the problem.

As workaround i am using `paramiko 2.4` and it is working well.

Will close the issue, thanks again.
