### ISSUE TITLE
athentication failure for doamin users or local users using sshclient.connect(host,username,password)

### ISSUE THREAD

**Issue by Narengowda** [paramiko/paramiko#15]
Hi Below is the code, tel me why PARENT\\puser (puser is joined to PARENT.com domain)
fails to authenticate, if i try to authenticate using the below show code. exeption thrown is: raise saved_exception.

if i try to authenticate the same PARENT\\puser indipendently authentication succeds successfly,

could any one tell me the ideal way of authenticating users?

import paramiko
import time
import os
import sys

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('10.10.60.68',username ='root',password ='span1234',timeout='10')
transport = ssh.get_transport()
chan = ssh.invoke_shell()
time.sleep(2)
print chan.recv(9999)
ssh.close()
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('10.10.60.68',username ='PARENT\puser',password ='parent@1234',timeout='10')
chan = ssh.invoke_shell()
time.sleep(2)
print chan.recv(9999)
ssh.close()

thanks in advance....

**Comment by bskinn** [comment]
Hi! I'm helping bitprophet by going through the issues and PRs backlog, and for anything more than a few years old, we're just closing them out for now.

If this support request is still relevant, please comment with more detail and reopen.

Thanks!
