### ISSUE TITLE
Paramiko authentication failed with valid .pem

### ISSUE THREAD

**Issue by notihs** [paramiko/paramiko#1500]
Hi, 
I am trying to authenticate using a .pem file. 
I'm using paramiko v2.6.0 (but this is also visible on 2.4.2)
This is the code that I'm using:

```
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

private_key = paramiko.RSAKey.from_private_key_file(sshCredentials.passwordCertificatePath)
client.connect(hostname=sshCredentials.hostname,
               username=sshCredentials.username,
               pkey=private_key)
```

I always obtain the following exception: 
`paramiko.ssh_exception.AuthenticationException: Authentication failed.`

My .pem does start with 
`-----BEGIN RSA PRIVATE KEY-----`

I also enabled DEBUG logging on paramiko and this was printed: 
```
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for <my_host>: a0248e1aa7579ed496a87ea23063deef
DEBUG:paramiko.transport:Trying SSH key 9a51d8ced523322cc1b8858719a0df0e
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
```
(being <my_host> the name of my host 😛  )

I know that a lot of issues already exist regarding this, but they all seem kind of "forgotten". Also most of those were started some years ago or so and have some comments regarding this (looking at #1135, for example)

Also I tried adding `allow_agent` and `look_for_keys` both with value `False` but the same behaviour is visible

If I'm doing something wrong, I would be very grateful if anyone could tell me where 😄 
Also, if more info is needed, please ask me and I will provided it
Regards

**Comment by notihs** [comment]
This was a configuration problem, so not a real issue

**Comment by PTrempler** [comment]
> This was a configuration problem, so not a real issue

The issue was related to the server configuration?
