### ISSUE TITLE
Agent support for OpenSSH on Windows (Powershell/OpenSSH)

### ISSUE THREAD

**Issue by benj56** [paramiko/paramiko#1509]
The OpenSSH that comes with Windows is not supported.
In `agent.py`, if the platform is Windows, it checks for a running Putty `pageant` agent, if not found it fails. 

Is there any chance this can be implemented? I believe the OpenSSH agent on Windows communicates via a named pipe, while `pageant` seems to use a mapped file. 

I would need this for agent forwarding.

**Comment by maxslimmer** [comment]
It does use named pipes. I have a decent start on this. There are some parts missing (such as detecting the openssh agent is running, error handling) and it currently depends on pywin32. Unsure where to go from here, do I submit a PR?

**Comment by bitprophet** [comment]
Let's roll this into #1868.
