### ISSUE TITLE
How to disable sshd weak algorithms?

### ISSUE THREAD

**Issue by andylhz-mojie** [paramiko/paramiko#1527]
as title? or this new version is already  resolved?
Disable MD5 and 96-bit MAC algorithms as follow:
  hmac-md5
  hmac-md5-96
  hmac-sha1-96

Disable CBC mode cipher encryption as follow, and enable CTR or GCM cipher mode encryption.
  3des-cbc
  aes128-cbc
  aes192-cbc
  aes256-cbc
  blowfish-cbc

**Comment by ploxiln** [comment]
If you are using the `Transport` class directly, you can call [Transport.get_security_options()](http://docs.paramiko.org/en/2.6/api/transport.html#paramiko.transport.Transport.get_security_options) to get a [SecurityOptions](http://docs.paramiko.org/en/2.6/api/transport.html#paramiko.transport.SecurityOptions) object on which you can get and then set lists of allowed ciphers, macs, etc.

If you are using the `SSHClient` class, you can't do that, but paramiko very recently added the `disabled_algorithm` kwarg to [SSHClient.connect()](http://docs.paramiko.org/en/2.6/api/client.html#paramiko.client.SSHClient.connect) (though it is actually documented under [Transport.__init__()](http://docs.paramiko.org/en/2.6/api/transport.html#paramiko.transport.Transport.__init__))

**Comment by bitprophet** [comment]
See #2054
