### ISSUE TITLE
OSError: Operation unsupported when using posix_rename on folder (Ubuntu 18.04)

### ISSUE THREAD

**Issue by waltner** [paramiko/paramiko#1551]
Hello,

I want to recursively rename my folder structure with a python script from
```/ftp-server/folder_name1/file_name1.ext```
to
```/ftp-server/folder_name2/file_name2.ext```
where `name1` is some identifier that must be changed to `name2`. For files this works without problems, but the following code fails on my system:

``` python
import paramiko
ssh_client = paramiko.SSHClient()
ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh_client.connect("some.server," username="some_user", key_filename="keyfile.pem")

# this line fails:
sftp_client.posix_rename("/ftp-server/folder_name1/", "/ftp-server/folder_name2/")
# this works:
sftp_client.posix_rename("/ftp-server/folder_name1/file_name1.ext", "/ftp-server/folder_name1/file_name2.ext")
```

The error is: `*** OSError: Operation unsupported`

Any idea? Workaround would be to create the target directory (`test_folder2`) copy the directory content from the source directory (`test_folder1`) and delete it afterwards. Copying means down- and uploading which is very inefficient.

Edit: OS: Linux Mint 19.1 (Ubuntu 18.04 based), python 3.6.8

**Comment by ploxiln** [comment]
You can create the target directory, then rename all the files from being in the source directory to being in the target, then delete the source (now empty) directory. Like:

```
sftp_client.mkdir("/ftp-server/folder_name2")
sftp_client.posix_rename("/ftp-server/folder_name1/file_name1.ext", "/ftp-server/folder-name2/file_name1.ext")
...
```

so you'll have to list files and handle folders recursively ...

**Comment by waltner** [comment]
Hi @ploxiln,

thx for the suggestion, it almost worked. I had to use the non-posix rename version like:

```python
ftp_root_dir = '/ftp-server-path/'
src_file = os.path.join(ftp_root_dir, 'folder_name1', 'file_name1.txt')
dst_file = os.path.join(ftp_root_dir, 'folder_name2', 'file_name1.txt')

sftp_client.mkdir(os.path.dirname(src_file))
sftp_client.mkdir(os.path.dirname(dst_file))

f1 = sftp_client.open(src_file, mode='w', bufsize=-1)
f1.close()

# throws 'OSError: Operation unsupported'
# #sftp_client.posix_rename(src_file, dst_file) 

# works
sftp_client.rename(src_file, dst_file)
```

This way the file was moved to the new folder as needed.
