### ISSUE TITLE
consider activation github sponsorship

### ISSUE THREAD

**Issue by ssbarnea** [paramiko/paramiko#1553]
Please consider enabling user to donate using github-sponsor program.

**Comment by XVilka** [comment]
Looks like this project is dead. So many problems with newer OpenSSH keys, dangling and unmerged pull requests, last commit was two months ago...

**Comment by bitprophet** [comment]
Yea, that's out of beta now so I'll be taking a look. Thanks! I'm also on Tidelift, fwiw.
