### ISSUE TITLE
TypeError: public_bytes() takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by sergeyyatmellanox** [paramiko/paramiko#1564]
After upgrading from 2.3.3 to 2.6.0 I get this exception when I try to create new connection:

```
Python 2.7.15 (default, Oct 15 2018, 18:36:25) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> conn = paramiko.SSHClient()
>>> conn.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> conn.connect(host, username=user, password=password, timeout=150.0)
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
TypeError: public_bytes() takes exactly 1 argument (3 given)
```
The same code works fine in 2.3.3.

**Comment by ploxiln** [comment]
What is the version of the `cryptography` module/library on your system? Paramiko now requires cryptograpy 2.5 or later (usually checked in setup.py)

**Comment by sergeyyatmellanox** [comment]
I have cryptography 2.8.

```
$ pip2 show paramiko
Name: paramiko
Version: 2.6.0
Summary: SSH2 protocol library
Home-page: https://github.com/paramiko/paramiko/
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /usr/lib/python2.7/site-packages
Requires: cryptography, pynacl, bcrypt
$ pip2 show cryptography 
Name: cryptography
Version: 2.8
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.
Home-page: https://github.com/pyca/cryptography
Author: The cryptography developers
Author-email: cryptography-dev@python.org
License: BSD or Apache License, Version 2.0
Location: /usr/lib64/python2.7/site-packages
Requires: enum34, cffi, six, ipaddress

```

**Comment by bitprophet** [comment]
This doesn't seem to be a blanket issue since this is the first I've seen of it & can't trivially find others searching. So it may be specific to a given key (type?) in play. @sergeyyatmellanox can you try enabling debug logging (typical stdlib - `import logging; logging.basicConfig(level=logging.DEBUG)`) and also clarify what the remote endpoint is (OS, sshd version, host key type)?

Typically this would be either the remote host key (would be a bit odd) or a local key being loaded by default (i.e. `~/.ssh/id_rsa` and friends, or an SSH agent, tho with the latter I don't see you enabling it so I think it's moot).

**Comment by ploxiln** [comment]
These methods are only called by paramiko in KexCurve25519 and KexNistNNN:

```
paramiko/kex_ecdh_nist.py
41:            self.Q_C.public_bytes(
85:            self.Q_S.public_bytes(
99:            self.Q_S.public_bytes(
128:            self.Q_C.public_bytes(

paramiko/kex_curve25519.py
53:            self.key.public_key().public_bytes(
71:        peer_key = X25519PublicKey.from_public_bytes(peer_key_bytes)
83:        exchange_key_bytes = self.key.public_key().public_bytes(
107:        peer_key = X25519PublicKey.from_public_bytes(peer_key_bytes)
121:            self.key.public_key().public_bytes(

sites/www/changelog.rst
77:  use EllipticCurvePublicKey.public_bytes to obtain both compressed and
```

so it's probably that new paramiko has new kex that is now being used preferentially.

There was a change in cryptography-2.5 for the `X25519PublicKey.public_bytes()` method, adding 2 more arguments. Compare [2.4.2](https://github.com/pyca/cryptography/blob/2.4.2/src/cryptography/hazmat/primitives/asymmetric/x25519.py#L27) and [2.5](https://github.com/pyca/cryptography/blob/2.5/src/cryptography/hazmat/primitives/asymmetric/x25519.py#L28)

So the likely explanation is that, while you have cryptography-2.8 somewhere, python is finding cryptography-2.4 or older source somewhere else, when paramiko imports it.

**Comment by sergeyyatmellanox** [comment]
> This doesn't seem to be a blanket issue since this is the first I've seen of it & can't trivially find others searching. So it may be specific to a given key (type?) in play. @sergeyyatmellanox can you try enabling debug logging (typical stdlib - `import logging; logging.basicConfig(level=logging.DEBUG)`) 
```
>>> conn.connect('XXX', username='XXX', password='XXX', timeout=150.0)
DEBUG:paramiko.transport:starting thread (client mode): 0xc63a7050L
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_7.5
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_7.5)
DEBUG:paramiko.transport:kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'rsa-sha2-512', u'rsa-sha2-256', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes256-ctr', u'aes256-cbc', u'aes128-gcm@openssh.com', u'aes128-ctr', u'aes128-cbc', u'3des-cbc'] server encrypt:[u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes256-ctr', u'aes256-cbc', u'aes128-gcm@openssh.com', u'aes128-ctr', u'aes128-cbc', u'3des-cbc'] client mac:[u'umac-128-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'umac-128@openssh.com', u'hmac-sha1', u'hmac-sha2-256', u'hmac-sha2-512'] server mac:[u'umac-128-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'umac-128@openssh.com', u'hmac-sha1', u'hmac-sha2-256', u'hmac-sha2-512'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
ERROR:paramiko.transport:Unknown exception: public_bytes() takes exactly 1 argument (3 given)
ERROR:paramiko.transport:Traceback (most recent call last):
ERROR:paramiko.transport:  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 2083, in run
ERROR:paramiko.transport:    self._handler_table[ptype](self, m)
ERROR:paramiko.transport:  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 2199, in _negotiate_keys
ERROR:paramiko.transport:    self.kex_engine.start_kex()
ERROR:paramiko.transport:  File "/usr/lib/python2.7/site-packages/paramiko/kex_curve25519.py", line 54, in start_kex
ERROR:paramiko.transport:    serialization.Encoding.Raw, serialization.PublicFormat.Raw
ERROR:paramiko.transport:TypeError: public_bytes() takes exactly 1 argument (3 given)
ERROR:paramiko.transport:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
TypeError: public_bytes() takes exactly 1 argument (3 given)

```

> and also clarify what the remote endpoint is (OS, sshd version, host key type)?
It's Fedora27, OpenSSH_7.5p1, OpenSSL 1.1.0i-fips  14 Aug 2018.

**Comment by sergeyyatmellanox** [comment]
> These methods are only called by paramiko in KexCurve25519 and KexNistNNN:
> 
> ```
> paramiko/kex_ecdh_nist.py
> 41:            self.Q_C.public_bytes(
> 85:            self.Q_S.public_bytes(
> 99:            self.Q_S.public_bytes(
> 128:            self.Q_C.public_bytes(
> 
> paramiko/kex_curve25519.py
> 53:            self.key.public_key().public_bytes(
> 71:        peer_key = X25519PublicKey.from_public_bytes(peer_key_bytes)
> 83:        exchange_key_bytes = self.key.public_key().public_bytes(
> 107:        peer_key = X25519PublicKey.from_public_bytes(peer_key_bytes)
> 121:            self.key.public_key().public_bytes(
> 
> sites/www/changelog.rst
> 77:  use EllipticCurvePublicKey.public_bytes to obtain both compressed and
> ```
> 
> so it's probably that new paramiko has new kex that is now being used preferentially.
> 
> There was a change in cryptography-2.5 for the `X25519PublicKey.public_bytes()` method, adding 2 more arguments. Compare [2.4.2](https://github.com/pyca/cryptography/blob/2.4.2/src/cryptography/hazmat/primitives/asymmetric/x25519.py#L27) and [2.5](https://github.com/pyca/cryptography/blob/2.5/src/cryptography/hazmat/primitives/asymmetric/x25519.py#L28)
> 
> So the likely explanation is that, while you have cryptography-2.8 somewhere, python is finding cryptography-2.4 or older source somewhere else, when paramiko imports it.

Bingo. I had:
```
>> ll /usr/lib64/python2.7/site-packages/ | grep cryptography
drwxr-xr-x  4 root root   4096 Dec  3 19:49 cryptography
drwxr-xr-x  2 root root   4096 Dec  3 19:49 cryptography-2.3-py2.7.egg-info
drwxr-xr-x  2 root root   4096 Dec  3 19:42 cryptography-2.8.dist-info
```
Thanks!
