### ISSUE TITLE
bug of parsing new format keys

### ISSUE THREAD

**Issue by huashengdun** [paramiko/paramiko#1565]
![Screenshot from 2019-12-05 18-02-11](https://user-images.githubusercontent.com/909962/70225331-c87fd280-1789-11ea-9e91-c9cf4aa5dce5.png)

From the screenshot above, you see parsing dsa ed25519 keys succeeded, parsing rsa ecdsa keys failed.
The interesting part is parsing rsa key, paramiko recognize it as both rsa and dss type key.

**Comment by huashengdun** [comment]
generate dsa ecdsa ed25519 rsa private keys
```bash
for t in dsa ecdsa ed25519 rsa; do ssh-keygen -t $t -f id_$t -q -N "" && rm *.pub; done
```

parse.py

```python
import sys
from paramiko import DSSKey, ECDSAKey, Ed25519Key, RSAKey


filenames = sys.argv[1:]
keyclasses = [DSSKey, ECDSAKey, Ed25519Key, RSAKey]


for filename in filenames:
    print('Parsing {}'.format(filename))
    print('='*20)
    for keycls in keyclasses:
        try:
            print(keycls.__name__, end=' ')
            key = keycls(filename=filename)
        except Exception as e:
            print('x')
        else:
            print('√')
        print('-'*20)
    print()
```
```

**Comment by ploxiln** [comment]
The bug with new-format ECDSAKey was mentioned here: https://github.com/paramiko/paramiko/pull/1343#discussion_r286619386 (and was not addressed in that pull-request, but I think the maintainer was under the impression that it was addressed)

**Comment by huashengdun** [comment]
Notice the bug of parsing rsa key still has not been fixed yet.
Although paramiko can recognize the rsa type key correctly, but there are still chances that paramiko recognizes the ras key as the DSS type key.
