### ISSUE TITLE
Not able to move to another folder using exec_command

### ISSUE THREAD

**Issue by Jithinqw** [paramiko/paramiko#1576]
When controlling an SSH session, I am not able to change the directories using exec_command
   ```
 stdin,stdout,stderr = session.exec_command('cd sales_coach_bot')
    print(stderr.readlines())
    print(stdout.readlines())
```
`stderr.readlines() `and `stdout.readlines()` is returning as empty array.

**Comment by Mr-ZBin** [comment]
yes, I have the save problem. when I cd to other folder, it's always return the default folder to me. But I really think it should same with putty when I cd to other folder.

**Comment by Jithinqw** [comment]
Hi @Mr-ZBin,
 This is because according to the paramiko documentation the adding multiple commands should be done in a single SSH instance. For each command paramiko will create a new channel for executing the command. So you can do this,

`session_obj = self.ssh_instance.connect(
                hostname=host_name, username=user_name, pkey=session_key
            )
session_obj.exec_command('cd my_site\nls\n')
`
for multiple commands work around.
