### ISSUE TITLE
ERROR: Could not build wheels for cryptography, pynacl which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by waldemarstal** [paramiko/paramiko#1579]
I wanted to install paramiko in my docker container (using image python:3.7-alpine) and I can't do it.

![image](https://user-images.githubusercontent.com/1853938/71128544-bec88700-21ed-11ea-9673-272ead99ca69.png)

I would like to add that locally I can install paramiko normally.
Can somebody told me how I can use paramiko in docker?

**Comment by ploxiln** [comment]
It depends on the base docker image you are using. It looks like you need to `apt-get install make` or `apk add make` or equivalent for that distro image (and then possibly more stuff).

**Comment by waldemarstal** [comment]
@ploxiln you're right, thanks :)
