### ISSUE TITLE
Problem with installing on Kali Linux

### ISSUE THREAD

**Issue by Florent22** [paramiko/paramiko#1586]
## UPDATE

I was able to fix it, the following package had to be installed: 

> libffi-dev

according to this topic: [https://stackoverflow.com/questions/31508612/pip-install-unable-to-find-ffi-h-even-though-it-recognizes-libffi](url)

##  Problem

Im currently trying to install Paramiko on my Rasperyy Pi 3 (running Kali Linux).  

The installation finishes with the error message below. Does anyone knows where the problem could be located and solved ?

I use this command: 

>  sudo pip3 install paramiko

The result is the message below

## Error

> root@kali:~/routersploit# sudo pip3 install paramiko
> ^XCollecting paramiko
>   Using cached https://files.pythonhosted.org/packages/06/1e/1e08baaaf6c3d3df1459fd85f0e7d2d6aa916f33958f151ee1ecc9800971/paramiko-2.7.1-py2.py3-none-any.whl
> Requirement already satisfied: cryptography>=2.5 in /usr/lib/python3/dist-packages (from paramiko) (2.6.1)
> Collecting pynacl>=1.0.1 (from paramiko)
>   Using cached https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz
>   Installing build dependencies ... error
>   Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-oqjd39ae --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "cffi>=1.4.1; python_implementation != 'PyPy'":
>   Collecting setuptools
>     Using cached https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl
>   Collecting wheel
>     Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
>   Collecting cffi>=1.4.1
>     Using cached https://files.pythonhosted.org/packages/2d/bf/960e5a422db3ac1a5e612cb35ca436c3fc985ed4b7ed13a1b4879006f450/cffi-1.13.2.tar.gz
>   Collecting pycparser (from cffi>=1.4.1)
>   Building wheels for collected packages: cffi
>     Running setup.py bdist_wheel for cffi: started
>     Running setup.py bdist_wheel for cffi: finished with status 'error'
>     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-nzo0df94/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-s2lqp7y0 --python-tag cp37:
>     running bdist_wheel
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-aarch64-3.7
>     creating build/lib.linux-aarch64-3.7/cffi
>     copying cffi/vengine_gen.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/lock.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/cparser.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/commontypes.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/recompiler.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/ffiplatform.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/__init__.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/pkgconfig.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/error.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/model.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/verifier.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/api.py -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/_cffi_include.h -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/parse_c_type.h -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/_embedding.h -> build/lib.linux-aarch64-3.7/cffi
>     copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-3.7/cffi
>     running build_ext
>     building '_cffi_backend' extension
>     creating build/temp.linux-aarch64-3.7
>     creating build/temp.linux-aarch64-3.7/c
>     aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-aarch64-3.7/c/_cffi_backend.o
>     c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
>        15 | #include <ffi.h>
>           |          ^~~~~~~
>     compilation terminated.
>     error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
> 
>     ----------------------------------------
>     Failed building wheel for cffi
>     Running setup.py clean for cffi
>   Failed to build cffi
>   Installing collected packages: setuptools, wheel, pycparser, cffi
>     Running setup.py install for cffi: started
>       Running setup.py install for cffi: finished with status 'error'
>       Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-nzo0df94/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-r5dkmsbn/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-oqjd39ae --compile:
>       running install
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-aarch64-3.7
>       creating build/lib.linux-aarch64-3.7/cffi
>       copying cffi/vengine_gen.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/backend_ctypes.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/lock.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/cparser.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/commontypes.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/setuptools_ext.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/recompiler.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/ffiplatform.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/__init__.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/vengine_cpy.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/pkgconfig.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/error.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/cffi_opcode.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/model.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/verifier.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/api.py -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/_cffi_include.h -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/parse_c_type.h -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/_embedding.h -> build/lib.linux-aarch64-3.7/cffi
>       copying cffi/_cffi_errors.h -> build/lib.linux-aarch64-3.7/cffi
>       running build_ext
>       building '_cffi_backend' extension
>       creating build/temp.linux-aarch64-3.7
>       creating build/temp.linux-aarch64-3.7/c
>       aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-aarch64-3.7/c/_cffi_backend.o
>       c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
>          15 | #include <ffi.h>
>             |          ^~~~~~~
>       compilation terminated.
>       error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
> 
>       ----------------------------------------
>   Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-nzo0df94/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-r5dkmsbn/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-oqjd39ae --compile" failed with error code 1 in /tmp/pip-install-nzo0df94/cffi/
> 
>   ----------------------------------------
> Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-oqjd39ae --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "cffi>=1.4.1; python_implementation != 'PyPy'"" failed with error code 1 in None
> 
> 

## My Environment
* Operating System and version: Raspberry Pi 3 - Kali Linux
* Python Version: 3.7.5
* Python3-Pip version : 18.1-5

**Comment by MrMino** [comment]
@Florent22 please close the issue if you managed to fix the problem yourself.
