### ISSUE TITLE
Inconsistent output length with get_pty()

### ISSUE THREAD

**Issue by spulm** [paramiko/paramiko#1591]
Was wondering if somebody could shed some light on the below behavior.

I rely on back and forth communication with the remote server, hence I use `get_pty()` (default width of 80 characters) and `invoke_shell()`. I then run two different 'ps' commands with different arguments on the server which should return some processes that I am interested in. What I noted is that with one of the two commands, the pty width of 80 characters is enforced, and with the other one this is not the case. See below code to demonstrate this behavior

```
import paramiko
import socket

def receive_output(some_channel):
    data = b''
    while True:
        if some_channel.recv_ready():
            data += some_channel.recv(1024)

        if data.endswith(b'~]$ '):
            return data.decode()


sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(('192.168.1.100', 22))
transport = paramiko.Transport(sock)
transport.start_client()
transport.auth_password('username', 'password')
channel = transport.open_channel('session')
channel.get_pty()
channel.invoke_shell()

channel.sendall('ps -ef|grep gluster_volmgr|grep -v grep\n')
output_1 = receive_output(channel)
print('output 1:')
for line in output_1.splitlines():
    print(line)


print(2 * '\n')
print(50 * '-')


channel.sendall('ps -fp $(pgrep gluster_volmgr)\n')
output_2 = receive_output(channel)
print('output 2:')
for line in output_2.splitlines():
    print(line)

channel.close()
transport.close()
```

And the output:

```
output 1:
Last login: Wed Jan  8 08:57:47 2020 from 192.168.222.98

rootA
ps -ef|grep gluster_volmgr|grep -v grep
[username@LRTBPP1 ~]$ ps -ef|grep gluster_volmgr|grep -v grep
root     23853 23623  0  2019 ?        00:01:41 gluster_volmgr -pid 10000 -pn gluster_volmgr -ipc ilrm_0_IPC -adm eth0.1 -cluster_id 123225 -cp 10000 -mode pp_mnc -nms_obj_id 123228 -pp_id 128 -rid idirect_gluster_volume_mgr -sid 11 -tun eth0.4048 
[username@LRTBPP1 ~]$ 



--------------------------------------------------
output 2:
ps -fp $(pgrep gluster_volmgr)
UID        PID  PPID  C STIME TTY          TIME CMD
root     23853 23623  0  2019 ?        00:01:41 gluster_volmgr -pid 10000 -pn gl
[username@LRTBPP1 ~]$ 

Process finished with exit code 0
```

As per above, the output of the first command matches the full line, however the output of the second command is cut of at exactly 80 characters. This is consistently happening, and the order in which these commands are executed has no effect, it is always `ps -p $(pgrep gluster_volmgr)` where the output is cut off at 80 characters. Note that this is also the case when I hard code the PID (e.g. `ps -fp 23853`.

This is not a major issue, as there are easy workarounds, but I was wondering what the cause might be. 

On a different note, I also noted that the first command that is sent after `invoke_shell()` is always printed present twice the output, as per above. Is the command actually sent to the server twice?

**Comment by ploxiln** [comment]
This behavior of `ps` is not related to paramiko - try it locally on your own machine (or using the openssh client to access some other unix machine). When you pipe `ps` through anything, in your case `grep`, then it does not detect that stdout is a tty (because it is a pipe instead), and does not trim the lines.

**Comment by spulm** [comment]
You are certainly correct. If I pipe the output into some other process (e.g. cat), then it does return the full output. Thanks for clarifying!
