### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by goertzenator** [paramiko/paramiko#16]
I have Paramiko running on Python 3 at https://github.com/goertzenator/paramiko

All unit tests, except for sftp, pass.  Needs documentation updates for the many str -> bytes changes.

Looking for advice on what to do with this.  Adding a python 3 branch to paramiko would have a lot of complications...

**Comment by TeeBSD** [comment]
Error from python 3.4.3:     
from Crypto.Util import _counter
ImportError: Cannot load specified object

**Comment by Russell-Jones** [comment]
@TeeBSD could you 
a) provide more context. e.g. Why is an error from Crypto to do with paramiko? Which OS and version of paramiko? How was it installed?
b) open a new ticket for this issue if there isn't one already

**Comment by Lazik** [comment]
Paramiko uses pyCrypto.
It's more about how/which version of pyCrypto you installed.
