### ISSUE TITLE
Paramiko SFTP not using custom port for connecting

### ISSUE THREAD

**Issue by JulianCeaser** [paramiko/paramiko#1605]
I use paramiko for uploading and downloading files over SFTP however today I found out it always connects using the default port 22 instead of a given custom port.
I verified by manually connecting to the server using the paramiko sftp client and doing a listdir() and found that it is connecting to the default port 22 everytime.
Here are the commands I used 
```
import paramiko
transport = paramiko.Transport('IP', port)
transport.connect(username='user', password='pass')
sftp = paramiko.SFTPClient.from_transport(transport)
sftp.listdir()
transport.close()
```
Please me resolve this issue. It is breaking a lot of things since we often do not use the default port for sftp.

**Comment by ploxiln** [comment]
`paramiko.Transport('IP', port)` is not correct. You can do either:
  * `paramiko.Transport("IP:port")`
  * `paramiko.Transport(('IP', port))`

(extra parentheses are because (ip,port) needs to be a single tuple argument)

**Comment by JulianCeaser** [comment]
Thank you, this solved the issue for me. Wasn't quite clear to me from the docs.
