### ISSUE TITLE
Support stronger MAC schemes

### ISSUE THREAD

**Issue by EtiennePerot** [paramiko/paramiko#161]
As of this writing, the strongest MAC supported by Paramiko is `hmac-sha1`. Since [OpenSSH 5.9](http://www.openssh.com/txt/release-5.9), stronger MAC schemes such as `hmac-sha2-512` and `hmac-sha2-256` are available.

Additionally, [OpenSSH 6.2](http://www.openssh.com/txt/release-6.2) added Encrypt-Then-MAC (ETM) schemes as well, which are [even](http://www.daemonology.net/blog/2009-06-24-encrypt-then-mac.html) [safer](http://crypto.stackexchange.com/questions/202/should-we-mac-then-encrypt-or-encrypt-then-mac) and are therefore used by default since 6.2. These are available under OpenSSH as `hmac-sha2-512-etm@openssh.com`, `hmac-sha2-256-etm@openssh.com`, `hmac-sha1-etm@openssh.com`, etc.

It would be nice if Paramiko kept up with this.

**Comment by ThomasWaldmann** [comment]
OMG, I am stumbling over a 2013 ticket. :-(

I am trying to use paramiko as a client, doing sftp against some relatively securely configured server.

```
    t.connect(hostkey, user, passwd)
  File "...env/lib/python3.5/site-packages/paramiko/transport.py", line 1218, in connect
    self.start_client()
  File "...env/lib/python3.5/site-packages/paramiko/transport.py", line 587, in start_client
    raise e
  File "...env/lib/python3.5/site-packages/paramiko/transport.py", line 2010, in run
    self._handler_table[ptype](self, m)
  File "...env/lib/python3.5/site-packages/paramiko/transport.py", line 2125, in _negotiate_keys
    self._parse_kex_init(m)
  File "...env/lib/python3.5/site-packages/paramiko/transport.py", line 2365, in _parse_kex_init
    raise SSHException("Incompatible ssh server (no acceptable macs)")
paramiko.ssh_exception.SSHException: Incompatible ssh server (no acceptable macs)
```

From the log:
```
client mac:[
'hmac-sha2-512-etm@openssh.com',
'hmac-sha2-256-etm@openssh.com',
'hmac-ripemd160-etm@openssh.com',
'umac-128-etm@openssh.com'
]
server mac: [
'hmac-sha2-512-etm@openssh.com',
'hmac-sha2-256-etm@openssh.com',
'hmac-ripemd160-etm@openssh.com',
'umac-128-etm@openssh.com'
]
```

**Comment by dIgor93** [comment]
When server settings are:
```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
HostKeyAlgorithms ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-ed25519
```
i got error from paramiko client
```
Execute on ip_host: /usr/bin/env python2 -c "import tempfile; print tempfile.mkdtemp();"
Exception: Incompatible ssh server (no acceptable macs)
Traceback (most recent call last):
  File "/home/user/.virtualenvs/stab_test/lib/python2.7/site-packages/paramiko/transport.py", line 2010, in run
    self._handler_table[ptype](self, m)
  File "/home/user/.virtualenvs/stab_test/lib/python2.7/site-packages/paramiko/transport.py", line 2125, in _negotiate_keys
    self._parse_kex_init(m)
  File "/home/user/.virtualenvs/stab_test/lib/python2.7/site-packages/paramiko/transport.py", line 2365, in _parse_kex_init
    raise SSHException("Incompatible ssh server (no acceptable macs)")
SSHException: Incompatible ssh server (no acceptable macs)
```

**Comment by mikeln** [comment]
Same error connecting to Azure VMs. "Incompatible ssh server (no acceptable macs)"
on the azure vm: MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

paramiko:  _preferred_macs = (
"hmac-sha2-256",
"hmac-sha2-512",
"hmac-sha1",
"hmac-md5",
"hmac-sha1-96",
"hmac-md5-96",

**Comment by mikeln** [comment]
Looks like this will fix the issue: https://github.com/paramiko/paramiko/pull/1233

**Comment by bitprophet** [comment]
Thanks for digging that up, @mikeln - that ticket is in my top priority milestone so it should get handled RSN. Closing this.
