### ISSUE TITLE
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key

### ISSUE THREAD

**Issue by bse-sja** [paramiko/paramiko#1612]
Providing key file name to client.connect
Key file starts with -----BEGIN RSA PRIVATE KEY----- and end with -----END RSA PRIVATE KEY-----
Code works fine under linux but on windows I get:
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key

python3.8 on windows. python3.6 on linux. 
Windows deps:
paramiko==2.7.1
  - bcrypt [required: >=3.1.3, installed: 3.1.7]
    - cffi [required: >=1.1, installed: 1.13.2]
      - pycparser [required: Any, installed: 2.19]
    - six [required: >=1.4.1, installed: 1.14.0]
  - cryptography [required: >=2.5, installed: 2.8]
    - cffi [required: >=1.8,!=1.11.3, installed: 1.13.2]
      - pycparser [required: Any, installed: 2.19]
    - six [required: >=1.4.1, installed: 1.14.0]
  - pynacl [required: >=1.0.1, installed: 1.3.0]
    - cffi [required: >=1.4.1, installed: 1.13.2]
      - pycparser [required: Any, installed: 2.19]
    - six [required: Any, installed: 1.14.0]

Linux deps:
paramiko==2.7.1
  - bcrypt [required: >=3.1.3, installed: 3.1.7]
    - cffi [required: >=1.1, installed: 1.12.3]
      - pycparser [required: Any, installed: 2.19]
    - six [required: >=1.4.1, installed: 1.12.0]
  - cryptography [required: >=2.5, installed: 2.7]
    - asn1crypto [required: >=0.21.0, installed: 0.24.0]
    - cffi [required: >=1.8,!=1.11.3, installed: 1.12.3]
      - pycparser [required: Any, installed: 2.19]
    - six [required: >=1.4.1, installed: 1.12.0]
  - pynacl [required: >=1.0.1, installed: 1.1.2]

**Comment by ploxiln** [comment]
That is a misleading exception, due to this logic in the client:

https://github.com/paramiko/paramiko/blob/2.7.1/paramiko/client.py#L674

It tries to load the keyfile with each key type, and if there is some error/exception it continues on to the next key type, but it also saves the last exception encountered. So loading your RSA key as an `RSAKey` had some error, and after that it tried `ECDSAKey`, and then `Ed25519Key`, and that error that was printed is from when your RSA keyfile was loaded as an `Ed25519Key`.

You can try running `RSAKey.from_private_key_file("path/to/your/keyfile")` to see what the problem with loading it as an RSAKey is.

I also notice that the version of cryptography installed is different, you could try getting both windows and linux on the same version of cryptography, just as an experiment to narrow-down the issue.

**Comment by mirceaulinic** [comment]
I've bumped into the same issue, when using a perfectly usable RSA key:

```
[DEBUG   ] Kex agreed: curve25519-sha256@libssh.org
[DEBUG   ] HostKey agreed: ssh-ed25519
[DEBUG   ] Cipher agreed: aes128-ctr
[DEBUG   ] MAC agreed: hmac-sha2-256
[DEBUG   ] Compression agreed: none
[DEBUG   ] kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
[DEBUG   ] Switch to new keys ...
[DEBUG   ] [host <host> session 0x7f28264e9668] Private key file is encrypted
[DEBUG   ] [host <host> session 0x7f28264e9668] encountered RSA key, expected DSA key
[DEBUG   ] [host <host> session 0x7f28264e9668] encountered RSA key, expected EC key
[DEBUG   ] [host <host> session 0x7f28264e9668] encountered RSA key, expected OPENSSH key
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jnpr/junos/device.py", line 1339, in open
    "use_filter": self._use_filter,
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 168, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 135, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 362, in connect
    self._auth(username, password, key_filenames, allow_agent, look_for_keys)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 464, in _auth
    raise AuthenticationError(repr(saved_exception))
ncclient.transport.errors.AuthenticationError: SSHException('encountered RSA key, expected OPENSSH key',)
```

The key header is:

```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
```


If using a different key, no password protected (!), it works fine, so I think it rather sounds like a preamble issue as per #1641.

**Comment by guyskk** [comment]
I see this exception when the public key not in the server user's authorized keys (so login failed), it's a very misleading exception.

**Comment by Micsi** [comment]
It can also happen if the key has a passphrase set and the phrase is not in your ssh-agent.

Very misleading indeed ;-)

**Comment by gormux** [comment]
I happens also simply if you have an authentication error.
I got this exact problem when I forgot to change the username that connects to a server in the paramiko configuration (it used the local username, and not anymore).

So yeah, very misleading.

**Comment by andrew-lee-metaswitch** [comment]
I hit this today, and yeah, it's irritating.

I wonder if we can fix this by being careful in client.py about not necessarily setting saved_exception  to the last exception it hit. To be honest, what is really required is adding much more granular Exception classes. Or perhaps some way to compare exceptions for their relative importance.

**Comment by doguz2509** [comment]
I got this error with Ubuntu14 on AWS (kernel: 3.13.0-74-generic)
I cannot login into vm with paramiko, but I must use it
Are some workaround available?

**Comment by mewa** [comment]
I tested this and this behaviour was introduced in paramiko 2.9.0. A key that works fine on 2.8.1 fails on 2.9.0.

**Comment by MichaelKueller** [comment]
I'm running into the same issue. I can confirm that it worked with 2.8.1 but started failing when upgrading to 2.9.0

**Comment by bitprophet** [comment]
Those of you having "this error" on 2.9 in particular, are likely hitting issues with RSA2 key handshaking and then (as noted by other commenters) encountering the overall problem of #387 re: the auth logic presenting misleading final errors.

If you haven't yet, please check [the changelog](https://paramiko.org/changelog.html) re: the possible need to supply `disabled_algorithms`, and also make sure you've tried the 2.10.x line as this adds some bugfixes to the RSA2 feature area (eg for OpenSSH<7.8 targets).

**Comment by QGB** [comment]
SSHException('encountered EC key, expected OPENSSH key')

**Comment by ranjithreddyn9** [comment]
I'm getting the same (encountered RSA key, expected OPENSSH key) error while creating and testing SSH/SFTP connection profile  to AIX server from Airflow web portal.

**Comment by sdarwin** [comment]
Hi, I just hit the error 

```
paramiko.ssh_exception.SSHException: encountered RSA key, expected OPENSSH key
```

Could the source code be enhanced to be more verbose when it hits this error? If the answer is that it "seems to expect ed25519 type key", it could probably say that more clearly, about how RSA is deprecated.  This is just very terse. "encountered RSA key, expected OPENSSH key".

**Comment by bskinn** [comment]
@ranjithreddyn9, @sdarwin -- this ticket is closed. Please make sure you have tried the [solution indicated by bitprophet](https://github.com/paramiko/paramiko/issues/1612#issuecomment-1146216252).

If that still doesn't work for you, please open new support tickets and include a reference back to this issue.

Thanks!

**Comment by TarunCore** [comment]
> That is a misleading exception, due to this logic in the client:
> 
> https://github.com/paramiko/paramiko/blob/2.7.1/paramiko/client.py#L674
> 
> It tries to load the keyfile with each key type, and if there is some error/exception it continues on to the next key type, but it also saves the last exception encountered. So loading your RSA key as an `RSAKey` had some error, and after that it tried `ECDSAKey`, and then `Ed25519Key`, and that error that was printed is from when your RSA keyfile was loaded as an `Ed25519Key`.
> 
> You can try running `RSAKey.from_private_key_file("path/to/your/keyfile")` to see what the problem with loading it as an RSAKey is.
> 
> I also notice that the version of cryptography installed is different, you could try getting both windows and linux on the same version of cryptography, just as an experiment to narrow-down the issue.

Everyone try this to know what is the actual error. In my case I had a newline in top of the key file
