### ISSUE TITLE
Paramiko terminal window size

### ISSUE THREAD

**Issue by NSimpraga** [paramiko/paramiko#1619]
Hi all, 

I want to know if it's possible to resize the virtual terminal windows paramiko opens when I connect to a remote server using SSH. I have a problem with the print output of a command I run, the data does not fit inside the window paramiko opens so half of the output table doesn't even get printed out.

I saw the invoke_shell command has the height&width parameters but it doesn't change my output when I set to a different value. As a matter of fact, I connect and execute the commands without even using the invoke_shell comand.

Here is the code:

```
import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('myIP', username='myUsername', password='myPassword')
stdin, stdout, stderr = client.exec_command('ip firewall connection print')
for line in stdout:
    print(line.strip('\n'))
    
client.close()
```

What and how do I need to add to resize the terminal window paramiko opens?

**Comment by ploxiln** [comment]
you could try the technique from https://github.com/paramiko/paramiko/pull/1526

**Comment by ploxiln** [comment]
I should clarify: paramiko does not open or resize terminal windows, it just uses whatever terminal "tty" it is running in. That link shows a way you can try to detect the size of the terminal paramiko is running in, and communicate it to the remote process currently running. You may have some other library or component which is opening the local terminal window.

**Comment by NSimpraga** [comment]
Just to update - switched to librouteros instead of paramiko because every potential solution seemed too complicated.
