### ISSUE TITLE
Request a login shell

### ISSUE THREAD

**Issue by alexandernst** [paramiko/paramiko#1645]
Is there a way to make Paramiko's `exec_command` run a command inside a logged-in shell? (a shell with all the environment variables / settings loaded from `/etc/profile`, `.bashrc`, etc...)

I tried using the argument `get_pty`, but that doesn't seem to be achieving my goal.

**Comment by ploxiln** [comment]
something like `...exec_command('bash -l -c "<your command properly escaped>"')`

**Comment by alexandernst** [comment]
But this assumes having `bash` in the machine that I'm running the commands. Is there a way I can use whatever the default shell is?

**Comment by ploxiln** [comment]
`/bin/sh -l -c "..."` should always work.

If you want some special signal to tell sshd on the remote end to use a "login shell" to run a command, then I am not aware of such a thing (besides "invoke_shell()" which you have to control interactively).

**Comment by alexandernst** [comment]
Fair enough. I think I'll go on with `invoke_shell`
