### ISSUE TITLE
Expose lists of advertised crypto algorithms

### ISSUE THREAD

**Issue by blackbit42** [paramiko/paramiko#1652]
When paramiko is acting as an SSH server, a client is connecting to it and advertises lists of supported crypto algorithms. of various categories. Currently these lists are not accessible to programs that use paramiko.
Note that I don't mean the algorithms that are agreed upon, but the list of supported algorithms that are used as foundation for negotiation.
Please consider exposing these lists.

- Symmetric ciphers (aes256-gcm@openssh.com, chacha20-poly1305@openssh.com, ...)
- Message authentication codes (hmac-sha2-256, umac-64-etm@openssh.com, ...)
- Key exchange algorithms (diffie-hellman-group1-sha1, curve25519-sha256, ...) - incl GSS variants
- Key types (ssh-rsa, sk-ssh-ed25519@openssh.com, ...) - I am not 100% sure these are advertised

**Comment by blackbit42** [comment]
Any update on this?
Is it deemed to be feasible to implement this?
@bitprophet  are you in favor of the idea?

**Comment by bitprophet** [comment]
See #2054
