### ISSUE TITLE
Setting Transport.connect auth_timeout

### ISSUE THREAD

**Issue by jdshkolnik** [paramiko/paramiko#1695]
Hi,

I see [auth_timeout defaults to 30 at init](https://github.com/paramiko/paramiko/blob/ae3d0febef17a8ece5268bbf6c210a30573ce800/paramiko/transport.py#L489). How would I set that during a call to transport.connect? Something like this...

```
transport = paramiko.Transport((hostname, port)
transport.auth_timeout = 60
transport.connect(self=transport, username=username, password=password, pkey=pkey)
```

**Comment by ploxiln** [comment]
Yes, it seems that is the intended way, that is how `SSHClient` does it:

https://github.com/paramiko/paramiko/blob/2.7.1/paramiko/client.py#L386-L389

**Comment by jdshkolnik** [comment]
I think my error is in the call to transport.connect() with that first "self" parameter. It's probably just my inexperience with Python. Is the reference to my instantiated "transport" already implied by "self" without trying to pass it in?

**Comment by ploxiln** [comment]
ah, yes, do not pass "self", it is automatic
