### ISSUE TITLE
python3.7 + paramiko2.71 + pyinstaller：Error reading SSH protocol banner

### ISSUE THREAD

**Issue by TIanCat** [paramiko/paramiko#1717]
I run my code in pycharm as follows:
`import paramiko

ssh=paramiko.Transport(('192.168.0.128',22))

ssh.connect(username='xx',password='xx')

sftp=paramiko.SFTPClient.from_transport(ssh)

#Copy a local file (localpath) to the SFTP server as remotepath
sftp.put('user.ini','/data/wj/123/1.ini')

ssh.close()`
It execute successfully and the file "user.ini" indeed is uploaded from client to sever. But when the code is built to ".exe" by pyinstaller, it report a error:`Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "site-packages\paramiko\transport.py", line 2211, in _check_banner
  File "site-packages\paramiko\packet.py", line 380, in readline
  File "site-packages\paramiko\packet.py", line 609, in _read_timeout
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\paramiko\transport.py", line 2039, in run
  File "site-packages\paramiko\transport.py", line 2216, in _check_banner
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner`

I tried the method : modifying banner_timeout = 300 but it is useless. Can you give me some advices?

**Comment by Kani999** [comment]
@TIanCat Did you solved the issue? I'm still running into the same error

**Comment by jun66j5** [comment]
> @TIanCat Did you solved the issue? I'm still running into the same error

I don't think it is good idea to post "same error" comment to every issue.

**Comment by Kani999** [comment]
@jun66j5 I'm trying to add some logs too because I don't see which of the issue is trying to be fixed.

**Comment by TIanCat** [comment]
@jun66j5 @Kani999  I don't know why you have the same problem，but the client is encrypted in my case. After my software is added to the whitelist, the problem did not reappear.
