### ISSUE TITLE
paramiko/2.7.1: tests/configs/ directory is missing, leading to test failures

### ISSUE THREAD

**Issue by sandrotosi** [paramiko/paramiko#1726]
Hello,
while updating paramiko/2.7.1 for debian, we discovered that `tests/configs/` directory is not included in the tarball released to PyPI, this leads to test failures when running the testsuite:

```
...
tests/test_config.py EEEEEEEEEEEEEEEEEEEEEEEEEE..................FFFFFFFsFFFFFFFFssssssFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
...

self = <tests.test_config.TestSSHConfig object at 0x7f281ce91a90>

    def setup(self):
>       self.config = load_config("robey")

tests/test_config.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_config.py:49: in load_config
    return SSHConfig.from_path(_config(name))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'paramiko.config.SSHConfig'>, path = '/build/paramiko-2.7.1/.pybuild/cpython3_3.8_paramiko/build/tests/configs/robey'

    @classmethod
    def from_path(cls, path):
        """
        Create a new, parsed `SSHConfig` from the file found at ``path``.
    
        .. versionadded:: 2.7
        """
>       with open(path) as flo:
E       FileNotFoundError: [Errno 2] No such file or directory: '/build/paramiko-2.7.1/.pybuild/cpython3_3.8_paramiko/build/tests/configs/robey'

paramiko/config.py:108: FileNotFoundError
...etc...
```

can you please include that directory in the next release so that we can tests run without failure? thanks!

**Comment by MrMino** [comment]
Pretty sure the tests should not be the part of a python distribution. Why would you want them to be there?

**Comment by sandrotosi** [comment]
what? you want tests to verify that the installation and build process worked?

**Comment by MrMino** [comment]
You do that in CI. Python distributions are meant to go into production environments, where tests for a dependency would not be used.

**Comment by sandrotosi** [comment]
Do you know what a linux binary distribution is (Debian in this case)?

also, what are you arguing for? tests are already included in the PyPI tarball, they're just not fully functional right now.

**Comment by MrMino** [comment]
You are talking about a Debian source distribution or a Python distribution? Those are two different things. If it is, I'd rather post an  issue so that it is removed. There's barely any reason to pack up those with a build for PyPI.

**Comment by sandrotosi** [comment]
if you cared to read the first sentence of my original message it says "while updating paramiko/2.7.1 for debian" so i'm talking about debian, yeah...

Do as you please, i just want to make the tests *as currently provided* functional again.

removing tests is just wrong, but i'm not gonna try to convince you, given you have no interest to listen.

@bitprophet your opinion on this, please?

**Comment by MrMino** [comment]
I'm also pretty positive, that debian binary distributions are stripped of any tests for the files they provide. I'd be happy to be corrected.

**Comment by sandrotosi** [comment]
that's not done automatically or actively, it depends on what the specific module installs. regardless of if they end up in the final binary packages, we still run the test suite at build time against the freshly built module

**Comment by MrMino** [comment]
Ugh, just realized that these are the ->sdists<- you're talking about, in which case... Brainfart on my side. Yea, no objections there.

**Comment by sandrotosi** [comment]
well, i made that clear in the original post with "not included in the tarball released to PyPI"

**Comment by MrMino** [comment]
True. As an apology for being dumb, I'll PR this. Give me a sec.

**Comment by bitprophet** [comment]
I really hate having to remember to put stuff explicitly in the manifest file (as noted in the PR, I plumb forgot when refactoring the test fixtures for improved SSH config support). Definitely something to add (unpack the sdist and try running the tests from it) when I overhaul CI. Thanks all.

**Comment by bitprophet** [comment]
Rolling into PR which I am merging shortly.
