### ISSUE TITLE
SFTP uploading fails when trying to update an opened file

### ISSUE THREAD

**Issue by antoscha** [paramiko/paramiko#1731]
```
Traceback (most recent call last):
  File "mapper.py", line 115, in <module>
    main()
  File "mapper.py", line 89, in main
    upload(bs)
  File "mapper.py", line 77, in upload
    sftp.putfo(csv, path)
  File "/usr/lib/python3.8/site-packages/paramiko/sftp_client.py", line 714, in putfo
    with self.file(remotepath, "wb") as fr:
  File "/usr/lib/python3.8/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python3.8/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/usr/lib/python3.8/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3.8/site-packages/paramiko/sftp_client.py", line 898, in _convert_status
    raise IOError(text)
OSError: Failure
```  
Is there any way to update a file without closing it on the remote machine?

**Comment by MrMino** [comment]
If we're talking about a Windows host - no, not in the general case. The way Windows locks files upon opening them by a process is rooted deeply in the system. The behavior of file locking may be in some ways altered by [`dwShareMode` parameter to `CreateFile`](https://docs.microsoft.com/pl-pl/windows/win32/api/fileapi/nf-fileapi-createfilea?redirectedfrom=MSDN), but it's something that would have to be implemented server-side in a cooperative fashion

If we're talking about a Linux host - boy oh boy, why are you using mandatory file locks? [The feature is unreliable and might be removed in the future.](https://man7.org/linux/man-pages/man2/fcntl.2.html#DESCRIPTION:~:text=Warning%3A%20the%20Linux%20implementation%20of%20mandatory,removing%20this%20feature%20completely.)

**Comment by MrMino** [comment]
If we're talking about a Windows host - no, not in the general case. The way Windows locks files upon opening them by a process is rooted deeply in the system. The behavior of file locking may be in some ways altered by [`dwShareMode` parameter to `CreateFile`](https://docs.microsoft.com/pl-pl/windows/win32/api/fileapi/nf-fileapi-createfilea?redirectedfrom=MSDN), but it's something that would have to be implemented server-side in a cooperative fashion

If we're talking about a Linux host - why are you using mandatory file locks? [The feature is unreliable and might be removed in the future.](https://man7.org/linux/man-pages/man2/fcntl.2.html#DESCRIPTION:~:text=Warning%3A%20the%20Linux%20implementation%20of%20mandatory,removing%20this%20feature%20completely.)

**Comment by antoscha** [comment]
Yes, we're talking about a Windows host. Thank you for the link!
