### ISSUE TITLE
why does stdin.write work wrong?

### ISSUE THREAD

**Issue by jiliguluss** [paramiko/paramiko#1755]
when I config openvpn on linux server, it needs to input user and password for authentication, like this:
[![enter image description here][1]][1]

> szvpdb00013:~ # openvpn --cd /etc/openvpn --config /etc/openvpn/client.ovpn --daemon

> Enter Auth Username: ********* 

> Enter Auth Password: **********

I want to config openvpn with paramiko. So I store user and pwd in tuple (user, pwd), and I want to input user and pwd with stdin. The python code is like this：

    ssh_client = paramiko.SSHClient()
    ssh_client.connect(server_ip, server_port, server_user, server_pwd)

    stdin, stdout, stderr = ssh_client.exec_command("openvpn --cd /etc/openvpn --config /etc/openvpn/client.ovpn --daemon")
    
    for val in (user, pwd):
        stdin.write(val + '\n')
        stdin.flush()

However, this code occur error. I print the stderr info, which is "Failed to query password: Timer expired".

What's wrong with this code? How should I use stdin to write user and pwd correctly?

  [1]: https://i.stack.imgur.com/QsyVn.png

**Comment by ploxiln** [comment]
That process does not just read stdin, it attempts to open the tty, in order to handle input more "raw" and echo stars instead of the typed characters themselves. It might work to read stdout until you get the full prompt before writing the username, then again for the password ...

**Comment by ploxiln** [comment]
check out the openvpn `--auth-user-pass <user-pass-file>` option, which takes the path to a simple text file with username and password on two separate lines

**Comment by jiliguluss** [comment]
> check out the openvpn `--auth-user-pass <user-pass-file>` option, which takes the path to a simple text file with username and password on two separate lines

Thanks very much for your reply. When I use "--auth-user-pass <user-pass-file>" option with a text file, it can work correctly. However, the linux server may be used by many users at the same time. I am worried about security with the text files which store username and password. It seems stdin may be safer than text file, am I right?

**Comment by jiliguluss** [comment]
> That process does not just read stdin, it attempts to open the tty, in order to handle input more "raw" and echo stars instead of the typed characters themselves. 

Do you mean that my code work wrong because openvpn use stars instead of original characters?  Is it caused by openvpn, but not the usage of stdin?

> It might work to read stdout until you get the full prompt before writing the username, then again for the password ...

Sorry I do not understand what you mean. Should I run stdin.write and stdout.read alternately like this?
`stdin.write(user + '\n')`
`stdin.flush()`
`stdout.read()`
`stdin.write(pwd + '\n')`
`stdin.flush()`
`stdout.read()`

**Comment by ploxiln** [comment]
Yes, it may be more secure to feed username/password via stdin. If you have a unique user on the server, you could make the file readable only by you, that helps.

Regarding openssh and stdin, I mean that it doesn't do the most simple buffered stdin read, it uses a more raw mode, and I think it may wait for the keypresses after it displays the prompt (and possibly other complicated things). So if you send input before it writes the prompt, it may skip over it. So you can try to read a limited number of characters at a time (perhaps 1 is simplest), in a loop, until you have received the full expected prompt, then send the username, then read again until you have fully received the next prompt, then send the password.

**Comment by bskinn** [comment]
It appears this has been resolved; closing due to age.
