### ISSUE TITLE
Paramiko error while building pynacl (libaesni.la libtool:   error: require no space between '-L' and '-Wl,-O1')

### ISSUE THREAD

**Issue by paulacarrillo** [paramiko/paramiko#1761]
Hi, I am working on my embedded board (TI's TDA4VMXEVM). I have been able to PIP install several python modules (pillow, boto3, notebook, ipython, etc) but I am facing and error when building/installing "paramiko". 

Error happens when installing "pynacl"
    **CCLD     libaesni.la
  libtool:   error: require no space between '-L' and '-Wl,-O1'
  make[3]: *** [Makefile:1186: libaesni.la] Error 1**

Attached complete log.

Is there any fix or workaround? Am I missing something?
[pip3_paramiko_installError_10062020.txt](https://github.com/paramiko/paramiko/files/5341487/pip3_paramiko_installError_10062020.txt)

Thanks in advance for your help
Paula

**Comment by yuba** [comment]
I also cannot solve the very same error, but I have successfully worked around.

It occurs only with PyNaCl==1.5.0, so you can specify PyNaCl==1.4.0 .
It's OK because paramiko's requirement is  PyNacl>=1.0.1 .

**Comment by bskinn** [comment]
Thanks for reporting your workaround, @yuba!

I'm going to go ahead and close this, since it's not specifically a paramiko problem. @paulacarrillo, you can re-open if you determine that there is something within paramiko that needs fixing.
