### ISSUE TITLE
Python Paramiko Support for Cipher aes128-gcm@openssh.com and aes256-gcm@openssh.com

### ISSUE THREAD

**Issue by Rajalaxmi-web** [paramiko/paramiko#1773]
Please let me know when this update planned for Paramiko to use **"aes128-gcm@openssh.com and aes256-gcm@openssh.com"**...WHich is more encrypted way of connecting. In mean while please anyone help me how to connect ssh using these ciphers using python.....Is there any alternative way....

_Originally posted by @Rajalaxmi-web in https://github.com/paramiko/paramiko/issues/1394#issuecomment-722781513_

**Comment by adiroiban** [comment]
I think that this can be closed as it's a duplicate for #982
