### ISSUE TITLE
SFTP: Openin symlinked file on SFTP server yield's "file not found"

### ISSUE THREAD

**Issue by cs-1** [paramiko/paramiko#1774]
Hi all,

I'm using paramiko.sftp_client.SFTPClient to open an SFTP connection server. On the server there's a symlink pointing to a file. I try to open this symlink as a file with open() to use it as any other file object, however, I always get a "file not found" error. I'm pretty sure that the problem is that I'm opening a symlink to get the content of the linked file, however, even using normalize() on the filename doesn't help me so I'm starting to wonder, what the issue is. Is this a bug? Am I doing something wrong (also very likely). I'd appreciate if you could point me in the right direction. Thanks!

Christian

**Comment by jiahaoc1993** [comment]
@cs-1 hi, have you figured out why readlink() return failed?  met same issue here.

**Comment by cs-1** [comment]
I'm sorry but I don't remember what exactly the solution was, it's been too long.
