### ISSUE TITLE
Incompatible ssh peer (no acceptable host key)

### ISSUE THREAD

**Issue by UnknowZang** [paramiko/paramiko#1776]
python version :2.7
systemplatform:Windows 10
systemplatform2:Linux Euler aarch64

When I use this package to connect to Linux in the Windows operating system through SSH, the following error message is displayed:“SSHException: Incompatible ssh peer (no acceptable host key)”

transport.py  7996行：agreed_keys = list(filter(server_key_algo_list.__contains__, self._preferred_keys))
server_key_algo_list = [u'rsa-sha2-512', u'rsa-sha2-256', u'ssh-ed25519']
self._preferred_keys = 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256'

What's wrong with my environment?

**Comment by ploxiln** [comment]
Paramiko does not support `rsa-sha2-512` or `rsa-sha2-256`. It does support `ssh-ed25519` if you have `pynacl` and `bcrypt` installed.

**Comment by bitprophet** [comment]
Paramiko 2.9 will fix this.
