### ISSUE TITLE
Problem with OpenSSL 1.0.2 during Travis CI pypy and pypy3 build

### ISSUE THREAD

**Issue by wolfgangmichaelkraus** [paramiko/paramiko#1782]
The following [build #2749](https://travis-ci.org/github/paramiko/paramiko/builds/746223499) indicates that Travis CI has a problem using the specified OpenSSL-version and therefore throws a runtime error while running the [pypy #2749.7](https://travis-ci.org/github/paramiko/paramiko/jobs/746223506) and [pypy3 #2749.8](https://travis-ci.org/github/paramiko/paramiko/jobs/746223507) build:

`E   RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.`

It seems that this runtime error is unrelated to the pull request but instead being caused by an outdated OpenSSL configuration.

**Comment by mattip** [comment]
This is using [pypy 7.1.1](https://travis-ci.org/github/paramiko/paramiko/jobs/746223507#L197) which is very old. Latest pypy versions use openssl1.1.0.

**Comment by mattip** [comment]
Perhaps you can move to github actions and use the https://github.com/actions/setup-python action which provides the latest and greatest PyPy.
