### ISSUE TITLE
response packet hex dump logging bug in packetizer?

### ISSUE THREAD

**Issue by riptusk331** [paramiko/paramiko#1794]
To preface, I'm not sure if I'd call the following a bug vs just being misleading. I'm not sure. It doesn't really break anything. I just don't think it's right (but maybe I am wrong). Regardless, I wanted to bring it up.

Anyway, I noticed something peculiar when analyzing response hex dumps printed by `read_message` in the `Packetizer` class. I've been trying to teach myself the SSH protocol really down to the nuts and bolts, so I've been comparing the hex dumps out of Paramiko for a given action to what I'd expect to see after reading the [SSH RFCs](https://wiki.filezilla-project.org/SFTP_specifications). All the outbound hex dumps looked exactly like what I'd expect, but I was getting extremely hung up on an oddity of all the inbound ones.

Without getting too deep into the weeds of the protocol specs (but somewhat unavoidable here) ... when we're using SFTP, we have an SFTP packet as the data payload of an SSH packet. The 1st 4 bytes of an SSH packet are its length in bytes (minus the length bytes themselves), followed by 1 byte giving the random padding length, followed by the data payload itself. The payload usually starts with a 1 byte SSH message indicating what it is, followed by whatever bytes are part of the actual meat of the request/response.

Knowing this, let's look at this response hex dump printed by paramiko to a simple `stat` call on a single file when using the SFTP client. **Warning**, this is getting really deep in the weeds (sorry, directly contradicting myself above) and requires advanced knowledge of the SSH RFCs, but it explains what I think seems off:

```
DEBUG: IN: 00 00 00 3C 09 5E 00 00 00 00 00 00 00 29 00 00    ...<.^.......)..
DEBUG: IN: 09 5E 00 00 00 00 00 00 00 29 00 00 00 25 69 00    .^.......)...%i.
DEBUG: IN: 00 00 0D 00 00 00 0F 00 00 00 00 00 00 03 BE 00    ................
DEBUG: IN: 08 19 6D 00 00 27 12 00 00 81 B0 5F F0 D8 26 5F    ..m..'....._..&_
DEBUG: IN: EF C8 08 50 61 14 5B 37 9B F6 5A 20                ...Pa.[7..Z
```
The 1st 4 bytes (`00 00 00 3C`) tell us the rest of the packet should be 60 bytes long (excluding these 1st 4 length bytes). Already something looks off. If you count the "bytes" (hex pairs) after `00 00 00 3C` above, I get 72. Huh? What's going on here?

If we keep going, the next byte (`09`) tell us there are 9 bytes of random padding on this message. So that's what bytes `50 61 14 5B 37 9B F6 5A 20` on the end are. Ok that looks fine. The next byte, `5E` is 94 in decimal, which is the SSH_MSG_CHANNEL_DATA message. Per the spec, when we're transferring data, the next 4 bytes should be the channel we're using - `00 00 00 00` in this case. Still good. After the channel, follows the data we want to transfer itself. This is represented as a `string` - which is defined in the specs as 4 bytes defining its length, followed by the string itself. The "string" here is the actual SFTP packet. ` 00 00 00 29` indicates that it's 41 bytes long...so the next 41 bytes after that should be our SFTP packet.

An SFTP packet is _also_ defined in the spec as starting with 4 bytes to indicate it's length, followed by a request/response type, etc... So the first 4 bytes here should be the length of our SFTP packet minus the 1st 4 length bytes. Intuitively, this should be 41 - 4 = 37 (since the length of the "string" representing this data was 41, and that number is including the 4 length bytes). So we should see `00 00 00 25` (37 in hex), which is the start of our SFTP packet. But instead the next 4 printing are `00 00 09 5E` ... which is 2398. There is no way the packet above is 2398 bytes long. This REALLY puzzled me for a while. I reread the specs several times to see if I was missing something, but I couldn't find anything to explain it.

Then I noticed that the second line of the hex dump is the same as the first line minus the 1st 4 bytes. This seemed consistent in nearly every case. So I took a look at the source code in `packet.py` and I think I see the culprit [here](https://github.com/paramiko/paramiko/blob/5cf145ffd3d7cd4d96a511376267a7f27cce5eed/paramiko/packet.py#L478). This looks like it essentially logs the hex dump of the header block (including the 4 length bytes). Then a bit further [down](https://github.com/paramiko/paramiko/blob/5cf145ffd3d7cd4d96a511376267a7f27cce5eed/paramiko/packet.py#L504), the entire packet EXCEPT the 1st 4 bytes are logged. The net result is the logging of this weird hybrid of the 1st block + the entire packet starting from byte 5. If you look at my example above, that's exactly what's happening.

Am I missing something here as to why this is set up this way? I feel like the hex dump should reflect the actual packet. Why is the logging being split up like this? It caused me a fair bit of confusion.

In order to reproduce, call the `set_hexdump` method on your `Transport` with True, and then read the log output on the requests and responses on a simple operation like an SFTP stat call. You'll notice the requests (OUT) look fine, but the responses (IN) exhibit this behavior.

Any thoughts?

**Comment by ploxiln** [comment]
I think this is due to a desire to log the "header+??" before possibly failing before finishing the "packet" (e.g. due to "invalid packet blocking").

This might be a bit better ... though a bit messier code, and putting the first 4 bytes on their own line ...

```diff
--- a/paramiko/packet.py
+++ b/paramiko/packet.py
@@ -436,6 +436,8 @@ class Packetizer (object):
         """
         header = self.read_all(self.__block_size_in, check_rekey=True)
         if self.__etm_in:
+            if self.__dump_packets:
+                self._log(DEBUG, util.format_binary(header[:4], 'IN: '))
             packet_size = struct.unpack(">I", header[:4])[0]
             remaining = packet_size - self.__block_size_in + 4
             packet = header[4:] + self.read_all(remaining, check_rekey=False)
@@ -450,13 +452,15 @@ class Packetizer (object):
 
         if self.__block_engine_in is not None:
             header = self.__block_engine_in.update(header)
-        if self.__dump_packets:
-            self._log(DEBUG, util.format_binary(header, 'IN: '))
 
         if self.__etm_in:
             # already decrypted everything above
             packet = header
+            if self.__dump_packets:
+                self._log(DEBUG, util.format_binary(packet, 'IN: '))
         else:
+            if self.__dump_packets:
+                self._log(DEBUG, util.format_binary(header[:4], 'IN: '))
             packet_size = struct.unpack(">I", header[:4])[0]
             # leftover contains decrypted bytes from the first block (after the length field)
             leftover = header[4:]
@@ -469,9 +473,8 @@ class Packetizer (object):
             if self.__block_engine_in is not None:
                 packet = self.__block_engine_in.update(packet)
             packet = leftover + packet
-
-        if self.__dump_packets:
-            self._log(DEBUG, util.format_binary(packet, 'IN: '))
+            if self.__dump_packets:
+                self._log(DEBUG, util.format_binary(packet, 'IN: '))
 
         if self.__mac_size_in > 0 and not self.__etm_in:
             mac = post_packet[:self.__mac_size_in]
```

**Comment by riptusk331** [comment]
looks like you fixed this....closing
