### ISSUE TITLE
import paramiko need a long time

### ISSUE THREAD

**Issue by Shimon-Guo** [paramiko/paramiko#1799]
here is my code:
test.py: 
import paramiko
print 111111111

when I execute the script,  it will show the follwing massage:

 supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography.hazmat.backends import default_back

it sometimes take a very long time(usuallt 1-5 minutes) but some times take a very short time(few seconds)

python version: python 2.7.17,
platform: linux

**Comment by bskinn** [comment]
What paramiko version are you using?

**Comment by Shimon-Guo** [comment]
paramiko==2.7.2

**Comment by bitprophet** [comment]
I can't reproduce this on Linux (NixOS) under Python 2.7(.18) - paramiko imports in under a second reliably. FWIW The warning you see is common to every user on the latest Cryptography release; it's easily ignorable. Their future releases will just not show up on Python 2.

(Paramiko will drop Python 2 support on its end this year sometime, but as with Crypto, you shouldn't see existing installs break, you will just stop seeing new versions.)

@Shimon-Guo If I were you I'd try a few quick things like installing older Paramiko versions (anything 2.0 or up should be plenty usable) or trying a Python 3 interpreter in case your platform's Python 2 has some odd issue.

If you can identify a specific Paramiko release that triggers this, please reopen and we can suggest deeper troubleshooting based on what changed in that release. Thanks!
