### ISSUE TITLE
Paramiko SFTP.symlink implementation is backwards

### ISSUE THREAD

**Issue by heapcrash** [paramiko/paramiko#1821]
The documentation for `sftp_client.symlink`: http://docs.paramiko.org/en/stable/api/sftp.html#paramiko.sftp_client.SFTPClient.symlink

States that the prototype is:

```
symlink(source, dest)
Create a symbolic link to the source path at destination.
```

However, its implementation does the reverse of this.

Invoking `symlink(source, target)` creates a symlink such that `target --> source`.

**Comment by ploxiln** [comment]
It's confusing, but I think you're saying the same thing. The new link created is "dest", what you call "target", and it points to existing file "source". The description of each parameter in the docs makes this clearer.

**Comment by bskinn** [comment]
Agreed on both counts -- it's confusing, but the behavior matches the documentation. Closing as no action needed.
