### ISSUE TITLE
ModuleNotFoundError: No module named 'paramico' on Windows 10

### ISSUE THREAD

**Issue by dburtsev** [paramiko/paramiko#1830]
Hello
I install paramico but can't import it
import paramico
ModuleNotFoundError: No module named 'paramico'

C:\>pip install paramiko 
Requirement already satisfied: paramiko in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (2.7.2)
Requirement already satisfied: cryptography>=2.5 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from paramiko) (3.4.6)
Requirement already satisfied: bcrypt>=3.1.3 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from paramiko) (3.2.0)
Requirement already satisfied: pynacl>=1.0.1 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from paramiko) (1.4.0)
Requirement already satisfied: cffi>=1.1 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from bcrypt>=3.1.3->paramiko) (1.
14.5)
Requirement already satisfied: six>=1.4.1 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from bcrypt>=3.1.3->paramiko) (1
.15.0)
Requirement already satisfied: pycparser in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from cffi>=1.1->bcrypt>=3.1.3->pa
ramiko) (2.20)

**Comment by bskinn** [comment]
You've misspelled the package name in your import, you need to use `import paramiko`, not `import paramico`.

**Comment by dburtsev** [comment]
Thank you
