### ISSUE TITLE
How can i pass ssh-rsa-cert-v01@openssh.com , signed key in paramiko ?

### ISSUE THREAD

**Issue by rohitjain25** [paramiko/paramiko#1854]
Due to my company norms i have to login into machines using the command ssh -i cert.pub 192.x.x.x. The cert.pub need to be passed in the paramiko! How can i do it ?

**Comment by rohitjain25** [comment]
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('10.57.xx.xx',pkey=r'/Users/rj/cert.pub')
stdin, stdout, stderr = ssh.exec_command("date")
I am using this method but it's not working!

**Comment by tars01** [comment]
Isn't it `key_filename ` ?
http://docs.paramiko.org/en/stable/api/client.html

**Comment by rohitjain25** [comment]
raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long
