### ISSUE TITLE
SFTP get a file hang when the stat() return a size greater than the real file size

### ISSUE THREAD

**Issue by etiennebrateau** [paramiko/paramiko#1871]
If the server returns a size greater than the real file, the download hangs forever (or if the timeout is set, get() will raise an exception) because it waits for bytes that will never come. Instead, it should return the file content when reaching EOF.

**Comment by dhruvinsh** [comment]
can you put the code snippet here, which really easy to reproduce.

**Comment by etiennebrateau** [comment]
Here a sample of the download code.
```python
from paramiko import SFTPClient, Transport
import io

if __name__ == '__main__':
    client_transport = Transport(("127.0.0.1", 2222))
    client_transport.connect(username="test")
    client = SFTPClient.from_transport(client_transport)
    client.get_channel().settimeout(600)  # timeout to not wait indefinitely
    
    fetched_file = io.BytesIO()
    client.getfo("test_file", fetched_file)
```
what is important is that the server much return a greater size when doing stat() than the real size of the file.
In my case:
```
sftp> ls -l file.json
-rwxr--r--    ? 0        0           68099 Jun 21 04:01 file.json
sftp> get file.json
Fetching /file.json to file.json
sftp> !ls -l file.json
-rwxr--r--  1 etienne  etienne  64894 21 Jun 08:04 file.json

```

**Comment by etiennebrateau** [comment]
After a recent test, paramiko seemed to work correctly and that our problem was somewhere else.
