### ISSUE TITLE
All server-side, non-group-exchange Diffie-Hellman algorithms are using SHA1 even when they shouldn't

### ISSUE THREAD

**Issue by jeamland** [paramiko/paramiko#1882]
All the non-group-exchange (i.e. `diffie-hellman-group{1,14,16}-*`) Diffie-Hellman algorithms derive from the KexGroup1 implementation in [paramiko/kex_group1.py](https://github.com/paramiko/paramiko/blob/master/paramiko/kex_group1.py). To support other digest algorithms, KexGroup1 has a `hash_algo` class variable which defaults to `sha1`. In the `_parse_kexdh_reply` method (used when we are the client side of the exchange), this is correctly used like so to generate the hash:

```
        self.transport._set_K_H(K, self.hash_algo(hm.asbytes()).digest())
```

Thus allowing the sha256 and sha512 variants to substitute those algorithms. Unfortunately in `_parse_kexdh_init` (used when we are the server side of the exchange) we have the sha1 algorithm hardcoded rather than using `self.hash_algo`:

```
        H = sha1(hm.asbytes()).digest()
```

This should almost certainly be:

```
        H = self.hash_algo(hm.asbytes()).digest()
```

**Comment by bitprophet** [comment]
Feels related to #1452 a tiny bit.

**Comment by bitprophet** [comment]
Seems legit, the last change to the offending line was by Alex 7 years ago: https://github.com/paramiko/paramiko/commit/4d3e0b711a98c440810004cb599a00d0f72978d7 - but the subclasses you reference were created within the last 2-3 years generally, and clearly made assumptions based on that attribute.

Wondering why tests aren't catching this 😐  unless it's one of the areas not sufficiently tested.

**Comment by ploxiln** [comment]
This was reported way back in https://github.com/paramiko/paramiko/issues/1462 soon after these kex classes were added.

**Comment by jeamland** [comment]
@bitprophet did mention that there may have been prior art on this one. I just happened to stumble on it the other day while doing something else.
