### ISSUE TITLE
When loading known hosts file, Paramiko is needlessly slow.

### ISSUE THREAD

**Issue by ostacey** [paramiko/paramiko#191]
When load() is called on a large known_hosts file that contains hashed keys, that is an innately expensive process, because the code in load() must try to prevent duplicates, and that means calculating the hash of every incoming hostname with the salt in each hashed key in the structure. There's no way around that, even though it can cause O(n^2) invocations of the hash function.

However, some of the checks Paramiko is making right now can safely be omitted. When the loaded hostname is a hash, we don't need to compute the hash of the hash; we simply need to see if the overall hash string matches. In my own case - a 1062-entry known-hosts file with 903 hashed keys - omitting just these checks reduced the run time of HostKeys.load() by about 6 seconds.

I suspect this might also be related to Issue #183.

(This is an especially relevant issue for folks using Paramiko through Fabric. Fabric makes a Paramiko SSHClient each time it connects to a different host, separately loading the known_hosts file each time. So multiply that runtime reduction by the number of hosts you are administering.)

**Comment by douglaz** [comment]
Just got this issue with paramiko 2.0.2 (python 3.4.3). It's terribly slow to load a 16k known_hosts (3.5MB).
