### ISSUE TITLE
 FAILED! => {"changed": false, "msg": "paramiko is not installed: No module named 'paramiko'"}

### ISSUE THREAD

**Issue by yousefii** [paramiko/paramiko#1936]
**hi every one**
I have an issue with running an Ansible playbook, in my opinion, everything is ok in my ansible.cfg and my file.yaml but unfortunately get this error:
 FAILED! => {"changed": false, "msg": "paramiko is not installed: No module named 'paramiko'"}

**my ansible.cfg :**
[defaults]
inventory = ./hosts
timeout = 60
host_key_checking = false
forks = 25
command_timeout = 80
[persistent_connection]
connect_timeout = 60

**my play book :**

---
- name: backup configuration
  hosts: R
  gather_facts: no
  connection: local

  vars:
    backup_root: ./backups

    cli:
      host: "{{ inventory_hostname }}"
      username: xxx
      password: xxx
      #transport: cli
      authorize: yes

  tasks:
    - name: run show running-config on remote devices
      ios_command:
        authorize: yes
        commands: show running
        provider: "{{ cli }}"
      register: config

    - name: ensure backup folder is created
      file:
        path: "{{ backup_root }}"
        state: directory
      run_once: yes

    - name: ensure device rolder is created
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}"
        state: directory

    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp

    - name: get/copy backup
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}"

**Comment by ploxiln** [comment]
Ansible depends on paramiko (depending on mode?) but it appears that paramiko is not installed in the python env that ansible is running from. This probably is not related to your ansible playbook.

**Comment by yousefii** [comment]
@ploxiln
hi 
I install paramiko with "apt-get install -y python3-paramiko) and then try to do my playbook and it worked!
thanks for your help

**Comment by shanksleo** [comment]
@yousefii  Thank You . It is helpful

**Comment by SpeesAce** [comment]
I just got a timeout error..
Luckily enabling debugging (https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html): 

# Specify the location for the log file
export ANSIBLE_LOG_PATH=~/ansible.log
# Enable Debug
export ANSIBLE_DEBUG=True

# Run with 4*v for connection level verbosity
ansible-playbook -vvvv ... 

I was able to find the missing module that led me to this post!
