### ISSUE TITLE
drop Python 2.x support (Paramiko 3.x)

### ISSUE THREAD

**Issue by dulmandakh** [paramiko/paramiko#1952]
I would like to volunteer in dropping support for Python 2.x, and would like to discuss plans how we can move forward with it. 

I find projects do Python 2.x removal and refactor (utilize more Python 3) at the same time, thus taking longer to ship a release. Therefore, I propose to do removal and refactor in separate steps.

1. Remove compatibility code.
2. Release 3.0
3. Refactor to utilize more Python 3.x features, and release minor versions. It'll be easier because we have less code.

Any comments @bitprophet

**Comment by bitprophet** [comment]
See https://bitprophet.org/blog/2021/02/25/byethon2/#how-exactly for my plans here :) (and https://bitprophet.org/projects/#high-level--cross-project for where it fits in my timeline.)

Given the sensitivity of the work I'd prefer to do it myself, but I appreciate the offer of help & would _definitely_ appreciate assistance testing the results once they're far enough along.
