### ISSUE TITLE
consider providing high-level API or some recipies/examples as an alternative to pysftp

### ISSUE THREAD

**Issue by vdwees** [paramiko/paramiko#1979]
Traditionally, [pysftp](https://bitbucket.org/dundeemt/pysftp/src/master/) has provided the high-level interface to paramiko. However, pysftp has not had a release since 2016 and there are now several open and unanswered PR there. It is possible that pysftp is no longer maintained.

IMO it's in the interest of the paramiko project take advantage of the situation and start targeting/serving the typical users of pysftp, initially by providing some high-level recipies for common tasks (e.g. log in and copy a file from a remote server to a local directory). In the long term, perhaps it would make sense to also include a high-level API.

In any case, I will be migrating away from pysftp, I would be happy to contribute some recipies to the docs if that is ok.

**Comment by JohnTravolski** [comment]
I agree with this.

**Comment by bitprophet** [comment]
Hi! Fabric currently serves as the high level API on top of Paramiko, and it does have SFTP support (which IIRC should include a `cd` contextmanager). See eg https://docs.fabfile.org/en/2.6/getting-started.html#transfer-files and the linked API docs farther into the site.

A quick glance at pysftp implies that Fabric's coverage of SFTP actions is at least a good 80% match; I'd certainly be up for improving anything that's missing. Please drop tickets over at Fabric's tracker if you spot anything!
