### ISSUE TITLE
exec_command run "git push" hangs and not be executed

### ISSUE THREAD

**Issue by SukiYume** [paramiko/paramiko#1981]
I want to use `paramiko` to run `git push` on a remote machine to push the update to GitHub periodically.
`git add .` and `git commit -m 'xxx'` can be executed perfectly. 
When running `git push`, the process hangs and is not executed.
Following is an example, `std_out.read()` seems to run forever.

By the way, `git push` works fine in my bash. Please tell me where needs to be fixed.

```python
import paramiko

ssh_client = paramiko.SSHClient()
ssh_client.load_system_host_keys()
ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh_client.connect(host, port, user, passwd)

_, std_out, std_err = ssh_client.exec_command('cd {};git push'.format(path))
std_out.read()
```

**Comment by jun66j5** [comment]
I don't think that is a paramiko issue. I recommend you confirm the command does work using `ssh` instead of paramiko.

**Comment by SukiYume** [comment]
> I don't think that is a paramiko issue. I recommend you confirm the command does work using `ssh` instead of paramiko.

Yes, I have already tested. All commands works fine in remote machine, remote machine `ssh localhost`, and local machine `ssh remote machine`.

**Comment by jun66j5** [comment]
Ok. Secondly, check `ssh git@github.com` works like the following.

```python
stdin, stdout, stderr = ssh_client.exec_command('ssh -v git@github.com </dev/null 2>/dev/null 2>&1')
stdin.close()
stderr.close()
print(stdout.read())
```

**Comment by SukiYume** [comment]
> Ok. Secondly, check `ssh git@github.com` works like the following.
> 
> ```python
> stdin, stdout, stderr = ssh_client.exec_command('ssh -v git@github.com </dev/null 2>/dev/null 2>&1')
> stdin.close()
> stderr.close()
> print(stdout.read())
> ```

Thank you very much, this is indeed the problem. After `ssh locahost`, `ssh git@github.com` stuck at `debug1: client_input_channel_req: channel 0 rtype exit-status reply 0`. And I found the `pledge` is **filesystem full**, while `pledge` is **network** at local. I don't know much about ssh, maybe it's not related to the problem here.

This really has nothing to do with `paramiko`, I will close this issue. And I will continue to look for solutions, if you have relevant experience, please share it with me, this will be a great help. Thank you again.
