### ISSUE TITLE
SSH Authentication fails with 2.9.2

### ISSUE THREAD

**Issue by tpcgold** [paramiko/paramiko#1984]
This code snippet is working with 2.8.1 but not with 2.9.2:
``` 
import paramiko
import io

host = ''
port = ''
ssh_key = ''
username = ''
password = ''

transport = paramiko.Transport((host, int(port)))
rsa_key = paramiko.RSAKey.from_private_key(io.StringIO(ssh_key), password=password)
transport.connect(username=username, pkey=rsa_key)
sftp = paramiko.SFTPClient.from_transport(transport)
print(sftp.listdir())
```

Authentication Error is thrown by 2.9.2 downgrade solves the issue

**Comment by jun66j5** [comment]
If the host is a legacy SSH server which doesn't support rsa-sha2-256/512 signatures, you need to use `disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']}` to fix it.

See https://www.paramiko.org/changelog.html#2.9.0

If the issue is not fixed even using `disabled_algorithms`, please share the trace back of the `AuthenticationError`.

**Comment by vitali-r** [comment]
I have the same issue. Downgrading helps. Passing `disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']}` does not help
```
Traceback (most recent call last):
  File "/home/project_folder/progect/common/scp.py", line 105, in __enter__
    self._ssh.connect(**ssh_credentials)
  File "/home/project_folder/.venv/lib/python3.9/site-packages/paramiko/client.py", line 435, in connect
    self._auth(
  File "/project_folder/.venv/lib/python3.9/site-packages/paramiko/client.py", line 766, in _auth
    raise saved_exception
  File "/project_folder/.venv/lib/python3.9/site-packages/paramiko/client.py", line 742, in _auth
    self._transport.auth_publickey(username, key)
  File "/project_folder/.venv/lib/python3.9/site-packages/paramiko/transport.py", line 1634, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/project_folder/.venv/lib/python3.9/site-packages/paramiko/auth_handler.py", line 258, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
```

**Comment by jun66j5** [comment]
> I have the same issue. Downgrading to `2.8.1` helps. Downgrading to `2.9.0` does not help. Passing `disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']}` **does not help**

 - What SSH server and the version are you using?
 - Check log of your SSH server.

**Comment by vitali-r** [comment]
Looks like the issue is in filtering out keys. Will try to provide a fix.

**Comment by jun66j5** [comment]
Ah, I noticed https://www.paramiko.org/changelog.html#2.9.0 has typo about `disabled_algorithms`....

Please try to pass:
```
disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']}
```
instead of:
```
disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']}
```

**Comment by vitali-r** [comment]
Yep it worked! Thank you!

**Comment by bitprophet** [comment]
Good spot @jun66j5 - it's arguably not a typo as both of those dict-keys are valid ("keys" means host keys, "pubkeys" means public key auth - this follows from older, regrettable IMO, naming conventions 😂 ) but I've just updated the changelog to be more explicit about the pubkey version of the config.

**Comment by marc-swingler** [comment]
Thanks, disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']} worked for me as well, hitting an old MINA implementation.

**Comment by realcp1018** [comment]
Hi @bitprophet, I got the same error and solved it by: `client.connect("<hostname>", disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']})`

But get error `Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!` for other hosts.  Can we have a general way for this situation?

**Comment by ghostbody** [comment]
`disabled_algorithms` is a very bad idea if you really need it for both version ...

**Comment by bitprophet** [comment]
Yea I'm not very happy with disabled_algorithms as-is, it was fine for the fix it came in with, but is proving unintuitive/complex at this point in time. There are a few other small backwards incompatible API changes in the pipeline that will likely accompany the drop of Python 2 support - I expect changing this would be included there.

**Comment by marc-swingler** [comment]
@[realcp1018](https://github.com/realcp1018) 

> Hi @bitprophet, I got the same error and solved it by: `client.connect("<hostname>", disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']})`
> 
> Then got error `Unable to agree on a pubkey algorithm for signing a 'ssh-rsa' key!` for other hosts. Can we have a general way for this situation? **Ps: I have to downgrade to 2.7.2 to adapt all hosts o(╥﹏╥)o**

I solved that by associating hostnames to dictionaries of connection parameters similar to stanzas in an ~/.ssh/config file.

**Comment by justinpryzby** [comment]
The changelog still says "Specifically, you need to specify disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']} in either [SSHClient](https://docs.paramiko.org/en/latest/api/client.html#paramiko.client.SSHClient.__init__) or [Transport](https://docs.paramiko.org/en/latest/api/transport.html#paramiko.transport.Transport.__init__). See below for details on why."

Using "keys" and not "pubkeys".  So I've had to rediscover the fix (after having put upgrading paramiko on hold for a couple weeks).

**Comment by bskinn** [comment]
> The changelog still says "Specifically, you need to specify disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']} in either [SSHClient](https://docs.paramiko.org/en/latest/api/client.html#paramiko.client.SSHClient.__init__) or [Transport](https://docs.paramiko.org/en/latest/api/transport.html#paramiko.transport.Transport.__init__). See below for details on why."
> 
> Using "keys" and not "pubkeys". So I've had to rediscover the fix (after having put upgrading paramiko on hold for a couple weeks).

@justinpryzby Since you've been elbows-deep in understanding this, could you create a PR on the CHANGELOG with suitable edits?

In particular, are there some circumstances where you want to use `keys` and some where you want to use `pubkeys`? Or is it just a typo, and it should always be `pubkeys`?

**Comment by justinpryzby** [comment]
I think I'm only ankles-deep -- I know that "pubkeys" is what works for our application, and for other people who had opened github issues.

But @bitprophet suggests that both keys are valid, and presumably some people will need "keys" (perhaps in addition to "pubkeys").
https://github.com/paramiko/paramiko/issues/1984#issuecomment-1036475103

**Comment by bskinn** [comment]
How's this for improved language, @justinpryzby: https://github.com/paramiko/paramiko/pull/2104

**Comment by justinpryzby** [comment]
On Tue, Aug 23, 2022 at 07:20:42AM -0700, Brian Skinn wrote:
> How's this for improved language, @justinpryzby: https://github.com/paramiko/paramiko/pull/2104

|    Specifically, you need to specify one or both of ``disabled_algorithms={'keys':
|    ['rsa-sha2-256', 'rsa-sha2-512']}`` or ``disabled_algorithms={'pubkeys':
|    ['rsa-sha2-256', 'rsa-sha2-512']}``in either `SSHClient 

You can't actually specify both of:
disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']}
disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']}

Rather, you'd specify 
disabled_algorithms = dict(keys=['rsa-sha2-256', 'rsa-sha2-512'] 
			pubkeys=['rsa-sha2-256', 'rsa-sha2-512'])

Also, I think you're missing a space before "in either".

I wrote the review here since github's review editor is so poor that I couldn't
even use it to review a 3 line change..

**Comment by bskinn** [comment]
Good catches, all - thanks! See [revised PR](https://github.com/paramiko/paramiko/pull/2104).

**Comment by bskinn** [comment]
Good catches, all - thanks, @justinpryzby! See [revised PR](https://github.com/paramiko/paramiko/pull/2104).

And yea -- the 'add suggestion' feature works decently if everything that needs changing is on a single line, but it's pretty bad for suggestions on multiline chunks.
