### ISSUE TITLE
paramiko 2.9.2 doesn't handle Match option in ssh config

### ISSUE THREAD

**Issue by anandb-ripencc** [paramiko/paramiko#1992]
I have a `Match` option in my ssh config file, like this:
```
Match final !originalhost proxy !exec "test -S /tmp/%r@%h:%p || nc -zG2 %h %p &>/dev/null"
    ProxyCommand ssh proxy "exec nc -i60 %h %p 2>/dev/null"
```
When I ask paramiko to load this config file, it throws an exception:
```
Traceback (most recent call last):
  File "/Users/anandb/project/pyinfra-playground/./test-paramiko", line 6, in <module>
    config = paramiko.SSHConfig.from_path('/Users/anandb/.ssh/config')
  File "/Users/anandb/.virtualenvs/pyinfra/lib/python3.10/site-packages/paramiko/config.py", line 109, in from_path
    return cls.from_file(flo)
  File "/Users/anandb/.virtualenvs/pyinfra/lib/python3.10/site-packages/paramiko/config.py", line 119, in from_file
    obj.parse(flo)
  File "/Users/anandb/.virtualenvs/pyinfra/lib/python3.10/site-packages/paramiko/config.py", line 158, in parse
    context["matches"] = self._get_matches(value)
  File "/Users/anandb/.virtualenvs/pyinfra/lib/python3.10/site-packages/paramiko/config.py", line 524, in _get_matches
    raise ConfigParseError(
paramiko.ssh_exception.ConfigParseError: Missing parameter to Match 'test -S /tmp/%r@%h:%p || nc -zG2 %h %p &>/dev/null' keyword
```
My `Match` option works just fine with ssh. Is this a bug in paramiko?

**Comment by anandb-ripencc** [comment]
I now have paramiko version 2.11.0, and I'm still getting this error.

**Comment by bskinn** [comment]
Did this Match option work successfully in any paramiko versions? Or has it always errored?

From looking at #1729, I'm guessing there are still outstanding issues with paramiko's handling of Match in ssh_config. 

That said, a complex Match predicate with shell delegation is a pretty nontrivial feature -- even if #1991 takes care of #1729, additional work may be required to make your Match function...and the challenge of parsing the shell delegation may or may not be deemed too much to commit to. That'll be bitprophet's call, when the time comes.

**Comment by anandb-ripencc** [comment]
@bskinn no, I've never managed to get paramiko to work with my ssh config because of my complex Match.

My ssh config works with ansible, because ansible just calls "ssh" directly. However, when I try pyinfra, it uses paramiko, and fails on this Match condition. What I'm basically trying to do is to see if a host is reachable directly. If it is, then avoid the proxy, otherwise go through a proxy. If there's a smart way to do this without my Match, and that would work with pyinfra, I'd be happy to change my ssh config.

**Comment by jun66j5** [comment]
`paramiko.SSHConfig()` currently doesn't support `final` keyword which is introduced in [OpenSSH 8.0](https://www.openssh.com/txt/release-8.0).

```
$ git grep -wc canonical refs/tags/2.11.0 paramiko/config.py
refs/tags/2.11.0:paramiko/config.py:13
$ git grep -wc final refs/tags/2.11.0 paramiko/config.py
$ echo $?
1
```

**Comment by commonism** [comment]
Anyone tried https://github.com/paramiko/paramiko/pull/1907 for Match final?

**Comment by jcharaoui** [comment]
I've tried the patch over python3-paramiko_2.7.2-1 on Debian and it worked.

**Comment by jcharaoui** [comment]
Patch still applies fine over python3-paramiko_2.12.0-2 in Debian bookworm.

**Comment by commonism** [comment]
#1907 got merged, can be closed?

**Comment by bskinn** [comment]
Given the use of `Match final` being identified as a likely culprit (https://github.com/paramiko/paramiko/issues/1992#issuecomment-1247144668), I'm going to go ahead and close.

@anandb-ripencc, if you still have problems with this using paramiko 3.3.0+, please comment and reopen.

Thanks for the report!
