### ISSUE TITLE
raskey.py is hardcoded with "ssh-rsa" in places where we need support for rsa-sha2-256 and other versions

### ISSUE THREAD

**Issue by aswanidutt** [paramiko/paramiko#1997]

**Comment by jun66j5** [comment]
No. That code should be correct. Please describe the details if you encounter an issue with the latest version of paramiko.

**Comment by aswanidutt** [comment]
when we create a cert and try to sign it using paramiko, its not giving us option to sign the cert with SHA2 its hardcoded to sign and verify only with SHA1(ssh-rsa), though it has mentioned the different algorithms(Hashes) in that file 
    HASHES = {
        "ssh-rsa": hashes.SHA1,
        "ssh-rsa-cert-v01@openssh.com": hashes.SHA1,
        "rsa-sha2-256": hashes.SHA256,
        "rsa-sha2-256-cert-v01@openssh.com": hashes.SHA256,
        "rsa-sha2-512": hashes.SHA512,
        "rsa-sha2-512-cert-v01@openssh.com": hashes.SHA512,
    }
its hard coded in the line 95 to "ssh-rsa", because of this we are unable to sign(verify after the signing part) for the cert.

**Comment by jun66j5** [comment]
I've posted PR #1977 to fix publickey authentication with signed RSA key. Try it. See also #1963.

I believe the asbytes() is correct.

**Comment by 11chri** [comment]
@jun66j5 I just checked your PR on Paramiko 2.9.2 and it fixes https://github.com/paramiko/paramiko/issues/1963

**Comment by aswanidutt** [comment]
I dont see your change of      **m.add_string("ssh-rsa"**) to 
        **m.add_string(algorithm)** in the rsakey.py file, it is not reflected in the version 2.10.1

**Comment by bitprophet** [comment]
Jun's fix from #1977 will be out in 2.9.3 and 2.10.3.
