### ISSUE TITLE
Documentation for SFTPClient.open is potentially misleading

### ISSUE THREAD

**Issue by r-thomson** [paramiko/paramiko#2000]
If we look at [the documentation for `SFTPClient.open(filename, mode='r', bufsize=-1)`](https://docs.paramiko.org/en/stable/api/sftp.html#paramiko.sftp_client.SFTPClient.open), we can see the following:

> The file will be buffered **in standard Python style by default**, but can be altered with the `bufsize` parameter. `0` turns off buffering, `1` uses line buffering, and any number greater than 1 (`>1`) uses that specific buffer size.

And if we look at [the Python docs for `open()`](https://docs.python.org/3/library/functions.html#open), we see this:

> _buffering_ is an optional integer used to set the buffering policy. Pass 0 to switch buffering off (only allowed in binary mode), 1 to select line buffering (only usable in text mode), and an integer > 1 to indicate the size in bytes of a fixed-size chunk buffer. **When no _buffering_ argument is given, the default buffering policy works as follows:**
> 
> * Binary files are buffered in fixed-size chunks; the size of the buffer is chosen using a heuristic trying to determine the underlying device’s “block size” and falling back on [`io.DEFAULT_BUFFER_SIZE`](https://docs.python.org/3/library/io.html#io.DEFAULT_BUFFER_SIZE). On many systems, the buffer will typically be 4096 or 8192 bytes long.

From this, I would assume that omitting `bufsize` would cause Paramiko to enable buffering, choosing its own size for the buffer. However, in the code for `BufferedFile`, we can see that this is not the case.

https://github.com/paramiko/paramiko/blob/4300732c8c392cb246fc7b2839e3700732846fff/paramiko/file.py#L460-L475

This seems misleading to me. I'd suggest that one of these two options be taken:

- Update the documentation to clarify that buffering is disabled by default
- Update the behavior of `_set_mode` to enable buffering when `bufsize=-1` (potentially backwards incompatible)

**Comment by josephfemia** [comment]
Weird, I was experiencing the same problem. Thank you for pointing it out.
