### ISSUE TITLE
Memory leak with long-running processes

### ISSUE THREAD

**Issue by rkojedzinszky** [paramiko/paramiko#2002]
Paramiko stores thread-ids in a dictionary, which never gets cleaned up. In a long-running process, this leaks memory. One example is https://github.com/truenas/zettarepl which runs persistently in a TrueNAS system, and thus leaks memory.

The leaking structure is here: https://github.com/paramiko/paramiko/blob/main/paramiko/util.py#L228

**Comment by stuartonyx** [comment]
Has there been any resolution to this because we have a use case where we are creating and removing many connections a day and the result has been a memory leak that means we are having to force a reboot every day
