### ISSUE TITLE
SSHConfig get_hostnames fails with Match entries

### ISSUE THREAD

**Issue by geoffreywiseman** [paramiko/paramiko#2014]
The `get_hostnames` code in `SSHConfig` fails for match entries:

```
Traceback (most recent call last):
  File "/Users/geoffrey/work/tpa/scripts/demo-broker-replication/test_connection.py", line 18, in <module>
    print(config.get_hostnames())
  File "/Users/geoffrey/.pyenv/versions/broker_replication/lib/python3.9/site-packages/paramiko/config.py", line 323, in get_hostnames
    hosts.update(entry["host"])
KeyError: 'host'
```

If I iterate over the collection of parsed config myself, I can see that it's a match entry that's messing it up:

```
Config entry without host:
{'config': {'user': 'someuser', 'identityfile': ['somepath], 'forwardagent': 'yes'}, 'matches': [{'type': 'Host', 'param': 'somehostname', 'negate': False}, {'type': 'User', 'param': 'someuser', 'negate': False}]}
```
(I've replaced anything vaguely sensitive with strings that begin with 'some', but I don't think that changes anything important.)

So `get_hostnames` expects every config entry to have a `host` key, but clearly some of them do not. Even just skipping any entry without a host entry would significantly improve the current state.

**Comment by jun66j5** [comment]
It seems that it is a duplicate of #1729 and PR #1991 is proposed for the issue.

**Comment by geoffreywiseman** [comment]
Ah, yes, #1674 looks like it would fix it, agreed.
