### ISSUE TITLE
Comparing PKey to None fails

### ISSUE THREAD

**Issue by jsonar-cpapke** [paramiko/paramiko#2023]
We recently updated to paramiko version 2.10.3 and encountered a bug with PKey. If you create a key, and then check the equality vs `None`, it will throw an exception:
```
./site-packages/paramiko/pkey.py:143: in __eq__
    return self._fields == other._fields
E   AttributeError: 'NoneType' object has no attribute '_fields'
```

This issue can be duplicated by running this code:
```
RSAKey(filename=public_key_path) == None
```

This seems like a bug, as equals should instead return false when something is of the wrong type, instead of throwing an exception.

**Comment by bitprophet** [comment]
Rolling into the PR.
