### ISSUE TITLE
Unable hide errors

### ISSUE THREAD

**Issue by yhojann-cl** [paramiko/paramiko#2032]
By example:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import paramiko
import sys
import logging

logging.disable('DEBUG')
logging.disable('INFO')
sys.tracebacklimit = 0

try:
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect('127.0.0.1', 22, 'root', 'password')
    ssh.close()

except:
    pass
```

The results:

```
$ ./ssh.py 
Exception (client): Error reading SSH protocol banner
EOFError
During handling of the above exception, another exception occurred:
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
```

Can not hide and handle connection problems.

**Comment by jun66j5** [comment]
You could add `paramiko.util.log_to_file('/dev/null')` to stop showing the exceptions to stderr.

**Comment by MorningLightMountain713** [comment]
> You could add `paramiko.util.log_to_file('/dev/null')` to stop showing the exceptions to stderr.

What if it's a package that you've imported? I just can't supress these errors

**Comment by bskinn** [comment]
@MorningLightMountain713 Is this a problem you're having specifically with paramiko?

If so, please open a new issue with more details of the problem you're having so that we can evaluate it more effectively.
