### ISSUE TITLE
Add support for Teleport servers

### ISSUE THREAD

**Issue by jforcier-jumptrading** [paramiko/paramiko#2035]
(it's me, @bitprophet! via work account because reasons...)

Discovered issue with cert-type hostkeys at $DAYJOB when trying to use Paramiko with the Teleport ssh RBAC/etc/etc system (goteleport.com) - which, at least in our configuration, is using:
```
server key: rsa-sha2-512-cert-v01@openssh.com, rsa-sha2-256-cert-v01@openssh.com, ssh-rsa-cert-v01@openssh.com
```
Notice none of those are "regular" key types: they are all certs. I can't say I have ever run into cert-based _host keys_ before - only cert-based _publickey userauth_ ones.

`Transport._preferred_keys` (the attribute holding the equiv of the HostKey algos we support) only has regular ol' key types in them, and the check is a naive "do any of these strings match" - not taking into account any variants like cert suffixes. (Which, at present, has been delegated to the PKey classtree, and is only really referenced once the code has moved on to the userauth step...)

**Comment by jforcier-jumptrading** [comment]
That seems fixable by just adding the cert strings to the preferred keys list. However we then hit a deeper userauth problem which doesn't make any sense - one key is rejected, then a second key is submitted and teleport just clams up (eventually causing a network timeout to crash the process).

Going to continue tracking this as general "work with teleport" issue for the time being.

**Comment by jforcier-jumptrading** [comment]
Looks like that 2nd error was just a harder to spot variant on the "defaulting to rsa2 algos for a key or cert which wants ssh-rsa, often blows up". Once I rubbed `disabled_algorithms` on it, success.

So right now at least, the only real fix for this is the hostkey list additions for certs.

**Comment by jforcier-jumptrading** [comment]
Hostkey fix is released in 2.9.4/2.10.4

**Comment by justinas** [comment]
Via trial and error, this is what succeeded for me (connecting to a Teleport v9 server):

```python
disabled_algorithms={'pubkeys': ['rsa-sha2-512', 'rsa-sha2-256']}
```

**Comment by jforcier-jumptrading** [comment]
Sorry, yea, that's exactly what I meant by "rubbed disabled_algorithms on it" @justinas!
