### ISSUE TITLE
Pin cryptography version on Python 3.6?

### ISSUE THREAD

**Issue by alexpdp7** [paramiko/paramiko#2041]
Sorry, I fear this might be a duplicate bug, but I have not been able to find one, nor any doc about this. But maybe I haven't done my due diligence.

https://github.com/paramiko/paramiko/blob/main/setup.py#L96

Paramiko seems to have an unbound upper dependency on cryptography, while tests and the doc indicate Python 3.6 is supported.

cryptography>=37 deprecates support of Python 3.6 and shows warnings when running under Python 3.6:

https://cryptography.io/en/latest/changelog/#v37-0-0

Maybe Paramiko should have a conditional pin cryptography<37 when running on Python 3.6?

**Comment by jun66j5** [comment]
Workaround:

```python
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings('ignore', category=UserWarning)
    from cryptography.utils import CryptographyDeprecationWarning
with warnings.catch_warnings():
    warnings.filterwarnings('ignore', category=CryptographyDeprecationWarning)
    import paramiko
```

**Comment by alexpdp7** [comment]
You can also downgrade. But if cryptography does break compatibility with Python 3.6 (and the warnings "announce" they probably intend to do that), silencing warnings will not help.

**Comment by jun66j5** [comment]
-1. The pin is not needed.

`python_requires` in `cryptography` should be changed when  `cryptography` requires 3.7+. See https://github.com/pyca/cryptography/blob/main/setup.cfg#L40

**Comment by alexpdp7** [comment]
Well, I didn't say it was needed- I said "maybe". The downside of not pinning is that anyone who installs cryptography is going to get warnings spewed over the place. Which is not terrible, and cryptography do still to still run their test suite on Python 3.6 *and* seem to signal Python version compatibility correctly, so it's unlikely things will break hard...

But still you're going to force warnings to appear randomly downstream. Hopefully no one's parsing output and getting broken by the extra warnings... but really, what'd be the reason *against* the pin? Maybe not getting potential security patches?

**Comment by bskinn** [comment]
Is Python 3.6 still the core version on many distributions? 3.6 is officially EOL, so ideally most distributions will be upgrading away from it, making this compat question moot.

**Comment by alexpdp7** [comment]
Rocky Linux 8 (and other RHEL-derived distros) is supported until 2029 and defaults to Python 3.6. You can install other Python versions easily, but still the default behavior is to have Python 3.6 and you have to do additional work to switch to a newer version.

Ubuntu 18.04 is supported until 2028, and also runs Python 3.6. I'm not sure how easy to switch to a newer Python version, but it's also probably doable.

I want to note that I'm just making a suggestion. I kinda expect to handle these problems when choosing to use Python 3.6 which is EOL upstream. It's extra work that I'd like to be done here instead of having to deal with it myself, and also this is something that can be "harder" to solve here than in my code.

So if you wish to close this ticket, I'm good with that. I'm also happy to provide any further information you need to make a decision or to implement an improvement. The main purpose of this issue from my POV is to document the choice and provide some information to other potential users of Python 3.6

**Comment by bskinn** [comment]
@alexpdp7 Those are exactly the sort of things that would motivate keeping 3.6 compat, I would figure. It's ultimately @bitprophet's choice, but I bet this will tilt in favor of keeping 3.6 working cleanly.

How important are backports of a fix to the paramiko 2.9.x maintenance lines?

> what'd be the reason against the pin? Maybe not getting potential security patches?

Exactly. Crypto is not something you want to pin back. It may make paramiko eventually have to carry a separate security warning for 3.6, that it's forced to use an outdated version of cryptography.

----

Separately, for my understanding: is this issue separate from https://github.com/paramiko/paramiko/issues/2038? (A more general 3.6 deprecation, as opposed to specifically cryptography no longer supporting blowfish?)

**Comment by alexpdp7** [comment]
Hmmm, actually I am not sure fixing this is the way to go :) But I just wanted to discuss this. This is a subjective matter and I can completely understand if the decision made is to do nothing. It does makes sense in many aspect.

I think this is completely separate from #2038. That would affect people running all Python versions. If Paramiko can be configured to use Blowfish, when cryptography removes Blowfish, there will be breakage- I expect that to be reduced to code actually using Blowfish (but it's "possible" that people not using Blowfish will suffer. Hopefully not).

**Comment by ARMoir** [comment]
Commenting out the `blowfish-cbc` entire in the `_cipher_info` JSON of `paramiko\transport.py` has resolved the issue for me. this way there is no need to downgrade `cryptography` or suppress warnings.

```
        #"blowfish-cbc": {
        #    "class": algorithms.Blowfish,
        #    "mode": modes.CBC,
        #    "block-size": 8,
        #    "key-size": 16,
        #},
```

**Comment by alexpdp7** [comment]
That solves #2038. The problem I describe here is that if you do `import paramiko` you'll trigger cryptograhy's Python 3.6 deprecation warning, not the Blowfish warning.

**Comment by alexpdp7** [comment]
Interesting. I decided to poke a little bit in cryptography...

Apparently, Python says that deprecation warnings should by default be invisible to users, and visible to developers. Cryptography intentionally uses a "non-deprecation" warning for deprecations, so they are visible to users.

I think that means that a solution to my liking is inviable. If cryptography is making noise on purpose, it's unlikely that they will revert that change.

The ideal solution would be for paramiko to "undo" what cryptography does with warnings, so users of paramiko don't need to deal with issues in dependencies in paramiko, but I don't have a proposal on how to do that that I can endorse. So unless someone has a bright idea, I agree to closing this with wontfix.

**Comment by bskinn** [comment]
It *does* make sense to me that a security-critical library like cryptography would ignore that general Python guidance and make the warning noisy for all. For similar reasons, I doubt it's wise for paramiko (or any other consumer of cryptography) to muffle those warnings.

**Comment by alexpdp7** [comment]
Well, something like "we are going to be noisy because CryptoAlgorithmFoo is unsafe and everyone should stop using it directly or indirectly", I could agree with. But this is different, this is "right now we support Python 3.6, but we won't in the future", which sounds less dangerous to me- it sounds like they're deprecating Python 3.6 for convenience (which I can fully stand behind! It's a pain having to support a million different Python versions and code using lowest common denominator), not because it's fundamentally unsafe to do so.

However, if the cryptography maintainers think that running their code on Python 3.6 is unsafe per se, that's a different story. I think the wording of the warning implies it's a compatibility version, not a security issue.

However, I think I'm derailing, and having a discussion somewhere it doesn't belong. Happy to reply to any question directed explicitly at me, but for caution, I'll go shut up. I'm good with closing this with wontfix.

**Comment by bskinn** [comment]
No worries! This conversation has helped me flesh out my (hopefully ~accurate) understanding of what's going on, and may be useful for others who come by and read.

If I understand their deprecation correctly, they're not saying "it's unsafe to use Python 3.6 with cryptography", but instead the reverse: "over time, it will become progressively more unsafe to use cryptography with Python 3.6, because you'll be forced to pin to out-of-date, progressively-more-unsafe versions of cryptography."

Pinning cryptography to an old version while still using Python 3.6 avoids the warnings, but is a security problem.

**Comment by bitprophet** [comment]
Thanks for the discussion, folks 👍🏻  Yea, the Cryptography maintainers are AFAIK treating this very literally: this is the announcement of intent, via changelog and warnings module, but it's not even yet dropping official support.

Once they do officially drop support, it would at least mean no more testing on 3.6 (but otherwise, might keep working), and more likely, prevention of installation using setup.py metadata (stating that eg Cryptography 39 is only compatible with python>=3.7).

In the bad old days, that feature didn't exist, and we would have needed to do some defensive pinning to avoid fresh installs of Paramiko exploding, as soon as the dependency inserted Python 3.6-incompatible syntax (or etc). I don't think that's necessary anymore (any version of pip for many years now supports these "new" markers and will just hide incompatible releases) unless a dependency neglects to put those markers in their metadata. Not worried about Cryptography there.

Re: warnings: my general take is that's an end-user responsibility to use the stdlib module to mask out warnings they find offensive. Our packaging metadata should only be used to prevent serious explosions or critical security problems.

**Comment by bitprophet** [comment]
Addendum: re our own Python 3.6 support, I tend to lag behind the bleeding edge for basically the reasons @alexpdp7 mentions, so I'm planning to support it until it becomes at least moderately painful and/or moderately insecure to do so.

Cryptography will likely be the main driver here, but only in the sense that we find ourselves harming users by supporting an older version w/ a severe vulnerability, or if supporting some important new algorithm requires one of their Python 3.7+ releases.
