### ISSUE TITLE
Feature request: add st_ctime to SFTPAttributes

### ISSUE THREAD

**Issue by pvannierop** [paramiko/paramiko#2052]
# Problem
We need the timestamp of the last change time (a.k.a. the _ctime_ timestamp) for files from the remote files. At present, only _atime_ and _mtime_ are supported.

# Solution
Update _SFTPAttributes_ class to include the _str_ctime_ attribute.

I have submitted this #2053 that does implement this.

**Comment by pvannierop** [comment]
OpenSSH does not expose this attribute for remote files. Implementation of ctime is not possible for paramiko.

**Comment by RolfBly** [comment]
In addition, not all `ctimes` are equal. From [Python's stat docs](https://docs.python.org/3/library/stat.html):

> stat.ST_CTIME
> The “ctime” as reported by the operating system. On some systems (like Unix) is the time of the last metadata change, and, on others (like Windows), is the creation time (see platform documentation for details).

I just had the same question, so I happened to find out.
