### ISSUE TITLE
Need a command or function that reads a string file and returns an array object

### ISSUE THREAD

**Issue by hamad12a** [paramiko/paramiko#2062]
The summary starts with commenting on the `loadtext()` method used in the NumPy module and I use it for local processing.
I invoke it in my script as,
`np.loadtxt(skiprows=1,usecols=(1,2,3),fname = '/path/to/file')`
The parameter `fname` accepts file-like "objects" and after executing the previous line of code produces an array object.
I would like the same behavior accomplished by the Paramiko module.
If it is feasible using Paramiko to read the file as an array I can get rid of `numpy.loadtext()`.

**Comment by jun66j5** [comment]
You could use [readlines](https://docs.paramiko.org/en/stable/api/file.html#paramiko.file.BufferedFile.readlines), [readline](https://docs.paramiko.org/en/stable/api/file.html#paramiko.file.BufferedFile.readline), [\_\_iter\_\_](https://docs.paramiko.org/en/stable/api/file.html#paramiko.file.BufferedFile.__iter__) of the `stdout` and `SFTPFile`.

```python
stdin, stdout, stderr = client.exec_command('cat ' + filename)
for line in stdout:
   ...
```

or

```python
sftp = client.open_sftp()
with sftp.open(filename) as f:  # a instance of SFTPFile
  for line in f:
    ...
```

According to https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy.loadtxt, `stdout` and SFTPFile instance should be passed to `loadtxt`.

**Comment by hamad12a** [comment]
Your [answer](https://github.com/paramiko/paramiko/issues/2062#issuecomment-1140059841) helped me, however, I don't need a line by line data but an array instead which is `stdout` and/or `sftp.open(filename)`.

stdin, stdout, stderr = client.exec_command('cat ' + filename)
data = np.loadtxt(skiprows=1,usecols=(1,2,3),fname=stdout)
   ...

sftp = client.open_sftp()
with sftp.open(filename) as f:  # a instance of SFTPFile
 	data = np.loadtxt(skiprows=1,usecols=(1,2,3),fname=f)
    ...

The above snippets did the work conveniently.

**Comment by jun66j5** [comment]
> I'm still asking though; couldn't there be a method that reads that `filename` as an array to avoid using `numpy.loadtext()`?

I am not a expert of numpy, however it is needed to call `numpy.loadtext()` if you want to convert the contents of the file to a instance of `numpy.array`.

**Comment by bskinn** [comment]
This is starting to feel like we're facing an XY problem.

What is the problem with `nunpy.loadtext()`? Why are you trying to implement what you need without using it?

**Comment by hamad12a** [comment]
@bskinn  I thought there is some way to use Paramiko to read a remote file as an array which enables me to surpass using NumPy and reduce the number of lines in my code.

**Comment by bskinn** [comment]
@hamad12a Sure, I can understanding wondering if there might be a helper function of this sort on the paramiko side. If you want a numpy array, though, you're still going to need numpy -- and, it really doesn't make sense to have numpy as a dependency of paramiko: most users won't need it, and it's a _significant_ install/import burden. So, there will likely never be a paramiko API function for this.

So, your best bet is probably to tuck away the make-array-from-SFTP-file functionality in a helper function somewhere in your codebase.

Good luck with what you're working on!
