### ISSUE TITLE
Treat EOFError in early connection case differently

### ISSUE THREAD

**Issue by Anthchirp** [paramiko/paramiko#2063]
<details>
  <summary>When connecting to a busy OpenSSH server, or a server with a low `MaxStartups` setting, the server can reject incoming unauthenticated connections.
</summary>
  
```
     MaxStartups
             Specifies the maximum number of concurrent unauthenticated
             connections to the SSH daemon.  Additional connections will
             be dropped until authentication succeeds or the
             LoginGraceTime expires for a connection.  The default is
             10:30:100.

             Alternatively, random early drop can be enabled by
             specifying the three colon separated values start:rate:full
             (e.g. "10:30:60").  sshd(8) will refuse connection attempts
             with a probability of rate/100 (30%) if there are currently
             start (10) unauthenticated connections.  The probability
             increases linearly and all connection attempts are refused
             if the number of unauthenticated connections reaches full
             (60).
```
</details>

On the client this results in an `EOFError` during reading, which is then caught and replaced with an `SSHException` saying "**Error reading SSH protocol banner**":
https://github.com/paramiko/paramiko/blob/0f888a5a9d4bcfdc1d98296ad165d7da2a7e63db/paramiko/packet.py#L603-L609
https://github.com/paramiko/paramiko/blob/0f888a5a9d4bcfdc1d98296ad165d7da2a7e63db/paramiko/transport.py#L2270-L2277

While this is technically correct, I don't find it very helpful for debugging or instructive to the user, and it's not easy to distinguish the error programmatically either. Could we treat `EOFError`s differently and return an `SSHException` with a different message, eg. "**Connection rejected by server**" if nothing has been read so far?

I'm happy to make a PR to this effect.

**Comment by bskinn** [comment]
Seems to me like a reasonable feature to add! I've flagged for bitprophet's input.

**Comment by jun66j5** [comment]
I don't think your suggestion is reasonable.

The `_check_banner()` method is used on both client mode and server mode. Especially, the `"Connection rejected by server"` message  is not reasonable for server mode.

**Comment by Anthchirp** [comment]
I think your suggestion would be a user experience improvement 👍 
Do you want me to prepare a PR?

Out of interest - why would this need `#noqa`?

**Comment by bskinn** [comment]
You can go ahead and work on a PR, @Anthchirp, sure -- up to you whether or not you want to wait for @bitprophet to opine.

**Comment by jun66j5** [comment]
@Anthchirp

Yes, could you please create pullreq if possible?

`# noqa` is to prevent warnings from flake8. e.g. https://github.com/paramiko/paramiko/blob/2.11.0/paramiko/auth_handler.py#L325.

**Comment by bitprophet** [comment]
Jun's suggestion looks sound to me at a glance. Not sure how well tested this corner of the code is though, but it'd be nice to have a test around this if it's easy enough to add in the PR. 👍🏻

**Comment by bskinn** [comment]
Rolling into the PR #2066
