### ISSUE TITLE
paramiko wont work with ssh keys RSA

### ISSUE THREAD

**Issue by guno1928** [paramiko/paramiko#2069]
so i made ssh keys added them to my server and restarted the sshd service. i tested with putty and the private key worked fine but paramiko wont work at all. tried like 6 different versions from the latest 2.11 to 2.8.1 nothing works. here is my script

`import paramiko
import io
import base64
my_key = """\\
-----BEGIN OPENSSH PRIVATE KEY-----
mykey
-----END OPENSSH PRIVATE KEY-----"""

pkey = paramiko.RSAKey.from_private_key(io.StringIO(my_key))

ssh =paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
paramiko.common.logging.basicConfig(level=paramiko.common.logging.DEBUG)
ssh.connect(timeout=15, hostname="ip",username="root",password="pass",pkey=pkey)`

for security reasons changed the details and here is my output log

DEBUG:paramiko.transport:starting thread (client mode): 0x2df89520
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.1
DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5
INFO:paramiko.transport:Connected (version 2.0, client OpenSSH_8.2p1)
DEBUG:paramiko.transport:kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256'] server key:['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: curve25519-sha256@libssh.org
DEBUG:paramiko.transport:HostKey agreed: ssh-ed25519
DEBUG:paramiko.transport:Cipher agreed: aes128-ctr
DEBUG:paramiko.transport:MAC agreed: hmac-sha2-256
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-ed25519 host key for ip: b'86396d184aa0c375f275e8cabf57888d'
DEBUG:paramiko.transport:Trying SSH key b'161d7714b737d915a1a624d77b07f615'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (publickey) failed.
DEBUG:paramiko.transport:userauth is OK
Traceback (most recent call last):
  File "C:\Users\lachie\Desktop\hacker sim game\test2.py", line 28, in <module>
    ssh.connect(timeout=15, hostname="ip",username="root",password="pass",pkey=pkey)
  File "C:\Users\lachie\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 435, in connect
    self._auth(
  File "C:\Users\lachie\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 766, in _auth
    raise saved_exception
  File "C:\Users\lachie\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\client.py", line 753, in _auth
    self._transport.auth_password(username, password)
  File "C:\Users\lachie\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 1509, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "C:\Users\lachie\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\auth_handler.py", line 250, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.
DEBUG:paramiko.transport:EOF in transport thread

**Comment by bskinn** [comment]
Is this ~the same as https://github.com/paramiko/paramiko/issues/2020?

If so, see if the `disabled_algorithms` machinery helps you.

A complete rework of the auth system is planned at some point, which will hopefully make this workflow a whole lot smoother.

**Comment by jun66j5** [comment]
I believe that is configuration issue and not a bug. `disabled_algorithms` option doesn't help it because the reporter says that the issue occurs with paramiko 2.8.1 (the option is introduced in 2.9).

The following line is logged. It seems that your publickey is not configured in .ssh/authorized_keys file.

```
INFO:paramiko.transport:Authentication (publickey) failed.
```

Both private key and password are given to `connect` method. Are you trying two-factor authentication?

**Comment by jun66j5** [comment]
> ssh.connect(timeout=15, hostname="ip",username="root",password="pass",pkey=pkey)

I recommend passing `look_for_keys=False` and `allow_agent=False` when `pkey` parameter is used. `SSHClient.connect` tries to authenticate with .ssh/id_* key files and keys from agent by default.

**Comment by guno1928** [comment]
> > ssh.connect(timeout=15, hostname="ip",username="root",password="pass",pkey=pkey)
> 
> I recommend passing `look_for_keys=False` and `allow_agent=False` when `pkey` parameter is used. `SSHClient.connect` tries to authenticate with .ssh/id_* key files and keys from agent by default.

Thanks this fixed it
