### ISSUE TITLE
SSH Authentication failed causes issues with aiohttp requests

### ISSUE THREAD

**Issue by marek-leszczynski** [paramiko/paramiko#2070]
In an application I'm developing, I created an AWS lambda function responsible for delivering files over sftp.
I have several python clients for the internal APIs, and the flow follows.

1. Get file from S3 using boto3
2. Update file status in the system of record
3. Create an SSH client
4. Upload file to SFTP
5. Update file status in the system of record
6. Create a delivery log in the system of record

In the happy path, everything works like a charm. However, when I provide the wrong credentials (on purpose), in step 3, I have an AuthenticationException that I'm catching and doing needed python logging. 
After that, I'm trying to make step 5 and 6, but requests to the internal API fails with 
`aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected`

Here's part of the code for creating SSHClient
```python
class SFTPHandler:
    def __init__(self, uri, username, password, key):
        self._ssh_client = self._get_ssh_client(uri, username, password, key)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        self._ssh_client.__exit__(exc_type, exc_value, traceback)

    @staticmethod
    def _get_ssh_client(uri, username, password, key ):
        ssh_client = paramiko.SSHClient()
        ssh_client.set_missing_host_key_policy(paramiko.WarningPolicy)
        try:
            ssh_client.connect(
                *uri.split(":"), username=username, password=password, pkey=key
            )
        except paramiko.ssh_exception.AuthenticationException:
            ssh_client.close()
            raise
        return ssh_client

    def upload(self, file_: bytes, remote_path: str):
        with self._ssh_client.open_sftp() as sftp:
            file_buffer = BytesIO(file_)
            sftp.putfo(
                file_buffer, remote_path, file_size=file_buffer.getbuffer().nbytes
            )
```

and usage of above

```python
class Handler:
    # Here, I have helper methods

    async def sample_method:
        file_ = self._get_file_from_s3()
        confg = self._get_config()
        remote_path = self._get_path_from_config()
        await service_client.file.update(...)

        try:
            with SFTPHandler(**config) as handler:
                handler.upload(file_, remote_path)
        except:
            logger.execption()

        finally:
            await service_client.logs.create(...)  # This requests failes with aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

Traceback of the last error 
```
Traceback (most recent call last):
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/my-function-73ULBVc--py3.9/lib/python3.9/site-packages/company_api_client/client.py", line 79, in _call
    async with method(self._get_path(path), **kwargs) as response:
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/my-function-73ULBVc--py3.9/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/my-function-73ULBVc--py3.9/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/my-function-73ULBVc--py3.9/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/marek/Library/Caches/pypoetry/virtualenvs/my-function-73ULBVc--py3.9/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

```

I was trying to track down the issue, although I cannot pinpoint this to anything. When I provide a bad remote path, all other stuff works. When I decrease auth_timeout to e.g., 4 seconds, I don't have this error, but it's not a solution.
I've validated that all of the internal services are up and running. 

I'd be glad if someone could provide any tips what I should look for.

**Comment by marek-leszczynski** [comment]
One additional info - after putting sleep(5) after calling `sftp_client.close()` in `try ... except ... ` subsequent http request works fine.

**Comment by jun66j5** [comment]
I think that is a issue about usage of aiohttp, not a paramiko issue.... It should be asked on community of aiohttp rather than here.

**Comment by jun66j5** [comment]
* `paramiko.Transport` is a subclass of `Thread` (`SSHClient` is using the `Transport`)
* `run()` method of the `Transport` class receives and sends packets via TCP (network IO).
* `SFTPClient` doesn't do network IO.
* Therefore, I don't think `await service_client.file.update(...)` works as you're expecting.

**Comment by jun66j5** [comment]
Reconsidering the issue and sorry about my wrong comments.

* Current paramiko is not asyncio friendly.
* [asyncio and paramiko for concurrent ssh connectivity](https://stackoverflow.com/questions/71169287/asyncio-and-paramiko-for-concurrent-ssh-connectivity) page might help if using paramiko with async/await.
* I think you could use [asyncssh](https://pypi.org/project/asyncssh/) module which is asyncio friendly (but I haven't used it yet).

**Comment by marek-leszczynski** [comment]
@jun66j5 thank you for your response. I tried asyncssh and it seems to be working as expected. I'm not facing the issue with aiohttp anymore.
