### ISSUE TITLE
Paramiko timing out despite constant activity

### ISSUE THREAD

**Issue by mvvlpradeep** [paramiko/paramiko#2073]
Hi

I have a script(Firmware build ) on a remote server "A" that executes for around 30 minutes. However, the script terminates after a while on the remote server "A" when executed through the Paramiko SSH connection from another server "B". 

ipmort paramiko
from func_timeout import func_timeout, FunctionTimedOut

timeout = 3600

def communicate_with_host():
	command = "cd /root; ./bldFW.sh"
	try:
		ssh = paramiko.SSHClient()
		ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
		ssh.connect(hostname=args.server,username=args.username,password=args.password,timeout=60,auth_timeout=15)
		stdin, stdout, stderr = channel.exec_command(command)
	except Exception as E:
	        print(f"make: *** SSH error: {str(E)}")

try:
	func_timeout(timeout, communicate_with_host)
except FunctionTimedOut as err2: 
        print(f"make: *** timed-out after {timeout} secs {str(err2)}")
except Exception as e:
        print(f"make: *** exception {str(E)}")

![image](https://user-images.githubusercontent.com/35365429/175535188-ac57d722-5b07-44b5-84ab-77a53809d0c3.png)

This always returns me a Time-out error after 1 hour and I'm pretty sure that on the remote server it executes for a while and terminates abruptly

**Comment by mvvlpradeep** [comment]
Manual execution of the script on the remote server works perfectly fine and no issues are observed.

**Comment by jun66j5** [comment]
That is not a paramiko issue.

* Recommend to close `stdin`. Even if the script needs no inputs.
* Should read and close `stdout` and `stderr`. If the script has many output, the buffer of `stdout` (and `stderr`) has no left space and the script stops. 
* If no interests about output of the script, recommend to redirect stdout and sterr to /dev/null (`cd /root; ./bldFW.sh >/dev/null 2>&1`)

**Comment by mvvlpradeep** [comment]
Thanks for the suggestion, however, we need the output of the script to look for any errors during the build. 
Sometimes, the output can be in MegaBytes as well. Is there any other alternative to collect the output and even run the script without any termination?

**Comment by bskinn** [comment]
You _have_ to manage the script output somehow. Either you dispose of the output on the remote side via `/dev/null`, or you have to manage receipt of the output from the remote in a continuous fashion.

Otherwise the output buffer fills and your process locks: the remote process tries to put more output to the buffer, but the write call to the buffer hangs as long as the buffer is full. Once you read some content from the buffer and it's no longer full, remote execution should resume.

**Comment by mvvlpradeep** [comment]
Thanks for the headsup, I dumped the output to a log file with the ">" operator so that the output buffer will have enough space to run the script. Luckily after making the change in the script I was able to run the script without any issues. 

I can add an sftp line in my code to download the file from the remote server to check for the errors. 

With your help, I could able to understand the exact problem and a workaround is available.

**Comment by bskinn** [comment]
Terrific, glad you found a solution!

**Comment by mvvlpradeep** [comment]
Once again, thanks for the suggestions and timely responses over the weekend. Appreciate your help. Closing the ticket.

**Comment by jun66j5** [comment]
I tried to capture stdout/stderr of the command. It is easier to use `Channel.exec_command()` rather than `SSHClient.exec_command()`.

```python
CHUNK_SIZE = 4096

command = 'your-command...'

with paramiko.SSHClient() as client:
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    client.connect(...)
    transport = client.get_transport()
    with transport.open_session() as channel:
        channel.exec_command(command)
        channel.shutdown_write()  # close stdin
        stdout = io.BytesIO()
        stderr = io.BytesIO()
        exit_status = None
        while 1:
            if channel.exit_status_ready():
                exit_status = channel.recv_exit_status()
            while channel.recv_ready():
                stdout.write(channel.recv(CHUNK_SIZE))
            while channel.recv_stderr_ready():
                stderr.write(channel.recv_stderr(CHUNK_SIZE))
            if exit_status is not None:
                break
            channel.status_event.wait(0.125)
        stdout = stdout.getvalue()
        stderr = stderr.getvalue()
```
