### ISSUE TITLE
Unexepcted kwarg in AgentKey classmethod

### ISSUE THREAD

**Issue by colin-pm** [paramiko/paramiko#2079]
https://github.com/paramiko/paramiko/blob/1824a27c644132e5d46f2294c1e2fa131c523559/paramiko/pkey.py#L249

The from_private_key_file classmethod passes an invalid keyword argument for the constructor. Running the code below produces the the following TypeError...

```
from paramiko.agent import AgentKey
AgentKey.from_private_key_file(filename="crypto/test_id_rsa")
```

`TypeError: __init__() got an unexpected keyword argument 'filename'`

**Comment by jun66j5** [comment]
That's wrong usage.

`AgentKey` class is for internal uses by `AgentSSH` class. You cannot use directly the class. See also:

https://github.com/paramiko/paramiko/blob/1824a27c644132e5d46f2294c1e2fa131c523559/paramiko/agent.py#L75-L84
