### ISSUE TITLE
Authentication (publickey) failed

### ISSUE THREAD

**Issue by ScottSwain** [paramiko/paramiko#2085]
Hi -
I read through the following closed issue: https://github.com/paramiko/paramiko/issues/1961
I tried everything. I have latest Paramiko with Python 3.9.13 in Windows.
Only thing I have not tried is to install Paramiko 2.7.2 or 2.8, which some in that thread said works.
How do I find that version or is it possible to just "pip install paramiko-xxxx"? <--- I tried that and maybe used wrong syntax?
Thank you!

**Comment by bskinn** [comment]
The syntax would be of the form: `pip install "paramiko==2.7.2"`

**Comment by bskinn** [comment]
To be clear: you tried using the `disabled_algorithms` mechanism described in #1961 (and/or in links from that PR)?

If so -- it's hard to know what's going on with your specific situation without more details. Can you provide the error messages that you're seeing?

**Comment by ScottSwain** [comment]
First: THANK YOU BRIAN, for helping so fast!

Yes on the disabled_algos. Here's my code (and below you will find paramiko log):
"""
    ssh = SSHClient()
    ssh.set_missing_host_key_policy((AutoAddPolicy))
    try:
        key = paramiko.RSAKey.from_private_key_file(key_file, key_file_pass)
        print("\n\n")
        print("===================")
        print("\n\n")
        print("key found and verified")
    except Exception as err:
        key = None
        print("error getting key: " + str(err))
        sys.exit()

    try:
        with ssh as sftp:
            sftp.connect(host, username='" + user + "', pkey=key, timeout=4, disabled_algorithms=dict(pubkeys=['rsa-sha2-256', 'rsa-sha2-512']))
"""

DEB [20220713-18:54:42.550] thr=1   paramiko.transport: starting thread (client mode): 0xc6d3be0
DEB [20220713-18:54:42.551] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.11.0
DEB [20220713-18:54:42.566] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-AWS_SFTP_1.1
INF [20220713-18:54:42.566] thr=1   paramiko.transport: Connected (version 2.0, client AWS_SFTP_1.1)
DEB [20220713-18:54:42.593] thr=1   paramiko.transport: === Key exchange possibilities ===
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: kex algos: ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: server key: rsa-sha2-512, rsa-sha2-256, ssh-rsa
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: client encrypt: ***@***.***, aes128-ctr, aes192-ctr, aes256-ctr, ***@***.***, ***@***.***
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: server encrypt: ***@***.***, aes128-ctr, aes192-ctr, aes256-ctr, ***@***.***, ***@***.***
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: client mac: ***@***.***, ***@***.***, ***@***.***, ***@***.***, hmac-sha2-256, hmac-sha2-512
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: server mac: ***@***.***, ***@***.***, ***@***.***, ***@***.***, hmac-sha2-256, hmac-sha2-512
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: client compress: none, ***@***.***
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: server compress: none, ***@***.***
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: client lang: <none>
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: server lang: <none>
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: kex follows: False
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: === Key exchange agreements ===
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: Kex: ecdh-sha2-nistp256
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: HostKey: rsa-sha2-512
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: Cipher: aes128-ctr
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: MAC: hmac-sha2-256
DEB [20220713-18:54:42.594] thr=1   paramiko.transport: Compression: none
DEB [20220713-18:54:42.595] thr=1   paramiko.transport: === End of kex handshake ===
DEB [20220713-18:54:42.612] thr=1   paramiko.transport: kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
DEB [20220713-18:54:42.612] thr=1   paramiko.transport: Switch to new keys ...
DEB [20220713-18:54:42.613] thr=1   paramiko.transport: Got EXT_INFO: {'server-sig-algs': ***@***.******@***.******@***.***'}
DEB [20220713-18:54:42.613] thr=2   paramiko.transport: Adding ssh-rsa host key for sftp.adhererx.com: b'436cb95b8bee5aac8dd138fc573acd59'
DEB [20220713-18:54:42.613] thr=2   paramiko.transport: Trying SSH key b'6d7d36d9bb45042f968b0263dc80b955'
DEB [20220713-18:54:42.679] thr=1   paramiko.transport: userauth is OK
DEB [20220713-18:54:42.679] thr=1   paramiko.transport: Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEB [20220713-18:54:42.679] thr=1   paramiko.transport: Our pubkey algorithm list: ['ssh-rsa']
DEB [20220713-18:54:42.680] thr=1   paramiko.transport: Server-side algorithm list: ['ssh-ed25519', ***@***.***', 'ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', ***@***.***', ***@***.***']
DEB [20220713-18:54:42.680] thr=1   paramiko.transport: Agreed upon 'ssh-rsa' pubkey algorithm
INF [20220713-18:54:42.815] thr=1   paramiko.transport: Authentication (publickey) failed.
DEB [20220713-18:54:42.819] thr=1   paramiko.transport: EOF in transport thread

________________________________

**Comment by ScottSwain** [comment]
Brian -
I got it to work!
That final part was a bug that was my fault with how I was sending the connection string.
Sorry to bug ya!
Scott
________________________________

**Comment by bskinn** [comment]
Congrats! Yeah, with that `EOF in transport thread` at the end of the log, I wondered if it had something to do with how the key was packaged for sending across the wire. Glad you got it figured out!

**Comment by ScottSwain** [comment]
Maybe you can help with this last thing?
Now I'm trying to figure out how to "put" a file to the server using that connection.
But all I see out there by way of examples are people using transport.
Can I do it using the current ssh/sftp connection you see I built?
________________________________

**Comment by ScottSwain** [comment]
OOops! I got it!
Thanks again for all your help, Brian!
________________________________

**Comment by ScottSwain** [comment]
Apologies: I didn't know all my email replies would go here to clutter up your forum. Please feel free to delete anything you want in order to keep this area clean!

**Comment by ScottSwain** [comment]
If you think my finished Python 3.x script will help others, I'm happy to share it with you to put wherever you want.

**Comment by bskinn** [comment]
No worries! This is just an issue thread -- now that it's closed, it will be out of the way of anyone coming to the repo, unless they happen to find it in search. Might as well leave it!

And sure, if you want to post your finished script here, it sure can't hurt -- might help someone else in the future! Just paste it in -- though, if you would, please paste it here, as a new comment on this issue, and use triple-backticks to "code fence" the code:

```
    ```
    {paste code here}
    ```
```
