### ISSUE TITLE
disabled_algorithms getting ignored?

### ISSUE THREAD

**Issue by gusostow** [paramiko/paramiko#2090]
RSA authentication with paramiko as a client broke in versions >=2.9. I believe this is because paramiko is defaulting to sha2 algorithms instead of ssh-rsa as mentioned in the [changelog](https://www.paramiko.org/changelog.html). However, the recommended fix of using `disabled_algorithms` seems to be getting ignored by `Transport`:

Version: `2.11.0`

```
import io
import paramiko

creds = ...   # creds excluded

transport = paramiko.Transport(
    (creds["host"], 22),
    disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512']}
)

private_key = paramiko.rsakey.RSAKey.from_private_key(
    io.StringIO(creds["private_key"])
)
transport.connect(username=creds["username"], password=None, pkey=private_key)
```

Produces
```
13:27:02.432 [DEBUG] starting thread (client mode): 0x81edec50
13:27:02.432 [DEBUG] Local version/idstring: SSH-2.0-paramiko_2.11.0
13:27:02.432 [DEBUG] Remote version/idstring: SSH-2.0-SSHD
13:27:02.432 [INFO ] Connected (version 2.0, client SSHD)
13:27:02.440 [DEBUG] === Key exchange possibilities ===
13:27:02.440 [DEBUG] kex algos: diffie-hellman-group1-sha1, diffie-hellman-group14-sha1, diffie-hellman-group-exchange-sha1, diffie-hellman-group-exchange-sha256
13:27:02.441 [DEBUG] server key: ssh-rsa
13:27:02.441 [DEBUG] client encrypt: aes128-ctr, aes256-cbc, aes192-cbc, aes128-cbc, aes256-ctr, aes192-ctr, blowfish-cbc, 3des-cbc
13:27:02.441 [DEBUG] server encrypt: aes128-ctr, aes256-cbc, aes192-cbc, aes128-cbc, aes256-ctr, aes192-ctr, blowfish-cbc, 3des-cbc
13:27:02.441 [DEBUG] client mac: hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96, hmac-sha256, hmac-sha256@ssh.com, hmac-sha2-256, hmac-sha2-512
13:27:02.441 [DEBUG] server mac: hmac-sha256, hmac-sha1, hmac-md5, hmac-sha1-96, hmac-md5-96, hmac-sha256@ssh.com, hmac-sha2-256, hmac-sha2-512
13:27:02.441 [DEBUG] client compress: none, zlib
13:27:02.441 [DEBUG] server compress: none, zlib
13:27:02.441 [DEBUG] client lang: <none>
13:27:02.441 [DEBUG] server lang: <none>
13:27:02.441 [DEBUG] kex follows: False
13:27:02.441 [DEBUG] === Key exchange agreements ===
13:27:02.441 [DEBUG] Kex: diffie-hellman-group-exchange-sha256
13:27:02.441 [DEBUG] HostKey: ssh-rsa
13:27:02.441 [DEBUG] Cipher: aes128-ctr
13:27:02.441 [DEBUG] MAC: hmac-sha2-256
13:27:02.441 [DEBUG] Compression: none
13:27:02.441 [DEBUG] === End of kex handshake ===
13:27:02.535 [DEBUG] Got server p (2048 bits)
13:27:02.596 [DEBUG] kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
13:27:02.596 [DEBUG] Switch to new keys ...
13:27:02.596 [DEBUG] Attempting public-key auth...
13:27:02.642 [DEBUG] userauth is OK
13:27:02.642 [DEBUG] Finalizing pubkey algorithm for key of type 'ssh-rsa'
13:27:02.642 [DEBUG] Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
13:27:02.642 [DEBUG] Server did not send a server-sig-algs list; defaulting to our first preferred algo ('rsa-sha2-512')
13:27:02.642 [DEBUG] NOTE: you may use the 'disabled_algorithms' SSHClient/Transport init kwarg to disable that or other algorithms if your server does not support them!
13:27:02.651 [INFO ] Authentication (publickey) failed.
Traceback (most recent call last):
  File "/home/aostow/projects/paramiko/test_sftp.py", line 29, in <module>
    transport.connect(username=creds["username"], password=None, pkey=private_key)
  File "PREFIX/lib/python3.7/site-packages/paramiko/transport.py", line 1388, in connect
    self.auth_publickey(username, pkey)
  File "PREFIX/lib/python3.7/site-packages/paramiko/transport.py", line 1635, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "PREFIX/lib/python3.7/site-packages/paramiko/auth_handler.py", line 259, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

```

Please advise, thanks!

**Comment by gusostow** [comment]
Oh I realized it needs to be `pubkeys` in my case. Can the docs be clarified here?
```
disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']}
```

**Comment by bskinn** [comment]
@gusostow By all means -- we'd welcome a PR with a clarification!

**Comment by gusostow** [comment]
I would've offered sooner, except I have very little understanding of paramiko or public key cryptography. I can give it a shot though.

**Comment by bskinn** [comment]
No pressure! If you'd rather not, we can just leave it here to pick up later.

**Comment by perrinjerome** [comment]
> @gusostow By all means -- we'd welcome a PR with a clarification!

Would https://github.com/paramiko/paramiko/pull/2200 be a good clarification ?

**Comment by Kache** [comment]
Ran into this "slightly backwards incompatible" issue, as summarized in [Paramiko fails ... when upgrading to 2.9.0+](https://stackoverflow.com/questions/75836730/paramiko-fails-connecting-w-private-key-file-is-encrypted-when-upgrading-to-2)

Also linking: https://github.com/paramiko/paramiko/pull/1643#issuecomment-1483228060

Not sure why @bitprophet closed #2200 without suggesting an alternative, clearly the docs for this "slightly backwards incompatible" change are lacking.

**Comment by bskinn** [comment]
> Not sure why bitprophet closed https://github.com/paramiko/paramiko/pull/2200 without suggesting an alternative

The alternative is going to be the new, opt-in key/auth machinery that he's working on for #387.

The hope is that a new system, built from scratch, will be much cleaner and easier to work with all around, and all of this dancing about with `disabled_algorithms` will become moot.

**Comment by bitprophet** [comment]
I can confirm that I've included fixes in what will become v3.2 that, at least in my production cases (server target which does not send server-sig-algs and does not support SHA2, and was thus breaking due to the default choice of SHA2, even when ssh-rsa was available as an option). So this will ideally become moot once 3.2 is out (should be within a few weeks unless something comes up).

**Comment by ShiftyF9** [comment]
> Oh I realized it needs to be `pubkeys` in my case. Can the docs be clarified here?
> 
> ```
> disabled_algorithms={'pubkeys': ['rsa-sha2-256', 'rsa-sha2-512']}
> ```

please do this! just wasted about four hours of my day wondering why the changelog spec'd 'keys' wasn't working...

**Comment by f3xadm** [comment]
When using nested ssh connection (ssh to jump server and then ssh from jump server to the target machine) I am still getting the same error.

```
with paramiko.SSHClient() as jhost:
    jhost.connect(hostname=JUMP_SERVER, username=user,  allow_agent=True, timeout = 10, disabled_algorithms=dict(pubkeys=['rsa-sha2-256', 'rsa-sha2-512']))
    jhost_transport = jhost.get_transport()
    dest_addr = (RESOURCES_SERVER, 22)
    local_addr = (JUMPHOST_SERVER, 22)
    jhost_channel = jhost_transport.open_channel("direct-tcpip", dest_addr, local_addr)
    
    with paramiko.SSHClient() as target_server:
        target_server.connect(hostname=TARGET_SERVER, sock=jhost_channel,  allow_agent=True, timeout = 10, disabled_algorithms=dict(pubkeys=['rsa-sha2-256', 'rsa-sha2-512']))
    
        _, stdout, stderr = target_server.exec_command(command)
        stdout = stdout.read().decode('utf-8')
        stderr = stderr.read().decode('utf-8')
```
		
		
These are the disabled_algorithms configurations that I have tried but no success:

disabled_algorithms=dict(pubkeys=['rsa-sha2-256', 'rsa-sha2-512'])

disabled_algorithms={'pubkeys':['rsa-sha2-512', 'rsa-sha2-256']}

disabled_algorithms={'keys': ['rsa-sha2-256', 'rsa-sha2-512'], 'pubkeys':['rsa-sha2-512', 'rsa-sha2-256']}

Do you have any idea what I am doing wrong?

Connecting to jump server works fine, but the connection fails from jump server to the target machine.

DEB [20250122-14:49:28.502] thr=9   paramiko.transport: Got EXT_INFO: {'server-sig-algs': b'ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521'}
DEB [20250122-14:49:28.503] thr=2   paramiko.transport: Adding ssh-rsa host key for <IP>: b'<DATA>'
DEB [20250122-14:49:28.505] thr=2   paramiko.transport: Trying SSH agent key b'<DATA>'
DEB [20250122-14:49:28.668] thr=9   paramiko.transport: userauth is OK
DEB [20250122-14:49:28.669] thr=9   paramiko.transport: Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEB [20250122-14:49:28.669] thr=9   paramiko.transport: Our pubkey algorithm list: ['ssh-rsa']
DEB [20250122-14:49:28.669] thr=9   paramiko.transport: Server-side algorithm list: ['ssh-ed25519', 'ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521']
DEB [20250122-14:49:28.669] thr=9   paramiko.transport: Agreed upon 'ssh-rsa' pubkey algorithm
INF [20250122-14:49:28.759] thr=9   paramiko.transport: Authentication (publickey) failed.
