### ISSUE TITLE
ConfigParseError if ssh config contains a comment with a single quote

### ISSUE THREAD

**Issue by PicoGeyer** [paramiko/paramiko#2111]
I'm using fabric and wanted to test a very simple run command:
```
from fabric import Connection
c = Connection('myhost')
```

This gave me the exception:
`
paramiko.ssh_exception.ConfigParseError: Unparsable host 172.16.0.1  # Bob's server
`

It seems paramiko trips over config files with single quotes in comments.
openssh has no problem with this config.
Perhaps the parser could be improved to handle this? 

```
paramiko.__version__
'2.11.0'
```

**Comment by jun66j5** [comment]
It seems to be a paramiko issue, however lines starts with `#` character and empty lines are interpreted as comments.

Your `# Bob's server` in `host 172.16.0.1 # Bob's server` is not comment.

**Comment by PicoGeyer** [comment]
I think it's okay if you want to close this as not a bug.
The openssh parser may be more lenient than the docs say because it still manages to parse and treat lines like that properly.
I got into the habit of adding comments that way, but I can change my config to have the comments on their own line.
