### ISSUE TITLE
upload 0kb file when use "sftp.put" func

### ISSUE THREAD

**Issue by poplangfan** [paramiko/paramiko#2113]

**Comment by poplangfan** [comment]
When I tried to upload my local script to a Linux device, I found that all the files were 0kb.

**Comment by bskinn** [comment]
@poplangfan You'll need to provide much more detail in order for someone to help you. What were the exact commands you used? What output did you observe while paramiko was working?

**Comment by poplangfan** [comment]
I'm sorry, but my purpose is to upload a folder to a Linux device, and the underlying call is 'sftp.put()'. The entire process is to traverse all files in the folder and upload the files in sequence. However, there is a possibility that all the files to be uploaded are 0 KB. I tried to find a solution by sending a'sync' command to linux after uploading a file, but it didn't work.

**Comment by jun66j5** [comment]
That is not a paramiko issue.

[SFTPClient.put](https://docs.paramiko.org/en/stable/api/sftp.html#paramiko.sftp_client.SFTPClient.put) expects a file for local and remote.

> Copy a local file (localpath) to the SFTP server as remotepath. Any exception raised by operations will be passed through. This method is primarily provided as a convenience.

Paramiko says at https://www.paramiko.org/:

> Direct use of Paramiko itself is only intended for users who need advanced/low-level **_primitives_** or want to run an in-Python sshd.

See also: https://stackoverflow.com/questions/4409502/directory-transfers-with-paramiko
