### ISSUE TITLE
AutoAddPolicy not working

### ISSUE THREAD

**Issue by iliawhite** [paramiko/paramiko#2115]
Here's my code
```
import paramiko

paramiko.SSHClient().set_missing_host_key_policy(paramiko.AutoAddPolicy())

host = 'ip here'
user = 'root'
passwd = 'password here'

paramiko.SSHClient().connect(hostname=host, port=22, username=user, password=passwd, look_for_keys=False)
stdin, stdout, stderr = paramiko.SSHClient().exec_command('ls -l')
data = stdout.read() + stderr.read()
paramiko.SSHClient().close()
```
Got this error
```
SSHException
Server 'ip here' not found in known_hosts
  File "D:\Code\dns-configurator\test.py", line 9, in <module>
    paramiko.SSHClient().connect(hostname=host, port=22, username=user, password=passwd, look_for_keys=False, timeout=60)
```

**Comment by jun66j5** [comment]
That is caused by wrong programming. The instance of `paramiko.SSHClient` should be stored to a variable and call methods of the variable.

```
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(...)
```

**Comment by chengyechun** [comment]
Is that for sure? I tried it and there was no error. Is this related to the interpreter?

**Comment by jun66j5** [comment]
No. The cause is just a wrong programming. Also, I recommend you post a script which you've tried if you have different opinion.

@bskinn I suggest closing this issue because no feedback from the reporter and just a simple programming error.

**Comment by bskinn** [comment]
Agreed re closing, @jun66j5.

@chengyechun, this is a fairly common model in various packages, where you create an instance of a class and then configure *that same instance* via calling its methods before using it. Please try using it as @jun66j5 has suggested, and if you still have trouble please open a new issue, providing as much detail as you can. Good luck!
