### ISSUE TITLE
No __del__() would be called in the whole project if SSHClient.connect() called

### ISSUE THREAD

**Issue by easylyou** [paramiko/paramiko#2120]
Hi! I found something odd in paramiko. Please see the two example code below.

```py
import paramiko
class Dummy:
    def __del__(self):
        print('del')

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
d = Dummy()
# When the process exit, "print('del')" outputs correctly.
```

```py
import paramiko
class Dummy:
    def __del__(self):
        print('del')

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('<ip>', 22, '<name>', '<password>') # plz make connect successful by putting the right params
d = Dummy()
# When the process exit, no output at all.
```

It seems the refcount of python broken after connect() called. Although I know '__del__' is not reliable, I think paramiko should not affect other code's behaviors.

Here is my environment.
both python3.9 and python3.10
macOS 12.5
Apple M1 silicon

**Comment by jun66j5** [comment]
That is a Python issue, not a paramiko issue.

`__del__` method of variables in global scope may not invoked on Python interpreter shutdown.

Instead, create an instance in a method (e.g. `main()`) or destruct the instances using `atexit`.

```python
def main():
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(...)
    d = Dummy()

if __name__ == '__main__':
    main()
```

**Comment by easylyou** [comment]
Thanks for reply! 
You are right. The `__del__` works well in the `main()` scope.
