### ISSUE TITLE
Paramiko SSH Agent Lost when developping inside a Container using Remote Explorer

### ISSUE THREAD

**Issue by EvaGayraud** [paramiko/paramiko#2124]
Hello,

I am trying to develop inside vscode remote container and use debug. However, the SSH agent from the lib paramiko is lost when using vscode to develop in a remote container. I am not facing this issue if I run the code inside the container and outside of the remote explorer or locally. All works well with MAC OS and Vscode.

VSCode Version: 1.71.2
Local OS Version: Windows 10 Professionnel
Remote OS Version: Docker Desktop 4.0.0 / engine v20.10.8
Remote Extension/Connection Type: Remote Explorer - Containers
We are using the lib paramiko in Python to implementate the SSHv2 protocol with Python.

Here is the issue I get :
raise SSHException("lost ssh-agent") paramiko.ssh_exception.SSHException: lost ssh-agent

This did not happen last month.

I already posted this issue on vscode remote explorer : https://github.com/microsoft/vscode-remote-release/issues/7298

Thank you

**Comment by jun66j5** [comment]
Please provide minimal code to reproduce the issue and stacktrace of the error.

**Comment by EvaGayraud** [comment]
Hello, 

Below are the files and the code used to reproduce the error, I used the same environment as mentionned above:

```
# docker-compose.yml 
version: '3.8'

services:
  sftp_python_client:
    container_name: sftp_python_client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SFTP_URL=sftp
      - SFTP_PORT=22
      - SFTP_USER=foo
      - SFTP_PASSWORD=pass

  sftp:
    container_name: sftp
    image: atmoz/sftp
    command: foo:pass:1001
```

```
# Dockerfile
FROM python:3.9.7

# Install
RUN pip install paramiko

# Run commands
RUN echo 'import paramiko \n\
import os \n\
sshclient = paramiko.SSHClient() \n\
sshclient.load_system_host_keys() \n\
sshclient.set_missing_host_key_policy(paramiko.AutoAddPolicy()) \n\
sshclient.connect(hostname=os.environ["SFTP_URL"], port=os.environ["SFTP_PORT"], username=os.environ["SFTP_USER"], password=os.environ["SFTP_PASSWORD"]) \n\
print("status: ", sshclient.get_transport().is_active())' > /ssh_command.py

ENTRYPOINT tail -f /dev/null
```
## Commands 

**Without Remote Explorer (works well):** 

- docker-compose build
- docker-compose up -d
- docker exec -it sftp_python_client bash

Then, inside the container: 

- python3 /ssh_command.py

##### Output:
**status: True**

--- 

**With Remote Explorer (does not work):** 

- docker-compose build
- docker-compose up -d

Open Remote Explorer and open a new terminal:
- python3 /ssh_command.py

##### Output:
![image](https://user-images.githubusercontent.com/64273829/194524115-462997e2-565c-4b2e-be6e-26a0bb55f9d4.png)

It also does not work if I run the file with Vscode button "Run Python File"

**Comment by EvaGayraud** [comment]
Thank you a lot, setting `allow_agent=False` works well! It seems that Vscode set SSH_AUTH_SOCK. 

```
echo $SSH_AUTH_SOCK 
/tmp/vscode-ssh-auth-1896c9be0aae3b37ae4d7e176ee9b99913b50e5e.sock
```
