### ISSUE TITLE
Cisco, ChannelException(3, 'Unknown channel type')

### ISSUE THREAD

**Issue by pbulay** [paramiko/paramiko#2127]
When I use cisco as the jump server to connect to the target server,
local -> ciscoA-> ciscoB-> targer
`channel = transport.open_channel("direct-tcpip", dest_address, local_address, timeout=20)`

The local connection to ciscoA is successful. The following error occurs when ciscoA connects to ciscoB:
```
2022-10-12 13:54:22,736 transport.py 1874 ERROR Secsh channel 0 open FAILED: : Unknown channel type
2022-10-12 13:54:22,737 paramiko_ssh_multi_server.py 106 ERROR ciscoB:ChannelException(3, 'Unknown channel type')
```

remark:
When the jump server is not a cisco device, the program runs normally

**Comment by jun66j5** [comment]
Your cisco device doesn't support `direct-tcpip` channel type. That's  a cisco device issue. Please ask on cisco support rather than here.
