### ISSUE TITLE
channel.send ascii codes [80-FF] are alway converted to utf8

### ISSUE THREAD

**Issue by adrenochrome25** [paramiko/paramiko#2132]
Hello,

our ssh target is an old Unix-AIX running pick-universe which rely on chars in range [80-FF] , especially 0xff,0xfe,0xfd that are intensively used as multivalue separators. So we are using single-byte [windows-1252](https://en.wikipedia.org/wiki/Windows-1252)(=cp-1252) encoding in order to get reliable representation of theses chars.
This way of doing works very well with openssh command, putty and various gui based ssh clients, but today i'm struggling with a python webssh implementation.

When i use paramiko to send 1 byte char 'ý', verifying this byte has really value '\xfd', as expected channel.send() report 1 byte written.
But when i trap input from shell on server-side (using byte-by-byte read loop dumping to file, without echo) , unfortunately it reveal paramiko internals sends to the shell an 'ý' encoded in utf-8 on two bytes '\xc3\xbd'

in the other way no problem : if i cat a stored '\xfd' byte from server-side,  channel.recv() receive a b'\fd' that i can encode properly the way i want

any idea how to send ascii chars in range [80-FF] into ssh channel without paramiko converting them to utf-8 ?

thanks in advance
(edit : light rewording and typo)

**Comment by jun66j5** [comment]
`Channel.send()` expects a `bytes` instance. I guess `str` instance is passed. Try to pass a `bytes` instance rather than a `str` instance (`b'\xfd'`).

```
>>> ord(u'ý')
253
>>> u'ý'.encode('utf-8')
b'\xc3\xbd'
```

**Comment by adrenochrome25** [comment]
thank you so much
i never tried because doc says str

> send(s)
> ...
> Parameters:	s (str) – data to send

that may explain why every exemple i gathered are using str too (or maybe i'm bad at searching)

**Comment by jun66j5** [comment]
That `str` is `str` in Python 2.

**Comment by jun66j5** [comment]
Ideally, I think the docstring should use `bytes` rather than `str` and the method should raise `ValueError` on non-`bytes` instance, but doesn't currently do so.

`Channel.send` is designed similarly to `socket.send`, so it makes sense to use a `bytes` instance...

Anyway, please close this issue if fixed.
