### ISSUE TITLE
pseudo terminal

### ISSUE THREAD

**Issue by chengyechun** [paramiko/paramiko#2141]
After executing invoke_shell on the SSHClient, run the vim 1.txt command. How can I exit the SSHClient?

**Comment by chengyechun** [comment]
This method may be problematic. You can use the open function of sftpclient to write files or use put to transfer written local files. An error occurs when interactive commands are executed using an independent channel.

**Comment by jun66j5** [comment]
Please describe the error which you've encountered and what you want to do. In most case, interactive shell is not needed.
