### ISSUE TITLE
How to get contents of a file

### ISSUE THREAD

**Issue by gamesharkmike** [paramiko/paramiko#2148]
How can I get the contents of a file on an SSH server w/ Paramiko? I do not want to download the file, just get the contents of it

I figure the cat command would work, but is there a better way or built-in method to get the contents of a file?

Thanks.

**Comment by jun66j5** [comment]
Try SFTP and check documentation and demo codes:

* https://github.com/paramiko/paramiko/blob/main/demos/demo_sftp.py
* https://docs.paramiko.org/en/stable/api/sftp.html

**Comment by gamesharkmike** [comment]
Thanks. I didn't intend to download a temp file, but it appers the sftp modules can get the contents of a file over sftp without downloading to a file :)
