### ISSUE TITLE
dev-requirements.txt pins are not compatible with python 3.10

### ISSUE THREAD

**Issue by alex** [paramiko/paramiko#2149]
This looks to be because the pytest pinned there is relatively old. Can that pin be bumped? Happy to send a PR for that.

Example failing run: https://github.com/pyca/cryptography/actions/runs/3508654856/jobs/5877217208

**Comment by alex** [comment]
I think this requires updates to pytest-relaxed, https://github.com/bitprophet/pytest-relaxed/pull/22.

**Comment by bitprophet** [comment]
Rolling into reaperhulk's PR 👍🏻
