### ISSUE TITLE
channel.recv is block and it not throw any error 

### ISSUE THREAD

**Issue by yangislet** [paramiko/paramiko#2152]
When I call the recv() function, the SSH connection is disconnected at this time, but the recv() function does not throw any exception, so my program is stuck in the recv() function。 how to deal this **throuble?**
`_channel = self.ssh.invoke_shell()
if not _channel.recv_ready(): 
    return
#if ssh connection is  disconnected at this time, the "recv()" function is block and it not throw any error
_channel.recv(100)`

**Comment by avatarofhope2** [comment]
try calling `_channel.settimeout(5)`

channel.py shows
```python
def settimeout(self, timeout):
    """
    Set a timeout on blocking read/write operations.  The ``timeout``
    argument can be a nonnegative float expressing seconds, or ``None``.
    If a float is given, subsequent channel read/write operations will
    raise a timeout exception if the timeout period value has elapsed
    before the operation has completed.  Setting a timeout of ``None``
    disables timeouts on socket operations.
    ``chan.settimeout(0.0)`` is equivalent to ``chan.setblocking(0)``;
    ``chan.settimeout(None)`` is equivalent to ``chan.setblocking(1)``.
    :param float timeout:
        seconds to wait for a pending read/write operation before raising
        ``socket.timeout``, or ``None`` for no timeout.
    """
    self.timeout = timeout
```

**Comment by bskinn** [comment]
Given the age of this ticket, I'm going to close.

@yangislet, if you still need assistance, please create a [new support ticket] and provide all of the info requested by the template. Thanks!

[new support ticket]: https://github.com/paramiko/paramiko/issues/new?assignees=&labels=Support&projects=&template=10_support_request.yml&title=%5BSUPPORT%5D+-+%3Ctitle%3E
