### ISSUE TITLE
Equivalent of `ssh -N` ?

### ISSUE THREAD

**Issue by ardell** [paramiko/paramiko#2164]
Ssh has a `-N` flag to skip executing a remote command:

```
$> man ssh
...
-N      Do not execute a remote command.  This is useful for just forwarding ports.
```

Is there a way to achieve this with paramiko?

**Comment by jun66j5** [comment]
The `ssh` command automatically invokes shell by default after connected to remote server, however `paramiko` does automatically nothing.
