### ISSUE TITLE
Pageant Windows - specify key

### ISSUE THREAD

**Issue by jeee-naut** [paramiko/paramiko#2168]
I'm trying to build a small application which connects to multiple servers.
While the pageant integration works fine, it only does so for servers which are stored in "saved sessions" (from PuTTy).
Like the keys are identified by hostname only.

Is there another  way to specify the key to use?

There is no error message. The execution of the ssh command fails silently, there is just no output.
Could this mean the login is successful, but decrypting the answer fails?

Thanks for your help win advance

Best

Jochen

**Comment by jun66j5** [comment]
It seems your support question is about PuTTY pageant with `ssh` command, not paramiko. This issue tracker is for to develop paramiko. You may not get a good answer here.

Instead, please ask on stackoverflow.

If you have any questions about paramiko, please explain how you're trying to use paramiko with PuTTY pagaent.

**Comment by jeee-naut** [comment]
Hi jun66j5,

thanks for your quick reaction.

In the meantime I found out that I managed to choose a bad example of a server for testing. (facepalm!)
Sorry for bothering you.
Works great. Keep up with the good work!

Best

P.S:

Just for the record, and in case someone has use for a working example,
This is my test code
(Windows 10, Python 3.10, paramiko 2.12.0)

`import paramiko


def remote_ssh(server, u_name, exec_cmd, ssh_client):
    ssh_client.connect(hostname=server, port=port, username=u_name, allow_agent=True, look_for_keys=False)
    r_stdin, r_stdout, r_stderr = ssh.exec_command(exec_cmd)
    out_res = []
    out_err = []
    for i in r_stdout:
        out_res.append(i.rstrip())
    for i in r_stderr:
        out_err.append(i.rstrip())
    return out_res, out_err


if __name__ == '__main__':
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    port = 22
    user = '<username>'
    hostlist = ['host01', 'host02']
    command = 'ls /etc/crontab'
    for host in hostlist:
        stdout, stderr = remote_ssh(host, user, command, ssh)
        print("Host: {0}: {1}: {2}".format(host, command, stdout))
    ssh.close()`
