### ISSUE TITLE
Interactive.py DEMO

### ISSUE THREAD

**Issue by gabriel-dahan** [paramiko/paramiko#2171]
Hi, there might be an error in https://github.com/paramiko/paramiko/blob/main/demos/interactive.py ; there is no file py3compat anymore, from where should 'u' must be imported now ? Thank you :)

**Comment by vXtreniusX** [comment]
> from where should 'u' must be imported now ?

I think that using [bytes.decode()](https://docs.python.org/3/library/stdtypes.html#bytes.decode) on line 54 should work correctly.

`x = chan.recv(1024).decode()`

From [py3compat](https://github.com/paramiko/paramiko/blob/81f49ed4fcd46685002d4dd8b299a6c8fb3b2367/paramiko/py3compat.py#L158):
```py3
def u(s, encoding="utf8"):
    """cast bytes or unicode to unicode"""
    if isinstance(s, bytes):
        return s.decode(encoding)
    elif isinstance(s, str):
        return s
    else:
        raise TypeError("Expected unicode or bytes, got {!r}".format(s))
```

**Comment by bskinn** [comment]
@vXtreniusX If you're so inclined, a quick PR to remove the dead import and rewrite the `u()` call would be great to have.

Thanks for the help here!
