### ISSUE TITLE
Intermittent Python crash when gc traverses the Packetizer.read_all frame

### ISSUE THREAD

**Issue by ni-balexand** [paramiko/paramiko#2184]
I'm trying to identify the root cause of a Python crash in an application I am working on. A peek at the crash dump shows that it might be coming from some sort of memory corruption in Paramiko. Specifically, the crash is coming from inside the `subtract_refs` function, called from `collect`:

```
python37!visit_decref+0x6 [c:\a\18\s\modules\gcmodule.c @ 271]
python37!frame_traverse+0xd2 [c:\a\18\s\objects\frameobject.c @ 516]
python37!subtract_refs+0x87 [c:\a\18\s\modules\gcmodule.c @ 296]
python37!collect+0xb6 [c:\a\18\s\modules\gcmodule.c @ 861]
python37!collect_with_callback+0x34 [c:\a\18\s\modules\gcmodule.c @ 1026]
python37!collect_generations+0x4d [c:\a\18\s\modules\gcmodule.c @ 1048]
python37!_PyObject_GC_Alloc+0xb6 [c:\a\18\s\modules\gcmodule.c @ 1705]
python37!_PyObject_GC_Malloc+0xb6 [c:\a\18\s\modules\gcmodule.c @ 1715]
python37!_PyObject_GC_New+0xc3 [c:\a\18\s\modules\gcmodule.c @ 1727]
python37!new_dict+0xeb [c:\a\18\s\objects\dictobject.c @ 584]
python37!new_dict_with_shared_keys+0x16e [c:\a\18\s\objects\dictobject.c @ 615]
python37!_PyObjectDict_SetItem+0x42d [c:\a\18\s\objects\dictobject.c @ 4319]
python37!_PyObject_GenericSetAttrWithDict+0x537 [c:\a\18\s\objects\object.c @ 1360]
python37!_PyEval_EvalFrameDefault+0xf43 [c:\a\18\s\python\ceval.c @ 2015]
python37!PyEval_EvalFrameEx+0x17 [c:\a\18\s\python\ceval.c @ 547]
python37!function_code_fastcall+0x63 [c:\a\18\s\objects\call.c @ 283]
python37!_PyFunction_FastCallKeywords+0xb7 [c:\a\18\s\objects\call.c @ 408]
python37!call_function+0x291 [c:\a\18\s\python\ceval.c @ 4616]
```

(Yes, this is Python 3.7 on Windows - specifically Windows 10 64-bit version 22H2)

The frame object that the garbage collector is traversing when it crashes is in `paramiko/packet.py`. Specifically, it is the `read_all` function, and looking at the memory there it seems like the local variable `out` has somehow been corrupted. I have no idea how, but that's what I'm going on so far.

Some other notes on this - I'm on paramiko 3.0.0, I've also tried upgrading Python from 3.7.9 to 3.9.13 but saw the same symptoms after upgrading (saw crash, did not dig into the crashdump). The crash is intermittent and difficult to reproduce.

Something is going awry among Python, the Windows socket, the Linux SSH server I'm connecting to, and the Paramiko SSH client.

I have more experiments to try on my end to see if I can get to the bottom of this, but since the crash seems to be pointing to Paramiko code, I figure I'd submit an issue for this and see if anyone has any suggestions for troubleshooting.

**Comment by ni-balexand** [comment]
This issue seems related to #520
That issue points to a hang at `socket.recv` inside of `read_all`, which is the original reason that the transport couldn't cleanly `join`.

**Comment by ni-balexand** [comment]
Closing this issue, as the intermittent crash was root-caused and it was identified that the memory corruption was being caused by code in a different C++ library running in the process.

**Comment by bskinn** [comment]
Thanks for following up on this, @ni-balexand!
