### ISSUE TITLE
Need clarity on cryptography vulnerability

### ISSUE THREAD

**Issue by sanjaikumaar** [paramiko/paramiko#2195]
Hi, 

I would like to know whether paramiko is affected by the [cryptography security vulnerability listed here](https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r). I didn't find update_into method of cryptography in any part of paramiko code but I would like to get a confirmation from you that paramiko is not affected by this security vulnerability.

Thanks in advance!!

**Comment by bitprophet** [comment]
We only appear to use `Cipher.update()` ([e.g.](https://github.com/paramiko/paramiko/blob/main/paramiko/ed25519key.py#L129-L136)), not `update_into`, so we should be safe from this. Thanks!

**Comment by Shilpi-J** [comment]
Thanks @bitprophet for the response.

**Comment by Shilpi-J** [comment]
But we have been using Paramiko version < 1.0.
In this version as well, can we say that this vulnerability is not impacting paramiko ?
