### ISSUE TITLE
File transfer hangs while closing the channel

### ISSUE THREAD

**Issue by gautamvs82** [paramiko/paramiko#2197]
Hello!,

We face this issue frequently where the file transfer hangs while closing the channel. This is what we see in the logs when the file transfer hangs. 

DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
INFO:paramiko.transport.sftp:[chan 0] Opened sftp connection (server version 3)
DEBUG:paramiko.transport.sftp:[chan 0] open(b'./Inbox/file_1.gz.pgp', 'wb')
DEBUG:paramiko.transport.sftp:[chan 0] open(b'./Inbox/file_1.gz.pgp', 'wb') -> 30
DEBUG:paramiko.transport.sftp:[chan 0] close(30)

We use the paramiko version 3.0.0
Is this known bug ? Is there any plan to fix ?

Thanks

**Comment by bskinn** [comment]
@gautamvs82 Please provide more information about the platform you're working on (OS, etc.), as well as the code you're using that causes the problem.

**Comment by bskinn** [comment]
I am closing this issue for now. Please feel free to reply with the requested additional information and reopen the issue if you wish further support.
