### ISSUE TITLE
Is paramiko affected with cryptography vulnerability

### ISSUE THREAD

**Issue by Shilpi-J** [paramiko/paramiko#2198]
In continuation to this issue: https://github.com/paramiko/paramiko/issues/2195
The vulnerability link for quick reference: https://github.com/pyca/cryptography/security/advisories/GHSA-w7pp-m8wf-vj6r

As disposition of this issue, it is mentioned that 
"We only appear to use Cipher.update() ([e.g.](https://github.com/paramiko/paramiko/blob/main/paramiko/ed25519key.py#L129-L136)), not update_into, so we should be safe from this."
 
The question from our end is that we have been using **Paramiko version < 2.0.0**
In this version as well, can we say that this vulnerability is not impacting paramiko ?

**Comment by bskinn** [comment]
@Shilpi-J First of all, if you're using a version of paramiko that old, you have significant *additional* security concerns than just this one.

That said, this is something that you can determine for yourself.

Within the environment where the version of paramiko you're interested in is installed, look for the `site-packages/paramiko` directory. Then, search the contents of the files in that directory for `.update_into`.

One way to do this is with the 'search in files' feature of an IDE like VS Code -- click into the file explorer and press Ctrl+Shift+F to open the 'search in files' dialog.

Alternatively, if you're on Linux (and probably Mac?): open a terminal window, navigate to the `site-packages/paramiko` directory, and run `rgrep '.update_into'`.

With either of these methods, if no results are returned, then this vulnerability does not apply to that version of paramiko.

**Comment by bitprophet** [comment]
What @bskinn said! And we no longer support Paramiko <2.0, so I'm afraid this would be irrelevant anyways. Please upgrade when you can, and good luck!
