### ISSUE TITLE
python3 arm64 instance installation fails

### ISSUE THREAD

**Issue by clcc2019** [paramiko/paramiko#2199]
> [4/4] RUN pip install paramiko:
#0 14.39 ERROR: Exception:
#0 14.39 Traceback (most recent call last):
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
#0 14.39     status = run_func(*args)
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#0 14.39     return func(self, options, args)
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 285, in run
#0 14.39     session = self.get_default_session(options)
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 75, in get_default_session
#0 14.39     self._session = self.enter_context(self._build_session(options))
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 89, in _build_session
#0 14.39     session = PipSession(
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 282, in __init__
#0 14.39     self.headers["User-Agent"] = user_agent()
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 122, in user_agent
#0 14.39     linux_distribution = distro.name(), distro.version(), distro.codename()
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 341, in version
#0 14.39     return _distro.version(pretty, best)
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 861, in version
#0 14.39     self.uname_attr("release"),
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1052, in uname_attr
#0 14.39     return self._uname_info.get(attribute, "")
#0 14.39   File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
#0 14.39     val = self.func(instance)
#0 14.39   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1186, in _uname_info
#0 14.39     stdout = subprocess.check_output(cmd, stderr=devnull)
#0 14.39   File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
#0 14.39     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#0 14.39   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
#0 14.39     raise CalledProcessError(retcode, process.args,
#0 14.39 subprocess.CalledProcessError: Command '('uname', '-rs')' returned non-zero exit status 1.
#0 14.40 Traceback (most recent call last):
#0 14.40   File "/usr/local/bin/pip", line 8, in <module>
#0 14.40     sys.exit(main())
#0 14.40   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 70, in main
#0 14.40     return command.main(cmd_args)
#0 14.40   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 101, in main
#0 14.41     return self._main(args)
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
#0 14.41     self.handle_pip_version_check(options)
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 144, in handle_pip_version_check
#0 14.41     session = self._build_session(
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 89, in _build_session
#0 14.41     session = PipSession(
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 282, in __init__
#0 14.41     self.headers["User-Agent"] = user_agent()
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_internal/network/session.py", line 122, in user_agent
#0 14.41     linux_distribution = distro.name(), distro.version(), distro.codename()
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 341, in version
#0 14.41     return _distro.version(pretty, best)
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 861, in version
#0 14.41     self.uname_attr("release"),
#0 14.41   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1052, in uname_attr
#0 14.42     return self._uname_info.get(attribute, "")
#0 14.42   File "/usr/local/lib/python3.9/functools.py", line 993, in __get__
#0 14.42     val = self.func(instance)
#0 14.42   File "/usr/local/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1186, in _uname_info
#0 14.42     stdout = subprocess.check_output(cmd, stderr=devnull)
#0 14.42   File "/usr/local/lib/python3.9/subprocess.py", line 424, in check_output
#0 14.42     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#0 14.42   File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
#0 14.42     raise CalledProcessError(retcode, process.args,
#0 14.43 subprocess.CalledProcessError: Command '('uname', '-rs')' returned non-zero exit status 1.

**Comment by bskinn** [comment]
This is an error in pip, not in paramiko. You'll need to report it on [their issue tracker](https://github.com/pypa/pip/issues).
