### ISSUE TITLE
Channel send buffer not flushed when remote server is closed

### ISSUE THREAD

**Issue by zhaoshan99** [paramiko/paramiko#2208]
Hi,

I was having this issue. It seems none of my work arounds is working.  
Maybe some of you folks can guide or suggest how to fix this.

Thank you,
Jack

 def _check_if_connection_closed_by_remote_host(self, data):
        """
        Will check if a connection is closed by remote host. 
        
        If the remote host is suddenly disconnected, any command will be 
        replied ::
        
            dev01@lnx-dev-03:~$
            Connection to 192.168.1.22 closed by remote host.
            Connection to 192.168.1.22 closed.
            dev01@lnx-dev-02:~$
            
            
        Additional details on this closed by remote host.
            
            Program (running in 192.168.1.20)
                |
                |---> Connect to 192.168.1.21 using paramiko client connect
                    |
                    |---> Send ssh command to 192.168.1.22
        
        
            Then reboot 192.168.1.22 to simulate disconnection. 
            Normally the shell will go back to previous connected host.
            
        
        1.  These are the log traces during a disconnection of a ssh host.
            The numbers are added for references. ::
            
                1   Last login: Mon Mar 13 15:09:14 2023 from 192.168.1.21
                2
                3   dev01@lnx-dev-03:~$
                4   dev01@lnx-dev-03:~$
                5   dev01@lnx-dev-03:~$ 
                6    
                7   2023-03-13 15:49:22.840 [DEBUG] SshSshOps: ssh_to_host();
                8   Connected to 192.168.1.22:22
                9
                10  dev01@lnx-dev-03:~$ pwd         <-- this is sent via Channel.send
                11  /home/dev01
                12  dev01@lnx-dev-03:~$ hostname -I <-- this is sent via Channel.send
                13  192.168.1.22
                14  dev01@lnx-dev-03:~$ 
                15  
                16<--- not part of log; remote host 192.168.1.22 is rebooted here
                17<--- not part of log; a command `hostname -I` is sent to 192.168.1.22
                18
                19  Connection to 192.168.1.22 closed by remote host.
                20  Connection to 192.168.1.22 closed.
                21  dev01@lnx-dev-02:~$ hostname -I
                22  192.168.1.21
                23  dev01@lnx-dev-02:~$
                
        2.  As can be seen in the trace the last failed command sent(line 17) to 
            192.168.1.22 was carried over to the previous connected host 
            at 192.168.1.21(line 21); All successive commands to 192.168.1.21 
            are replied 1 command late.
            
            2023-03-13: As of this writing, there is no way to flush the failed
            sent command in paramiko.Channel  
            
            The related paramiko codes are readable from here
            
            https://valorizacionvtr.cl/restore/usr/share/doc/python-paramiko-1.7.5/docs/paramiko.channel-pysrc.html
            https://github.com/jbouse-debian/paramiko/blob/master/paramiko/transport.py
            https://github.com/jbouse-debian/paramiko/blob/master/paramiko/packet.py
            
        3.  2023-03-13: The following work arounds are not working 
            
            1.  Sending newline via Channel.send('\n')
            
            2.  Sending backspaces to delete the previous failed command via 
                Channel.send('\x08')

**Comment by zhaoshan99** [comment]
Nevermind about this'. i found the correct work around. should send at least two new lines to flush the carried over command;  not an ideal solution but it works.

**Comment by bskinn** [comment]
Yeah, I have to imagine coping with a sudden disconnect is challenging to craft a general solution for.

Closing this since you found a fix -- feel free to reopen if needed.
