### ISSUE TITLE
Issues Installing Paramiko

### ISSUE THREAD

**Issue by marav82** [paramiko/paramiko#222]
Hi! I'm trying to install paramiko in a windows computer and the installation fails with this error:

"unable to find vcvarsall .bat"

Do you have any idea what could be the reason?

Thanks!

**Comment by sanseihappa** [comment]
I found this helpful: http://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/

Essentially, for Python 2.7 you just need setuptools >= 6.0 (should be a given if you're using the latest 2.7.x) and the key item: [Microsoft Visual C++ Compiler for Python 2.7](http://www.microsoft.com/en-us/download/details.aspx?id=44266)

**Comment by bitprophet** [comment]
Thanks to those who provided extra links; also note our own [install page](http://www.paramiko.org/installing.html#pycrypto) has a handful of notes about installing dependencies on Windows (i.e. other avenues besides raw source install).

**Comment by kjin9174** [comment]
How to install paramiko 
error No module named 'paramiko'
How to fix?
