### ISSUE TITLE
executing exec_command() using an invoke_shell() session

### ISSUE THREAD

**Issue by ulrat** [paramiko/paramiko#2228]
I am a beginner using paramiko.I need to ssh to the intermediate server and then ssh to the target server.
I use invoke_shell().After SSH reaches the target server, exec_command() cannot be used to get results.
How should I log in to the server without using a tunnel?
paramiko version 2.9.2

```python
import time

import paramiko

middle_host = middle_host
middle_user = middle_user
middle_password = middle_password
dest_host = dest_host
dest_user = dest_user
dest_password = dest_password

middle_ssh = paramiko.SSHClient()
middle_ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
middle_ssh.connect(middle_host, username=middle_user, password=middle_password, timeout=10, banner_timeout=200,
                   auth_timeout=10, look_for_keys=False)

dest_ssh = middle_ssh.invoke_shell()
dest_ssh.send(f'ssh {dest_user}@{dest_host}\n')
time.sleep(1)

dest_ssh.send(dest_password + '\n')
time.sleep(1)

stdin, stdout, stderr = dest_ssh.exec_command('ls -l')
output = stdout.read()

print(output)

dest_ssh.close()
middle_ssh.close()

``` 
<details><summary>Details</summary>
<p>

Traceback (most recent call last):
  File logi_1.py, line 31, in <module>
    stdin, stdout, stderr = dest_ssh.exec_command('ls -l')
  File channel.py, line 72, in _check
    return func(self, *args, **kwds)
  File channel.py, line 257, in exec_command
    self._wait_for_event()
  File channel.py, line 1226, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.

Process finished with exit code 1

</p>
</details>

**Comment by fhamborg** [comment]
This is the same issue as in https://github.com/paramiko/paramiko/issues/1444

**Comment by bskinn** [comment]
Closing this issue for now. @ulrat, if you still require assistance, please reopen and comment with any updates.
