### ISSUE TITLE
Cisco switch - multiple exec_command fail with EOFError

### ISSUE THREAD

**Issue by bitboy85** [paramiko/paramiko#2230]
I'm using this code. the second run of exec_command always fails.
```
stdin, stdout, stderr = session.exec_command('show cdp neighbors')
output_cdp = stdout.read().decode()
stdin, stdout, stderr = session.exec_command('show mac address-table')
output_mac = stdout.read().decode()
```

Error Output is
```

Traceback (most recent call last):
  File ""c:\python\Test.py", line 154, in <module>
    stdin, stdout, stderr = session.exec_command('show mac address-table')
  File ""c:\python\.venv\lib\site-packages\paramiko\client.py", line 534, in exec_command
    chan = self._transport.open_session(timeout=timeout)
  File ""c:\python\.venv\lib\site-packages\paramiko\transport.py", line 925, in open_session
    return self.open_channel(
  File ""c:\python\.venv\lib\site-packages\paramiko\transport.py", line 1056, in open_channel
    raise e
  File ""c:\python\.venv\lib\site-packages\paramiko\transport.py", line 2109, in run
    ptype, m = self.packetizer.read_message()
  File ""c:\python\.venv\lib\site-packages\paramiko\packet.py", line 453, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File ""c:\python\.venv\lib\site-packages\paramiko\packet.py", line 303, in read_all
    raise EOFError()
EOFError
```

Might be related to https://github.com/paramiko/paramiko/issues/550

**Comment by jun66j5** [comment]
I'm not sure without checking the logs, but it looks like your CISCO switch dropped the SSH connection after running the command. Try connecting to the switch for each command.

Also see: [Paramiko doesn’t work with my Cisco, Windows or other non-Unix system!](https://www.paramiko.org/faq.html#paramiko-doesn-t-work-with-my-cisco-windows-or-other-non-unix-system) in [FAQ](https://www.paramiko.org/faq.html#frequently-asked-answered-questions).

**Comment by bitboy85** [comment]
I enabled debug log, and this is what i got.
Didn't try but i guess login for each command will work but i wouldn't be happy with that solution as there might be a login log enabled which would be flooded this way.

```
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] EOF received (0)
DEBUG:paramiko.transport:[chan 1] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] EOF sent (0)
DEBUG:paramiko.transport:EOF in transport thread
```

Currently i'm using invoke_shell. Its working for multiple commands.
But exec_command seems easier to use and i guess it should work, as long as the executed commands are independant from each other.

**Comment by jun66j5** [comment]
> DEBUG:paramiko.transport:EOF in transport thread

According to the above log, the CISCO switch indeed dropped the SSH connection after the `exec_command`. I don't think it will change the behavior, but try to pass `get_pty=True` to `exec_command`.

I believe this behavior is by design of the SSH implementation on the CISCO switch, regardless of SSH client. I would suggest contacting CISCO support instead of here.

**Comment by jun66j5** [comment]
I'd suggest closing this issue because that is just an issue of cisco switch.

**Comment by bitboy85** [comment]
Yes, seems cisco specific. Checked again, and found another report about his:
https://github.com/paramiko/paramiko/issues/55
