### ISSUE TITLE
Handling and getting huge output when using invoke_shell

### ISSUE THREAD

**Issue by bitboy85** [paramiko/paramiko#2238]
Because exec_command is not working for some cisco devices i go with invoke_shell.

i send a command which produces a huge output and i'm unable to get the complete output.

i currently have two issue
1. paramiko seems to hang during receiving
2. Even if i ignore the hang, i have no idea when the output is fully received.

I printed the buffer ssize too see whta happening using this code
```
shell = session.invoke_shell(width=1000, height=1000)
shell.sendall('show ap summary\r\n')
time.sleep(5)
for x in range(90):
    time.sleep(.1)
    print(len(shell.in_buffer))
    buffer = shell.recv(1024).decode()
    output_cmd += buffer
```

i get this output. I have no idea how to determine how long it takes for the command to complete. The amount of output is obviously different on different devices. Just guessing a wait time seems unreliable to me.
```
7685 <- initial size after sendall
6661
5637
4613
3589
2565
1541
517
0 <- seems empty, nothing more to come?
21780 <- after few seconds(!), buffer is filled again
20756
19732
18708
17684
16660
15636
14612
13588
12564
11540
10516
9492
8468
7444
6420
5396
4372
3348
2324
1300
276
0  <- Hang again
21780 <- fill again after few seconds
20756
19732
18708
17684
16660
15636
14612
13588
12564
11540
10516
9492
8468
7444
6420
5396
4372
3348
2324
1300
276
0
21417
20393
19369
18345
17321
16297
15273
14249
13225
12201
11177
10153
9129
8105
7081
6057
5033
4009
2985
1961
937
0
21780
20756
19732
18708
17684
16660
15636
14612
13588
12564
11540
10516
9492
```

**Comment by jun66j5** [comment]
It should check whether data is arrived using `.recv_ready()` before calling `.recv()`.

```python
output_cmd = bytearray()
exit_status = None
shell = session.invoke_shell(width=1000, height=1000)
shell.set_combine_stderr(True)
shell.sendall('show ap summary\r\n')
while True:
    if shell.recv_ready():
        chunk = shell.recv(1024)
        output_cmd.extend(chunk)
        continue
    if shell.exit_status_ready():
        exit_status = shell.recv_exit_status()
        break
    if shell.closed or shell.eof_received or not shell.active:
        break
    time.sleep(.1)
```

**Comment by bitboy85** [comment]
Thx for providing an example code. Sadly it doesn't work. The loop never ends, no break condition is met.
I tried also some variations of
```python
if len(chunk) == 0:
break
```

But also no luck. Loop runs forever.
The output is about 140 kb and using putty its printed in 1 or 2 seconds.

Next, i added a timeout to break the loop.
With setting a timeout of 2 minutes(!) the output is complete (lower values leads to incomplete output). Again, i have to "guess" how long the execution will take to complete and obviously, there is something wonky going on if it takes minutes instead of seconds.

```python
shell = session.invoke_shell(width=1000, height=1000)
shell.sendall('config paging disable\r\n')
time.sleep(.5)
buffer = shell.recv(len(shell.in_buffer)) # clear buffer
buffer = 0
exit_status = None
shell.set_combine_stderr(True)
shell.sendall('show ap summary\r\n')
timeout = time.time() + 120 # 2 Minutes
while True:
    if shell.recv_ready():
        chunk = shell.recv(1024)
        #output_cmd.extend(chunk)
        output_cmd += chunk.decode()
        continue
    if shell.exit_status_ready():
        exit_status = shell.recv_exit_status()
        break
    if shell.closed or shell.eof_received or not shell.active:
        break
    if "--More-- or (q)uit" in output_cmd:
        print("Pagination enabled. Exiting")
        break
    if time.time() > timeout:
        break
    time.sleep(.1)
print(output_cmd)
```

**Comment by jun66j5** [comment]
> With setting a timeout of 2 minutes(!) the output is complete (lower values leads to incomplete output). Again, i have to "guess" how long the execution will take to complete and obviously, there is something wonky going on if it takes minutes instead of seconds.

If your remote host is a CISCO device and `config prompt` is supported, I think you could detect termination of the command using configured prompt like the following: 

```python
def run_command(shell, command, prompt=':::PROMPT:::', timeout=120):
    prompt = prompt.encode('utf-8')
    shell.sendall(command + '\r\n')
    out = bytearray()
    startts = time.time()
    while time.time() - startts < timeout:
        if shell.recv_ready():
            chunk = shell.recv(1024)
            if not chunk:
                break
            out.extend(chunk)
            if prompt in out:
                break
        if shell.exit_status_ready():
            exit_status = shell.recv_exit_status()
            break
        if shell.closed or shell.eof_received or not shell.active:
            break
    pos = out.index(prompt)
    return out[:pos].decode('utf-8')

shell = session.invoke_shell(width=1000, height=1000)
shell.set_combine_stderr(True)
shell.sendall('config prompt ":::PROMPT:::"\r\n')
while shell.recv_ready():
    shell.recv(1024)
print(run_command(shell, 'config paging disable'))
print(run_command(shell, 'show ap summary'))
```

**Comment by bitboy85** [comment]
Wow great idea to set and use the prompt as exit condition!
I just needed to put in a time.sleep(.5) after sendall(command + '\r\n') otherwise the chunk could be empty, and the loop exits

```python
def run_command(shell, command, prompt=':::PROMPT:::', timeout=120):
    prompt = prompt.encode('utf-8')
    shell.sendall(command + '\r\n')
    time.sleep(.5)
    out = bytearray()
```

Note for anyone else working with cisco devices:
"config paging disable" is temporary, and also bound to the paramiko session. No other user will be affected
"config prompt" is a permanent change, so ether make sure changing it will not break something else, or get the current prompt with sending an empty command first.
quick and dirty:
```python
def getPromptString(shell):
    chunk = bytearray()
    chunk = shell.recv(65535) # Clear buffer
    shell.sendall('\r\n')
    time.sleep(0.5)
    chunk = shell.recv(1024)
    out = chunk.decode('utf-8')
    return out.strip()
```

Still think, that 2 minutes is way to long.

**Comment by bitboy85** [comment]
Performance update:

in common.py of paramiko lib i changed
```python
DEFAULT_WINDOW_SIZE = 64 * 2**15`
```
to
```python
DEFAULT_WINDOW_SIZE = 2**15`
```

The default takes ~ 80-90 seconds to run,
the modified takes ~ 12 seconds to run

With those
```python
DEFAULT_WINDOW_SIZE = 4 * 2**15
```

I got a runtime about ~ 2 seconds which is the expected result.
Sadly, i wasn't able to override those values within my script, it needs to be done in common.py.

**Comment by jun66j5** [comment]
You could use `transport_factory` parameter of `SSHClient.connect()` with paramiko 2.12+ like the following:

```python
def transport_factory(*args, **kwargs):
    kwargs.setdefault('default_window_size', 4 * 2**15)
    return paramiko.Transport(*args, **kwargs)

session = paramiko.SSHClient()
session.set_missing_host_key_policy(paramiko.AutoAddPolicy)
session.connect(hostname, ..., transport_factory=transport_factory)
```

**Comment by bitboy85** [comment]
Perfect. Many thanks this works.

**Comment by network-shark** [comment]
I can't reproduce this . I updated to latest netmiko and paramiko settings and changed the settings in the common.py file. 
my script is getting slower . 

default settings 

values in seconds 

39.779 
39.786 
39.986 

4 * 2**15
46.601  
46.400 
47.098
 
 2**15
54.077 
53.427
53.311
