### ISSUE TITLE
Paramiko server signed client key verification 

### ISSUE THREAD

**Issue by HajoRed** [paramiko/paramiko#2248]
Hey there,

I am currently trying to write a server with Paramiko that executes commands. I am successful so far, but I am currently stuck at the client public key verification step in the check_auth_publickey method.

As multiple users and servers are involved registering the public keys of every user explicitly on every server is error prone and cumbersome, a central certificate authority is used. A user verifies their identity against the central certificate authority and in return get their public key signed as a ssh-rsa-cert-v01@openssh.com certificate.
On server side only the public key of the certificate authority is stored and access should be granted to every user that has a key signed by the certificate authority.

Now in the check_auth_publickey method the key parameter only seems to contain the public key information of the user, but not the other parts of the certificate like the public key of the certificate authority or principals.
As the public key of the user is not relevant/useful in this scenario, is there a way to get the certificate information and do the verification based on that information?

**Comment by bskinn** [comment]
Do I understand correctly that you're trying to set this up so that users can log into this server using what amounts to a _server_ certificate? Because AFAIK normal user public keys don't carry signing information.

If so, this seems like a pretty non-standard use-case for any auth system ... do I have it right, @HajoRed?

**Comment by HajoRed** [comment]
This is basically only a question if Paramiko already supports this use case and if yes an initial hint how to do certificate based authentication on a Paramiko server side would be helpful.
But even if not, this is not necessarily a feature request from my side as I am currently evaluating a couple of other libraries as well. But feel free to keep it as a backlog item then

**Comment by jun66j5** [comment]
If I understand correctly, paramiko has no supports to authenticate publickey with signed key server-side.

If a client tries publickey authentication with signed key, certificate data is attached in `public_blob` attribute of `key` parameter of `check_auth_publickey` method. However, paramiko doesn't have utility method to verify the certificate and read attributes (e.g. `principal`, `valid_after`, ...) from the certificate.

```diff
     def check_auth_publickey(self, username, key):
         print("Auth attempt with key: " + u(hexlify(key.get_fingerprint())))
+        if key.public_blob:
+            print("Public blob: {}".format(key.public_blob.key_type))
         if (username == "robey") and (key == self.good_pub_key):
             return paramiko.AUTH_SUCCESSFUL
         return paramiko.AUTH_FAILED
```

```console
$ ~/venv/paramiko-dev/bin/python demo_server.py
Read key: 60733844cb5186657fdedaa22b5a57d5
Listening for connection ...
Got a connection!
Auth attempt with key: 60733844cb5186657fdedaa22b5a57d5
Public blob: ssh-rsa-cert-v01@openssh.com
```

**Comment by HajoRed** [comment]
Thanks for the heads-up. I will try to get the public blob parsed as a cryptography SSHCertificate then.
From my view the ticket can be closed.

**Comment by jun66j5** [comment]
Thanks for the information to load the public blob.

* [cryptography.hazmat.primitives.serialization.load_ssh_public_identity](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_ssh_public_identity
)

```diff
     def check_auth_publickey(self, username, key):
         print("Auth attempt with key: " + u(hexlify(key.get_fingerprint())))
+        if key.public_blob:
+            from cryptography.hazmat.primitives.serialization import load_ssh_public_identity
+            cert = load_ssh_public_identity(
+                key.public_blob.key_type.encode('ascii') + b' ' +
+                base64.b64encode(key.public_blob.key_blob)
+            )
+            print(f"  serial:\t{cert.serial!r}")
+            print(f"  type:\t{cert.type!r}")
+            print(f"  key_id:\t{cert.key_id!r}")
+            print(f"  valid_principals:\t{cert.valid_principals!r}")
+            print(f"  valid_after:\t{cert.valid_after!r}")
+            print(f"  valid_before:\t{cert.valid_before!r}")
+            print(f"  critical_options:\t{cert.critical_options!r}")
+            print(f"  extensions:\t{cert.extensions!r}")
+            # XXX Check cert.signature_key() == public key of CA certificate
+            try:
+                cert.verify_cert_signature()
+            except:
+                print('  Verify cert signature FAIL')
+                return paramiko.AUTH_FAILED
+            else:
+                print('  Verify cert signature OK')
+        else:
+            print("  Public blob: n/a")
         if (username == "robey") and (key == self.good_pub_key):
             return paramiko.AUTH_SUCCESSFUL
         return paramiko.AUTH_FAILED
```

```console
$ ~/venv/paramiko-dev/bin/python demo_server.py
Read key: 60733844cb5186657fdedaa22b5a57d5
Listening for connection ...
Got a connection!
Auth attempt with key: d7d4311d66726bb2af2bf8c6f1f62712
  Public blob: n/a
Auth attempt with key: d7d4311d66726bb2af2bf8c6f1f62712
  serial:       0
  type: <SSHCertificateType.USER: 1>
  key_id:       b'client'
  valid_principals:     [b'user1', b'user2']
  valid_after:  0
  valid_before: 18446744073709551615
  critical_options:     {}
  extensions:   {b'permit-X11-forwarding': b'', b'permit-agent-forwarding': b'', b'permit-port-forwarding': b'', b'permit-pty': b'', b'permit-user-rc': b''}
  Verify cert signature OK
```

**Comment by jun66j5** [comment]
I noticed we could use [cryptography.hazmat.primitives.serialization.load_ssh_public_key](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_ssh_public_key) to check the signing key.

```diff
diff --git a/demos/demo_server.py b/demos/demo_server.py
index 6cb2dc51e..f5af008fe 100644
--- a/demos/demo_server.py
+++ b/demos/demo_server.py
@@ -27,7 +27,19 @@ import threading
 import traceback

 import paramiko
-from paramiko.py3compat import b, u, decodebytes
+u = lambda v: v.decode('utf-8') if isinstance(v, bytes) else v
+decodebytes = base64.b64decode
+
+
+from pathlib import Path
+from cryptography.hazmat.primitives.serialization import (
+    SSHCertificateType, load_ssh_public_identity, load_ssh_public_key,
+)
+_trusted_user_ca_keys = [
+    load_ssh_public_key(Path(p).read_bytes()) for p in (
+        '/path/to/user-ca.pub',
+    )
+]


 # setup logging
@@ -65,6 +77,33 @@ class Server(paramiko.ServerInterface):

     def check_auth_publickey(self, username, key):
         print("Auth attempt with key: " + u(hexlify(key.get_fingerprint())))
+        if key.public_blob:
+            cert = load_ssh_public_identity(
+                key.public_blob.key_type.encode('ascii') + b' ' +
+                base64.b64encode(key.public_blob.key_blob)
+            )
+            if cert.signature_key() not in _trusted_user_ca_keys:
+                print('  Signing key is not listed in trusted user ca keys')
+                return paramiko.AUTH_FAILED
+            print('  Signing key is listed in trusted user ca keys')
+            try:
+                cert.verify_cert_signature()
+            except:
+                print('  Verify cert FAIL')
+                return paramiko.AUTH_FAILED
+            print('  Verify cert OK')
+            print(f"  serial:\t{cert.serial!r}")
+            print(f"  type:\t{cert.type!r}")
+            print(f"  key_id:\t{cert.key_id!r}")
+            print(f"  valid_principals:\t{cert.valid_principals!r}")
+            print(f"  valid_after:\t{cert.valid_after!r}")
+            print(f"  valid_before:\t{cert.valid_before!r}")
+            print(f"  critical_options:\t{cert.critical_options!r}")
+            print(f"  extensions:\t{cert.extensions!r}")
+            if cert.type != SSHCertificateType.USER:
+                print('  Cert type must be for a user')
+                return paramiko.AUTH_FAILED
+            # XXX Check valid_principals, valid_after, valid_before
         if (username == "robey") and (key == self.good_pub_key):
             return paramiko.AUTH_SUCCESSFUL
         return paramiko.AUTH_FAILED
```

**Comment by bskinn** [comment]
Thanks for all the work here, @jun66j5!

@HajoRed, I'll go ahead and close, but feel free to continue the discussion on the closed ticket if it's helpful.
