### ISSUE TITLE
cannot get the correct stdout after calling exec_command function

### ISSUE THREAD

**Issue by lijingyi2002** [paramiko/paramiko#2256]
I added the follow code to exec some shell commands. 
However, I found out **the stdout had no context** . but **the stderr have the context I wanted to use.**

class ssh_session():
    client = 0
    def __init__(self) -> None:
        self.client = paramiko.SSHClient()
        self.client.set_missing_host_key_policy(paramiko.AutoAddPolicy()) 
        self.client.connect('10.1.0.79', 22, 'root', 'test')
        pass
    def __del__(self):
        self.client.close()

def testcase_complicated(name, command, result_judgment, recovery = None):
    my_ssh = ssh_session()
    output = []
    for i in range(len(command)):
        print("[XXXXX]start i=", i, command[i])
        stdin, stdout, stderr = my_ssh.client.exec_command(command[i])
        errstr = stderr.read()
        if ( errstr.decode('ascii') != "" ):
            log_print("test", name, "meets some error:", errstr.decode('ascii'))
            break
        outstr = stdout.read()
        strtmp = outstr.decode('ascii')
        print(strtmp)

**the terminal has the following output:**

[XXXXX]start i= 0 **time systemctl stop test-process**
test refresh_003_stop_service  meets some error: 
real    0m0.028s
user    0m0.006s
sys     0m0.009s

**the environment has showed below:**
user@rxd0021u:~/code/hpc_linux_testcase$ pip3 show paramiko
Name: paramiko
Version: 3.2.0
Summary: SSH2 protocol library
Home-page: https://paramiko.org
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /home/user/.local/lib/python3.6/site-packages
Requires: bcrypt, cryptography, pynacl
Required-by: 

python version is 3.6.9, using Ubuntu18.04

**Comment by lijingyi2002** [comment]
time systemctl stop test-process is the command I try to get the result context. But I cannot get them from the stdout.

**Comment by lijingyi2002** [comment]
I upgrade the python into python3.8. This issue was still here.

**Comment by jun66j5** [comment]
Please post scripts and logs using <code>\`\`\`</code> (triple backticks).

See https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code.

**Comment by lijingyi2002** [comment]
> This is not a paramiko issue.
> 
> Both your script and the given command are wrong. `time` command writes timing stats of the given command to **_stderr_**. See https://man7.org/linux/man-pages/man1/time.1.html.

Hi jun , sorry to raise this issue  before comfirmming the man page. I didn't mention this information. I will close this issue. And thank you very much for your repley.
