### ISSUE TITLE
How to get ChannelExceptions that paramiko captures?

### ISSUE THREAD

**Issue by Obliman** [paramiko/paramiko#2264]
The simplest way that I know of to test whether a connection has been made is to detect the exception when it fails. Currently that exception seems to be captured by paramiko in a way that I don't know how to access/detect (other than seeing it in the logs).

Ex:
I have port forwarding setup through sshtunnel, using paramiko.
I then try to create a connection via asyncio:
`self.reader, self.writer = await asyncio.open_connection(self.host, self.port)`
which would normally raise a `ConnectionRefusedError`, or something else that I could catch to tell me if it has failed.

log message example: 
`[Could not establish connection from local (---) to remote (---) side of the tunnel] open new channel ssh error: ChannelException(2, 'Connect failed')
`

How do I detect this exception? Is there a handler that I should replace?

**Comment by jun66j5** [comment]
Please provide your script. None can help without providing your script. Also, paramiko is not currently friendly with `async` because paramiko uses threads (`Transport` class is a subclass of `Thread`, see #389 and https://github.com/paramiko/paramiko/issues?q=is%3Aissue+asyncio).

**Comment by Obliman** [comment]
> paramiko is not currently friendly with `async` because paramiko uses threads

Fortunately this is not an issue, since the tunnel is intentionally run in a separate thread, which then exposes a port that anything on my computer could connect to. This means that there is no conflict when I use code running asyncio to connect.

The problem is not specific to my setup. It is a core paramiko question: how do I "see" error messages in the code? In this case the tunnel will attempt to create a new "channel" when a socket connects. If the channel creation fails, then I want to be able to detect the paramiko `ChannelException`, but right now paramiko buries that error in some kind of handler.

I can't use `try/except` because it has already been caught. Paramiko must have a way to check whether errors have happened, right?

**Comment by jun66j5** [comment]
> How do I detect this exception?

No way.

**Comment by Obliman** [comment]
I have found an alternative for my use-case. Instead of changing the error handlers, sshtunnel has a method for generating a test socket connection for each tunnel, which can be used like so:
```
tunnel = SSHTunnelForwarder(...)
tunnel.start()
tunnel.check_tunnels() # Attempt to create a socket connection on each tunnel
# Retrieve the dictionary of boolean statuses: {(host, port): connected, ...}
for k, v in tunnel.tunnel_is_up.items():
    print(f"Tunnel {k} connected?: {v}")
```
This captures the connection error when it occurs, then stores the boolean pass/fail in a dictionary that can be easily read.

The checking process is slow by default due to the default TUNNEL_TIMEOUT of 10 seconds, but can be changed like so:
```
import sshtunnel

sshtunnel.TUNNEL_TIMEOUT = 1
```

**Comment by Obliman** [comment]
I'm assuming the issue was really sshtunnel capturing the error since it can perform the socket connection testing, so I'll close this issue.

**Comment by bskinn** [comment]
Thanks for all the work digging into this, glad you found a solution that will work for you!
