### ISSUE TITLE
Cannot install paramiko 3.2.0 precompiled whl on a windows 10 with python 3.11

### ISSUE THREAD

**Issue by neoclust** [paramiko/paramiko#2272]
setuptools 68.0.0 is installed.

What i don't understand is: ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)

c:\Program Files\Pulse\tmp>"C:\Program Files\Python311\Scripts\pip3" install --quiet --upgrade --no-index --find-links="C:\Program Files\Pulse\tmp" paramiko-3.2.0-py3-none-any.whl
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Looking in links: c:\Program Files\Pulse\tmp
      Processing c:\program files\pulse\tmp\setuptools-68.0.0-py3-none-any.whl
      ERROR: Could not find a version that satisfies the requirement wheel (from versions: none)
      ERROR: No matching distribution found for wheel
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by neoclust** [comment]
my fault, i was missing a deps.

**Comment by bskinn** [comment]
No worries, glad you figured it out!
