### ISSUE TITLE
[SUPPORT] - <wireshark 4.0.7 support to decrypt SSH, how to get the key log file with extra debug>

### ISSUE THREAD

**Issue by gnlsw** [paramiko/paramiko#2273]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.2.0

### What version(s) of Python are you using?

3.8.8

### What operating system and version are you using?

Windows 7

### If you're connecting as a client, which SSH server are you connecting to?

CentOS 7.2009

### What are you trying to do with paramiko?

using paramiko to get cipher key and mac key, analysis SSH

### How are you trying to do it, and what's happening instead?

using paramiko to get cipher key and mac key, analysis SSH

**Comment by gnlsw** [comment]
Here is the wireshark key log file description：
    /* File format: each line follows the format "<cookie> <key>".
     * <cookie> is the hex-encoded (client or server) 16 bytes cookie
     * (32 characters) found in the SSH_MSG_KEXINIT of the endpoint whose
     * private random is disclosed.
     * <key> is the private random number that is used to generate the DH
     * negotiation (length depends on algorithm). In RFC4253 it is called
     * x for the client and y for the server.
     * For openssh and DH group exchange, it can be retrieved using
     * DH_get0_key(kex->dh, NULL, &server_random)
     * for groupN in file kexdh.c function kex_dh_compute_key
     * for custom group in file kexgexs.c function input_kex_dh_gex_init
     * For openssh and curve25519, it can be found in function kex_c25519_enc
     * in variable server_key.
     *
     * Example:
     *  90d886612f9c35903db5bb30d11f23c2 DEF830C22F6C927E31972FFB20B46C96D0A5F2D5E7BE5A3A8804D6BFC431619ED10AF589EEDFF4750DEA00EFD7AFDB814B6F3528729692B1F2482041521AE9DC
     */

**Comment by jun66j5** [comment]
Use `paramiko.util.log_to_file()` and `Transport.set_hexdump(True)` to search kex init and reply.

**Comment by gnlsw** [comment]
> Use `paramiko.util.log_to_file()` and `Transport.set_hexdump(True)` to search kex init and reply.
Transport.set_hexdump(True) can get the plain message，but can not find the key and cookie. can you give an example for the wireshark parameter <key>  <cookie>?

File format: each line follows the format "<cookie> <key>".
<cookie> is the hex-encoded (client or server) 16 bytes cookie
(32 characters) found in the SSH_MSG_KEXINIT of the endpoint whose
private random is disclosed.
<key> is the private random number that is used to generate the DH
negotiation (length depends on algorithm). In RFC4253 it is called
x for the client and y for the server.
For openssh and DH group exchange, it can be retrieved using
DH_get0_key(kex->dh, NULL, &server_random)
for groupN in file kexdh.c function kex_dh_compute_key
for custom group in file kexgexs.c function input_kex_dh_gex_init
For openssh and curve25519, it can be found in function kex_c25519_enc
in variable server_key.

Example:
 90d886612f9c35903db5bb30d11f23c2 DEF830C22F6C927E31972FFB20B46C96D0A5F2D5E7BE5A3A8804D6BFC431619ED10AF589EEDFF4750DEA00EFD7AFDB814B6F3528729692B1F2482041521AE9DC

**Comment by gnlsw** [comment]
> Use `paramiko.util.log_to_file()` and `Transport.set_hexdump(True)` to search kex init and reply.

Transport.set_hexdump(True) can get the plain message，but can not find the key and cookie. can you give an example for the wireshark parameter ?

File format: each line follows the format cookie key.
cookie is the hex-encoded (client or server) 16 bytes cookie
(32 characters) found in the SSH_MSG_KEXINIT of the endpoint whose
private random is disclosed.
key is the private random number that is used to generate the DH
negotiation (length depends on algorithm). In RFC4253 it is called
x for the client and y for the server.
For openssh and DH group exchange, it can be retrieved using
DH_get0_key(kex->dh, NULL, &server_random)
for groupN in file kexdh.c function kex_dh_compute_key
for custom group in file kexgexs.c function input_kex_dh_gex_init
For openssh and curve25519, it can be found in function kex_c25519_enc
in variable server_key.

Example:
 90d886612f9c35903db5bb30d11f23c2 DEF830C22F6C927E31972FFB20B46C96D0A5F2D5E7BE5A3A8804D6BFC431619ED10AF589EEDFF4750DEA00EFD7AFDB814B6F3528729692B1F2482041521AE9DC

**Comment by gnlsw** [comment]
> Use `paramiko.util.log_to_file()` and `Transport.set_hexdump(True)` to search kex init and reply.

Transport.set_hexdump(True) can get the plain message，but can not find the key and cookie. can you give an example for the wireshark parameter ?

File format: each line follows the format **cookie key**.
**cookie** is the hex-encoded (client or server) 16 bytes cookie
(32 characters) found in the SSH_MSG_KEXINIT of the endpoint whose
private random is disclosed.
**key** is the private random number that is used to generate the DH
negotiation (length depends on algorithm). In RFC4253 it is called
x for the client and y for the server.
For openssh and DH group exchange, it can be retrieved using
DH_get0_key(kex->dh, NULL, &server_random)
for groupN in file kexdh.c function kex_dh_compute_key
for custom group in file kexgexs.c function input_kex_dh_gex_init
For openssh and curve25519, it can be found in function kex_c25519_enc
in variable server_key.

Example:
 90d886612f9c35903db5bb30d11f23c2 DEF830C22F6C927E31972FFB20B46C96D0A5F2D5E7BE5A3A8804D6BFC431619ED10AF589EEDFF4750DEA00EFD7AFDB814B6F3528729692B1F2482041521AE9DC

**Comment by jun66j5** [comment]
The cookie and key could be found by referring to the following. Then, you convert the cookie and key to the format Wireshark expects.

### Cookie

The cookie is first 16 bytes in `MSG_KEXINIT` packet.

* https://github.com/paramiko/paramiko/blob/3.2.0/paramiko/transport.py#L2374
* https://datatracker.ietf.org/doc/html/rfc4253#section-7.1

### Key

The key is sent from `start_kex()` method.

* https://github.com/paramiko/paramiko/blob/3.2.0/paramiko/kex_group1.py#L67
* https://github.com/paramiko/paramiko/blob/3.2.0/paramiko/kex_ecdh_nist.py#L40-L45
* https://github.com/paramiko/paramiko/blob/3.2.0/paramiko/kex_curve25519.py#L52-L56

**Comment by gnlsw** [comment]
The  cookie is right.

The Key is the private key, not the public key.

Wireshark need to modify function ssh_kex_hash_type() in packet-ssh.c. Because the kex may be curve25519-sha256@libssh.org not curve25519-sha256, which result to can not decrypt.

**Comment by gnlsw** [comment]
closed

**Comment by bskinn** [comment]
> The cookie is right.
> 
> The Key is the private key, not the public key.
> 
> Wireshark need to modify function ssh_kex_hash_type() in packet-ssh.c. Because the kex may be [curve25519-sha256@libssh.org](mailto:curve25519-sha256@libssh.org) not curve25519-sha256, which result to can not decrypt.

I'm not sure what you're trying to tell us with this, @gnlsw.  Have you found the problem? Is it with Wireshark? Have you identified something specific that you need to be able to do with paramiko, that you don't know how to yet?
