### ISSUE TITLE
[SUPPORT] - Can't compile paramiko installed with toolchain in Xcode 

### ISSUE THREAD

**Issue by JanBartos6** [paramiko/paramiko#2281]
### Are you using paramiko as a client or server?

Both

### What feature(s) aren't working right?

Something else

### What version(s) of paramiko are you using?

3.3.1

### What version(s) of Python are you using?

3.9.6

### What operating system and version are you using?

MacOS Ventura 13.5

### What are you trying to do with paramiko?

I have made a Kivy app where I use paramiko and I want to build the app for iOS. 

### How are you trying to do it, and what's happening instead?

When I built kivy with toolchain and installed paramiko with "toolchain pip install paramiko", I got this [error log ](https://gist.github.com/JanBartos6/d9587c0d1e178e6bcceb204b361630ae) which is caused by paramiko. It has something to do with Xcode and the toolchain because when I install the exact same version of paramiko with pip and try to run the app in VS Code, everything works normally.

### Anything else?

I'm using an M1 mac

**Comment by bskinn** [comment]
It looks like you're missing (at least) the Rust build toolchain needed to build cryptography (at least) from source, to satisfy kivy's needs.

It's likely working in the non-kivy context because a wheel is available for your system.

**Comment by jun66j5** [comment]
This is not a paramiko issue, at least, is an issue of kivy and/or cryptography. Also, the same issue has been reported at https://github.com/kivy/kivy-ios/issues/733. I'd suggest closing this issue.

**Comment by bskinn** [comment]
Agreed, closing as not a paramiko problem.
