### ISSUE TITLE
[SUPPORT] - Dumbass here: How do I use `from_type_string()`? I'm going insane.

### ISSUE THREAD

**Issue by hyler** [paramiko/paramiko#2283]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

Keys/auth

### What version(s) of paramiko are you using?

3.3.1

### What version(s) of Python are you using?

3.10.12

### What operating system and version are you using?

macOS Ventura

### If you're connecting as a client, which SSH server are you connecting to?

OpenSSH 8.2p1

### What are you trying to do with paramiko?

Use a private key from a string, _not_ from a file.

### How are you trying to do it, and what's happening instead?

Okay, I'm sorry I'm so stupid. But I'd appreciate any help.

Suppose I have a private key (which I do). This key starts with `BEGIN OPENSSH PRIVATE KEY`, etc. This key works. Here is how it works:

```python
import io
import paramiko

key = '-----BEGIN OPENSSH PRIVATE KEY-----\n ...'  # \n where the key would break in the keyfile
pkey = paramiko.RSAKey.from_private_key(io.StringIO(key))
transport = ...
```

and so on. It **works**, I can get an SFTP client and list the remote contents.

But I am tricking **paramiko** into reading the key as if it was in a keyfile. For the life of me, I _cannot_ manage to accomplish the above by using `RSAKey.from_type_string('ssh-rsa', key)`. I've tried all sorts of permutations:

* `key.encode()` - invalid RSA key
* `key.encode().hex()` - error about it being a string
* `key.encode().hex().encode()` - invalid RSA key

I've tried the above with the key being one big string. I tried it with the key having `\n` where it would naturally break in the keyfile. I've tried all of the above with all the possible versions of `key_type` ('ssh-rsa', 'rsa-sha2-256', etc.).

Can someone _please_ tell me if what I want to do is even possible. Have I misunderstood the method `from_type_string` altogether? Is the _only_ way to use a key from a string with `StringIO` or similar trickery?

Thank you for the help.

**Comment by bskinn** [comment]
Not an expert in this, but I see two things that make me go "hmmm".

First, the `PKey` class is by default aimed at public keys, not private keys ([code][pkey doc]):

```
"""
Common API for all public keys.
"""
```

And, in the definition there of `from_type_string()`, it indicates that the `bytes` 2nd argument is "`public bytes`" ([code][public bytes]):

```
"""
Given type `str` & raw `bytes`, return a `PKey` subclass instance.

For example, ``PKey.from_type_string("ssh-ed25519", <public bytes>)``
will (if successful) return a new `.Ed25519Key`.

...

"""

```

So -- my best guess is that `from_type_string()` is meant to consume public key data, whereas `from_private_key()` is meant to consume private key data.

This would suggest that `key.encode()` is the right way to get the key data into the correct `bytes` format; but, since you're passing it a private instead of a public key, it's complaining (accurately) that it's an invalid public key.

[pkey doc]: https://github.com/paramiko/paramiko/blob/fd068633004b2635ffd71e3ad881455e053ae1d8/paramiko/pkey.py#L20
[public bytes]: https://github.com/paramiko/paramiko/blob/fd068633004b2635ffd71e3ad881455e053ae1d8/paramiko/pkey.py#L192C39-L192C39

**Comment by hyler** [comment]
Okay, so first of all it sounds like I'm getting all mixed up about _what_ it is that I'm trying to do and _how_ to go about it. (The "what" is to connect to an SFTP server with a key that's a string.)

My confusion aside, it doesn't work with a public key either.

```python
key = 'ssh-rsa AAAAB3NzaC1yc2 ... Pw== <username>@<hostname>'
paramiko.RSAKey.from_type_string('ssh-rsa', key.encode())
```

This results in:

```python
paramiko.ssh_exception.SSHException: Invalid key (class: RSAKey, data type: rsa AAA
```

As an aside, what is `from_type_string()` intended for? For when I do a pubkey auth (like I'd do with SSH/SFTP, etc. and I have put my public key on the host) or for something else?

**Comment by bskinn** [comment]
> The "what" is to connect to an SFTP server with a key that's a string.

Ok - so here, the SFTP server should have a copy of your public key on file, and I would assume you're needing to provide paramiko with the matching private key. All seems in order there.

> My confusion aside, it doesn't work with a public key either.

&lt;helpless shrug&gt; Welp, that surpasses my level of knowledge, then!

> As an aside, what is `from_type_string()` intended for?

If I had to _guess_, it would be for when you're using paramiko from the server side? But I don't really know.

@jun66j5, can you shed any light here?

**Comment by jun66j5** [comment]
> ```python
> key = 'ssh-rsa AAAAB3NzaC1yc2 ... Pw== <username>@<hostname>'
> paramiko.RSAKey.from_type_string('ssh-rsa', key.encode())
> ```

Incorrect. Try to decode 2nd field as base64-string and pass the decoded data to the method.

```
$ curl -s https://github.com/jun66j5.keys
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH7RmQW7JajZ/0s+XPUlDbemmbRQUht/7lWB2fX7XRfw

$ ~/venv/paramiko-dev/bin/python
Python 3.11.4 (main, Jun  7 2023, 12:45:49) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import base64, paramiko
>>> content = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH7RmQW7JajZ/0s+XPUlDbemmbRQUht/7lWB2fX7XRfw\n'
>>> fields = content.split()
>>> type_ = fields[0]
>>> data = base64.b64decode(fields[1])
>>> paramiko.PKey.from_type_string(type_, data)
PKey(alg=ED25519, bits=256, fp=SHA256:BCpfZxJ2r9LMKkqOFvhwF6+9R05MtSan9mD/UQeuIEg)
>>>
```

> As an aside, what is `from_type_string()` intended for? For when I do a pubkey auth (like I'd do with SSH/SFTP, etc. and I have put my public key on the host) or for something else?

`PKey.from_type_string` is not needed to do publickey authentication. The method is for internal uses. In publickey authentication, public key is needed for server and private key is needed for client. Instead, use `RSAKey.from_private_key` or `RSAKey.from_private_key_file`.

refs:

> In addition, [PKey.from_type_string](https://docs.paramiko.org/en/latest/api/keys.html#paramiko.pkey.PKey.from_type_string) now exists, and is being used in some internals to load ssh-agent keys.

See https://www.paramiko.org/changelog.html#3.2.0

**Comment by hyler** [comment]
> PKey.from_type_string is not needed to do publickey authentication. The method is for internal uses. In publickey authentication, public key is needed for server and private key is needed for client. Instead, use RSAKey.from_private_key or RSAKey.from_private_key_file.

Ooof. Thank you. I guess I skimmed over that part of the changelog (I _did_ read it) and jumped to my own wishful conclusions.

I appreciate the attention this post got, and I'm sorry for the trouble.

**Comment by jun66j5** [comment]
> Sorry, for re-opening this. I'm trying to do the same for an ECDSA key. From a string in this format private_key_pem = """-----BEGIN EC PRIVATE KEY----- .... -----END EC PRIVATE KEY-----"""
> 
> I tried the base64 encode decode, also tried bytes(private_key_pem, ...) with different types of encodings utf-8, ascii, latin-1 type = 'ecdsa-sha2-nistp256' paramiko.PKey.from_type_string(type, strbytes)

Incorrect. `PKey.from_type_string` expects public key bytes in the 2nd argument, not private key bytes.

> I did manage to do in another way where private_key_pem is a raw string and using from_private_key(io.StringIO(..)) but I still would like to understand why I'm failing with from_type_str.

Try to use `ECDSAKey.from_private_key_file` to load ecdsa private key like the following:

```
$ ssh-keygen -t ecdsa -f /tmp/id_ecdsa.key
Generating public/private ecdsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /tmp/id_ecdsa.key
Your public key has been saved in /tmp/id_ecdsa.key.pub
The key fingerprint is:
SHA256:TlOMLcgd1Zow39kDi3sp4bfRUass951FrSt/DDcFbr4 jun66j5@localhost
The key's randomart image is:
+---[ECDSA 256]---+
|        ....     |
|     . oo=  o . .|
|      o +++= * oo|
|         o* + *.+|
|        S. o.=.=.|
|       o .+.=+=.o|
|        .  +oo.*=|
|            o Eo+|
|             o.. |
+----[SHA256]-----+
$ ~/venv/paramiko-dev/bin/python
Python 3.11.13 (main, Jun  4 2025, 08:57:29) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> key = paramiko.ECDSAKey.from_private_key_file('/tmp/id_ecdsa.key')
>>> key
PKey(alg=ECDSA, bits=256, fp=SHA256:TlOMLcgd1Zow39kDi3sp4bfRUass951FrSt/DDcFbr4)
```
