### ISSUE TITLE
[BUG] - Symbolic Link to directory is considered to be a directory

### ISSUE THREAD

**Issue by manoss96** [paramiko/paramiko#2284]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SFTP

### What version(s) of paramiko are you using?

3.2.0

### What version(s) of Python are you using?

3.10.11

### What operating system and version are you using?

linuxserver/openssh-server:amd64-version-9.3_p2-r0

### Expected/desired behavior

I am trying to determine whether a symbolic link that points to a directory is a symbolic link.
```python
from stat import S_ISDIR, S_ISLNK

# Init SFTP client as "sftp"...

mode = sftp.stat(path='path/to/symlink').st_mode

print("Is directory: ", S_ISDIR(mode))
print("Is symbolic link: ", S_ISLNK(mode))
```
The program's output should be:
```
Is directory: False
Is symbolic link: True
```

### Actual behavior

Instead, the program's output is the opposite:
```
Is directory: True
Is symbolic link: False
```

**Comment by jun66j5** [comment]
> ```python
> mode = sftp.stat(path='path/to/symlink').st_mode
> ```

That is caused by your wrong code. You should use [lstat](https://docs.paramiko.org/en/3.3/api/sftp.html#paramiko.sftp_client.SFTPClient.lstat) rather than [stat](https://docs.paramiko.org/en/3.3/api/sftp.html#paramiko.sftp_client.SFTPClient.stat).

**Comment by manoss96** [comment]
Oh you're right, I missed that. I'm closing the issue.
