### ISSUE TITLE
[SUPPORT] - retrieving the result on separate context than the execution (getting response a-synchronously)

### ISSUE THREAD

**Issue by lilachassor** [paramiko/paramiko#2292]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

12.11.0

### What version(s) of Python are you using?

3.10.4

### What operating system and version are you using?

linux, fedora 36

### What are you trying to do with paramiko?

import paramiko
import threading

class SSHCommandRunner:
    def __init__(self, host, username, password):
        self.host = host
        self.username = username
        self.password = password
        self.channels = {}

    def _create_ssh_client(self):
        ssh_client = paramiko.SSHClient()
        ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh_client.connect(hostname=self.host, port=22, username=self.username, password=self.password)
        return ssh_client

    def execute_command(self, command):
        ssh_client = self._create_ssh_client()

        stdin, stdout, stderr = ssh_client.exec_command(command)
        self.channels[command] = stdout

        return stdout

    def wait_and_retrieve(self, command):
        stdout = self.channels.get(command)

        if stdout is None:
            raise ValueError(f"No channel found for command: {command}")

        response = stdout.read().decode().strip()
        return response

# Create an instance of SSHCommandRunner
ssh_runner = SSHCommandRunner('hostname', 'username', 'password')

# Execute a command and save the channel
command = 'ls -l'
channel = ssh_runner.execute_command(command)

# Now you can do other tasks

# Later, wait and retrieve the response using the saved channel
response = ssh_runner.wait_and_retrieve(command)
print("Response:", response)

### How are you trying to do it, and what's happening instead?

I get -1 as return code

### Anything else?

i would like to know if this operation is supported
if not, how can i get the response a-synchronously?

**Comment by timlegrand** [comment]
I guess paramiko is not reentrant, thus you cannot use multiple SSH connections at the same time.

**Comment by jun66j5** [comment]
@timlegrand Not correct. The issue is caused by `SSHClient` instance is dropped when exiting `execute_command`. The `SSHClient` instance should be kept at least until the command finishes.
