### ISSUE TITLE
[Feature] - It doesn't return the whole content on AlmaLinux8

### ISSUE THREAD

**Issue by SincerelyUnique** [paramiko/paramiko#2296]
### Is this feature for paramiko acting as a client or a server?

Client

### What functionality does this feature request relate to?

SSH, sshconfig

### For client-side features, does this relate to a specific type of SSH server?

AlmaLinux release 8.6 (Sky Tiger)

### Desired behavior

Hi Team,

Sorry to bother you, I met a problem, when I execute ssh commands by paramiko client, I found I cannot get the whole content, I tested same code in 3 servers
1. from my local server(macbook), run the code and can get the whole content
2. from linux7.3 server, run the same code and can get the whole content
3. but for AlmaLinux8 server, I cannot get the whole content, the content ends with '--More--'

python code is :
```
        device = InteractSSH(hostname, parameter['username'], parameter['password'])
        device.sendCMD('terminal length 0')
        content = device.sendCMD('show run interface') # content has '--More--' on AlmaLinux8
```

```
class InteractSSH():
    def __init__(self, ip, username, password, timeout=3):
        self.timeout = timeout
        self.ssh = paramiko.SSHClient()
        self.ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        self.ssh.connect(ip, username=username, password=password, timeout=30, \
                             look_for_keys=False, allow_agent=False)
        self.channel = self.ssh.invoke_shell()

    def sendCMD(self, cmd):
        self.channel.send(cmd+'\n')
        return self.getContent()
```
 
Team , can you help check ,do we have some configuration to handle this?

**Comment by SincerelyUnique** [comment]
sorry missed one function of python
```
    def getContent(self):
        channelData = ''
        i = 0
        while True:
            if self.channel.recv_ready():
                i = 0
                channelData += self.channel.recv(1024).decode('utf-8', errors='ignore')
            elif i<self.timeout:
                time.sleep(1)
                i += 1
                continue
            else:
                break
        return channelData
        
```

**Comment by jun66j5** [comment]
It seems that your `terminal length 0` command doesn't work. That is not a paramiko issue.

That question is about cisco device. Please ask on cicso support and/or community forum rather than here.

**Comment by SincerelyUnique** [comment]
@jun66j5  Thanks so much, I will ask cisco support about this issue~

**Comment by SincerelyUnique** [comment]
Hi, @jun66j5 , we find a solution,  if we add time.sleep(1) after paramiko ssh connect,  then it will work

```
        device = InteractSSH(hostname, parameter['username'], parameter['password'])
        time.sleep(1)
        device.sendCMD('terminal length 0')
        content = device.sendCMD('show run interface') # content has '--More--' on AlmaLinux8
 ```
 FYI

**Comment by jun66j5** [comment]
I think that it ideally should wait for prompt sent from cisco device before sending commands.
