### ISSUE TITLE
[BUG] - Unexpected results when command contains multiple pipe characters

### ISSUE THREAD

**Issue by XeonForce** [paramiko/paramiko#2309]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.3.1

### What version(s) of Python are you using?

3.11.2

### What operating system and version are you using?

Windows 11

### If you're connecting as a client, which SSH server are you connecting to?

OpenSSH 8.2p1

### Expected/desired behavior

Some files like `/app/<app name>/<version name>.jar` are in the `/app` directory, and is running via `java -jar <full path>`
Execute the following command in ssh shell to list the running processes
```bash
ps aux | egrep '/app/.*/.*\.jar' | grep java | awk '{print $NF}'
```
#### Result
```
/app/file/file-api_1.0_200007210959.jar
```

#### Server 1
```
["$NF}'\n", '/app/file/file-api_1.0_200007210959.jar\n']
```
#### Server 2
```
['/app/jh/jh-ui_20000720.jar\n', '/app/et/et.jar\n', '/app/assist/assist_200006161633.jar\n', "$NF}'\n"]
```

`$NF}'\n` appears in different line. 
It seems that paramiko may not correctly handle the `awk '{print $NF}'` command after multiple pipe characters, and `print $NF} `is executed.

### How to reproduce

Some files like `/app/<app name>/<version name>.jar` are in the `/app` directory, and is running via `java -jar <full path>`
```python
        command = r"""ps aux | egrep '/app/.*/.*\.jar' | grep java | awk '{print $NF}'"""
        stdin, stdout, stderr = self.client.exec_command(command)
        output = stdout.readlines()
        print(output)
```

**Comment by jun66j5** [comment]
No. That is not a paramiko issue. The new pid is assigned from low integer values when maximum pid reached. Also, your `grep` command wrongly matches `bash -c ps aux | ...` process invoked from `exec_command`.

When the command is invoked via `exec_command`, output of the `ps aux` always includes line like the following:

```
<username>   198698  0.0  0.0  12156  3228 ?        Ss   21:23   0:00 bash -c ps aux | egrep '/app/.*/.*\.jar' | grep java | awk '{print $NF}'
```

Your `grep` command wrongly matches the line and `$NF}` is output. Instead, try the following command:

```
ps aux | egrep '[/]app/.*/.*\.jar' | grep java | awk '{print $NF}
                ^^^ use [/] instead of /
```

See https://unix.stackexchange.com/a/295373

**Comment by XeonForce** [comment]
Thanks!
