### ISSUE TITLE
[SUPPORT] - Is there a maximum size of data we can send over a connection

### ISSUE THREAD

**Issue by Jean-PhilippeD** [paramiko/paramiko#2324]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.3.1

### What version(s) of Python are you using?

3.8.16

### What operating system and version are you using?

Redhat 7

### If you're connecting as a client, which SSH server are you connecting to?

openSSH

### What are you trying to do with paramiko?

I'm trying to send a simple echo command with paramiko_expect module.

`echo <string base64 encoded> ; echo exit_code: $?`

I echo the exit_code at the end to catch the end of my echo command with tail function from paramik_expect.

But in my case, the string can be very long and the limit seems to be around 32689 characters.
If I send with less than the limit, the command is working.
But If I send more than the limit, I can see with debug, that the command I send is truncated so I never catch the exit_code.

I do not know who is responsible for this truncate.
Is it paramiko, is it socket, is it the network, is it ssh server ... ?

### How are you trying to do it, and what's happening instead?

```
ssh_client = paramiko.SSHClient()
interaction = SSHClientInteraction(
          ssh_client, timeout=10
      )
# of course ssh_client connection is ok
interaction.send("echo very very big string; echo exit_code: $?") # more than ~32690 chars)
interaction.tail(
          callback=callback_func,
          stop_callback=stop_callback, # a callback function which should catch the exit_code but never does 
          output_callback=lambda m: logger.debug(m),
          timeout=timeout,
      )
```

In my case, the ssh_client get stucked in tail because it never catch the "exit_code" text due to to something is truncating the original command.

**Comment by Jean-PhilippeD** [comment]
Ok after few hours of digging, I've found the issue which is related to [paramiko_expect](https://github.com/fgimian/paramiko-expect/blob/master/paramiko_expect.py)

exec_command from paramiko handle correctly a data superior to 32KB by packetizing it. So it's working, but paramiko_expect does not, it uses directly [send](https://github.com/paramiko/paramiko/blob/main/paramiko/channel.py#L781) from channel.

**Comment by jun66j5** [comment]
That is not a paramiko issue. Documentation of the [send](https://docs.paramiko.org/en/latest/api/channel.html#paramiko.channel.Channel.send) says: _Applications are responsible for checking that all data has been sent_. Instead, use [sendall](https://docs.paramiko.org/en/latest/api/channel.html#paramiko.channel.Channel.sendall).

I'd suggest creating minimal reproducible code with only paramiko library before submitting a issue. Also, please report to project of the external library before the submitting, if you're using the external library.

**Comment by Jean-PhilippeD** [comment]
Yep my mistake.
I thought I add reproduced the behavior with only paramiko but checking again yesterday and I've seen my mistake.
