### ISSUE TITLE
[BUG] - bcrypt 4.1.0 No Longer Compatible with paramiko

### ISSUE THREAD

**Issue by aequitz** [paramiko/paramiko#2332]
### Are you using paramiko as a client or server?

Not sure

### What feature(s) aren't working right?

Something else

### What version(s) of paramiko are you using?

3.3.1

### What version(s) of Python are you using?

3.11.6

### What operating system and version are you using?

Windows 10

### Expected/desired behavior

Paramiko should not error out when attempting to import it.

### Actual behavior

Paramiko is producing the following error.

```shell
Traceback (most recent call last):
  File "anywhereusb_powercycle_port.py", line 15, in <module>
    import paramiko
  File ".venv\Lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import (
  File ".venv\Lib\site-packages\paramiko\transport.py", line 93, in <module>
    from paramiko.dsskey import DSSKey
  File ".venv\Lib\site-packages\paramiko\dsskey.py", line 37, in <module>
    from paramiko.pkey import PKey
  File ".venv\Lib\site-packages\paramiko\pkey.py", line 32, in <module>
    import bcrypt
  File ".venv\Lib\site-packages\bcrypt\__init__.py", line 13, in <module>
    from ._bcrypt import (
ModuleNotFoundError: No module named 'bcrypt._bcrypt'
```

### How to reproduce

1. Install paramiko.
2. Place `import paramiko` in a `test.py` file.
3. Run the file.
4. View the error shown.

### Anything else?

# Workaround
After installing paramiko, install bcrypt with the following version requirement:
```shell
python -m pip install "bcrypt>=3.2,<4.1"
```

**Comment by bskinn** [comment]
Thanks for this, @aequitz, definitely need to make sure we stay compatible here.

**Comment by bitprophet** [comment]
Like Brian said, thanks! This is kind of weird - the bad import call is _inside bcrypt itself_? This smells a lot like the kind of issue one gets with a problematic in-place upgrade of a dependency.

We'll try reproducing sometime; in the meantime, more details about whether you can repro this in a fresh virtualenv (or if the above _was_ a fresh virtualenv) and whether you can find any info about this upstream (changelog, tickets etc) would help!. Eg, did bcrypt break something, is this an intentional API change and we need to do something other than `import bcrypt` (seems unlikely?), etc.

**Comment by bskinn** [comment]
Oh, geez, yeah -- completely overlooked that the `_bcrypt` import is inside `bcrypt\__init__.py`.

Separately, I see those paths are backslash-delimited, implying you're on Windows, @aequitz -- is there any chance that `pip` tried to build `bcrypt` from sdist, and failed?  Could be that they don't have Windows wheels up on PyPI yet for v4.1?

**Comment by bskinn** [comment]
Aha.

![image](https://github.com/paramiko/paramiko/assets/11325439/08f54c46-5086-4db5-ba33-ae93306b2522)

**Comment by aequitz** [comment]
Thanks for the fast responses, guys! I’m good with closing this out since bcrypt has yanked that version.

I probably should’ve submitted a bug on bcrypt’s repo, but I was using paramiko and not bcrypt directly. However, it looks like somebody else submitted a bug here:
https://github.com/pyca/bcrypt/issues/677

Thanks again!
