### ISSUE TITLE
PyPI not actually on 3.3.1

### ISSUE THREAD

**Issue by patrick-a-lee** [paramiko/paramiko#2333]
When I `pip install paramiko`, `paramiko.__version__` and `pip show paramiko` both return 3.3.1, however, `_version.py` seems to indicate the library still points to version 2.8.1. At whatever rate, the fix from [#2039](https://github.com/paramiko/paramiko/pull/2039) is not in the package pip installed.

I haven't checked the wheel, but the tarball on PyPI seems to contain the updated source.

Using paramiko as a: client
Supposed version: 3.3.1
Python version: 3.10.11
OS: Windows 11

**Comment by bitprophet** [comment]
I'm afraid this sounds like a (weird!) pip/clientside issue - as you note, the data on PyPI should reflect what it claims to.

All I can suggest is doing a full `pip uninstall paramiko`, checking over your Python environment's `site-packages` to see if anything was left over somehow (and removing if so), then try another fresh install. Good luck!
