### ISSUE TITLE
[SUPPORT] - Adding Custom Extension or Implementing Server-Side Copy Operation

### ISSUE THREAD

**Issue by TWTom041** [paramiko/paramiko#2336]
### Are you using paramiko as a client or server?

Server

### What feature(s) aren't working right?

SFTP

### What version(s) of paramiko are you using?

3.3.0

### What version(s) of Python are you using?

3.9.11

### What operating system and version are you using?

Windows 11

### If you're connecting as a client, which SSH server are you connecting to?

OpenSSH v9.4.0

### What are you trying to do with paramiko?

I am attempting to implement a server-side file copy operation using Paramiko. The goal is to copy files on the remote server from one location to another without having to transfer the data to the client side.

### How are you trying to do it, and what's happening instead?

I have explored the existing Paramiko documentation and examples, but I couldn't find clear guidance on how to implement server-side file copy operations. Specifically, I want to add a custom extension or hook to Paramiko that supports a "copy-file" operation.

Here are my observations of the source code:

in paramiko\sftp.py, line 161, there's a check-file extension pair declared.
```python
extension_pairs = ["check-file", "md5,sha1"]
```
I tried to change it to `["copy-file", "md5,sha1"]` and `["copy-file", "md5,sha1"]`, but it seems to be not working.
![image](https://github.com/paramiko/paramiko/assets/57289975/d5f786e7-fb69-408e-950a-3d75b449abec)

So I doubt that should not be the proper way to add extension. But I can't find the documentation describe how to do it. 

Thanks to anyone that can guide me to the right path.

**Comment by TWTom041** [comment]
This question has been answered on Stackoverflow: [link](https://stackoverflow.com/questions/77675016/implementing-server-side-file-copy-with-paramiko-sftp-need-guidance-on-custom-e/77675165?noredirect=1#comment136942439_77675165)

**Comment by bskinn** [comment]
Thanks for following up and closing this out, @TWTom041! Glad you got your question answered.
