### ISSUE TITLE
[BUG] - test_sequence_number_rollover_detected fails on 32bit arches

### ISSUE THREAD

**Issue by stanislavlevin** [paramiko/paramiko#2353]
### Are you using paramiko as a client or server?

Both

### What feature(s) aren't working right?

Something else

### What version(s) of paramiko are you using?

3.4.0

### What version(s) of Python are you using?

3.12.1

### What operating system and version are you using?

ALTLInux Sisyphus 32bit

### Expected/desired behavior

Passed test.

### Actual behavior

Testing in downstream (32bit arches only) fails with:
```console
[user@host dir] python -m pytest tests/test_transport.py::TestStrictKex::test_sequence_number_rollover_detected

================================ test session starts =================================
platform linux -- Python 3.12.1, pytest-8.0.0, pluggy-1.4.0
rootdir: /usr/src/RPM/BUILD/python3-module-paramiko-3.4.0
configfile: pytest.ini
plugins: relaxed-2.0.1, xdist-3.4.0
collected 1 item                                                                     

tests/test_transport.py F                                                      [100%]

====================================== FAILURES ======================================
________________ TestStrictKex.test_sequence_number_rollover_detected ________________

self = <tests.test_transport.TestStrictKex object at 0xf5c5ebe8>

    def test_sequence_number_rollover_detected(self):
        class RolloverTransport(Transport):
            def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                # Induce an about-to-rollover seqno, such that it rolls over
                # during initial kex.
                setattr(
                    self.packetizer,
                    "_Packetizer__sequence_number_in",
                    sys.maxsize,
                )
                setattr(
                    self.packetizer,
                    "_Packetizer__sequence_number_out",
                    sys.maxsize,
                )
    
>       with raises(
            SSHException,
            match=r"Sequence number rolled over during initial kex!",
        ):
E       Failed: DID NOT RAISE <class 'paramiko.ssh_exception.SSHException'>

tests/test_transport.py:1434: Failed
```

During the test `__sequence_number_in` and `__sequence_number_out` are set to `sys.maxsize`:
https://github.com/paramiko/paramiko/blob/f0881ba8af57d1a122ef19c40d144afdcb6e0824/paramiko/packet.py#L429-L433 and
https://github.com/paramiko/paramiko/blob/f0881ba8af57d1a122ef19c40d144afdcb6e0824/paramiko/packet.py#L538-L542

but this doesn't work on 32bit arches:
```python
>>> (sys.maxsize + 1) & 0xFFFFFFFF
2147483648
```

**Comment by bitprophet** [comment]
Thanks for the report!

I can reproduce this with a modified version of the i386 Dockerfile used the last time a 32bit issue showed up.

Crafted what I think is the right fix now (namely, not using `sys.maxsize` under 64bit systems as a lazy shorthand for "something that rounds to 0 when you add 1 and then bitwise AND with a 32-bit full integer").

**Comment by stanislavlevin** [comment]
Thank you for the fix!
