### ISSUE TITLE
[BUG] - paramiko recv() function not reading the psql prompt when ssh to a windows and psql command is sent 

### ISSUE THREAD

**Issue by basu45** [paramiko/paramiko#2398]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH, Something else

### What version(s) of paramiko are you using?

3.3.0

### What version(s) of Python are you using?

3.10

### What operating system and version are you using?

Windows 11

### If you're connecting as a client, which SSH server are you connecting to?

OPENSSH

### If you're using paramiko as part of another tool, which tool/version?

Paramiko-expect

### Expected/desired behavior

The recv called after send should detect the psql prompt and return in output

### Actual behavior

Recv() not receiving the prompt when ssh is done to windows and giving eof of transport

### How to reproduce

1.paramiko connect to windows vm with poststresql and psql installed
2.Send the psql command using channel.send()
3.channel.rec()

### Anything else?
```
Import paramiko
Import time

ssh=paramiko.Ssh client()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy()
ssh.connect(hostname,username,pass,banner_timeout,timeout,auth_timeout)
Transport= ssh.get_transport()
Session=Transport.open_session()
Session.invoke_shell()
Session.send(psql -U postgres)
Time.sleep(5)
If(Session.recv_ready):
    Output=Session.recv(1024)
Print(output)
```

Tried with increasing nbytes in recv
Still it's not getting the pswl prompt
Same issue with most of executable(exe) on windows

**Comment by basu45** [comment]
Hi @jun66j5 ,
Can I get help on this issue

**Comment by jun66j5** [comment]
I'd suggest using `Channel.exec_command` instead of sending command via `Channel.invoke_shell` unless you are familiar with pty and shell.

Also, the script should be posted with <code>\`\`\`...\`\`\`</code> (code block). See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by jun66j5** [comment]
Also, that is not a paramiko issue. It is just a support question of paramiko-expect. I'd suggest to send the question to paramiko-expect project, not here.

**Comment by basu45** [comment]
No imean when command is sent via channel.send()

The channel.recv() is not providing the correct output
Here is the output provided by cahnnel.recv()

b'[6npswl -U postgres Microsoft windows version [version details]. \r\r\n 


We need to use channel.invoke_shell() because we need the expect like interactive shell

Whereas same works perfectly fine with linux

**Comment by basu45** [comment]
> I'd suggest using `Channel.exec_command` instead of sending command via `Channel.invoke_shell` unless you are familiar with pty and shell.
> 
> Also, the script should be posted with `` ```...``` `` (code block). See https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

My opologies.
Will follow above rules

**Comment by jun66j5** [comment]
Use PHPASSWORD enviroment (or PGPASSFILE) via exec_command rather than interactive mode.

**Comment by basu45** [comment]
We needed an interactive mode because we need to query the db and based on db details some additional queries needs to be executed based on previous outputs
Is there any way to find root cause and try to fix it?

**Comment by jun66j5** [comment]
Your usage is wrong.

> b'[6npswl -U postgres Microsoft windows version [version details]. \r\r\n'

Send command (`psql -U ...\r\n`) to the channel after receiving the prompt of cmd.exe.

**Comment by basu45** [comment]
Same thing is done the above output is what we are getting after sending '''psql ...\r\n ''' but output we are getting is somewhat like above

**Comment by jun66j5** [comment]
> We needed an interactive mode because we need to query the db and based on query output some additional queries needs to be executed based on previous outputs

If I were to do it, I'd implement it in a PowerShell script (or bat script) and run the script using exec_command from paramiko,  and avoid interactive mode.

**Comment by basu45** [comment]
> > We needed an interactive mode because we need to query the db and based on query output some additional queries needs to be executed based on previous outputs
> 
> If I were to do it, I'd implement it in a PowerShell script (or bat script) and run the script using exec_command from paramiko, and avoid interactive mode.

Ok thanks, but the issue is we already have pre built framework around that which worked perfectly fine with linux no we needed same script to work with window ssv

**Comment by basu45** [comment]
Can u plz try it once if you have the  windows setup 
That would give a clear picture to the issue

**Comment by jun66j5** [comment]
Hm, I don't have experience with shell operations on Windows Server from paramiko, and I don't think it works properly, so I can't help you.

**Comment by basu45** [comment]
> Hm, I don't have experience with shell operations on Windows Server from paramiko, and I don't think it works properly, so I can't help you.

Ok,can you point me to the right guy
That will be helpful..

**Comment by jun66j5** [comment]
Works fine on my environment but I don't recommend using interactive mode if you need it unless solving it yourself.

#### Script

```py
import os, re, sys, time
import paramiko

ssh_host = 'computer-name'
ssh_user = 'username'
ssh_pass = 'password'
psql_bin = r'"C:\Program Files\PostgreSQL\16\bin\psql.exe"'
psql_host = 'hostname'
psql_user = 'username'
psql_pass = 'password'
psql_dbname = 'dbname'
cmd_prompt_re = re.compile((r'^%s@\S+\s+C:\\[^>]*>' % re.escape(ssh_user)).encode('utf-8'), re.M)
psql_prompt_re = re.compile((r'^%s=[#>]' % re.escape(psql_dbname)).encode('utf-8'), re.M)

paramiko.util.log_to_file(__file__ + '.log')

def wait_for_prompt(shell, pattern):
    while True:
        while shell.recv_ready():
            data = shell.recv(1024)
            print(repr(data), file=sys.stderr, flush=True)
            if pattern.search(data):
                return
        time.sleep(1)

def wait_for_cmd_prompt(shell):
    wait_for_prompt(shell, cmd_prompt_re)

def wait_for_psql_prompt(shell):
    wait_for_prompt(shell, psql_prompt_re)

with paramiko.SSHClient() as cli:
    cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    cli.connect(ssh_host, username=ssh_user, password=ssh_pass)
    with cli.invoke_shell() as shell:
        wait_for_cmd_prompt(shell)
        shell.send(f'{psql_bin} --version\r\n'.encode('utf-8'))
        wait_for_cmd_prompt(shell)
        shell.send(f'set PGPASSWORD={psql_pass}\r\n'.encode('utf-8'))
        wait_for_cmd_prompt(shell)
        shell.send(f'{psql_bin} --host={psql_host} --username={psql_user} {psql_dbname}\r\n'.encode('utf-8'))
        wait_for_psql_prompt(shell)
        shell.send(b'SELECT version();\r\n')
        wait_for_psql_prompt(shell)
```

#### Results
```
C:>call C:\usr\src\paramiko.venv\Scripts\python.exe paramiko-windows.py
b'\x1b[2J\x1b[m\x1b[HMicrosoft Windows [Version 10.0.19045.4474]\x1b]0;C:\\WINDOWS\\system32\\conhost.exe\x07\x1b[?25h\x1b[25l\r\n(c) Microsoft Corporation. All rights reserved.\r\n\x1b[47X\r\nusername@COMPUTER-NAME C:\\Users\\username>    \x1b[4;44H\x1b]0;Administrator: C:\\WINDOWS\\system32\\conhost.exe\x07\x1b[?25h'
b'\rusername@COMPUTER-NAME C:\\Users\\username>"C:\\Program Files\\PostgreSQL\\16\\bin\\p\r\nsql.exe" --version\x1b[K\r\npsql (PostgreSQL) 16.3\x1b[21X\r\n\x1b[43X\r\nusername@COMPUTER-NAME C:\\Users\\username>'
b'set PGPASSWORD=password\r\n\r\nusername@COMPUTER-NAME C:\\Users\\username>'
b'\rusername@COMPUTER-NAME C:\\Users\\username>"C:\\Program Files\\PostgreSQL\\16\\bin\\p\r\nsql.exe" --host=192.168.11.122 --username=username dbname\x1b[K\r\n\x1b]0;Administrator: C:\\WINDOWS\\system32\\conhost.exe - "C:\\Program Files\\PostgreSQL\\16\\bin\\psql.exe"  --host=192.168.11.122 --username=username dbname\x07p\rpsql (16.3, server 9.5.25)\x1b[K\r\nSSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, compress\r\nion: off)\x1b[K\r\nType "help" for help.\x1b[K\r\n\x1b[K\r\ndbname=>\x1b[K\x1b[1C'
b'SELECT version();\r\n                                                      version\x1b[K\r\n\x1b[K\r\n--------------------------------------------------------------------------------\r\n-----------------------------------\x1b[K\r\n PostgreSQL 9.5.25 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu\r\n1~16.04.12) 5.4.0 20160609, 64-bit\x1b[K\r\n(1 row)\x1b[K\r\n\n\ndbname=>\x1b[1C'
```

**Comment by basu45** [comment]
Ok let me check I haven't encode the send command let me check with that

**Comment by jun66j5** [comment]
I don't think you should close an issue without explaining what caused it, especially when you've received help.

**Comment by basu45** [comment]
Hi,
Sorry for the inconvenience.
The issue was cause due to cygwin sshd service was not able to open any of the executables.so we changed cygwin's ssh service with openssh  and it worked.

Thak you very much for the help!!!
