### ISSUE TITLE
Locking remote ssh host with paramiko session/channel id

### ISSUE THREAD

**Issue by woodholly** [paramiko/paramiko#2399]
What is the correct way to create lock on remote server to prevent multiple simultaneous paramiko connections to the host (from different hosts) ?
I want to create remote file "lock" which contains current paramiko session id/channel id so that if this connection drops (before paramiko removes self lock), other paramiko instance will read this lock file and check if that "old" paramiko connection is still active (and exit) or has already been closed (update lock and continue).
Or in other words - how to check if some other paramiko connection (identified by some id) is still active on remote server?
Usually "echo $$" (pid) is used for this purpose, but not with paramiko.

**Comment by jun66j5** [comment]
Have you checked and tried [flock(1)](https://manpages.ubuntu.com/manpages/lunar/man1/flock.1.html)?

Also, use _Support Request_ template rather than _Blank Issue Template_ on creating new issue for support questions.

**Comment by woodholly** [comment]
@jun66j5 flock can't be used for that

**Comment by jun66j5** [comment]
Why? I think your question is just a problem for locking of the resource. So, I'd suggest to use the locking utility on the remote server....?

**Comment by jun66j5** [comment]
> how to check if some other paramiko connection (identified by some id) is still active on remote server?

Try `ss -n 'sport == 22'` (or /proc/net/tcp) to check active ssh connections but it is difficult to count them correctly.

**Comment by woodholly** [comment]
What I did - connect to 22 using own socket, profide paramiko that socket, use socket ports to identify the connection, and proc/net/tcp to check if it still active. This should be part of paramiko or at least the method to get socket from paramiko.
