### ISSUE TITLE
How to send Ctrl+C to ssh server?

### ISSUE THREAD

**Issue by wzcprince** [paramiko/paramiko#240]
Just as the title, thank you in advance!

**Comment by ankitacroit09** [comment]
I am  trying to execute the "\\x003" the same on Shell to break the Tailf command.
And its not working (means its not breaking the tailf command).

**Comment by bra-fsn** [comment]
I just found this one:
https://github.com/paramiko/paramiko/issues/785
which explains that finally openssh has support for this (without a TTY).
