### ISSUE TITLE
Anaconda release not up to date

### ISSUE THREAD

**Issue by Klest94** [paramiko/paramiko#2428]
While installing ``paramiko`` from anaconda, the latest release version is 2.8.1.
This is not up-to-date with the current latest release on pypi, currently at 3.4.0.
As an anaconda user for virtual environments, I would benefit from the latest version of ``paramiko`` without needing to resort to ``pip`` 

I am currently using the latest version of anaconda (24.7.1)

**Comment by bskinn** [comment]
Thanks for reporting this; however, this is not something that the paramiko project has control over.

Anaconda controls the package updates on the conda channels they curate directly. If you're using such a channel, you would need to reach out to Anaconda support.

The version on conda-forge is managed by the https://github.com/conda-forge/paramiko-feedstock repository. If you're using conda-forge, open a ticket on the `paramiko-feedstock` repo.
