### ISSUE TITLE
When used with Duplicity, paramiko presents truncated array of volumes

### ISSUE THREAD

**Issue by JElchison** [paramiko/paramiko#246]
This issue was first raised in a Duplicity forum, but the issue was found to be with paramiko.  I'm using 'paramiko-1.12.0-py2.7.egg' on OS X 10.9.1. I used Homebrew to install Duplicity 0.6.22. 

Please find verbose information at https://answers.launchpad.net/duplicity/+question/241395

I'm happy to (re)post any information here, just say the word.

Thanks in advance,
-je

**Comment by NerdyProjects** [comment]
Just to contribute here as well, I think this is not a paramiko bug.

Duplicity calls recv(-1) and expects all data back. Although not explicitly documented, paramikos recv() works basically the same as you would expect "lower level" read() methods to work: Return currently available data, at most the number of bytes given as parameter.

For a "long" result, this will return just "one" buffer - the length might depend on the window size or some other size restrictions.

recv() need to be called in a loop until the data is known to have ended (channel closed and no more data available). Alternatively, the BufferedFile readlines() or read() can be used.
