### ISSUE TITLE
[BUG] - Paramiko import failure on Raspberry PI Bullseye OS

### ISSUE THREAD

**Issue by jonathan84clark** [paramiko/paramiko#2472]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.5.0

### What version(s) of Python are you using?

3.9.2

### What operating system and version are you using?

Raspbian GNU/Linux Version 11 (Bullseye)

### Expected/desired behavior

I expect that when I do an
import paramiko
it will import without errors.

### Actual behavior

When I import paramiko in python I get the following:
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssg/.local/lib/python3.9/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import (
  File "/home/ssg/.local/lib/python3.9/site-packages/paramiko/transport.py", line 33, in <module>
    from cryptography.hazmat.primitives.ciphers import (
  File "/home/ssg/.local/lib/python3.9/site-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 11, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "/home/ssg/.local/lib/python3.9/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl
ImportError: libssl.so.3: cannot open shared object file: No such file or directory

If paramiko no longer is supported on the Bullseye OS then I would expect the package to be removed from the pip3 list so it can't be installed. Or perhaps a note made that indicates it is no longer compatible with this setup.

### How to reproduce

1. Create an image of Raspbian Bullseye 32-bit on an SD card
2. Run the image on the Raspberry PI 4
3. Update (sudo apt-get update)
4. Upgrade (sudo apt-get upgrade)
5. Install pip (sudo apt-get install python3-pip
6. Install paramiko (pip3 install paramiko)
7. Start a python shell (python)
8. import paramiko (import paramiko)

At this point the error will occur. 

### Anything else?

I tried to fix the issue by downgrading paramiko to version 2.0.0 that didn't work
I also tried installing openssl and tried removing and re-installing openssl without any luck.
Thanks for the help!

**Comment by jun66j5** [comment]
That's an issue of built distribution of cryptography. Please report to cryptography rather than here. Otherwise, you could build from source instead of pre-built wheel. See https://cryptography.io/en/latest/installation/#building

**Comment by jonathan84clark** [comment]
Apparently the latest version of SSL won't build on the Raspberry PI 4. At least not on the Bullseye OS. I didn't test it on Bookworm (although Bookworm has made running python a nightmare). 
The final solution was to ditch the Raspbian OS versions and run Ubuntu 22.04 on the PI. Ubuntu IS able to run paramiko on the PI4. Although you need to do an apt-get update and apt-get upgrade to be able to install it.

I suspect that trying to fix this problem on the Bullseye OS is going to be a wild goose chase. So if anyone reading this wants to run paramiko on the PI4 with Bullseye, you're out of luck....it isn't going to work.
