### ISSUE TITLE
[BUG] - Channel.exec_command() can't send '&' (ampersand) character!!!

### ISSUE THREAD

**Issue by perseoGI** [paramiko/paramiko#2474]
### Are you using paramiko as a client or server?

Client

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.5.0

### What version(s) of Python are you using?

3.12.3

### What operating system and version are you using?

MacOS Sonoma

### If you're connecting as a client, which SSH server are you connecting to?

OpenSSH

### Expected/desired behavior

Sending a command which contains an ampersand (&) it is expected for the server to receive that ampersand.
Ampersand in linux is a special character which tells the shell to run the former command in background.
But if the ampersand is escaped, for example between quotes, it MUST be interpreted as a character.

Example code:

```py
# Client side
def _run_command(self, command):
    ''' Run a command in an SSH session.
        When requesting a pseudo-terminal from the server,
        ensure we pass width and height that matches the current
        terminal
    '''
    channel = self.client.get_transport().open_session()
    if sys.stdout.isatty():
        width, height = os.get_terminal_size()
        channel.get_pty(width=width, height=height)

    channel.exec_command(command)

    stdout = channel.makefile("r")
    stderr = channel.makefile("r")
    return stdout, stderr

# Main code
# Initialize the client...
_run_command("python test.py Hi Mr '&' Mrs Smith")

# test.py Server side (on remote machine, in my case a Windows 11)
import sys
print(sys.argv)


# Expected result
['C:/Users/.../test.py',  'Hi', 'Mr', "'&'", 'Mrs', 'Smith']
```

### Actual behavior

Real result:

```
['C:/Users/.../test.py', 'Hi', 'Mr', "'"]
```

All contents from the ampersand to the end of the command will not be sent to the server.
I've tested all kind of escapations:

* "&"
* '&'
* \&
* &&
* Unicode character
* Ascii character
* _&_
* \\&

In all the cases, paramiko seems to be truncating the command when the ampersand (&) character is sent.

### How to reproduce

Tested with different scripts, different versions.

**Comment by jun66j5** [comment]
That is not a paramiko issue.

The command string is interpreted by shell of the remote server (cmd.exe in this case). So, `&` character must be enclosed by `"` characters.

**Comment by jun66j5** [comment]
I just tried it and works well (Remote host is Windows 10 with OpenSSH_for_Windows_9.5p1).

### Test script
```python
import paramiko

ssh_host = 'remotehost'
ssh_user = 'username'
ssh_pass = 'password'
command = r'python.exe C:\tmp\test.py abc "&" def'

with paramiko.SSHClient() as cli:
    cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    cli.connect(ssh_host, username=ssh_user, password=ssh_pass)
    remote_version = cli.get_transport().remote_version
    print(f'remote_version: {remote_version!r}')
    stdin, stdout, stderr = cli.exec_command(command)
    stdin.close()
    stdout = stdout.read()
    stderr = stderr.read()
    print(f'stdout: {stdout!r}')
    print(f'stderr: {stderr!r}')
```

### C:\tmp\test.py on the remote host
```python
import sys
print(sys.argv)
```

### Result
```
C> python.exe test-script.py
remote_version: 'SSH-2.0-OpenSSH_for_Windows_9.5'
stdout: b"['C:\\\\tmp\\\\test.py', 'abc', '&', 'def']\r\n"
stderr: b''
```

**Comment by perseoGI** [comment]
Yes, you are totally right! 
I've tested it with doble quotes inside single quotes and it works on a basic scenario, but it is still failing in this case:

```py
def _run_interactive_command(self, command: str):
    ''' Run a command in an SSH session.
        When requesting a pseudo-terminal from the server,
        ensure we pass width and height that matches the current
        terminal
    '''
    channel = self.client.get_transport().open_session()
    if sys.stdout.isatty():
        width, height = os.get_terminal_size()
        channel.get_pty(width=width, height=height)

    channel.exec_command(command)

    stdout = channel.makefile("r")
    stderr = channel.makefile("r")
    return stdout, stderr
```
Usage
```py
stdout, _ = self._run_interactive_command(command)
first_line = True
while not stdout.channel.exit_status_ready():
    line = stdout.channel.recv(1024)
    if first_line and self.is_remote_windows:
        # Avoid clearing and moving the cursor when the remote server is Windows
        # https://github.com/PowerShell/Win32-OpenSSH/issues/1738#issuecomment-789434169
        line = line.replace(b"\x1b[2J\x1b[m\x1b[H",b"")
    sys.stdout.buffer.write(line)
    sys.stdout.buffer.flush()
    first_line = False
```

By setting the channel `get_pty` it fails for some reason when sending `&`!
(Disclaimer: This is some legacy code, not mine. Maybe there is a better way to execute remotely in an interactive way)

**Comment by jun66j5** [comment]
The paramiko always sends entire of the command regardless of the pty. That's an issue of Win32-OpenSSH, not paramiko. Please report to Win32-OpenSSH project.

That aside, it could be escaped with `^` character with pty.

```diff
--- test-script.py.orig       2024-11-22 11:24:39.570238600 +0900
+++ test-script.py    2024-11-22 11:21:05.614189000 +0900
@@ -3,14 +3,14 @@
 ssh_host = 'remotehost'
 ssh_user = 'username'
 ssh_pass = 'password'
-command = r'python.exe C:\tmp\test.py abc "&" def'
+command = r'python.exe C:\tmp\test.py abc ^& def'

 with paramiko.SSHClient() as cli:
     cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
     cli.connect(ssh_host, username=ssh_user, password=ssh_pass)
     remote_version = cli.get_transport().remote_version
     print(f'remote_version: {remote_version!r}')
-    stdin, stdout, stderr = cli.exec_command(command)
+    stdin, stdout, stderr = cli.exec_command(command, get_pty=True)
     stdin.close()
     stdout = stdout.read()
     stderr = stderr.read()
```

### Result
```
remote_version: 'SSH-2.0-OpenSSH_for_Windows_9.5'
stdout: b"\x1b[2J\x1b[m\x1b[H['C:\\\\tmp\\\\test.py', 'abc', '&', 'def']\r\n\x1b]0;C:\\WINDOWS\\system32\\conhost.exe\x07\x1b[?25h"
stderr: b''
```

**Comment by jun66j5** [comment]
At least, it might be good that `_run_interactive_command` always call `get_pty()` regardless of whether stdin is a tty or not. Otherwise, the command would need to escape differently depending on whether stdin is a tty or not.

```diff
     if sys.stdout.isatty():
         width, height = os.get_terminal_size()
-        channel.get_pty(width=width, height=height)
+    else:
+        width = 80
+        height = 24
+    channel.get_pty(width=width, height=height)
```

Also, you could test using `ssh` command with `-t` and `-T` options like the following:
```
$ ssh -T username@remotehost 'python.exe C:\tmp\test.py abc "&" def' | python3 -c 'import sys; print(repr(sys.stdin.buffer.read()))'
b"['C:\\\\tmp\\\\test.py', 'abc', '&', 'def']\r\n"
$ ssh -t username@remotehost 'python.exe C:\tmp\test.py abc ^& def' | python3 -c 'import sys; print(repr(sys.stdin.buffer.read()))'
b"\x1b[2J\x1b[m\x1b[H['C:\\\\tmp\\\\test.py', 'abc', '&', 'def']\r\n\x1b]0;C:\\WINDOWS\\system32\\conhost.exe\x07\x1b[?25h"
                                                                                                                           Connection to remotehost closed.
```
I'd suggest test and confirm "works fine" with `ssh` command before implementing using paramiko.

**Comment by perseoGI** [comment]
Thank you for your quick response!
I've added your changes, good idea.

At the end as I don't have that much time, I've end up coping the full command (with `&`) to a script file and execute using this `run_interactive_command`. Works like a charm now!
Thank you ❤️
