### ISSUE TITLE
A strange error in Paramiko

### ISSUE THREAD

**Issue by 654sd** [paramiko/paramiko#2477]
### Are you using paramiko as a client or server?

Both

### What feature(s) aren't working right?

SSH

### What version(s) of paramiko are you using?

3.5.0

### What version(s) of Python are you using?

3.8

### What operating system and version are you using?

MacOS

### If you're connecting as a client, which SSH server are you connecting to?

127.0.0.1

### Expected/desired behavior

I have encountered a strange problem, I use paramiko module ➕scp module to implement remote ssh upload file, but I only upload one file so that the code will execute successfully, the following is a successful example: import paramiko

import scp

ssh = paramiko.SSHClient()

ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

SSH. Connect (hostname = '127.0.0.1,

port=22,

username='root',

password='alpine')

pro = scp.SCPClient(ssh.get_transport())

ssh.exec_command('ls')

ssh.exec_command('cd / & ls -l')

pro.put('test', remote_path='/var', recursive=False)

print('put done')

pro.close()

ssh.close()

This code executes successfully and the console outputs the put done string

But the following code will cause an error:

import paramiko

import scp

ssh = paramiko.SSHClient()

ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

SSH. Connect (hostname = '127.0.0.1,

port=22,

username='root',

password='alpine')

pro = scp.SCPClient(ssh.get_transport())

ssh.exec_command('ls')

ssh.exec_command('cd / & ls -l')

pro.put('test', remote_path='/var', recursive=False)

pro.put('test', remote_path='/var/1.txt', recursive=False)

print('put done')

pro.close()

ssh.close()

This code console error: Traceback (most recent call last):

File "/Users/macos/PyCode/pythonProject/IOS/mina.py", line 14, in <module>

pro.put('test', remote_path='/var/1.txt', recursive=False)

The File "/ Users/macos PyBin/T2Bypass/lib/python3.8 / site - packages/SCP. Py", line 198, put in

self.channel.exec_command(scp_command +

File "/ Users/macos PyBin T2Bypass/lib/python3.8 / site - packages/paramiko/channel. Py", line 70, in _check

return func(self, *args, **kwds)

File "/ Users/macos PyBin T2Bypass/lib/python3.8 / site - packages/paramiko/channel. Py", line 255, in exec_command

self._wait_for_event()

File "/ Users/macos PyBin T2Bypass/lib/python3.8 / site - packages/paramiko/channel. Py", line 1224, in _wait_for_event

raise e

paramiko.ssh_exception.SSHException: Channel closed.

So I find that the code works fine when I transfer the file only once, but when my code is uploaded two or more times my code will have an error paramiko.ssh_exception.SSHException: Channel closed. I tried to find a solution on goole, but it seems that no one met the same or similar situation with me, so I could not find a suitable solution. I suspect that this is a bug, because I made a judgment on the ssh connection status in the code that reported an error. It is found that the ssh connection status is still true when the upload code error is reported, which proves that the ssh ice has not broken the link. If you see the problem I raised, can you explain the reason for the error to me

### Actual behavior

fix bug

### How to reproduce

import paramiko
import scp

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname='127.0.0.1',
            port=22,
            username='root',
            password='alpine')
pro = scp.SCPClient(ssh.get_transport())
ssh.exec_command('ls')
ssh.exec_command('cd / & ls -l')
pro.put('test', remote_path='/var', recursive=False)
pro.put('test', remote_path='/var/1.txt', recursive=False)
print('put done')
pro.close()
ssh.close()

### Anything else?

Traceback (most recent call last):
  File "/Users/macos/PyCode/pythonProject/IOS/mina.py", line 14, in <module>
    pro.put('test', remote_path='/var/1.txt', recursive=False)
  File "/Users/macos/PyBin/T2Bypass/lib/python3.8/site-packages/scp.py", line 198, in put
    self.channel.exec_command(scp_command +
  File "/Users/macos/PyBin/T2Bypass/lib/python3.8/site-packages/paramiko/channel.py", line 70, in _check
    return func(self, *args, **kwds)
  File "/Users/macos/PyBin/T2Bypass/lib/python3.8/site-packages/paramiko/channel.py", line 255, in exec_command
    self._wait_for_event()
  File "/Users/macos/PyBin/T2Bypass/lib/python3.8/site-packages/paramiko/channel.py", line 1224, in _wait_for_event
    raise e
paramiko.ssh_exception.SSHException: Channel closed.

**Comment by jun66j5** [comment]
It seems to be an issue of scp.py module. Please report it to the scp.py repository, not here.

**Comment by 654sd** [comment]
Good brother

**Comment by 654sd** [comment]
I'll submit it to scp. Thank you for reminding me

**Comment by APCBoston** [comment]
@bskinn @654sd if everybody agrees the issue is in scp and not paramiko, can this ticket be closed?

**Comment by LovelyBunnyOfYe** [comment]
I got the same problem, so did you get any answer to this problem from scp?
