### ISSUE TITLE
[FEAT] - Python 3.12 support

### ISSUE THREAD

**Issue by cedrata** [paramiko/paramiko#2478]
### Is this feature for paramiko acting as a client or a server?

Client

### What functionality does this feature request relate to?

SFTP

### Desired behavior

I cannot see the current python version support to Python3.12, it would be great to have this support, and if already supported could the documentation be upgraded to show that as well?

**Comment by APCBoston** [comment]
Paramiko definitely works with Python 3.12.  Looks like this is just a matter of updating the `setup.py` list of compatible versions.

**Comment by cedrata** [comment]
Great, thank you for the information! I wanted to make sure it's still solid might need it in the close future!
