### ISSUE TITLE
There is no way to get the banner posted by an ssh server

### ISSUE THREAD

**Issue by rustyscottweber** [paramiko/paramiko#273]
I was looking through the code for paramiko, and maybe I missed it but, I wasn't able to find a way to get the posted banner from an ssh server.  I have a scenario in which information posted to the ssh banner is useful and important information.

For example,

<pre>
<code>
 ssh root@ion-01
The authenticity of host 'ion-01 (10.50.48.50)' can't be established.
ECDSA key fingerprint is 06:42:2d:ef:d1:0e:be:03:8c:ee:ce:6a:0c:59:e0:d8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'ion-01,10.50.48.50' (ECDSA) to the list of known hosts.
------------------------------------------------------------------------------
WARNING: This is a private system.  Do not attempt to login unless you are an
authorized user. Any authorized or unauthorized access or use may be monitored
and can result in criminal or civil prosecution under applicable law.
------------------------------------------------------------------------------
Welcome to Fusion-io ION Data Accelerator 2.3.0-461

System Serial Number: "USE233C9X1"

For first time log in, get password from the first password generator using the serial number:
Password:
</code>
</pre>

Above, in a normal ssh scenario, attempting to log in through ssh prints the serial number of the machine which is needed to generate the original password of the system, but there is no way to get this banner using paramiko.

**Comment by jossef** [comment]
```
# !/usr/bin/python

import paramiko


def grab_banner(ip_address, port):
    client = paramiko.SSHClient()
    client.load_system_host_keys()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    try:
        client.connect(ip_address, port=port, username='username', password='bad-password-on-purpose')
    except:
        return client._transport.get_banner()


if __name__ == '__main__':
    print grab_banner('192.168.1.26', 22)
```

**Comment by martinprikryl** [comment]
If Paramiko attempts other authentication methods (like public key authentication) after failing the password authentication, the banner is discarded.
See https://stackoverflow.com/q/62370184/850848

**Comment by rustyscottweber** [comment]
That's because the entire auth and transport object are thrown away after each authentication method; the result being that the banner is also discarded. I suggest that you find the part of the code where it get's thrown away, document the section of code and detail how throwing away the entire transport is not the best idea between each different authentication method, then file a new bug rather than commenting on a very old closed bug.

**Comment by ploxiln** [comment]
see also https://github.com/paramiko/paramiko/pull/438

**Comment by rustyscottweber** [comment]
OH! NICE! I didn't know they had patched that one!

**Comment by rustyscottweber** [comment]
> If Paramiko attempts other authentication methods (like public key authentication) after failing the password authentication, the banner is discarded.
> See https://stackoverflow.com/q/62370184/850848

What version of paramiko are you using and have you tried updating?

**Comment by ploxiln** [comment]
#438 is not merged in this project (... but it is in my fork, from which I've made a few releases: https://github.com/ploxiln/paramiko-ng/releases)
