### ISSUE TITLE
SFTPClient.get raise IOError

### ISSUE THREAD

**Issue by eight** [paramiko/paramiko#29]
I' had same problem with this.
  IOError, can not run sftp.get
  https://bugs.launchpad.net/paramiko/+bug/689903

And the problem is fixed by this patch.
  paramiko.SFTPClient get prefetch() raises "Operation unsupported" error
  https://bugs.launchpad.net/paramiko/+bug/510867

So, please include this patch into the official package.

**Comment by bitprophet** [comment]
This should be fixed as of 1.16 in #194.
