### ISSUE TITLE
Clients disconnected without recourse if key unsupported

### ISSUE THREAD

**Issue by luke-jr** [paramiko/paramiko#342]
Unsupported public keys just cause Paramiko to disconnect the client. Instead, it should reject the authentication and give an opportunity to try another key. Or at least, make it possible for the application to implement this behaviour...

**Comment by jansegre** [comment]
Is this related to #23?

**Comment by bitprophet** [comment]
It's definitely going to be covered under one of these: https://github.com/paramiko/paramiko/labels/Keys :) the linchpin there is #387 so watch that probably.
