### ISSUE TITLE
paramiko does not parse /etc/ssh/ssh_config by default

### ISSUE THREAD

**Issue by hvnsweeting** [paramiko/paramiko#363]
it only parse ~/.ssh/config, not system SSH config, does this consider a bug?

**Comment by BillyCroan** [comment]
I experience this issue in xpra, which uses paramiko for ssh by default

**Comment by bskinn** [comment]
@BillyCroan Sounds like, per bitprophet's last comment, you should raise this on the xpra tracker, not here.
