### ISSUE TITLE
Packet.read_all() hangs on socket.recv() when transport is closed by different thread

### ISSUE THREAD

**Issue by GMTA** [paramiko/paramiko#380]
I'm developing a FUSE library using Paramiko as an SSH client backend (see https://github.com/GMTA/mountload). FUSE can optionally run daemonized (foreground=False). I discovered that whenever I run FUSE as a daemon and directly unmount the mounted filesystem, Paramiko fails to close its SFTPClient causing the process to hang indefinitely.

I did some research and I discovered that the main difference between running FUSE as a daemon and in the foreground is that the construction and destruction happens in different threads when daemonized.

So what happens in this different thread?
- I close the SSHClient by calling .close()
- SSHClient.close() calls self._transport.close()
- Transport.close() calls self.stop_thread()
- Transport.stop_Thread() keeps looping on self.isAlive() and self.join(10)

Apparantly, Transport.run() is running indefinitely:
- Transport.run() calls self.packetizer.read_message()
- Packet.read_message() calls Packet.read_all()
- Packet.read_all() calls self.__socket.recv()

I added additional logging directly before and after this recv() call (and every possible **except**, even an additional **finally**) and it looks like recv() never returns. I tried replacing it with select.select(), but to no avail. I added socket.shutdown() in the Packet.close() method, but this did not help.

I find it quite odd that Transport itself always runs another thread, so it should not matter which thread calls the Transport.stop_thread() method...

**Comment by rustyscottweber** [comment]
+1 for this problem. Attempting some debugging but it would appear totally blocked on the read from the socket which never returns.

**Comment by zodiacsmash** [comment]
>"...the **main difference** between running FUSE as a daemon and in the foreground is that the construction and destruction happens in different threads ..."

Doesn't FUSE **fork()** a new process when 'foreground=False' ?

**Comment by GMTA** [comment]
@zodiacsmash That could very well be; it's been more than a year ago since I looked at this issue.

The only thing I know for sure is that I got equivalent thread IDs for foreground=True and different thread IDs for foreground=False. I'm not sure it's relevant here.

**Comment by bitprophet** [comment]
Let's roll this into #520.
