### ISSUE TITLE
No getsockname for direct-tcpip channel

### ISSUE THREAD

**Issue by zachriggle** [paramiko/paramiko#383]
If I open a `direct-tcpip` connection, there's no way to get the 'local' side of the connection.

Specifically, if I do this:

```python
transport.open_channel('direct-tcpip', (host, port), ('127.0.0.1', 0))
```
I want to be able to tell both tuples.  I can only get the `(host,port)` tuple via `getpeername()`.  There's no way for me to get the other half of the connection's information (i.e., `getsockname()`).  I can get `channel.get_transport().sock.getsockname()`, but that's the main connection to the SSH server.

**Comment by pkittenis** [comment]
The 'local' side is under your control, it being local and everything :)

The tuple `('127.0.0.1', 0)` is an instruction to bind to a new socket on a free, random, port >1024.

You can control which port (and ip) the local side is bound to by doing an explicit socket bind followed by a call to getsockname on the bound socket. For example:

```
import socket
def make_socket(listen_ip):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind((listen_ip, 0))

sock = make_socket('127.0.0.1')
local_listen_ip, local_listen_port = sock.getsockname()
transport.open_channel('direct-tcpip', (host, port), (local_listen_ip, local_listen_port))
```

**Comment by zachriggle** [comment]
Correct, Paramiko should be able to determine which port is assigned, when
requesting Port 0.

**Comment by bitprophet** [comment]
First, @pkittenis is right that one argument here is "if you care about the port, you can always explicitly define it".

Second, I'm not actually sure if what you're asking makes sense, my reading of [the RFC](https://tools.ietf.org/html/rfc4254#section-7.2) and the Paramiko implementation (which simply throws the contents of that 2nd tuple down the pipe as a network message) implies that the only info we can realistically obtain on the truly local end, is the local socket we've opened to talk to the gateway - which is what shows up when you do `Transport.sock.getsockname()`.

The "local socket" *on the gateway* (i.e. its own "local" socket in its connection to the final remote destination) doesn't seem to be provided back to the original client (Paramiko).

That said, I'm the maintainer but not original author & my knowledge of the protocol & networking bits isn't perfect. If you know more specifically that this information *is* available to SSH clients making a direct-tcpip gateway, then I'm certainly open to figuring out how to expose it in Paramiko's `Transport` or `Channel` class as appropriate.

**Comment by zachriggle** [comment]
It must be do-able since it's available from the default ssh client.

```
$ ssh -N -R 0:localhost:22 user@host
Allocated port 50527 for remote forward to localhost:22
```

**Comment by bitprophet** [comment]
Neat. Well, somebody needs to poke at how OpenSSH does it and figure out how we can do that on our end. I've already spent more time on this today than I probably should've (so many tickets :crying_cat_face:) but again I'm open to adding this if somebody can submit a patch for it.

**Comment by zachriggle** [comment]
Here's the relevant code in Dropbear:

https://github.com/mkj/dropbear/blob/master/cli-tcpfwd.c#L164-L170

For OpenSSH, here's the relevant structure, and all of the related code.

https://github.com/openssh/openssh-portable/blob/426117b2e965e43f47015942b5be8dd88fe74b88/misc.h#L18-L28
https://github.com/openssh/openssh-portable/search?utf8=%E2%9C%93&q=allocated_port&type=Code

**Comment by lndbrg** [comment]
Isn't this what we are doing here in the tests?
https://github.com/paramiko/paramiko/blob/681f32583fe052c0516a2fda67e163169676ad11/tests/test_transport.py#L508

**Comment by zachriggle** [comment]
Ah, yes that's what you're doing.  I was mistaken about the intent of my
original issue (reported back in August, I'd forgotten).

The example I cited, and the code you referred to, are both for forwarded
ports.

I was indeed looking for information on the remote socket pair when
creating remote connections, as opposed to listening remotely.

I cannot find any information that suggests that this is possible.

Please feel free to close the ticket.

**Comment by bitprophet** [comment]
Sorry for the confusion, @zachriggle! Glad it got figured out.
