### ISSUE TITLE
Unable to use nmap in command line from remote machine.

### ISSUE THREAD

**Issue by lokeshksymantec** [paramiko/paramiko#430]
steps for reproducibility:
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('remote_ip_address','username','password')
re_ssh=ssh.invoke_shell()
re_ssh.exec_command("nmap host_ip")

Facing error  - channel closed. Please help in rectifying this issue

**Comment by dtrodrigues** [comment]
if you leave out the `ssh.invoke_shell()` and instead run `ssh.exec_command("nmap host_ip")` it seems to work.

**Comment by lokeshksymantec** [comment]
Thanks   dtrodrigues !
