### ISSUE TITLE
channel.py cannot detect correct exit from OpenVMS.

### ISSUE THREAD

**Issue by schizo99** [paramiko/paramiko#434]
OpenVMS is not following the SSH standard. I've opened a request with HP to have it corrrected for the SSHD but I imagine it will take quite a while.

The error is this as seen in Fabric.

Fatal error: run() received nonzero return code -1 while executing!

To fix this I have added the following to the _handle_request(self, m) function.

        elif key == 'exit-signal':
            if repr(m.get_int()):
                self.exit_status = int(0)
            else:
                self.exit_status = m.get_int()
            self.status_event.set()
            ok = True

**Comment by geromueller** [comment]
Hello,

this is a serous bug, it would be great if could add those lines.

Thanks

**Comment by bitprophet** [comment]
@geromueller can you provide specific details in your case (esp how to reproduce - I do have debian systems I can try on)? I'd be surprised if Debian's openssh install is not following the SSH standard re: original description, so wondering if you have a separate issue. thanks!

**Comment by geromueller** [comment]
Open a connection to a debian wheezy (old stable) system, call a long running command (e.g. python), then kill the remote python process with SIGTERM.

**Comment by nolar** [comment]
The sample code to reproduce the issue & logs & details are in #598

**Comment by bitprophet** [comment]
Sweet, thanks @nolar. Going to compress these two now that the problem is clearer. will continue discussion in #598 as it's more generically targeted.
