### ISSUE TITLE
set_missing_host_key_policy crashes

### ISSUE THREAD

**Issue by bortzmeyer** [paramiko/paramiko#45]
I tried to use the example in the code samples, to deal with unknown hosts:

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.WarningPolicy)
client.connect("192.168.2.26")

But it fails:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pymodules/python2.6/paramiko/client.py", line 311, in connect
    self._policy.missing_host_key(self, server_hostkey_name, server_key)
TypeError: unbound method missing_host_key() must be called with WarningPolicy instance as first argument (got SSHClient instance instead)

This is on Debian "squeeze", the stable version.

Python 2.6.6 (r266:84292, Dec 27 2010, 00:02:40) 
[GCC 4.4.5] on linux2

Paramiko  1.7.6

**Comment by danackerson** [comment]
Would be great if the docs would be updated with this info (http://docs.paramiko.org/en/1.16/api/client.html) as this also tripped me up.

**Comment by bitprophet** [comment]
@danackerson: fair. Just took a stab at clarifying the docstring, see above. Thanks!

**Comment by virendra-09** [comment]
I am getting error while executing the below script 

import sys
import time
import paramiko
import os
import cmd
import datetime

###set date and time
now = datetime.datetime.now()

###authentication
USER = 'cisco'
PASSWORD = 'cisco'
secret = 'cisco'

###start FOR ...in
f = open('cisco_routerswitch.txt')
for ip in f.readlines():
        ip = ip.strip()
        ###prefix files for backup
        filename_prefix ='switches_backup' + ip

        ###session start
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(ip, port, username=USER, password=PASSWORD,look_for_keys=False)

        ###ssh shell
        chan = client.invoke_shell()
        time.sleep(2)
        ###enter enable secret
        chan.send('en\n')
        chan.send(secret +'\n')
        time.sleep(1)
        ###terminal lenght for no paging
        chan.send('term len 0\n')
        time.sleep(1)
        ###show config and write output
        chan.send('sh run\n')
        time.sleep(30)
        output = chan.recv(999999)
        ###show output config and write file with prefix, date and time
        print (output)
        ###filename in format (filename_prefix,now.day,now.month,now.year,now.hour,now.minute,now.second)
        filename = "%s_%.2i%.2i%i_%.2i%.2i%.2i" % (filename_prefix,now.year,now.month,now.day,now.hour,now.minute,now.second)
        ff = open(filename, 'a')
        ###ff.write(output)
        ff.write(output.decode("utf-8") )
        ff.close()
        ###close ssh session
        client.close()

        print (ip)
        f.close()



]$ python backup_cisco_routerswitch.py
Traceback (most recent call last):
  File "backup_cisco_routerswitch.py", line 28, in <module>
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
TypeError: unbound method set_missing_host_key_policy() must be called with SSHClient instance as first argument (got AutoAddPolicy instance instead)
