### ISSUE TITLE
shutdown_write() doesn't send EOF if using pty?

### ISSUE THREAD

**Issue by remram44** [paramiko/paramiko#451]
The following snippet works with `REQUEST_PTY=False` (remote python gets the EOF, executes the script and finishes with 0) but not `REQUEST_PTY=True` (remote python doesn't finish, `recv_exit_status()` hangs).

Is there a way to send EOF when using `get_pty()`?

``` python
import paramiko
import time

REQUEST_PTY = False

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.WarningPolicy())
ssh.connect(HOST, PORT, username=USER, password=PASSWD)
chan = ssh.get_transport().open_session()
if REQUEST_PTY:
    chan.get_pty()
chan.exec_command('python')
chan.send('print "a"\n')
chan.shutdown_write()

time.sleep(1)
print(repr(chan.recv(1024)))
print(chan.recv_exit_status())
ssh.close()
```

**Comment by banjaxedben** [comment]
Can you clarify the solution here?

When I run the script with REQUEST_PTY = False, I get
'a\n'
0

When I run the script with REQUEST_PTY = True, I get
'print "a"\r\n'
-1

If I insert the line
chan.send(b'\x04')
before the chan.shutdown_write() command, I don't see any difference.

**Comment by remram44** [comment]
You have to call chan.recv() a bit more than what is shown in my original code, but it does work :)

```python
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.WarningPolicy())
ssh.connect(HOST, PORT, username=USER, password=PASSWD)
chan = ssh.get_transport().open_session()
chan.get_pty()
chan.exec_command('python')
time.sleep(1)
print(repr(chan.recv(1024)))
chan.send('print "a"\n')
time.sleep(1)
print(repr(chan.recv(1024)))
chan.send(b'\x04')
chan.shutdown_write()

time.sleep(1)
print(repr(chan.recv(1024)))
print(chan.recv_exit_status())
ssh.close()
```

**Comment by banjaxedben** [comment]
OK, the script finishes now, but
- why does it depend on chan.recv() ?
- why is the exit code -1 ?

**Comment by remram44** [comment]
I get 0 as exit code on my machine. I have no idea why recv() is needed.
