### ISSUE TITLE
import issues with paramiko on mac and windows

### ISSUE THREAD

**Issue by Arjun-Kiran** [paramiko/paramiko#460]
I installed paramiko and crypto on my mac, it said it successfully installed but when I try to import the libraries through the interpreter I get the following error. (running python 2.7.6) ( I see the same error on my windows machine also. 

Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import paramiko
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/paramiko/**init**.py", line 30, in <module>
> > >     from paramiko.transport import SecurityOptions, Transport
> > >   File "/Library/Python/2.7/site-packages/paramiko/transport.py", line 49, in <module>
> > >     from paramiko.dsskey import DSSKey
> > >   File "/Library/Python/2.7/site-packages/paramiko/dsskey.py", line 26, in <module>
> > >     from Crypto.PublicKey import DSA
> > > ImportError: No module named Crypto.PublicKey

**Comment by Arjun-Kiran** [comment]
My bad, I installed pycrypto. but you import the module by writing "import crypto" ?

**Comment by kundansharmaindia** [comment]
@Arjun-Kiran I also faced the same problem and resolved it by installing paramiko on current directory path,where your other modules are placed.

**Comment by kundansharmaindia** [comment]
Sorry @Arjun-Kiran I'm late to answer, Hope you would have solved your problem
