### ISSUE TITLE
NameError: global name 'descriptor' is not defined

### ISSUE THREAD

**Issue by liminspace** [paramiko/paramiko#461]
There is error if use in windows.
File _winapi.py:220

    @descriptor.setter
    def descriptor(self, value):
        self._descriptor = descriptor
        self.lpSecurityDescriptor = ctypes.addressof(descriptor)

Maybe must be so:

    @descriptor.setter
    def descriptor(self, value):
        self._descriptor = value
        self.lpSecurityDescriptor = ctypes.addressof(value)

**Comment by ThiefMaster** [comment]
Yeah, Pageant is a windows-only thinf.

**Comment by liminspace** [comment]
Why this discussion, if there is an elementary error in the code that can be corrected in 5 seconds?

**Comment by hobbsd** [comment]
+1

**Comment by sanseihappa** [comment]
+1

**Comment by sorami** [comment]
+1

**Comment by perryjrandall** [comment]
@liminspace because talk is cheap XD

**Comment by mikedep333** [comment]
+1
@ThiefMaster's fix works fine

**Comment by bitprophet** [comment]
Merging this with #469
