### ISSUE TITLE
Missing sha256 algorithms results in some incompatibility

### ISSUE THREAD

**Issue by klaussfreire** [paramiko/paramiko#474]
Hardened server configurations that forbit sha1 in sshd_config are unreachable by paramiko since it doesn't implement the sha256 variants of kex and hmac algoritms, namely:

* diffie-hellman-group-exchange-sha256
* hmac-sha2-256

It doesn't seem that implementing them would be hard given sha256 is in hashlib (sha512 could also be implemented for good measure in hmac-sha2-512)

**Comment by Akendo** [comment]
Hello klaussfeiere this is a duplicated. There is a open Merge Request for this regards in #356 
Hope this help you!

so far
Akendo
