### ISSUE TITLE
Installing Paramiko for Python in Wine

### ISSUE THREAD

**Issue by ChrisTruncer** [paramiko/paramiko#481]
Hi there,

Just wanted to offer this bug (and solution) in case it helps you guys out.  I'm trying to install paramiko for python to run under wine (specifically, I am running it on Kali Linux).  When trying to install it via cloning the repo and installing that way, I get the following error:

wine python.exe /root/.wine/drive_c/Python27/paramiko/setup.py install
Traceback (most recent call last):
  File "/root/.wine/drive_c/Python27/paramiko/setup.py", line 59, in <module>
    with open('paramiko/_version.py') as fp:
IOError: [Errno 2] No such file or directory: 'paramiko/_version.py'

However, this is easily fixed by copying the _version.py file from within paramiko/paramiko and placing it within the root of the paramiko folder.  I also had to create a "__init__.py" file within the root of the paramiko folder.  Once I did that, it installed paramiko in wine without any issues and everything works great.

It's very possible that I could have done something incorrect, but I wanted to offer this up to you guys in case this helps you or anyone else.  This is mostly informational, not really an issue, so feel free to close if you would like to.

**Comment by bitprophet** [comment]
Thanks for the report. 99% of the time, install methods execute from the root of the unpacked sdist, but I think this is a case where that wasn't done - we should probably do an `os.abspath` or similar.

If you are able to change so your current working directory is the Paramiko source distribution, then running `wine python.exe setup.py install` will probably work as-is.
