### ISSUE TITLE
__str__ return type in Python 3

### ISSUE THREAD

**Issue by adamkerz** [paramiko/paramiko#484]
Code exists in various classes (eg. PKey implementations) like so:

```
def __str__(self):
    return self.asbytes()
```

But Python3.4 errors on calling str(obj):

```
TypeError: __str__ returned non-string (type bytes)
```

Guess that means that the `__str__` method isn't actually being called because in py3 it would error. Might be being used by third party code in py2 though. Better return type might be either base 64 encoding, or just returning `repr(self.asbytes())`.

Minor issue anyway as it's probably not being used anywhere.

**Comment by bitprophet** [comment]
Feels like these methods should probably get updated to use some other magic from the py3compat module, yea. Forget what offhand as it's been a while since I had py2+3 porting knowledge cached in my head. Thanks for the note! Labeling for later followup.

**Comment by bitprophet** [comment]
Rolling into #853 as it's got more chatter. Will credit in changelog.
