### ISSUE TITLE
support for PROTOCOL.certkeys

### ISSUE THREAD

**Issue by alonz** [paramiko/paramiko#485]
please add support for certifaction based authentication as described in [PROTOCOL.certkeys] (http://www.opensource.apple.com/source/OpenSSH/OpenSSH-175/openssh/PROTOCOL.certkeys)

**Comment by alonz** [comment]
support for RAS certificates was added in #531 closing

**Comment by mjkoo** [comment]
It looks like #531 wasn't ever merged and this wasn't fully addressed.
