### ISSUE TITLE
Transfer fails at 1GB: rekey window too small, hard-coded

### ISSUE THREAD

**Issue by chrisegner** [paramiko/paramiko#49]
First off, thanks for the great work with paramiko.

At 1GB of data transferred over sftp, paramiko initiates a ssh rekey request and then sets a limit on the number of packets exchanged before the remote side answers the rekey request.  This limit is hard-coded to 20.  If you have fat, long pipes, it's pretty easy to consistently exceed this threshold.  As a consequence in this context, paramiko is not able to transfer files larger than 1GB in size.  OpenSSH does not exhibit this behavior.  I manually patched the source to change the 20 to something that was more reasonable based on our RTT and bandwidth.  The exceptions immediately went away.

- What does openssh do in this situation?
- If doing what openssh does in not suitable or convenient, can this be made a configurable parameter, accessible from the higher-level API (ie SSHClient)?

**Comment by simon-online** [comment]
Is this still an issue with the latest release v1.15.2?

**Comment by bitprophet** [comment]
Given the age, it's at least a little likely, @simon-online - though I know there are still outstanding issues re: "large" file transfers (also with their own PRs, though...). Not sure if same or different.

Overall, we really need a thorough cleaning of the ticket queue (even if it is simply "close anything w/o activity in the last year" on the assumption that critical issues will get re-upped). Something I hope to find time for in the mid term.

**Comment by simon-online** [comment]
For what it's worth I can confirm that I was regularly having this issue with v1.7.7.1 but since I updated to v1.15.2 over a month ago this issue has stopped.

**Comment by bitprophet** [comment]
Thanks a lot for double checking, @simon-online!

**Comment by fthiery** [comment]
For what it's worth, i'm on 2.12.0 and the problem is (still?) present. The workaround provided here https://github.com/paramiko/paramiko/issues/151#issuecomment-508493434 worked wonders for me.

**Comment by bskinn** [comment]
If you're still observing this problem, @fthiery, then likely your root cause is different from that discussed in this ticket, at least to some degree.

Please test also on the most recent 3.x release, and if you're seeing the problem there open a new ticket to report as such. Thanks!
