### ISSUE TITLE
Handling broken entries in known_hosts

### ISSUE THREAD

**Issue by martintopholm** [paramiko/paramiko#490]
When broken entries exists in known_hosts, paramiko raises SSHException 
with "Invalid key".

    echo "example.net ssh-rsa AAAA" >>known_hosts
    python2
    >>> import paramiko
    >>> hostkeys = paramiko.HostKeys()
    >>> hostkeys.load('known_hosts')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/mph/.local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 99, in load
        e = HostKeyEntry.from_line(line, lineno)
      File "/home/mph/.local/lib/python2.7/site-packages/paramiko/hostkeys.py", line 327, in from_line
        key = RSAKey(data=decodebytes(key))
      File "/home/mph/.local/lib/python2.7/site-packages/paramiko/rsakey.py", line 65, in __init__
        raise SSHException('Invalid key')
    paramiko.ssh_exception.SSHException: Invalid key

It would be nice if paramiko would ignore unparsable lines in known_hosts 
or provide the file and line in the error message.

**Comment by bitprophet** [comment]
Fair point. Also, OpenSSH's implementation certainly doesn't seem to be as picky, and we generally use them as a guide for behavior. I'd merge a PR that implements this.

**Comment by martintopholm** [comment]
On Fri, 27 Feb 2015, Jeff Forcier wrote:
> [...] EDIT: should also see if any have been submitted previously first...

Related pull requests include #404 (Add informative BadHostKeyException).
