### ISSUE TITLE
Access violation in _winapi.py

### ISSUE THREAD

**Issue by taumeson** [paramiko/paramiko#498]
I'm running MySQL Workbench on Windows 8.1 and had to upgrade paramiko as part of a suggested bug fix on the MySQL bug tracker involving having pageant running at the same time (http://bugs.mysql.com/bug.php?id=76168). This was done successfully but I'm now receiving an access violation:

`ERR [20150310-15:49:00.816] thr=1   paramiko.transport:   File "C:\Program Files\MySQL\MySQL Workbench 6.2 CE/python/site-packages\paramiko\_winapi.py", line 150, in read`
`ERR [20150310-15:49:00.816] thr=1   paramiko.transport:     ctypes.windll.kernel32.RtlMoveMemory(out, self.view + self.pos, n)`
`ERR [20150310-15:49:00.818] thr=1   paramiko.transport: WindowsError: exception: access violation reading 0x00007FFE258A0000`

Here is the gist of the full traceback:
https://gist.github.com/taumeson/8853980184673ba88188

I'm running Windows 8.1 x64, and I know that Windows is a secondary concern. Hopefully it's something obvious but I am out of my element.

**Comment by thorstenkampe** [comment]
Same issue here (trying a simple `dir`):
```
 ctypes.windll.kernel32.RtlMoveMemory(out, self.view + self.pos, n)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
```
Issue occurs with Python 3.4.3 64bit Python 2.7.9 32bit on same machine is fine. Python3 issue or 64-bit issue?

**Comment by thorstenkampe** [comment]
The issue only occurs in Python3 64-bit, neither in Python 32-bit/64-bit nor in Python3 32-bit

**Comment by jaraco** [comment]
In back-porting #193 to [jaraco.windows](https://bitbucket.org/jaraco/jaraco.windows), the unit tests uncovered this bug as well. [The fix](https://bitbucket.org/jaraco/jaraco.windows/commits/76e7694c572e6fcf4cbf8141343028860ce6ebd3) has been released in jaraco.windows 3.3.

**Comment by bitprophet** [comment]
Rolling into #525, thanks @jaraco
