### ISSUE TITLE
Support for modern ciphers

### ISSUE THREAD

**Issue by fmarier** [paramiko/paramiko#509]
If I set the following in my `/etc/ssh/sshd_config` (as [recommended by Mozilla](https://wiki.mozilla.org/Security/Guidelines/OpenSSH#Modern_.28OpenSSH_6.7.2B.29)):

    KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
    Ciphers chacha20-poly1305@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

I get an `Incompatible ssh peer` exception (paramiko 1.15.1):

    Exception: Incompatible ssh peer (no acceptable kex algorithm)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1612, in run
        self._handler_table[ptype](self, m)
      File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1692, in _negotiate_keys
        self._parse_kex_init(m)
      File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1807, in _parse_kex_init
        raise SSHException('Incompatible ssh peer (no acceptable kex algorithm)')
    SSHException: Incompatible ssh peer (no acceptable kex algorithm)

and I see this in my `/var/log/auth.log`:

    sshd[30206]: fatal: no matching mac found: client hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96 server hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com [preauth]

In order to make it work, I had to:

* add `diffie-hellman-group-exchange-sha1` to `KexAlgorithms`
* add `hmac-sha1` to `MACs`

but I would really like to get rid of SHA-1 if possible.

**Comment by cyphase** [comment]
This is waiting in pull request #356; I need diffie-hellman-group-exchange-sha256 myself.

**Comment by bitprophet** [comment]
Closing as duplicate.
