### ISSUE TITLE
Document AgentRequestHandler

### ISSUE THREAD

**Issue by toejough** [paramiko/paramiko#516]
As far as I can tell, to do proper ssh-agent forwarding, you need to use the `paramiko.agent.AgentRequestHandler` API.  Also as far as I can tell, it's not documented.

I checked [Paramiko's docs](http://docs.paramiko.org/en/1.15/api/agent.html), but could not figure out how to do ssh-agent forwarding.  I ended up finding out how by reading pull requests/bugs for ssh-agent forwarding features in frameworks that use Paramiko under the covers, like [fabric](https://github.com/paramiko/paramiko/issues/399) and [ansible](https://github.com/ansible/ansible/pull/4100/files).

I wrote a [gist](https://gist.github.com/toejough/436540622530c35404e6) about what I found and how I use the API.  

This API should be documented.

**Comment by bitprophet** [comment]
Thanks for this! Will review & append when I get to the next bugfix milestone.

**Comment by July-NetEase** [comment]
I used paramikio as a ssh server，but sth really made me soconfused, who can help me.

when user log onto the jumpserver and ssh to the remote server.  sth is wrong
1、ssh.connect()
I found _agent.get_keys() is empty  though allow_agent is true
how can i got the agent keys

2、whether I can turn on the SSH agent forwarding use paramiko as the OpenSSH does
