### ISSUE TITLE
Keytype negotiation should considered available keys

### ISSUE THREAD

**Issue by nmoehrle** [paramiko/paramiko#517]
paramiko.transport.Transport uses the first common key
```1820: self.host_key_type = agreed_keys[0]```
if known_hosts has been loaded previously e.g.
```
client = SSHClient()
client.load_system_host_keys()
```
it would be nice to consider the available keys while choosing the host_key_type.

Right now I did not see a clean way to use the available key, I used:
```paramiko.transport.Transport._preferred_keys = ('ecdsa-sha2-nistp256',)```
which allows me to connect to my clients using the SSHClient.

**Comment by bitprophet** [comment]
This is a known issue, please see #387 and its related tickets/labels.
