### ISSUE TITLE
client.exec_command will take an entire ssh session from ssh server..

### ISSUE THREAD

**Issue by rustyscottweber** [paramiko/paramiko#528]
on some linux builds.. the following code will take an entire ssh session for each command executed using the exec_command from client.py.

<pre>
<code>
hostname = 'test_host.com'
username = 'test_user'
password = 'test_password'

import paramiko
pclient = paramiko.SSHClient()
pclient.load_system_host_keys()
pclient.set_missing_host_key_policy(paramiko.AutoAddPolicy())

pclient.connect(hostname=hostname,
                port=22,
                username=username,
                password=password,
                look_for_keys=True,
                timeout=10)
pclient.get_transport().set_keepalive(10)
for i in xrange(10000):
    pstdin, pstdout, pstderr = pclient.exec_command('sleep 120 ; echo %s' % (str(i)))
    print i
print 'all commmands were ran.'
</code>
</pre>

The code will eventually raise an exception
paramiko.ssh_exception.ChannelException: (1, 'Administratively prohibited')
when the ssh server runs out of sessions allotments.

**Comment by rustyscottweber** [comment]
This is endemic to how ssh works.  Every command executed by a connection takes up a session.. This can be worked around by running a shell and then using that shell to spawn other background commands.

**Comment by jabbas** [comment]
Is there native-paramiko way to limit number of opened channels then? Or some channel queuing?

**Comment by rustyscottweber** [comment]
Unfortunately, there is not a way internal to paramiko which ensures that you will not run into this maximum.  However, there might be a way to find out what the maximum is and less likely, the number of processes in use.  However, it would be up to you to know what channels are still open and when not to open new ones.  An alternative is to change the sshd.conf file to accept a much higher number of connections.  However, this is a security risk which I don't suggest in any active production deployment.

**Comment by jabbas** [comment]
As far as I understand the code Transport knows that, so there is a possibility to do that i think :)
