### ISSUE TITLE
weakdh.org: Doesn't work with "KexAlgorithms curve25519-sha256@libssh.org"

### ISSUE THREAD

**Issue by rata** [paramiko/paramiko#532]
As suggested here: https://weakdh.org/sysadmin.html on the new weakdh.org attack site, one solution is to use:

```
KexAlgorithms curve25519-sha256@libssh.org
```

On the sshd_config of the server. So that lines restricts the KexAlgorithms to just that one. But that makes paramiko unable to connect.

It throws this error:

```
No handlers could be found for logger "paramiko.transport"

Fatal error: Incompatible ssh peer (no acceptable kex algorithm)

Underlying exception:
    Incompatible ssh peer (no acceptable kex algorithm)
```

I'm using paramiko==1.15.2 (the last release). Can you please consider fixing this ?

**Comment by bitprophet** [comment]
See #256 :) thanks!

**Comment by rata** [comment]
Sorry @bitprophet, but I don't follow. That seems to be a pull req just changing to Sphinx.

Did you mean some other pull req ? If that is the case, can I know which one and when it will be included in a release ? :)

**Comment by bitprophet** [comment]
@rata - yea, that was a typo (probably induced by the fact that the topic involves "256"), I meant #356.

**Comment by rata** [comment]
Cool, thanks. But @bitprophet do you know when a new release that I can use with curve25519-sha256@libssh.org will be available ?

As I said, this is kind of important because of what weakdh.org site says

**Comment by rata** [comment]
@bitprophet can you pelase re-open as this doesn't seem to be fixed with pull req https://github.com/paramiko/paramiko/pull/356 (as https://github.com/gertvdijk commented) ?

**Comment by rata** [comment]
Thanks! The issue is as easy to reproduce as I originally reported. Let me know if I can help testing or something.



Thanks again!
Rodrigo

**Comment by bitprophet** [comment]
Will do, and thanks a lot for your input! I'll be tearing through all these key related issues in the near future.

**Comment by rata** [comment]
Thanks a lot! Let me know if I can help you testing or something!

**Comment by iandennismiller** [comment]
The weakdh.org recommendations ultimately brought me here.

There is a temporary fix that permits Paramiko to function without curve 25519.  This is essentially described at https://weakdh.org/sysadmin.html#openssh although it is not obvious how to apply it to the Paramiko situation.  I have clarified the instructions for Paramiko users:

### Generate fresh 2048-bit modulii

Assuming your sshd configuration is in /etc/ssh, the following would overwrite the weak moduli that ship with openssh by default.

```
ssh-keygen -G /etc/ssh/moduli-2048.candidates -b 2048
ssh-keygen -T /etc/ssh/moduli -f /etc/ssh/moduli-2048.candidates
```

### Set the available sshd key exchange algorithms:

In /etc/ssh/sshd_config, specify the available algorithms to include a non-elliptic-curve algorithm.

```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group14-sha1
```

This provides a fallback algorithm that Paramiko can use that will at least make use of the fresh 2048-bit modulii we generated, thereby mitigating weakdh (according to weakdh.org recommendations).

Of course, the solution for Paramiko is still to merge code that supports curve 25519...  I have to confess I haven't tried to solve this, so I know I've got no standing to complain.  I hope this temporary fix helps in the meanwhile.

**Comment by enmanuel17** [comment]
Hello @bitprophet ,

Thanks for maintaining paramiko. Do you know if there is any traction/implementing for curve25519-sha256@libssh.org

**Comment by miniCruzer** [comment]
+1

As an added bonus, with support for this KEx and the other OpenSSH builtin MACs and Ciphers, you can build OpenSSH without OpenSSL/LibreSSL.

**Comment by bitprophet** [comment]
Closing this in lieu of the kex implementations liked above.
