### ISSUE TITLE
ssh keys with a passphrase are considered invalid

### ISSUE THREAD

**Issue by Bert-Tijskens** [paramiko/paramiko#533]
this code fails when the key has a passphrase. an exception is raised telling the key is not a valid key

import paramiko

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

hostname = 'login.XXX.XXXXXX.XX'
username = 'xxxXXXXX'
key = '/Users/xxxxxxxxx/id_rsa'
ssh.connect(hostname=hostname, username=username, key_filename=key)

stdin, stdout, stderr = ssh.exec_command('ls -l')
out = stdout.readlines()
err = stderr.readlines()
print out
print err
print 1

**Comment by lndbrg** [comment]
@Bert-Tijskens if you want to use a password protected key you either need to add the `password` parameter to connect or use a ssh-agent.
