### ISSUE TITLE
pycrypto dependencies are a pain on OSX

### ISSUE THREAD

**Issue by axfelix** [paramiko/paramiko#542]
Hi folks,

I'm trying to deploy a paramiko app on OSX, but pycrypto stuff is making it a little more difficult than necessary. Specifically, it comes with an xcode requirement and it's the only part of the app that does, and worse, the pip formula for pycrypto seems to fail on certain xcode/clang versions: https://github.com/paramiko/paramiko/issues/283

Any way of getting this hopefully fixed upstream? pycrypto doesn't seem to be on github. Thanks!

**Comment by bitprophet** [comment]
Whoops, didn't see this before I commented on #283, please see my latest note there, thanks :)

**Comment by axfelix** [comment]
Aha -- thanks!
