### ISSUE TITLE
Paramiko based SSH automation, need help

### ISSUE THREAD

**Issue by arizzubair** [paramiko/paramiko#551]
Hi All experts here,
I need some help in automating SSH operations using paramiko.
I want two things:
1. Capture user's input and output in a text file.
2. Replay user's input and match the new output with previous output.

I have been trying to do this but I have not been successful so far.
Any suggestions about how to do this.

**Comment by bitprophet** [comment]
Please try [the mailing list](http://www.paramiko.org/contact.html) or e.g. StackOverflow, the bug tracker isn't suitable for a mailing list. thanks!
