### ISSUE TITLE
Client close doesn't close the client's socket

### ISSUE THREAD

**Issue by DerpDarako** [paramiko/paramiko#552]
Hello,

It seems  there is a bug in your transport.py. In deed, when I use client.close(), your code calls transport.close(), ending all channels and you should close the server socket... But, despite that socket.close() all sockets are not close on my server if I use netstat -an, I see all paramiko connections in TIME_WAIT status.

I stay at your disposal if you need more information.

**Comment by LozickyAlexey** [comment]
Isn't it correct behavior for sockets - http://superuser.com/questions/173535/what-are-close-wait-and-time-wait-states ?

**Comment by DerpDarako** [comment]
It seems you right, hm. all my apologies. :X
