### ISSUE TITLE
exec_command get the output stream continuously

### ISSUE THREAD

**Issue by Gon3s** [paramiko/paramiko#555]
Hi,

I dry on a Python script. I create a python script for a given IP will connect via Paramiko to a server to execute another Python script.

Here is some code:

```python
self._client = paramiko.SSHClient()
self._client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
self._client.connect(self._ip, username=self._server['username'], password=self._server['password'])
channel = self._client.get_transport().open_session()
channel.exec_command('python3 /tmp/scrap.py /tmp/' + self._ip + '.txt 0 1')
```

The script "scrap.py" returns every X seconds a line in the console of the remote machine, but I can not recover as and when these lines in the script above (at the exit of exec_command (. ..)).

Is this possible, and if so have you any idea how?

Thank you in advance.

**Comment by bitprophet** [comment]
Check out the source for Fabric as an example of how this sort of thing can work (or just use it - it wraps Paramiko!) - e.g. https://github.com/fabric/fabric/blob/master/fabric/operations.py#L721

**Comment by peterromfeldhk** [comment]
@bitprophet link does not work anymore, and fabric does not have this file anymore

**Comment by ploxiln** [comment]
https://github.com/fabric/fabric/blob/1.14/fabric/operations.py#L721
