### ISSUE TITLE
Proposal to make _convert_status IOError value more meaningful

### ISSUE THREAD

**Issue by chorsley** [paramiko/paramiko#566]
I've been having issues with paramiko's SFTPClient module intermittantly failing to transfer a file on receiving an EINTR signal during a put operation. After I've called put(), the only thing raised is IOError("Failure"), which makes it difficult to see exactly what happened, and if it's something I can / should retry.

In `paramiko.sftp_client.SFTPClient._convert_status()`, I had been thinking about a couple of options, first narrowly for EINTR:

```
...
elif code == SFTP_PERMISSION_DENIED:
    raise IOError(errno.EACCES, text)
elif code == errno.EINTR:
    raise IOError(code, text)
else:
    raise IOError(text)
```

or more generally...

```
...
elif code == SFTP_PERMISSION_DENIED:
    raise IOError(errno.EACCES, text)
else:
    raise IOError(code, text)
```

Tests seem to pass with either of these changes, but I'm wondering how many people are relying on the current behaviour. Any suggestions most welcome.

**Comment by bitprophet** [comment]
Feels related to #304 and #321 perhaps (though not duplicative, just related). Thanks for the report / thoughts.

**Comment by jbouse** [comment]
I believe this is related... I'm getting this while working on the Debian package for 1.16.0 currently:

```
======================================================================
ERROR: test_K_utf8 (tests.test_sftp.SFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/paramiko-1.16.0/tests/test_sftp.py", line 171, in tearDown
    sftp.rmdir(FOLDER)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 390, in rmdir
    self._request(CMD_RMDIR, path)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 777, in _read_response
    self._convert_status(msg)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(text)
IOError: Failure

======================================================================
ERROR: test_L_utf8_chdir (tests.test_sftp.SFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/paramiko-1.16.0/tests/test_sftp.py", line 679, in test_L_utf8_chdir
    sftp.mkdir(FOLDER + '/' + unicode_folder)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 380, in mkdir
    self._request(CMD_MKDIR, path, attr)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 777, in _read_response
    self._convert_status(msg)
  File "/tmp/buildd/paramiko-1.16.0/paramiko/sftp_client.py", line 807, in _convert_status
    raise IOError(text)
IOError: Failure

======================================================================
FAIL: test_K_utf8 (tests.test_sftp.SFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/paramiko-1.16.0/tests/test_sftp.py", line 675, in test_K_utf8
    self.fail('exception ' + str(e))
AssertionError: exception Failure

======================================================================
FAIL: test_O_getcwd (tests.test_sftp.SFTPTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/paramiko-1.16.0/tests/test_sftp.py", line 735, in test_O_getcwd
    self.assertEqual(None, sftp.getcwd())
AssertionError: None != u'/'

```

**Comment by CrazyCasta** [comment]
Perhaps the whole thing should be replaced with an "SFTPError" class that inherits from IOError. You would stuff whatever relevant details you want in the SFTP and just call the super __init__ in a similar way as what you do here (if this condition, do this, elif that condition do that, etc). Should be compatible with whatever anyone already has (caught by except IOError blocks) while adding the necessary information. I would caution against raising IOError with errno equal to the SFTP code because these are separate codes. The SFTP codes come from https://filezilla-project.org/specs/draft-ietf-secsh-filexfer-02.txt section 7, whereas errno is either implementation defined or at least a different set of codes.

**Comment by bitprophet** [comment]
Looking at this now, I think this does basically duplicate #321.
