### ISSUE TITLE
OpenSSL can't read protected keys written by paramiko

### ISSUE THREAD

**Issue by radssh** [paramiko/paramiko#569]
See PR #568 

Baffling 'bad decrypt' (or 'load failed' when ssh-keygen uses libssl) even though correct passphrase was being used. Error text masks the fact that the padding check(s) failed, not the block cipher decryption itself.

OSX ssh-keygen apparently does not use the OpenSSL lib, and is happy to read protected keys with zero-byte padding, but reading with `openssl rsa` fails.

```
$ openssl rsa -in /tmp/testkey.protected  -pubout
Enter pass phrase for /tmp/testkey.protected:
unable to load Private Key
15775:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/crypto/evp/evp_enc.c:330:
15775:error:0906A065:PEM routines:PEM_do_header:bad decrypt:/SourceCache/OpenSSL098/OpenSSL098-52.30.1/src/crypto/pem/pem_lib.c:428:
```

**Comment by bitprophet** [comment]
Let's just merge this with the PR. Thanks!
