### ISSUE TITLE
Upgrade GSSAPI support to the 'gssapi' (not 'python-gssapi') module

### ISSUE THREAD

**Issue by metaperture** [paramiko/paramiko#584]
[Maintainer edit: the action required on this ticket is to change Paramiko's GSSAPI functionality to use the API of `gssapi`, vs right now where it uses the API of `python-gssapi`. Then update `setup.py`.]

It looks like paramiko/ssh_gss.py refers to an older version of gssapi. See from https://github.com/paramiko/paramiko/blob/master/paramiko/ssh_gss.py#L253, all the references to gssapi.C_\* fail.

Note that gssapi 0.6.\* has these attributes (https://github.com/sigmaris/python-gssapi/blob/master/gssapi/__init__.py#L6), but the new gssapi (v >= 1.0, https://github.com/pythongssapi/python-gssapi/tree/master/gssapi/raw) doesn't appear to have these flags anywhere I can find.

Specifically, when I call connect in client.py, I get the following:

```
/home/mtartre/.conda/envs/std/lib/python3.4/site-packages/paramiko/ssh_gss.py in __init__(self,     auth_method, gss_deleg_creds)
    251 
    252         if self._gss_deleg_creds:
--> 253             self._gss_flags = (gssapi.C_PROT_READY_FLAG,
    254                                gssapi.C_INTEG_FLAG,
    255                                gssapi.C_MUTUAL_FLAG,

AttributeError: 'module' object has no attribute 'C_PROT_READY_FLAG'
```

I wish I could help fix this, but I'm out of my depth when it comes to C bindings like this. I'd be happy to test any ideas anyone has.

References:
- Issue https://github.com/paramiko/paramiko/issues/82
- Pull https://github.com/paramiko/paramiko/pull/267

**Comment by bitprophet** [comment]
Thanks for the report!

**Comment by linuxluser** [comment]
The [gssapi module](https://github.com/sigmaris/python-gssapi) which paramiko GSSAPI support was built with now states:
> There is a newer project which has superseded this one, https://github.com/pythongssapi/python-gssapi. Please use that package if suitable for your needs, as this project is unlikely to be developed further.

It looks like the dependency that Paramiko's GSSAPI support was built with seems to be deprecated in favor of a new fork of this module with the same name. If you `pip install gssapi` you will get the latest version which is now completely incompatible with what Paramiko currently expects to be using when you `import gssapi`.

Old python-gssapi module: https://github.com/sigmaris/python-gssapi
New python-gssapi module: https://github.com/pythongssapi/python-gssapi

I believe this means that the GSSAPI support in Paramiko will have to be revised. Until then it is referring to a zombified module.

**Comment by bitprophet** [comment]
Swell, and by swell, I mean my forehead is swelling up from hitting my desk. Programming! :( Thanks for looking into that, @linuxluser. I don't remember if our setup.py pins that dependency to a specific version, but that sounds like step 1, with step 2 being porting to the newer, not-unsupported version.

**Comment by bitprophet** [comment]
OK, I'd forgotten that because GSSAPI is an optional feature, we went the "document it and do not add to setup.py" route.

This means there's technically nothing we can do to "pin" to the older iteration of the library; we just need people to make sure they `pip install python-gssapi` and **NOT** `pip install gssapi`.

Which, to be fair, is what our docs say - `python-gssapi` - so anybody doing `pip install gssapi` is technically incorrect. I'm assuming that installing the latest `python-gssapi` (0.6.4) is still functional.

Going to rename this ticket to reflect this.

**Comment by pcharlan** [comment]
> I'm assuming that installing the latest python-gssapi (0.6.4) is still functional.

FYI, attempting to install python-gssapi 0.6.4 using pip3 from Python-3.4.3 on CentOS 6 fails with many dozens of compiler errors and Python tracebacks, so in at least some (common?) environments python-gssapi is unfortunately not still functional.

**Comment by bitprophet** [comment]
#861 implements optional support for *both* GSSAPI third party modules (it uses a simple heuristic to figure out which of the two was imported), so as long as I can get some other folks testing and confirming it's kosher (please note in here) that means this can actually be just another feature release for the 2.x line. Updating milestone.

**Comment by deepeshreja** [comment]
I've tested out the proposed patch and it works as expected.

**Comment by pwilthew** [comment]
The proposed fix works for me! Thank you.

**Comment by bitprophet** [comment]
Closing this in favor of the various PRs that have been opened (latest seems to be #1311). Will still allow conversations here (esp if I'm unable to get to it before yet another PR is opened...sob...but I hope to get to this relatively soon, famous last words notwithstanding).
