### ISSUE TITLE
import paramiko module failed when it is looking Crypto package

### ISSUE THREAD

**Issue by jaehokim00** [paramiko/paramiko#587]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "paramiko/transport.py", line 49, in <module>
    from paramiko.dsskey import DSSKey
  File "paramiko/dsskey.py", line 26, in <module>
    from Crypto.PublicKey import DSA 
ImportError: No module named Crypto.PublicKey  

however pip  pycrypto install created   package name "crypto" so it does not find  correct name for module.. 

once I rename the installed directory to Crypto... 
mv crypto Crypto

it worked fine...   Someone needs to look at it ,,, 
pycrypto-2.6.1 
paramiko-1.15.2

thanks

**Comment by hovissimo** [comment]
I just encountered this problem as well.

**Comment by bitprophet** [comment]
I know I've seen this again recently but can't find it. OTOH, #369 removes pycrypto entirely and is one of our highest priority tickets, so ideally the issue would be moot after 2.0 lands anyway.

If @jaehokim00 and @hovissimo could confirm their Python and OS versions, though, that'd be good too. Thanks!

**Comment by bitprophet** [comment]
Also, pip version!

**Comment by jaehokim00** [comment]
Mine is  OSX 10.10.5  
pip 7.1.2 from /Library/Python/2.6/site-packages (python 2.6)

**Comment by Honor123** [comment]
I faced the same problem in windows 10 python27 and was resolved after installing C++ compiler for python 2.7!

**Comment by mandshaw** [comment]
This is really annoying us as well
Whats the long term fix?

**Comment by alanlun516** [comment]
Mine is CentOS 6.7
pip 7.1.0 from /usr/lib/python2.6/site-packages (python 2.6)

**Comment by eaydin** [comment]
Any updates on this issue?

**Comment by bitprophet** [comment]
* Updating to 2.0+ should completely sidestep whatever bizarre pip/setuptools/Crypto issue is causing this
