### ISSUE TITLE
Daemonizing after importing paramiko breaks the random number generator

### ISSUE THREAD

**Issue by mgeens** [paramiko/paramiko#59]
Hi,

I'm writing a daemon which uses Paramiko to do SFTP transfers. I do the daemonization according to http://code.activestate.com/recipes/278731/ . When I try to connect to the server I get a "Bad file descriptor" exception from the Random.atfork() call in paramiko.transport.start_client.

The cause seems to be that when importing paramiko it creates a random number generator in paramiko.common, which opens a file descriptor to /dev/urandom (I'm on Linux). The daemonization recipe closes all open file descriptors in the child process, so when atfork() is called the /dev/urandom descriptor is not valid anymore.

I'm working around it by importing paramiko after the daemonization.

Is this an issue with Paramiko/PyCrypto or just with my code organisation?

Kind regards,
Raf

**Comment by vaygr** [comment]
This is also the case when you work with GCP in [libcloud](https://libcloud.apache.org/) from inside the daemon: https://github.com/apache/libcloud/blob/8bedf2472401186ca1038719a0cdd66155f833f5/libcloud/common/google.py#L96
