### ISSUE TITLE
[enhancement] context manager for ssh connection

### ISSUE THREAD

**Issue by wkentaro** [paramiko/paramiko#591]
I think context manager for ssh connection is useful.

``` python
with connect_ssh(HOST, LOGIN_USER) as ssh:
        _, stdout, stderr = ssh.exec_command('ls')
```

Any idea about this?

The implementation will be like this:

``` python
from contextlib import contextmanager

import paramiko


def connect_ssh(host, username=None, password=None, load_host_keys=True):
    return _connect_ssh_context(host, username, password, load_host_keys)


@contextmanager
def _connect_ssh_context(host, username, password, load_host_keys=True):
    try:
        ssh = paramiko.SSHClient()
        if load_host_keys:
            ssh.load_host_keys(os.path.expanduser('~/.ssh/known_hosts'))
        ssh.connect(host, username=username, password=password)
        yield ssh
    finally:
        ssh.close()
```

**Comment by aaronlelevier** [comment]
+1

I'd also like to be able to use a context manager, so SSH connections get close automatically when finished. It's easy to forget to call `client.close()`!

**Comment by bitprophet** [comment]
Fabric offers this: http://docs.fabfile.org/en/2.3/api/connection.html

Generally, this kind of high level feature lives in Fabric, not Paramiko, which is intended purely for the low level nuts and bolts. Thanks!
