### ISSUE TITLE
Client connection stays open

### ISSUE THREAD

**Issue by derchrisuk** [paramiko/paramiko#597]
Hi,

not sure if this is really an issue with paramiko. but I post it anyways to get some help troubleshooting this.
Basically I have the following code:

    def ssh(self, ip, username, password):
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.load_system_host_keys()
        client.connect(ip, username=username, password=password)
        scp = SCPClient(client.get_transport())
        scp.put('/root/sninstall', '/root/sninstall')
        scp.close()

        cmd_run = '/root/sninstall ' + self.config['snversion'] + ' ' + self.config['os'].lower() + ' ' + self.config['version'][0]
        stdin, stdout, stderr = client.exec_command(cmd_run)
        for line in stdout:
            print '... ' + line.strip('\n')
        client.close()

And run it like this

    self.ssh(ip, 'root', '****')

Now, the script runs ok on a RHEL6, I see the output of it, and once done client.close() is called, and returns to the script.
However, if I do the same with a RHEL5 system, the script runs, outputs, and finish.
But the client.close() is not being called.

Like as it is waiting for some more of stdout or stderr.
When I check the system, the script is no longer running, and I could not see any open connections.

But still, it is staying there waiting.
Any help much appreciated.

**Comment by StyXman** [comment]
Not sure this is the proper way, but did you try closing `stdin`?

**Comment by derchrisuk** [comment]
How do I close `stdin` ?
Since I couldn't get it to work I'm using a different approach to do the job.
So not sure if and when I would be able to test this again.
