### ISSUE TITLE
incorrect python version when using pyenv on remote system

### ISSUE THREAD

**Issue by actioncrypto** [paramiko/paramiko#601]
paramiko 1.15.3:
When in an SSH and you try to execute a command that is itself a python script, it seems forced into the system default python environment. So, if you use `pyenv` to have modules such as `pandas` installed on a shim, this breaks when you try and do things that are not in the default python system install.

    from paramiko import SSHClient, AutoAddPolicy
    with SSHClient() as ssh:
		ssh.load_system_host_keys()
		ssh.set_missing_host_key_policy(AutoAddPolicy())
		ssh.connect(hostname='x.x.x.x', port=3333, username='root')
		vers = ssh.exec_command('python -V')[2].read()
		print vers

    Python 2.7.6

On this x.x.x.x server, if I log in and run `python -V` manually:

    root@server:~# python -V

    Python 2.7.10

Similarly, if I try to run `pyenv` locally:

    root@server:~# pyenv versions

    system
    * 2.7.10 (set by /root/.python-version)

And the result of trying to access `pyenv` via `paramiko` SSH same as above code:

    bash: pyenv: command not found

So I have no way to access the same environment/modules/packages? what am I missing? I'm logged in to the same user as manual ssh....  Need to access the pyenv environment with the installed packages and run scripts via the SSH connection.... to return results and close connection. 

Any advice?

**Comment by bitprophet** [comment]
This is likely the same class of issue as described here: http://www.fabfile.org/faq.html#my-cd-workon-export-etc-calls-don-t-seem-to-work - the tl;dr is that running commands directly via ssh (this is often the same as running `ssh myhost mycommand`) is not quite the same as actually *logging in* interactively and then running the command.

I don't know exactly how pyenv works but it's probably hooks in users' Bash login files, which are the sorts of things not sourced when commands get run noninteractively.

**Comment by ash22194** [comment]
I am assuming you added commands to setup pyenv in your .bashrc when you installed it. Just source the .bashrc after you ssh and that should take care of it!
