### ISSUE TITLE
TypeError in connection exception handling code in 1.16.0

### ISSUE THREAD

**Issue by nchammas** [paramiko/paramiko#615]
I'm seeing this problem in 1.16.0 but not 1.15.4. I'm running Python 3.5.0 on OS X.

I'm trying to connect to a host as it comes up and am getting this failure:

```
Traceback (most recent call last):
  File "flintrock.py", line 714, in get_ssh_client
    timeout=3)
  File ".../venv/lib/python3.5/site-packages/paramiko/client.py", line 311, in connect
    raise NoValidConnectionsError(errors)
  File ".../venv/lib/python3.5/site-packages/paramiko/ssh_exception.py", line 166, in __init__
    body = ', '.join([x[0] for x in addrs[:-1]])
TypeError: 'dict_keys' object is not subscriptable
```

This error seems to refer to [this line](https://github.com/paramiko/paramiko/blob/2576b16b5439fd3487e498c21203593e10dbee52/paramiko/ssh_exception.py#L166). Looking at the history of `ssh_exception.py` and `client.py`, I'm guessing this problem was introduced as part of [this commit](https://github.com/paramiko/paramiko/commit/956de60d53f0f9ed2f6b583ccefe88162665235c#diff-169e8b6af6ef7bee0bb2c9a6a637aa5f).

I'm willing to track this down and provide a patch if you can give me a pointer. Perhaps [`_families_and_addresses()`](https://github.com/paramiko/paramiko/commit/956de60d53f0f9ed2f6b583ccefe88162665235c#diff-169e8b6af6ef7bee0bb2c9a6a637aa5fR283) is not behaving as expected?

**Comment by edk0** [comment]
I don't have a good way to test this but I believe the bug is on the previous line :) `dict.keys` returns a view not a sequence; addr needs to be `list(errors.keys())`

**Comment by nchammas** [comment]
Oh, you're right.  The traceback even gives it away. :derp:

**Comment by bitprophet** [comment]
Rollin' into the PR, thanks @nchammas / @edk0!
