### ISSUE TITLE
Error on init() for unpickling NoValidConnectionError

### ISSUE THREAD

**Issue by rschlussel** [paramiko/paramiko#617]
If you try pickling and then unpickling NoValidConnectionError, you get the following exception:
`TypeError: __init__() takes exactly 2 arguments (3 given)`

It seems to be passing the errno and string with the error message while init expects a dict.

Here is some simple code to reproduce the issue:

```python
from paramiko import ssh_exception.NoValidConnectionsError
import pickle
err = NoValidConnectionsError({'ab': ''})
p = pickle.dumps(err)
unpickled = pickle.loads(p)
```

A more practical application is for example if you are using the multiprocessing module and a child process raises a NoValidConnectionError.

**Comment by bitprophet** [comment]
Solved in #679.
