### ISSUE TITLE
Python 3 TypeError raised when SSH connection fails

### ISSUE THREAD

**Issue by wsong** [paramiko/paramiko#622]
I occasionally get tracebacks of this sort when attempting to connect to a server that has been shut down:

```
  File "/storage/testroot/venv/lib/python3.4/site-packages/paramiko/client.py", line 311, in connect
    raise NoValidConnectionsError(errors)
  File "/storage/testroot/venv/lib/python3.4/site-packages/paramiko/ssh_exception.py", line 166, in __init__
    body = ', '.join([x[0] for x in addrs[:-1]])
TypeError: 'dict_keys' object is not subscriptable
```

As the traceback indicates, this is caused by the code in ssh_exception attempting to run <dict>.keys()[:-1], which is not supported in Python 3; you need to do list(<dict>.keys())[:-1].

Unfortunately, I can't seem to get a solid repro; this only appears to happen intermittently.  Regardless, the code in question seems to be clearly incorrect.

**Comment by wsong** [comment]
Ah, actually, I can repro this consistently; it just only happens on 1.16.0.  Simply attempt to connect to a machine with no SSH capabilities (I did this by starting up a Docker container and killing the sshd process).  You'll see the above error as long as you're on version 1.16.0.

**Comment by bitprophet** [comment]
Thanks! Seems like a legit bug to sneak through the cracks, either from original Python 3 port work or for code added afterwards. Remembering to wrap everything in `list` is hard :( (I am on record as reallllly not liking that part of Python 3 despite being overall bullish on it...)

**Comment by bitprophet** [comment]
Upon reading the rest of the bug reports, someone's already filed a PR for this, #624. Rolling this into that.

**Comment by nchammas** [comment]
I think this is a dup of #615.
