### ISSUE TITLE
Paramiko does not work with pycryptodome

### ISSUE THREAD

**Issue by patrys** [paramiko/paramiko#637]
[pycryptodome](https://github.com/Legrandin/pycryptodome) is a self-contained fork of pycrypto that also happens to be the only crypto package that can be installed on Windows using nothing but `pip`.

It's mostly compatible save for some APIs that pycryptodome's author [considers insecure](https://github.com/Legrandin/pycryptodome/issues/6):

> Paramiko verifies RSA signatures in an insecure way and it does that by means of some old, questionable parts of the PyCrypto API (specifically, the method `verify` of an RSA key object).
>
> PyCryptodome is (fortunately or unfortunately, depending on how you look at it) not 100% compatible to PyCrypto: I explicitly removed or modified those few APIs that are inherently dangerous (like the `verify` method).

It would be great to be able to use Paramiko with pycryptodome even just for convenience it provides.

**Comment by bitprophet** [comment]
First I've heard of cryptodome, interesting. Thanks for the info!

We're actually planning to move away from PyCrypto anyway in 2.0 (see #394) so I don't know that this will get much love. If someone provides a minimally-disruptive patch against, say, 1.13 and up (at least 1.15 and up) I might merge it so people on the 1.x line have the option of using cryptodome. Would probably need to not make huge waves to be worth the risk tradeoff, though, FWIW.

**Comment by johnthagen** [comment]
+1 for ``pycryptodome`` support, or also check out ``cryptography``: https://cryptography.io/en/latest/

Though it's likely ``cryptography`` would require more porting work.

**Comment by Legrandin** [comment]
FWIW, I have created a minimal patch for this in #646.

**Comment by bitprophet** [comment]
Let's roll this into #646 - either that'll get merged or the 2.0 switch off of pycrypto will "solve" it for enough users.
