### ISSUE TITLE
add pty echo off option to exec_command

### ISSUE THREAD

**Issue by zhihuiFan** [paramiko/paramiko#639]
by default, when I run exec_command('sudo id', get_pty=True),  the pty is enabled echo by default.  however I can't turn it off anyway.   at last, I run into the following issue. 

http://stackoverflow.com/questions/34284376/paramiko-sudo-return-my-password-in-stdout-stderr

is it possible that we can have an parameter like 'echo=False' to turn off the stty echo? 

thanks

**Comment by bitprophet** [comment]
Paramiko as-is has no `get_pty` parameter in `exec_command`. We can't support third-party forks :(

Further, Paramiko is not explicitly enabling echoing as far as I can tell, it sends a blank value for the `pty-req` session request's "encoded terminal modes" field. Any echoing should be the domain of the remote pty itself and/or the program involved.

For example, if one executes a remote program making use of Python's `getpass`, you should see that your input is *not* echoed inside the getpass prompt - I just tested this locally.
