### ISSUE TITLE
errors in _winapi

### ISSUE THREAD

**Issue by mdclippe** [paramiko/paramiko#641]
Found issues in _winapi.py : 
 File "c:\Python26\lib\site-packages\paramiko\_winapi.py", line 92, in <module>
    GlobalAlloc.argtypes = ctypes.wintypes.UINT, ctypes.c_ssize_t
AttributeError: 'module' object has no attribute 'c_ssize_t'
After correcting that typo (c_ssize_t -> c_size_t), I stumbled upon another issue :

 File "c:\Python26\lib\site-packages\paramiko\_winapi.py", line 162, in write
    ctypes.windll.kernel32.RtlMoveMemory(dest, msg, length)
ValueError: Procedure probably called with too many arguments (4 bytes in excess)

**Comment by bitprophet** [comment]
This is a duplicate of #613
