### ISSUE TITLE
Trailing space in ssh configuration file

### ISSUE THREAD

**Issue by 56quarters** [paramiko/paramiko#653]
Hi,

I've run into an issue in Fabric that appears to be caused by the way Paramiko parses SSH configuration files (such as /home/$USER/.ssh/config). In [paramiko.config.SSHConfig.parse](https://github.com/paramiko/paramiko/blob/master/paramiko/config.py#L60) it looks like only trailing newlines (`\r\n`) are stripped. This means that any errant trailing spaces in an SSH configuration file cause issues. An example of a line that would cause an issue is below. Note that the `_` in the file name below would be a space in the real file.

```
Host *.dev.example.com
    IdentityFile ~/.ssh/my-dev-key_
```

In the case of a file like the above, an attempt would be made to read the key out of the file '/home/someuser/.ssh/my-dev-key ', which doesn't exist. 

I consulted the man page referenced in `config.py` (`man ssh_config`) and couldn't find any mention of trailing spaces one way or another. However, the OpenSSH client appears to strip any [trailing whitespace](https://github.com/openssh/openssh-portable/blob/master/readconf.c#L794).

Would you accept a PR to change `line.rstrip('\r\n').lstrip()` to `line.strip()` in `paramiko.config.SSHConfig.parse`?

Thanks!

**Comment by bitprophet** [comment]
Thanks for the details! Sounds like same issue as #499, let's roll it into there.

**Comment by 56quarters** [comment]
Gah, didn't see that issue. Thanks!
