### ISSUE TITLE
[bug] Signature verification (ssh-rsa) failed

### ISSUE THREAD

**Issue by Wizr** [paramiko/paramiko#657]
`paramiko` version: `1.15.2`
`python` version: `2.7.10`

I'am developing a software using `python` and packaged with `py2exe`. After distribution, most of them works well, but two of them got this exception, while no problem connecting the same server with other client tools.

> paramiko.transport: Exception: Signature verification (ssh-rsa) failed.
> paramiko.transport: Traceback (most recent call last):
> paramiko.transport:   File "paramiko\transport.pyc", line 1610, in run
> paramiko.transport:   File "paramiko\kex_group1.pyc", line 74, in parse_next
> paramiko.transport:   File "paramiko\kex_group1.pyc", line 110, in _parse_kexdh_reply
> paramiko.transport:   File "paramiko\transport.pyc", line 1490, in _verify_key
> paramiko.transport: SSHException: Signature verification (ssh-rsa) failed.

**Comment by bitprophet** [comment]
Do those connections work OK prior to packaging via py2exe? What are the nature of the keys and ciphers involved? Etc. More info needed :)

**Comment by Wizr** [comment]
One of the server's version number was manually changed from `OpenSSH_6.2` to `OpenSSH_6.8` for some reason. After reverting back, everything's OK now.

The other one was probably for some similar reason. It will be appreciated if you could point me the way to do some test, or monkey patch, to determine what caused this problem on the other server.

**Comment by GowdhamAppu** [comment]
HI ,
  I am also getting paramiko.sshexception signature varification (ssh-rsa) failed.

Could you please me to resolve this issue.

 on my server openSSH_5.3pl version installed

**Comment by rallen** [comment]
Also experiencing this issue using python 2.6.5.

As @Wizr also reported, can connect fine using other tools.

```
DEB [20160429-13:08:34.509] thr=2   paramiko.transport: starting thread (client mode): 0x1c04bad0L
DEB [20160429-13:08:34.509] thr=2   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_1.16.0
DEB [20160429-13:08:34.557] thr=2   paramiko.transport: Remote version/idstring: SSH-2.0-OpenSSH_6.7p1 Debian-5+deb8u1
INF [20160429-13:08:34.557] thr=2   paramiko.transport: Connected (version 2.0, client OpenSSH_6.7p1)
DEB [20160429-13:08:34.559] thr=2   paramiko.transport: kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group14-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256', u'ssh-ed25519'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com'] client mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] server mac:[u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-sha1'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
DEB [20160429-13:08:34.559] thr=2   paramiko.transport: Kex agreed: diffie-hellman-group14-sha1
DEB [20160429-13:08:34.559] thr=2   paramiko.transport: Cipher agreed: aes128-ctr
DEB [20160429-13:08:34.559] thr=2   paramiko.transport: MAC agreed: hmac-sha2-256
DEB [20160429-13:08:34.559] thr=2   paramiko.transport: Compression agreed: none
ERR [20160429-13:08:34.747] thr=2   paramiko.transport: Exception: Signature verification (ssh-rsa) failed.
```

**Comment by liucheng00355500** [comment]
Could some body give some advice?

**Comment by srish** [comment]
I am also running into the same issue. I am using Python 3 for my project. The same set of ssh keys work fine locally, but cause problems in a remote instance. Any pointers on how I can move forward on this?

**Comment by resonanzbchen** [comment]
I run into the same issue, anyone solved it?

**Comment by chell0veck** [comment]
+1

**Comment by gitmeh** [comment]
Hi, is the bug fixed?

python 3.8.2
paramiko 2.7.1

**Comment by bitprophet** [comment]
Worth trying Paramiko 2.9 for this as it adds SHA2 support and many errors like this turn out to be that problem!
