### ISSUE TITLE
Connection fails on 32-bit Python 3.4 under Windows

### ISSUE THREAD

**Issue by stevecohen42** [paramiko/paramiko#658]
Creating a connection fails on 32-bit Python 3.4 (and presumably all others) on Windows due to a data parameter size issue.  Pull request 659 has been entered to correct this issue.

**Comment by stevecohen42** [comment]
The associated pull request is 659.

**Comment by bitprophet** [comment]
Thanks! No need to make both an issue and a PR, for what it's worth, just the PR is fine :)
