### ISSUE TITLE
version 1.16 sftp_file prefetch not backward compatible

### ISSUE THREAD

**Issue by stevevanhooser** [paramiko/paramiko#676]
Bug: In version 1.16 of paramiko, the function in sftp_file.py called "prefetch" now requires 2 input arguments (self and the file_size to be read in). In previous libraries it assumed that the entire file was going to be read in and the second argument was not present.

This causes older software (such as bzr) that only pass one input argument to fail. 

I am working to patch the code so that if only 1 input argument is given, the code will default to the whole file, which is the legacy behavior.

**Comment by stevevanhooser** [comment]
This is now posted as pull #677

**Comment by bitprophet** [comment]
Rolling into the PR.
