### ISSUE TITLE
log_to_file shall use filemode "append", not "write"

### ISSUE THREAD

**Issue by vlcinsky** [paramiko/paramiko#683]
See [StackOverflow question](http://stackoverflow.com/questions/35268029/appending-the-log-file-using-logging)

Paramiko log files created by means of `paramiko.util.log_to_file("filename.log')` result always in overwriting the previous logs.

The reason is clear, the [`util.py` line 24](https://github.com/paramiko/paramiko/blob/master/paramiko/util.py#L24) is opening the file with "w" mode.

Consider changing to "a".

**Comment by sunjeewa** [comment]
+1

**Comment by vicosoft** [comment]
+1

**Comment by PurplePinkie** [comment]
+1

**Comment by bitprophet** [comment]
Fixed via #907

**Comment by PurplePinkie** [comment]
very nice. tnx! ;-)
