### ISSUE TITLE
Bad file descriptor and Broken pipe solution

### ISSUE THREAD

**Issue by qualab** [paramiko/paramiko#692]
In case of mass threads using paramiko we've got mass errors crashing transport like "Bad file descriptor" and "Broken pipe" on POSIX machines. I've traced this bug via strace and got a root of problem. In class PosixPipe we have no synchronization between close() and set() methods. Time after time close() from separated thread occurs between check of self._closed and os.write(self._wfd, b'*'). So we do write/read on descriptor that beaing closed or already closed at this time. There should be synchronization lock between close() and set() and clear() methods which changes state of file descriptor (socket actually). Solution was checked on mass threads, this is stable. Pull request has been created this moment. Please simply merge it if you agree with this solution:
https://github.com/paramiko/paramiko/pull/691/files

**Comment by bitprophet** [comment]
Rolling into PR, thanks!

**Comment by qualab** [comment]
You're welcome, nice lib.

**Comment by CalebRouleau** [comment]
Why is this issue closed? The code in https://github.com/paramiko/paramiko/blob/master/paramiko/pipe.py doesn't reflect that the changes from https://github.com/paramiko/paramiko/pull/691/files. Seems like 691 never got checked in.

**Comment by qualab** [comment]
Looks like it still send '*' repeately possibly in parallel with close() calling (and very heavy closing() function inside close() on *nix platforms). I afraid this problem may be not solved. Our tests are fixed with locks from code above, but other guys may have same problems with EPIPE or EBADF.
