### ISSUE TITLE
Occasional hang 

### ISSUE THREAD

**Issue by botanicvelious** [paramiko/paramiko#698]
In 1.16 occasionally some connections hang on line 249 in packet.py

`x = self.__socket.recv(n)`

I am using windows 10 64 bit using python 3.5.1

The call being done to paramiko is

.connect(**ssh_connect_params)

with the params of

{'key_filename': None, 'hostname': 'myhostip', 'timeout': 8, 'port': 903, 'password': 'mypass', 'look_for_keys': False, 'username': 'myusername', 'allow_agent': False}

 #380 -may- be releated

**Comment by botanicvelious** [comment]
I was able to work-around this with the following

```
1721a1722,1723
>                 exit_timeout = time.time() + 60*5 # 5 minutes from now
>                 
1722a1725,1727
>                     if time.time() > exit_timeout:
>                         raise Exception('read_message Timeout') 
>                         break
```

**Comment by sanseihappa** [comment]
#520 Looks like the same issue (Hang in packet.py `Packetizer.read_all()`)

**Comment by bitprophet** [comment]
This does seem likely to be the same issue as either #380 or #520 (if those aren't both the same, which they might be). Let's roll it into those. Thanks for the report!

(Also, yea, a timeout would solve many of these maybe-related-maybe-not hang issues, but ideally we'll figure out the actual race condition involved & fix it instead. Timeouts are usually not optimal :()

**Comment by botanicvelious** [comment]
What it seems to be sometimes is that some devices respond to the ssh initiation but then just hang on there side, so im not sure if its possible to fix it without a timeout

Ive noticed some devices have th eissue where others do not
