### ISSUE TITLE
AutoAddPolicy

### ISSUE THREAD

**Issue by igoreliasm** [paramiko/paramiko#720]
For work 
I needed add **ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())** 
before **.connect**

paramiko==1.16.0
python=2.7

**Comment by bitprophet** [comment]
If you're not loading any external host keys, yes, you need to override the default reject policy (see http://docs.paramiko.org/en/latest/api/client.html#paramiko.client.SSHClient.set_missing_host_key_policy). Not a bug! Thanks :)
