### ISSUE TITLE
using paramiko in tests with py.test or nosetests causes a hang

### ISSUE THREAD

**Issue by corey-dow** [paramiko/paramiko#721]
Hi, I like to use paramiko in my tests for checking simple things.  The code works just fine but when I try to run the code using py.test or nosetests it freezes. I have the sample code I'm using and trace output further below.  Any help appreciated.  I'm probably just doing something wrong. 

Ubuntu 14.04
1.16.0
ii  python-crypto                                    2.6.1-4build1                                                amd64        cryptographic algorithms and protocols for Python
ii  python-ecdsa                                     0.11-1~bpo70+1~0x2go~ubuntu14.04.1                           all          ECDSA cryptographic signature library (Python 2)
ii  python3-crypto                                   2.6.1-4build1                                                amd64        cryptographic algorithms and protocols for Python 3

**Sample Code**
import paramiko
import pytest
import ipdb

hostname = '151.1.1.45'
port = 22
username = 'admin'
password = 'admin'

#ipdb.set_trace()
handle = paramiko.SSHClient()
print handle
handle.set_missing_host_key_policy(paramiko.AutoAddPolicy())
handle.connect(hostname, port, username, password)

#ipdb.set_trace()
stdin, stdout, stderr = \
handle.exec_command('uname -a')

for line in stdout.readlines():
   print line

assert 'Linux' not in line

**Backtrace**
corey@h3664:/tmp/tests$ nosetests -v test_Paramiko.py
^CTraceback (most recent call last):
  File "/usr/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.3.1', 'console_scripts', 'nosetests')()
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 474, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/tests/test_Paramiko.py", line 14, in <module>
    handle.connect(hostname, port, username, password)
  File "build/bdist.linux-x86_64/egg/paramiko/client.py", line 325, in connect
    t.start_client()
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 488, in start_client
    event.wait(0.1)
  File "/usr/lib/python2.7/threading.py", line 620, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 358, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by seemethere** [comment]
It has something to do with the recent release of paramiko `2.0.0`.

If you downgrade using:
```shell
pip install paramiko==1.17.0 --upgrade
```

and then use the dirty hack outlined by @bucknerns in issue #104:
```python
from paramiko import py3compat
# dirty hack to fix threading import lock (issue 104) by preloading module
py3compat.u("dirty hack")
```

Your problems should be solved.

**Comment by bitprophet** [comment]
@seemethere Incorrect, version 2.0 came out yesterday, this bug is 17 days old - it's something else :(

That said, we fixed some race conditions in the 1.16.1 release so @corey-dow should definitely try that (or 1.17.0). I'd also suggest trying 2.0.0 if either of those don't work; the new backend may improve performance in some areas which could impact this, if it's a race condition.

**Comment by seemethere** [comment]
@bitprophet Downgrading to 1.17.0 solved my issues.

**Comment by bitprophet** [comment]
Let's roll this into #735, no need for 3-4 tickets about this XD

**Comment by bitprophet** [comment]
(And I might roll that one into #104 if they truly turn out to be the same issues.)
