### ISSUE TITLE
Timeout when getting SSH banner

### ISSUE THREAD

**Issue by thexder1** [paramiko/paramiko#722]
This is kind of a strange issue I am encountering and I have not been able to narrow down what is causing it. I only know that it only happens when running a specific Python script through Jenkins which uses paramiko to connect to an out of band management system on a server, runs a firmware update, then right after that when attempting to reconnect paramiko times out when getting the SSH banner. It keeps retrying unsuccessfully.

While this process is still failing to reconnect I can run the same process again or another process that will use paramiko to connect to the same system and it works.

Also when running the same process manually on the command prompt from the same system that Jenkins uses as a slave works without issue and other processes that perform nearly identical processes work both when run manually from command line and from Jenkins.

Debug logging does not provide any additional information, I have added additional logging in paramiko and can confirm that the packet.packetizer._read_timeout() is hitting the timeout without receiving any data.

After each attempt I am running multiple close() methods to try to make sure everything is closed before attempting to connect again.

The actual connection is nothing more than paramiko.client.SSHClient.connect() with the appropriate paramters being passed in and it fails, but only on one specific process, only after a firmware update, and only when being run through Jenkins.

I would appreciate any information that can help me at least gather more information about this problem

**Comment by bitprophet** [comment]
That does sound like a doozy. This isn't bringing anything specific to mind other than that something in the Jenkins environment might be preventing the Paramiko process from truly, fully closing up everything involved (sockets, whatever). (Have you tried running *as the Jenkins user, with its own login environment* on the Jenkins box yet? That would more closely represent the problem scenario vs a regular user on the same box.)

Another workaround could be to try discarding the `Client` object in question and create a new one with the same parameters. This is effectively what higher-level libs like Fabric do - e.g. Fabric keeps a cache/dict of Clients and when users request a force-reconnect, it `del`'s them out of the dict and creates a wholly new client object.

That's not 100% ideal, but offhand I don't see any major downsides to doing so.

Unless you can identify some specific bug causing this, I'm going to close it as non-actionable. Happy to reopen if something is identified. Good luck & thanks for the report.
