### ISSUE TITLE
Expose `ProxyCommand none` as None instead of stripping it

### ISSUE THREAD

**Issue by bitprophet** [paramiko/paramiko#732]
Follow-on from #670.

For that ticket, we updated the implementation to insert `None` (including a handful of spots that needed updating to not assume all values were list-like) and then stripped it out at the last minute to preserve backwards compatibility.

Both myself & original submitter agree that it's cleanest to actually expose `ProxyCommand none` as `{'proxycommand': None}`, so this ticket is for doing that in a backwards incompatible release (3.0).

Should be as easy as nuking the 2-3 lines noting `# TODO: ... #670` in `paramiko/config.py`.

**Comment by r0fls** [comment]
Why is there no branch for 3.0 yet? Where is the development for that version happening, current master?

**Comment by bitprophet** [comment]
No dev happening for it at the moment, once one of the 3.0-marked issues gets started on, will probably turn master into `2.0` and then a new `master` will be for 3.0 stuff.

**Comment by bitprophet** [comment]
This will be out in the impending 3.0 release.
