### ISSUE TITLE
Paramiko Wont Install

### ISSUE THREAD

**Issue by mnfost** [paramiko/paramiko#736]
I'm getting the following error when I try to install paramiko, but it was working a few days ago. 

Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-EDGulh/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0Hvas8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-EDGulh/cffi"

**Comment by bitprophet** [comment]
Please read [the changelog](http://www.paramiko.org/changelog.html) before upgrading! We carefully note backwards incompatible changes there in big red warning blocks :) thanks!
