### ISSUE TITLE
ImportErrror Cant find module named utils 

### ISSUE THREAD

**Issue by twr14152** [paramiko/paramiko#755]
So first time posting, so if this the wrong forum apologize. I was trying to run paramiko I get an ImportError for utils. Posted the output below:

I know there's been a change recently per the change log. 
I just upgraded to debian 8.4 on virtual box and did a pip install of paramiko, and noticed the error. It seemed to install fine. So for what its worth.

>>> import paramiko
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 53, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/dsskey.py", line 27, in <module>
    from cryptography.hazmat.primitives.asymmetric.utils import (
ImportError: No module named utils

I traced the path and utils is not in the asymmetric directory

root@debian:/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric# ls -la
total 104
drwxr-xr-x 2 root root  4096 May 21 10:28 .
drwxr-xr-x 7 root root  4096 May 21 10:28 ..
-rw-r--r-- 1 root root  9978 Oct 16  2014 dsa.py
-rw-r--r-- 1 root root 13604 May 21 10:28 dsa.pyc
-rw-r--r-- 1 root root  6299 Oct 16  2014 ec.py
-rw-r--r-- 1 root root 13950 May 21 10:28 ec.pyc
-rw-r--r-- 1 root root   611 Oct 16  2014 __init__.py
-rw-r--r-- 1 root root   293 May 21 10:28 __init__.pyc
-rw-r--r-- 1 root root  2012 Oct 16  2014 padding.py
-rw-r--r-- 1 root root  2766 May 21 10:28 padding.pyc
-rw-r--r-- 1 root root 11506 Oct 16  2014 rsa.py
-rw-r--r-- 1 root root 15843 May 21 10:28 rsa.pyc
root@debian:/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/asymmetric#

**Comment by marek-obuchowicz** [comment]
@twr14152  Can you tell how you fixed this issue? Running into the same problem.

**Comment by twr14152** [comment]
Hey Marek, 
Unfortunately I was not able to. Enough time passed i began to think it was just a fluke thing. I ended up moving away from debian 8.4 for some other issues, at which point i lost my ability to test. Rather than keep this open without the ability to test and provide real feedback, i thought it best to just close it.  I dont know if you can reopen this case or another. Since it wasnt simply a one time event. I would be curious to see what you find. I could but i dont have any real data any more.


Todd

**Comment by marek-obuchowicz** [comment]
Just for reference for others - debian 8.x delivers python-cryptography version 0.6.1. I was able to get my project working by including in requirements.txt newer versions of modules and install them by using `pip`:
```
cffi==1.7.0
cryptography==1.3.4
```

**Comment by waynelewis** [comment]
I was able to upgrade cffi and cryptography using:

    sudo pip install --upgrade cffi
    sudo pip install --upgrade cryptography

I also needed up upgrade PyNaCl:

    sudo pip install --upgrade PyNaCl
