### ISSUE TITLE
Can't connect without specifying user/password when I have key access

### ISSUE THREAD

**Issue by DavidVentura** [paramiko/paramiko#760]
Hi.

Trying to run

```
    ssh = paramiko.SSHClient()
    ssh.load_system_host_keys()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    ssh.connect(host,port)
    _,stdout,stderr = ssh.exec_command(command)

```

should work if I have user/key on my ssh config file. How can I get this to work? 

Running `ssh -v 192.168.1.7` gives me 

```
...
debug1: Offering RSA public key: /home/user/.ssh/testkey
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to 192.168.1.7 ([192.168.1.7]:22).
...
```

**Comment by birm** [comment]
what does .ssh/known_hosts look like as the user that's running this?

**Comment by DavidVentura** [comment]
It has the remote.. Signature? I've manually run the ssh command and accepted the host signature. Will update from PC later

On June 4, 2016 4:02:40 AM GMT-03:00, Ryan Birmingham <notifications@github.com> wrote:
>what does .ssh/known_hosts look like as the user that's running this?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/paramiko/paramiko/issues/760#issuecomment-223740866

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DavidVentura** [comment]
```
$ cat /home/mqttwarn/.ssh/known_hosts 
|1|vjBZbNuVpvhZdnlcgWE15JBPfGA=|p2tHmCzXdBelaZjufF/BMsxZ7Js= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLtWh0G9X7lczaZYkg+qDN2RW48+lR0LherRFFbh5j83sG38Eel/wW5qgBRRz84xyJ1ZFveVVDeGQfmHLv3Rq....

```

**Comment by birm** [comment]
You can take out any sensitive info from file. 
Are you running python as root or your user?

**Comment by DavidVentura** [comment]
I'm running as the user. That's the entire known_hosts file.
```bash
$ whoami
mqttwarn
$ ssh 192.168.1.7
david@pc-david:~$ 
david@pc-david:~$ logout
Connection to 192.168.1.7 closed.
mqttwarn@mqtt:~$ cat .ssh/config 
Host 192.168.1.7
        User david
        IdentityFile ~/.ssh/testkey
        Port 22
```
ssh does not ask for a password.

```python


import paramiko

ssh = paramiko.SSHClient()
ssh.load_system_host_keys()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())


host="192.168.1.7"
port=22
ssh.connect(host,port)
_,stdout,stderr = ssh.exec_command("ls")

for line in stdout:
    print('... ' + line.strip('\n'))
```
Traceback (most recent call last):
  File "ssh.py", line 19, in <module>
    ssh.connect(host,port)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 520, in _auth
    raise SSHException('No authentication methods available')
paramiko.ssh_exception.SSHException: No authentication methods available


```bash

```

**Comment by birm** [comment]
try connect with username="David". paramiko doesn't look at your config file in this case

**Comment by DavidVentura** [comment]
I was expecting something like this by default:

```python
def credentials(host,user=None,pwd=None,port=22):
    c={}
    if user is None and pwd is None:
        config = paramiko.SSHConfig()
        p=os.path.expanduser('~')+'/.ssh/config'
        config.parse(open(p))
        o = config.lookup(host)

        ident=o['identityfile']
        if type(ident) is list:
            ident=ident[0]
        if 'port' not in o:
            o['port']=port
        c={'hostname':o['hostname'], 'port':int(o['port']), 'username':o['user'], 'key_filename':ident}
    else:
        c={'hostname':host,'port':port,'username':user,'password':pwd}

    return c

```

I'll use this in my project for now, consider adding this/something like this (taking args from config file)

**Comment by rory** [comment]
AFAIK paramiko doesn't use your `ssh_config` file by default.

**Comment by DavidVentura** [comment]
Why isn't something like what I posted the default? (Parsing config file), or rather, is it done by paramiko in any way?

**Comment by bitprophet** [comment]
@DavidVentura Not being the original author, I can't say exactly why, but I'd guess simply because this library's more low-level and not every use case is going to want implicit/automatic config parsing.

Higher-level stuff like [Fabric](http://fabfile.org) is where that's more appropriate; sadly Fabric 1 only started leveraging PAramiko's config support partway through its lifecycle and so backwards compatibility dictated that it also require users to opt-in to the feature. Its 2.0 will almost definitely load configs by default - it *is* the common case, and advanced users not wanting it can easily turn it off.
