### ISSUE TITLE
Re-evaluate preferred_mac's and preferred_kex's

### ISSUE THREAD

**Issue by mimecuvalo** [paramiko/paramiko#766]
In updating https://github.com/mimecuvalo/paramikojs (the paramiko 'translation' project), I noticed in this commit last year the order of the macs/kexs were re-ordered:
https://github.com/paramiko/paramiko/pull/596/files
1. preferred_mac: It looks fine that 'hmac-sha2-256' was added to the front, but shouldn't 'hmac-sha1' go right after it, not at the end?
2. preferred_kex: 'diffie-hellman-group1-sha1' was re-ordered to the front 

Looking around it seems that diffie-hellman-group1-sha1 has been deprecated afaict:
https://weakdh.org/sysadmin.html (under the OpenSSH section):
"If you want to continue to support non-elliptic-curve Diffie-Hellman, at the very least, you should disable Group 1 support, by removing the diffie-hellman-group1-sha1 Key Exchange. It is fine to leave diffie-hellman-group14-sha1, which uses a 2048-bit prime."

Might be time to look at the orderings and re-evaluate what is currently recommended!

**Comment by bitprophet** [comment]
I suspect this is largely better now, after the tickets merged last week - we've added additional kex/mac/cipher algorithms, removed some outdated ones, and shuffled order around.
