### ISSUE TITLE
Can't connect if you have many encrypted private keys

### ISSUE THREAD

**Issue by rory** [paramiko/paramiko#768]
I have many ssh private keys, about one for each host. They are encrypted, and I have a SSH running which has them all unlocked and stored. And I'm trying to write a python programme which uses SSH & SFTP to one of these hosts, and I cannot connect when I use paramiko, but it works fine when using the `ssh` command line (I'm on ubuntu linux). From looking at the `_auth` method of `SSHClient` with a debugger and I've found the problem. paramiko will use all the keys from the agent to connect. However if you have a lot of keys, the remote ssh server will close the connection after several incorrect ssh keys (IME about 3 incorrect key). So the order of the ssh keys from the ssh agent affects if you can log in or not! (this didn't happen to me yesterday).

If I specify the filename of the correct ssh key (with `key_filename`), then paramiko will try that, encrypted, key. Which will fail.

The solution could be (i) properly use the `ssh_config` file, or (ii) if a key is specifed, and it's encrypted ask the ssh agent for the decrypted key.

**Comment by bitprophet** [comment]
Thanks for the report!

Generally, this falls under #387 - once that gets tackled it should make all of this behavior more configurable (and yea, ideally, honor more of SSHConfig than may presently be so). Going to roll into that. Also see below:

> If I specify the filename of the correct ssh key (with key_filename), then paramiko will try that, encrypted, key. Which will fail.

Off the top of my head, if you specify the `password` argument to `SSHClient.connect`, that will allow proper decrypting of the key given with `key_filename`.

Alternately, you can explicitly give it `pkey=AppropriatePKeySubclassHere.from_private_key_file('path', 'password')`. End result should be the same.
