### ISSUE TITLE
Missing git tag for 2.0.2 release

### ISSUE THREAD

**Issue by felixonmars** [paramiko/paramiko#786]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by bitprophet** [comment]
I usually do, looks like I missed the `git push --tags` last night - apologies! (I need to buckle down and finish polishing my "do all the steps" release tasks; right now it's mostly automating the actual PyPI level stuff.)

Just now:

```
» gps --tags
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:paramiko/paramiko.git
 * [new tag]         1.16.3 -> 1.16.3
 * [new tag]         1.17.2 -> 1.17.2
 * [new tag]         2.0.2 -> 2.0.2
 * [new tag]         v1.16.3 -> v1.16.3
 * [new tag]         v1.17.2 -> v1.17.2
```

**Comment by felixonmars** [comment]
Thanks :)
