### ISSUE TITLE
Connection fails when host key is ecdsa-sha2-nistp384 or ecdsa-sha2-nistp521

### ISSUE THREAD

**Issue by ncoult** [paramiko/paramiko#794]
The code seems to have just left out a few lines to support these host key types.

**Comment by ncoult** [comment]
Patch here that fixes it:

https://gist.github.com/ncoult/4e33ad3b15580f791fdd75348b902134

**Comment by mcclurem** [comment]
Any chance this could get some merge-love? I've had to start patching my own installs for this bug :-(

**Comment by bitprophet** [comment]
I've been letting releases slip lately but almost done with the side project that's taken up my time, so I will be trying to give Paramiko a lot of love soon. Sorry for the delays!

**Comment by alexreg** [comment]
Glad to see this is supported. Looks like the docs need updating though. (Grep for "keytype" in <http://docs.paramiko.org/en/2.4/api/hostkeys.html>.)
