### ISSUE TITLE
Transport object thread remains active after close()

### ISSUE THREAD

**Issue by wdukar** [paramiko/paramiko#799]
When using Python3, the Transport object thread is not joined properly on close(). 
This, causes fatal error on Py_EndInterpreter call 

```Fatal Python error: Py_EndInterpreter: not the last thread```

The workaround of this issue is to call join() method on Transport object (see example:)

```
# Sample file for transport thread problem


import sys
import paramiko
import threading


# Open a transport
host = "localhost"
port = 22
transport = paramiko.Transport((host, port))

# Auth
password = "test"
username = "test"
transport.connect(username = username, password = password)

# Go!
sftp = paramiko.SFTPClient.from_transport(transport)

# Download
filepath = '/etc/hosts'
localpath = '/tmp/hosts.downloaded.sftp'
sftp.get(filepath, localpath)

# Close
sftp.close()
transport.close()

# -----> this fixes problem   transport.join()

for th in threading.enumerate() :
   print("Has thread", th);
   print("Is alive", th.is_alive())

```

**Comment by bitprophet** [comment]
Thanks for the report! Thread cleanup is a common issue with many permutations, see e.g. #520. `Transport` itself generally should not need explicit joining as there are a few spots that attempt to make sure it happens on shutdown.

If you can identify why these aren't firing in your case, more details would be great. Going to close this as "probably covered elsewhere" for now though :)
