### ISSUE TITLE
Add optional timeout parameter to Channel.recv_exit_status()

### ISSUE THREAD

**Issue by paramiko-user** [paramiko/paramiko#806]
Please add an optional "timeout" parameter (default value: None) to Channel.recv_exit_status() and pass this parameter to the called "self.status_event.wait(timeout)".

This would allow waiting with timeout like subprocess.Popen.wait() does in Python 3.

**Comment by bskinn** [comment]
A number of timeout related features were added in paramiko 3.1.

This is sufficiently old that I'm going to close it. Please check paramiko 3.1 or later—if the timeout you want still isn't implemented, please open a new issue/PR and reference this one.

Thanks!
