### ISSUE TITLE
How can I use paramiko implement a ssh server like openssh-server return /bin/bash

### ISSUE THREAD

**Issue by ibuler** [paramiko/paramiko#818]
I have seen demo_server.py.

I seen the method `check_channel_shell_request` and `check_channel_pty_request`,
but they should return Boolaen object. 

How can I return /bin/bash to client ?

I have no idea? May be use event ?

**Comment by bitprophet** [comment]
I'm afraid the core team don't have the support bandwidth to help with detailed implementations, outside of the demo files. Locking this as "nothing to fix" but if you're lucky someone else might happen by with tips. Thanks & sorry!
