### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by fccagou** [paramiko/paramiko#82]
Hello, 

Is kerberos support  planned ?

Thanks a lot.

**Comment by bitprophet** [comment]
No idea how we managed to not close this, but we merged #267 some time ago.

**Comment by mkomitee** [comment]
FYI, while #267 was merged some time ago, GSSAPI support is currently broken. Please take a look at #496 when you have a chance.

**Comment by bitprophet** [comment]
Yup, the reason I saw this was open is I was poking around other tickets, including #496. It will definitely get love next time I put out a release.

**Comment by mkomitee** [comment]
That sounds great. I'll stop responding to this dead issue now, I promise :)
