### ISSUE TITLE
ValueError after compiling with py2exe

### ISSUE THREAD

**Issue by gloriousrootkit** [paramiko/paramiko#830]
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "client.py", line 15, in <module>
  File "paramiko\client.pyc", line 338, in connect
  File "paramiko\transport.pyc", line 493, in start_client
ValueError: Multibackend cannot be initialized with no backends. If you are seei
ng this error when trying to use default_backend() please try uninstalling and r
einstalling cryptography.

**Comment by bitprophet** [comment]
Sounds like you filed this at Cryptography as well (pyca/cryptography#3208) - it's definitely on their end, not ours. Hopefully the bugs they linked you to helped!
