### ISSUE TITLE
Fingerprint Hashing - support for sha256

### ISSUE THREAD

**Issue by dwieeb** [paramiko/paramiko#836]
OpenSSH changed the default fingerprint hash from md5 to sha256 in the [6.8 release](http://www.openssh.com/txt/release-6.8). paramiko seems to hardcode [`get_fingerprint()`](https://github.com/paramiko/paramiko/blob/30a7afcdc74443c74f2ebb344a1fbf235c23bf57/paramiko/pkey.py#L132-L141) with md5.

As a workaround, one could call the sha256 hashing algorithm on `asbytes()`, right?

Example usage of hash outputs:

```
dan ~/.ssh » ssh-keygen -E md5 -lf id_rsa2.pub
2048 MD5:4a:a9:68:03:f1:4d:b4:2e:4d:ad:c7:c9:d3:ea:30:b0 dan@dan.local (RSA)
```

```
dan ~/.ssh » ssh-keygen -E sha256 -lf id_rsa.pub
2048 SHA256:KPI+eARVyhXb3I4Kfv+MPblOrokVrX7iBXCw56szL9w dan@dan.local (RSA)
```

**Comment by dwieeb** [comment]
The [rfc for public keys](https://tools.ietf.org/html/rfc4716) doesn't mention anything but md5 fingerprints, however. I guess this is more of a question.

**Comment by bitprophet** [comment]
I'll leave this closed for now but FWIW we do often try to keep compatibility with OpenSSH's implementation when it makes sense.

Whether it makes sense in this situation I'm not sure of though :) (Ideally it'd be configurable...)

**Comment by dwieeb** [comment]
I know OpenSSH is often treated as the reference implementation. I suppose it makes sense to implement it somehow in paramiko. You're welcome :)

For future googlers, as a workaround for getting a sha256 hash you can do something like this (untested):

```python
import hashlib
import base64

# rsakey.asbytes() returns the public bytes of an instantiated paramiko RSAKey object
fpbytes = hashlib.sha256(rsakey.asbytes()).digest()
fp = base64.b64encode(fpbytes).decode('utf-8')
my_fingerprint = fp.rstrip('=')  # OpenSSH takes out b64 padding chars
```
