### ISSUE TITLE
Is it really necessary to use cryptography?

### ISSUE THREAD

**Issue by demonguy** [paramiko/paramiko#848]
I tried to distribute my own package for my colleagues using paramiko for ssh client.
But i found, since paramiko uses cryptography, there are so many serious compatibility problems.
Cryptography depends on at least six packages which are not standard library. and even .so files.

Besides, cryptography doesn't support python 2.7.5. I works so hard to solve all these problems. But it depends highly on users' environment.

Why do paramiko uses cryptography?

**Comment by bitprophet** [comment]
See #394 for the rationale :) I'm not sure what other options you had in mind...
