### ISSUE TITLE
openssl gives UserWarning

### ISSUE THREAD

**Issue by KodeZ** [paramiko/paramiko#851]
Not entirely sure what this means, but I do get this warning using OpenSuse leap 42.2, and pip3 version of paramiko. Not entirely sure it is related to paramiko at all, but I will try here first, then move it if this is the wrong place.
```
/home/mt/.local/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/ec.py:113: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
```

**Comment by bitprophet** [comment]
At the very least it's technically coming out of our newish crypto backend, Cryptography (https://cryptography.io), and given the nature of the exact message it feels related to either `libffi` or `openssl` itself.

I don't maintain any C wrappers myself so not sure what the best practices are re: such warnings - could be wrapping them in a more obvious message but keeping a warning, or hiding the warning entirely, or leaving it as-is and expecting users to manually use the `warnings` module to mute the warnings (which is the only thing I can really suggest here offhand).

Thanks for the report!
