### ISSUE TITLE
auth_gssapi_keyex minor documentation inconsistency

### ISSUE THREAD

**Issue by ScoreUnder** [paramiko/paramiko#854]
In the [documentation for `Transport`](http://docs.paramiko.org/en/2.0/api/transport.html#paramiko.transport.Transport.auth_gssapi_keyex), the `auth_gssapi_keyex` function is documented with a signature of only one parameter, but has descriptions for three parameters.

**Comment by bitprophet** [comment]
Thanks, sounds easily fixed.
