### ISSUE TITLE
TypeError: exec_command() got an unexpected keyword argument 'environment'

### ISSUE THREAD

**Issue by SethMichaelLarson** [paramiko/paramiko#858]
When running the following script on my local machine I receive the following error:
Script:
```python
>>> import paramiko
>>> c = paramiko.SSHClient()
>>> c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> c.connect("localhost", username="user", password="...")
>>> c.exec_command("echo $HELLO", environment={"HELLO": "WORLD"})
```
Exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: exec_command() got an unexpected keyword argument 'environment'
```
In the docs this keyword argument is advertised as a part of `SSHClient.exec_command` as well as in the code I can see that `environment` is a keyword argument.  However, when I inspect the method it also doesn't report the keyword argument.
```python
>>> import inspect
>>> print(inspect.getargspec(c.exec_command)[0])
['self', 'command', 'bufsize', 'timeout', 'get_pty']
```
What is going on here?

**Comment by bitprophet** [comment]
We haven't actually released the code with those changes in it (should go out today) - how exactly did you install Paramiko before running this? When you say "in the code" are you looking at the actual module you're truly running, or just on Github or whatnot?

I've got local code using this functionality (based on the git checkout) so I'd be surprised if it was actually misbehaving like this =/

**Comment by bitprophet** [comment]
OK, 1.18.0 and 2.1.0 are both out with this change in it; if you can still reproduce this with one of those copies of the code definitively installed, please let me know! Closing optimistically otherwise :)

**Comment by SethMichaelLarson** [comment]
Thanks a lot! I didn't realize that this feature was in 2.1.0, I was using 2.0.2.  I will try using with 2.1.0 :)

**Comment by bitprophet** [comment]
Oh I wasn't saying you missed anything, I was trying to say I had just released those versions and you had the option of using either :)
