### ISSUE TITLE
open_channel lockup when disconnected

### ISSUE THREAD

**Issue by bitprophet** [paramiko/paramiko#86]
Originally submitted as [SSH #44](https://github.com/bitprophet/ssh/issues/44) by @xiaclo:

> There is an issue which I have encountered with long-running transports, but can be replicated fairly easily by forcing a hard network disconnect (pulling a plug or similar).  There is demo code at http://pastebin.com/fT5yTUvU
> 
> Patch at http://pastebin.com/S6tybiws to add a timeout to open_channel.
> 
> Fairly simple to code and full compatible, but I've found it a big help (I use a 3 sec timeout, but too low for a default).

**Comment by aschlapsi** [comment]
It looks like this issue has been fixed with PR #491. I suggest closing this issue.
