### ISSUE TITLE
Channel with execute complete detection

### ISSUE THREAD

**Issue by vit1251** [paramiko/paramiko#864]
Hello, 

Your class Client provide exec_command() with result is stdin, stdout and stderr, but how to detect error_code_readey and error_code? I never receive channle object and can not call this method.

Could you provide another method with channel return for my purposes or suggest me right way to batch execution?

Thanx.

**Comment by bitprophet** [comment]
Check out the https://github.com/fabric/fabric codebase for some hints about using high level paramiko stuff (or just use it directly), I don't remember offhand exactly how it does this but it definitely manages.

**Comment by vit1251** [comment]
I discover follow code:

```
        chan.exec_command(command)
        stdin = chan.makefile('wb', bufsize)
        stdout = chan.makefile('r', bufsize)
        stderr = chan.makefile_stderr('r', bufsize)
        return stdin, stdout, stderr
```

There is source code provide only stdin, stdout, stderr, but can not provide chan. Could I make pull request with exec_command_2 with return chan?
