### ISSUE TITLE
Not possible to use the sftp.open file descriptor as an object for s3.upload_fileobj

### ISSUE THREAD

**Issue by zioalex** [paramiko/paramiko#871]
Hi I tried to copy a file object from an sftp connection:
`with sftp.open(remote_dir + "/" + filename, 'rb') as f:`
`data = f.read()`
`size = f.tell()`
`s3.upload_fileobj(f, s3bucket, 'logs/' + filename )`

The file is created but it is empty
Instead reading from the local file works as expected:

`
with open(localdir + "/" + filename, 'rb') as readlocalfile:
s3.upload_fileobj(readlocalfile, s3bucket, 'logs/' + filename)
`
Reading the docs [](http://docs.paramiko.org/en/2.1/api/sftp.html#paramiko.sftp_client.SFTPClient) I expected the same behaviour.

Please can you help with it.
Thanks
Alessandro

**Comment by zioalex** [comment]
I found a way to workaround it:
 ```
with sftp.open(remote_dir + "/" + filename, 'rb') as f:
        data = f.read()
s3.put_object(Bucket=s3bucket,
   Key="logs/" + filename,
   Body=data)```

However it doesn't use directly the f object.

**Comment by bitprophet** [comment]
I haven't tried using the result of `sftp.open` myself (and as far as I know it's not a commonly used feature) so have not encountered this, but I'd guess this implies it's missing some file object protocol methods or something.

Marking as a bug but it needs somebody to poke a bit more (possibly including seeing what `s3.upload_fileobj` is doing) to figure it out.

Thanks for the report!

**Comment by radssh** [comment]
After doing the `data = f.read()` call, the current file position is at the end. f is still valid as a file object, but subsequent `read()` calls won't provide any content, you've already pulled the file contents into `data`.

Using `Body=data` gets you the proper result into S3, as you discovered. If you want to use the file object, either avoid doing the `read()` call yourself, or try doing a `seek()` call to reposition back to start of file. If you're only reading the file to determine its length, then using `f.stat()` is a superior choice.

**Comment by bitprophet** [comment]
Nice catch, @radssh - that would definitely explain it. I skimmed over the code past the `with` statement :(

**Comment by zioalex** [comment]
Thanks Paul!
you are right. I will try it.
Cheers
Alessandro
