### ISSUE TITLE
write_private_key(_file) methods ignore passwords

### ISSUE THREAD

**Issue by LuboO** [paramiko/paramiko#873]
Following code:

>import paramiko
>k = paramiko.RSAKey.generate(2048)
>k.write_private_key_file("key", password="password")

will create file "key" with unencrypted private key. In this case, password is totally ignored. I am using paramiko-2.1.1, cryptography-1.7.1, python-3.5.2 on Ubuntu 16.04. No traceback or error is issued.

Is this some feature or am I doing something wrong?

**Comment by bitprophet** [comment]
I thought I'd heard of this before but I can't find it in the tracker, so this might be the first time it's come up. I'd guess it's a bug and not your fault. Needs someone to reproduce and confirm. Thanks for the report!

**Comment by bitprophet** [comment]
Should be fixed in #912
