### ISSUE TITLE
SSHException: Error reading SSH protocol banner on high latency connections

### ISSUE THREAD

**Issue by lobeck** [paramiko/paramiko#874]
We have several connections which have RTTs between 100 and 250 ms, this causes banner exceptions starting with paramiko 2.0.3.

We were able to pinpoint this to https://github.com/paramiko/paramiko/pull/681

In our observations, we've been a bit over the timeout so it jumps to https://github.com/paramiko/paramiko/pull/681/files#diff-da0434ac18262900f26e452884887940R102 and i suspect, that an incomplete banner is returned, which is causing the failures.

There are no issues with 2.0.2

**Comment by lobeck** [comment]
We've found some other issues which might explain our issues, will take another look and create a new bug, in case it's necessary

**Comment by RONNCC** [comment]
@lobeck  was that your issue by chance -- I think i'm running into something similar?

**Comment by lobeck** [comment]
@RONNCC had the issue with a connection between Europe and US West, due to some packet loss and other high latency effects we had the issue. It cleared after a few hours when the connection got better. Sorry that this might be no help for you.

**Comment by RONNCC** [comment]
Eh for now higher timeouts is working, so maybe?
