### ISSUE TITLE
channel closed during login

### ISSUE THREAD

**Issue by ImmoWetzel** [paramiko/paramiko#881]
dont no what really happens here.
filezilla works fine on this host with port 22 but robotframework which is using paramiko says session closed.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/library.py", line 792, in login
    return self._login(self.current.login, username, password, delay)
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/library.py", line 832, in _login
    login_output = login_method(username, *args)
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/abstractclient.py", line 150, in login
    return self._read_login_output(delay)
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/abstractclient.py", line 165, in _read_login_output
    return self.read(delay)
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/abstractclient.py", line 296, in read
    output = self.shell.read()
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/abstractclient.py", line 103, in shell
    self._shell = self._create_shell()
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/pythonclient.py", line 95, in _create_shell
    self.config.width, self.config.height)
  File "/usr/local/lib/python2.7/dist-packages/SSHLibrary/pythonclient.py", line 101, in __init__
    self._shell = client.invoke_shell(term_type, term_width, term_height)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 467, in invoke_shell
    chan.invoke_shell()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 208, in invoke_shell
    self._wait_for_event()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1161, in _wait_for_event
    raise e

**Comment by bitprophet** [comment]
Only thing that springs to mind would be if filezilla is not adhering to the normal (Open)SSH server spec/behavior.

**Comment by ploxiln** [comment]
The host might allow sftp only, not any other commands over ssh.

**Comment by ImmoWetzel** [comment]
Yes that could be the case and reason. How to overcome this ?

Immo


-------- Original message --------
From: Pierce Lopez
Date:01/02/2017 20:18 (GMT+01:00)
To: paramiko/paramiko
Cc: IMMO WETZEL , Author
Subject: Re: [paramiko/paramiko] channel closed during login (#881)


The host might allow sftp only, not any other commands over ssh.

**Comment by amias-channer** [comment]
try it on the command line , connect with "ssh user@host" and "sftp user@host" , . If it doesn't work on the command line then your server is doing something odd , running ssh with -v can explain a lot more about what is happening. If your server is doing something odd then report it to the admin not here.

**Comment by ImmoWetzel** [comment]
Sftp@host works
Ssh user@host doesnt work.  Cos there is no shell assigned

debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env MANDATORY_PATH
debug3: Ignored env KONSOLE_DBUS_SESSION
debug3: Ignored env KRB5CCNAME
debug3: Ignored env XDG_SEAT
debug3: Ignored env HOME
debug3: Ignored env COLORFGBG
debug3: Ignored env SHLVL
debug3: Ignored env LANGUAGE
debug3: Ignored env KDE_SESSION_VERSION
debug3: Ignored env XCURSOR_THEME
debug3: Ignored env LOGNAME
debug3: Ignored env XDG_SESSION_DESKTOP
debug3: Ignored env DBUS_SESSION_BUS_ADDRESS
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env LESSOPEN
debug3: Ignored env DISPLAY
debug3: Ignored env PROFILEHOME
debug3: Ignored env XDG_RUNTIME_DIR
debug3: Ignored env XDG_CURRENT_DESKTOP
debug3: Ignored env LESSCLOSE
debug3: Ignored env PAM_KWALLET_LOGIN
debug3: Ignored env XAUTHORITY
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 131072 rmax 98304
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug3: receive packet: type 100
debug2: channel_input_status_confirm: type 100 id 0
shell request failed on channel 0

**Comment by amias-channer** [comment]
so this is a server config problem and nothing that paramiko can sort out

**Comment by ploxiln** [comment]
https://github.com/paramiko/paramiko/blob/master/demos/demo_sftp.py suggests that maybe paramiko should ideally/theoretically be able to do sftp?

But it seems likely that "robotframework" would not be designed for pure sftp (but I'm not familiar with it).

**Comment by bitprophet** [comment]
Paramiko definitely supports SFTP, but for whatever reason, the program using us is still attempting to call `open_shell` instead - check the middle section of the original traceback.

So yea, if the server's not configured for actual shell session type channels, the only real hope I see here is to figure out why robotframework/SSHLibrary is trying to open one when you're expecting only SFTP traffic. Good luck - not familiar with it unfortunately :(

**Comment by piyh** [comment]
https://github.com/paramiko/paramiko/blob/master/demos/demo_sftp.py

This demo code should resolve the issue, just can't do the normal client object
