### ISSUE TITLE
Client unable to handle ecdsa-sha2-nistp256 based hosts

### ISSUE THREAD

**Issue by Paradoxis** [paramiko/paramiko#883]
I'm currently using Paramiko to connect to my local SSH server, I'm running into issues however when the server in my known hosts file is using `ecdsa-sha2-nistp256`. Is there any way of adding support for this?

I'm currently using version *2.1.1* on *Python 3.6.0*

This is the code I'm using:
```
self.client = SSHClient()
self.client.load_system_host_keys()
self.client.connect(
    hostname=self.config.server_address,
    port=self.config.server_port,
    username=self.config.auth_username,
    pkey=self.config.auth_public_key )
```

**Comment by ploxiln** [comment]
What are the issues specifically?

In my experience, ecdsa host keys work if only the ecdsa key is configured on the server side (no rsa key as well). They're supported, but key _selection_ is deficient.

**Comment by bitprophet** [comment]
@ploxiln beat me to it - we support that key type last I checked, but there can be issues re: whether both sides of the cxn agree on that particular key and/or algo/cipher.

This has come up a bunch before, see the [Keys label](https://github.com/paramiko/paramiko/labels/Keys) and I think a banner issue / appropriate duplicate would be #794.
