### ISSUE TITLE
Coveralls needs OAuth

### ISSUE THREAD

**Issue by KalleDK** [paramiko/paramiko#886]
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

https://coveralls.io/builds/9989839/source?filename=paramiko%2Fhostkeys.py

**Comment by bitprophet** [comment]
Actually been meaning to switch Paramiko to CodeCov which has seemed a bit better...

Did just sign in and it requested a re-oauth; I now get a different error there, it's claiming it can't find the file at all. Wondering if this is an issue on coveralls' side. But given above, don't have time to really dig into it XD
