### ISSUE TITLE
paramiko.SSHConfig does not parse or use Match blocks

### ISSUE THREAD

**Issue by mleinart** [paramiko/paramiko#896]
OpenSSH added syntax for a new type of config block in 4.4 https://www.openssh.com/txt/release-4.4:

    Implemented conditional configuration in sshd_config(5) using the
    "Match" directive. This allows some configuration options to be
    selectively overridden if specific criteria (based on user, group,
    hostname and/or address) are met. So far a useful subset of post-
    authentication options are supported and more are expected to be
    added in future releases.

Paramiko's current behavior in the case of a Match block is worse than just ignoring the blocks: the match line will be added as if it were a normal option to whatever the previous Host config was (or to the global ['*'] one if none proceeded it) along with the Match block's configs. 

This effectively makes any ssh_config with Match blocks in it unable to be used safely with Paramiko

**Comment by bitprophet** [comment]
Duplicates #717; doesn't look like anyone's supplied a PR for that yet unfortunately :( Will leave a longer comment over there covering the safety angle you bring up tho, thanks!
