### ISSUE TITLE
Paramiko does not respect CanonicalizeHostname and related options

### ISSUE THREAD

**Issue by mleinart** [paramiko/paramiko#897]
Openssh 6.5 introduced the ability for clients to canonicalize ambiguous hostnames for matching in known_hosts and Host config blocks https://www.openssh.com/txt/release-6.5:

    ssh(1): Add support for client-side hostname canonicalisation
    using a set of DNS suffixes and rules in ssh_config(5). This
    allows unqualified names to be canonicalised to fully-qualified
    domain names to eliminate ambiguity when looking up keys in
    known_hosts or checking host certificate names.

And related from https://www.openssh.com/txt/release-6.6:

    ssh(1): if hostname canonicalisation is enabled and results in the
    destination hostname being changed, then re-parse ssh_config(5) files
    using the new destination hostname. This gives 'Host' and 'Match'
    directives that use the expanded hostname a chance to be applied.

Paramiko currently ignores this setting and uses the hostname as-is in all cases

**Comment by mleinart** [comment]
This is somewhat related to #896 as the 'canonical' and 'originalhost' Matches are very useful in combination with CanonicalizeHostnames

**Comment by bitprophet** [comment]
Noting that #896 duped #717 which is the master ticket for implementing `Match`.

Agree that I'd like to see us support the canonicalization features.

**Comment by bitprophet** [comment]
This is done enough! What's obviously missing:

- `CanonicalizePermittedCNAMEs` - lots of fiddly coding/testing for a presumably less critical edge case, deferred
- `Proxy(Command|Jump)` honoring of whether `CanonicalizeHostname` is `yes` or `always` - that's not Paramiko's own concern at this time but would be implemented in the downstream library, such as Fabric. (Fabric is not getting support for that at this time, which basically means that `yes` acts like `always`, for now, I think...)

**Comment by bitprophet** [comment]
Also, when testing how this impacts `IdentityFile` I found an unreported bug around duplication in that value; eg say you had two stanzas that both applied and both said `IdentityFile foo` - you'd end up with `["foo", "foo"]`. Not super problematic - just means clients would potentially try the same key >1 time - but still dumb and can cost you authentication attempts or whatever.

This became even more obvious under canonicalization's triggering of a 2nd parse pass. It's now tested for and in the changelog as fixed.

**Comment by bskinn** [comment]
> Hi, could you at least merge something like [1e50709](https://github.com/paramiko/paramiko/commit/1e5070936aff684852d115a39e5834809d09bc90) to avoid `KeyError: 'canonicaldomains'` for those that set `CanonicalizeHostname always`?


This seems like a separate concern, @totaam, especially given this ticket was closed as completed more than four years ago.

Is this commit you reference part of another PR? If so, please comment on that PR to mark your interest in its being merged.

If it's not part of another PR, please create a new ticket for the fix. Either an issue with this request, if you're not comfortable making the requested changes yourself; or, a PR with the implementation.

**Comment by totaam** [comment]
> This seems like a separate concern

This is a direct result of the code added in this issue.

> please create a new ticket for the fix

https://github.com/paramiko/paramiko/pull/2338

**Comment by bskinn** [comment]
> This is a direct result of the code added in this issue.

Of course, my apologies, I didn't express myself well there.

It would have been better had I said, "This seems like something best addressed in a separate issue/PR ..."

Thanks for the new PR!

**Comment by totaam** [comment]
It was addressed in a new PR: #2338

This trivial one liner fix (with test) has been waiting there since last year.
