### ISSUE TITLE
What's the difference about `session` channel and `direct-tcpip` channel ?

### ISSUE THREAD

**Issue by ibuler** [paramiko/paramiko#898]
I want to build a ssh server support proxy and direct connect, like 

```
$ ssh -p2222 admin@localhost 
$ ssh -o ProxyCommand="ssh -p2222 -W %h:%p admin@localhost" root@other_host
```

Then, I find direct connect channel kind is 'session' and proxy channel kind is 'direct-tcpip',

```
class SSHInterface(paramiko.ServerInterface):
    ....
    def check_channel_shell_request(self, channel):
        request.method = 'shell'
        return True

    def check_channel_direct_tcpip_request(self, chanid, origin, destination):
        request.method = 'direct_tcpip'
        return paramiko.OPEN_SUCCEEDED

....
chan = transport.accept(20)
....

if request.method == 'shell':
    logger.info('Session')
    chan.send('Session')
elif request.method == 'direct_tcpip':
    logger.info('Direct tcpip')
    chan.send('Direct tcpip')
else:
....

```

Session channel work fine, but direct tcpip channel doesn't work (client recv nothing, but server can print log "Direct tcpip")  and no exception raise.

What's the difference about them ?

Thanks

**Comment by ibuler** [comment]
Get it, `direct-tcpip` channel just a sock, send method just send raw sock message, so the the raw message couldn't be read by client.  `session` channel message is ssh protocal message, client konw that

**Comment by bitprophet** [comment]
You've got it :)
