### ISSUE TITLE
Release 1.15.1 : SSH cmd args size limit crossed

### ISSUE THREAD

**Issue by atmneo** [paramiko/paramiko#905]
I am using Paramiko v1.15.1
While executing a fairly large ssh cmd (more than 8000 chars), I am having trouble with exec_command. It fails to take all args. I think paramiko trims the cmd to some limit
When I run the same command through "normal ssh" command - I am able to see the expected output.

Is there a place where I can increase the cmd length size/default it to ssh?
Appreciate any responses

**Comment by bitprophet** [comment]
Paramiko is not doing any trimming that I can see; it takes your string and hands it directly to the network bits, with the only intermediate steps being some basic string-to-bytes handling (which, again, is not doing any explicit truncation of any kind).

You may be running into a core Python bug or limitation, I feel like I've heard of that before; it's worth googling for.

To be super clear, you mean that you're doing `SSHClient().exec_command('a string that is greater than 8000 chars long')`, right?

**Comment by atmneo** [comment]
Yes, your example fits the command that I am running.
Thanks for the feedback though.

**Comment by bitprophet** [comment]
Also, a detailed traceback might provide a clue :)

**Comment by atmneo** [comment]
So, turns out the issue wasn't with Paramiko. :)

I am using the bash read cmd to get stdin .... and there is a os limit on the bytes that can be part of ur sys read calls -- apparently for some systems its a page size (4k)
Hence I have to figure out how to change that limit (either through setvbuf) or find something else to get me stdin data

Thanks for the help though. Appreciate it.

**Comment by ajinkyapande** [comment]
Hello @atmneo , 

Did you found issue for increasing bytes limit ? I am having the same issue

**Comment by Sea-Snell** [comment]
Hey, did either of you figure this out by any chance?
