### ISSUE TITLE
hostname canonicalization with GSSAPI

### ISSUE THREAD

**Issue by pseudometric** [paramiko/paramiko#915]
In `Transport.set_gss_host()`, there is this:

```
# We need the FQDN to get this working with SSPI
self.gss_host = socket.getfqdn(gss_host)
```

This is a common mistake in GSSAPI programming, and a misunderstanding. I'm sure the author needed to canonicalize the hostname in order to get his test case working with SSPI, but that does not mean it's the right thing to do in general.

When using hostbased-service names with GSSAPI (type GSS_C_NT_HOSTBASED_SERVICE) — the usual case — GSSAPI clients should pass the hostname exactly as provided by the user. It should *not* be canonicalized or altered in any way, because Kerberos implementations have their own name canonicalization policies when handling this name type, and it may not match. For example, if you are using MIT Kerberos and you set libdefaults.rdns = no in krb5.conf, this turns off the reverse-address component of hostname canonicalization — but the Python socket.getfqdn() still does it.

At a well-administered Kerberos site, the DNS and Kerberos principal names are coordinated, together with the local name canonicalization policy, so that everything works as expected. Applications that take it upon themselves to alter the hostname before passing it to GSSAPI will just break that correspondence in some cases, and not work properly.

It *is* useful to have a parameter like `gss_host`, so that users can override the hostname in cases where the site setup is wrong and names don't match. (Compare GSSAPIServerIdentity in OpenSSH. Even more useful is an option to pass a literal Kerberos principal name instead, bypassing the hostname entirely and providing complete flexibility) But, that would be the opposite of the current treatment of `gss_host`: it would *not* be canonicalized if passed. Worse, the current behavior of `gss_host` is inconsistent in this regard anyway: calling `set_gss_host()` canonicalizes, while passing `gss_host` as a parameter to the Transport init() routine does not, giving confusing behavior. It means that I can specify the literal GSSAPI hostname and fix the problem with this:

```
  t = paramiko.Transport((server, 22))
  t.connect(username = os.environ['LOGNAME'],
            gss_host = server,
            gss_auth = True,
            gss_kex  = True)
```

but not with this:

```
  ssh = paramiko.SSHClient()
  ssh.connect( hostname = server,
               gss_host = server,
               gss_auth = True,
               gss_kex  = True)
```

because the latter calls `set_gss_host()` and canonicalizes, while the former does not.

Finally, the code as-is is not in fact even right for SSPI. Windows behaves like MIT Kerberos with libdefaults.rdns = no: it does not reverse-map addresses, rather only resolving aliases (DNS CNAMEs) — so it does not match the behavior of socket.fqdn().

Since fixing the discrepancy in the behavior the kwarg `gss_host` vs `set_gss_host()` means that some existing use cases are bound to break, I would take the simplest route to fixing this: remove the canonicalization entirely, and tell people that if they need to change the hostname before passing it to Paramiko to deal with broken DNS/Kerberos correspondence at their site, they'll have to do that themselves.

If you think it's more important to preserve the canonicalization, then I suggest:

1. Fix the inconsistency by ensuring that `gss_host` is always canonicalized, regardless of how it's given.

1. Add a `gss_canonicalize` option controlling that, default true, preserving (some of) the current behavior. Setting this to false will give the more generally correct behavior, and also allow users to override the hostname effectively if needed.

**Comment by bitprophet** [comment]
First, thanks for the detailed explanation of the issue, greatly appreciated!

I'm a big fan of backwards compatibility so I don't think the "remove canonicalization" option is feasible before 3.0. That said, 3.0 is a real milestone that will be executed on sometime prior to the universe's heat death, there's other stuff already in there that I'll get to at some point. (tl;dr periodic backwards incompat releases should be a real thing.)

As a non-user of GSSAPI/etc, I'll defer to you and perhaps the original author of this functionality (@SebastianDeiss) as to which backwards compat option is most desirable; from what you've said it sounds like adding the param controlling canonicalization (and applying it consistently) is the most useful.

----

This also seems like another unfortunate example of code specific to SSHClient; the deeper I get my claws into all of this the more I dislike the API discrepancies between it and Transport. Anytime someone _has_ to muck with the raw Transport to work around problems in SSHClient, it's non-ideal. And of course, the fact that folks often have to add new params in both places is also annoying. But this is mostly a gripe to myself and not something actionable here.

**Comment by SebastianDeiss** [comment]
Basically we need an option wheter or not the FQDN of the host to connect to should be determined by DNS or not.
So, I added the parameter ``gss_trust_dns`` in ``client.py`` and ``transport.py``.  Set by default to ``True`` the parameter indicates whether or not the DNS is trusted to securely canonicalize the hostname of the target host. If set to ``False`` the hostname  entered will be passed to GSSAPI.
This option behaves like ``GSSAPITrustDNS`` from OpenSSH.

Also, the option ``gss_host``, if set, can be used to override the ``hostname`` for GSSAPI and herefore might be considered as the equivalent to ``GSSAPIServerIdentity `` from OpenSSH.

**Comment by SebastianDeiss** [comment]
@pseudometric: You may want to take a look at pull #919 to check if the patch solves your issue.

**Comment by bitprophet** [comment]
Let's assume #1063 fixes this; please comment if it does not and we can reopen.
