### ISSUE TITLE
Intel RDRAND support

### ISSUE THREAD

**Issue by cobaltjacket** [paramiko/paramiko#924]
Is it possible for paramiko to support rdrand for key generation?

**Comment by SethMichaelLarson** [comment]
Probably safer to just rely on `os.urandom` as the source of randomness.

**Comment by bitprophet** [comment]
Which is also what our crypto backend recommends: https://cryptography.io/en/latest/random-numbers/

Speaking of which, that's also probably the right place for this sort of request; our e.g. RSAKey generation doesn't set up any random numbers I can see offhand - that level of maths is delegated to the crypto backend.

I searched their repo and the only real mention of RDRAND is in this merged PR: https://github.com/pyca/cryptography/pull/98 - I don't know the library well myself so I don't know if that `engine` module is/can be used elsewhere (e.g. by the `cryptography.hazmat.primitives` subpackages we use in our key generation methods).

**Comment by ploxiln** [comment]
It is definitely cryptography's domain to pick and use the random number generator.

It currently uses the best operating-system provided system call: https://github.com/pyca/cryptography/blob/master/src/_cffi_src/openssl/src/osrandom_engine.h
