### ISSUE TITLE
paramiko.ssh_exception.SSHException: SSH session not active

### ISSUE THREAD

**Issue by shekharsingh** [paramiko/paramiko#928]
I am running a python program which logs in to server & run certain commands for next 5 minutes. I have set the ssh inactivity timeout as 3 minute. When running these set of command with paramiko library, the session timeout exactly at 3 minute But when I try to run with help of pywinauto library it works fine. I have following questions 
1. Is this an issue with existing paramiko library?
2. Whether paramiko opens an interactive session or not? Because it seems to me that the session is not interactive.
Here is my script :- 
`
import sys
import time
import select
import paramiko
host = 'myhost.com'
i = 1
while True:
    print ("Trying to connect to %s (%i/30)" % (host, i))

    try:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(host,username='user',password='pass')
        print ("Connected to %s" % host)
        break
    except paramiko.AuthenticationException:
        print ("Authentication failed when connecting to %s" % host)
        sys.exit(1)
    except:
        print ("Could not SSH to %s, waiting for it to start" % host)
        i += 1
        time.sleep(2)
    if i == 30:
        print ("Could not connect to %s. Giving up" % host)
        sys.exit(1)

iteration = 0
while True:

    stdin, stdout, stderr = ssh.exec_command("cmd1")
    while not stdout.channel.exit_status_ready():
        if stdout.channel.recv_ready():
            rl, wl, xl = select.select([stdout.channel], [], [], 0.0)
            if len(rl) > 0:
                print (stdout.channel.recv(1024))
    time.sleep(20)

    stdin, stdout, stderr = ssh.exec_command("cmd2")
    while not stdout.channel.exit_status_ready():
        if stdout.channel.recv_ready():
            rl, wl, xl = select.select([stdout.channel], [], [], 0.0)
            if len(rl) > 0:
                print (stdout.channel.recv(1024))
    time.sleep(20)

    stdin = ssh.exec_command("\n")
    if iteration == 6:
        sys.exit(1)
    print(iteration)
    iteration += 1

print ("Command done, closing SSH connection")
ssh.close()
`

Error :- 

Traceback (most recent call last):

Anaconda3\lib\site-packages\paramiko\client.py", line 436, in exec_command
    chan = self._transport.open_session(timeout=timeout)
Anaconda3\lib\site-packages\paramiko\transport.py", line 716, in open_session
    timeout=timeout)
 \Anaconda3\lib\site-packages\paramiko\transport.py", line 800, in open_channel
    raise SSHException('SSH session not active')
    paramiko.ssh_exception.SSHException: SSH session not active

**Comment by Aisuko** [comment]
Same problem with you,
```python3.5.2 . paramiko==2.4.2```

```
=================================== FAILURES ===================================
________________________________ test_hostname _________________________________

ros_kvm_create = <function ros_kvm_create.<locals>._ros_kvm_create at 0x7f3970b71ea0>
cloud_config_url = 'https://raw.githubusercontent.com/cnrancher/os-tests/master/assets/'

    def test_hostname(ros_kvm_create, cloud_config_url):
        command = 'hostname'
        feed_back = 'rancher-test'
        kwargs = dict(is_install_to_hard_drive=True)
        information = ros_kvm_create(cloud_config='{url}/test_hostname.yml'.format(url=cloud_config_url), **kwargs)
    
        client = information[0]
>       stdin, stdout, stderr = client.exec_command(command, timeout=10)

engine/test_hostname.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.5/dist-packages/paramiko/client.py:493: in exec_command
    chan = self._transport.open_session(timeout=timeout)
/usr/local/lib/python3.5/dist-packages/paramiko/transport.py:806: in open_session
    timeout=timeout,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <paramiko.Transport at 0x6b260cc0 (unconnected)>, kind = 'session'
dest_addr = None, src_addr = None, window_size = None, max_packet_size = None
timeout = 10

    def open_channel(
        self,
        kind,
        dest_addr=None,
        src_addr=None,
        window_size=None,
        max_packet_size=None,
        timeout=None,
    ):
        """
        Request a new channel to the server. `Channels <.Channel>` are
        socket-like objects used for the actual transfer of data across the
        session. You may only request a channel after negotiating encryption
        (using `connect` or `start_client`) and authenticating.
    
        .. note:: Modifying the the window and packet sizes might have adverse
            effects on the channel created. The default values are the same
            as in the OpenSSH code base and have been battle tested.
    
        :param str kind:
            the kind of channel requested (usually ``"session"``,
            ``"forwarded-tcpip"``, ``"direct-tcpip"``, or ``"x11"``)
        :param tuple dest_addr:
            the destination address (address + port tuple) of this port
            forwarding, if ``kind`` is ``"forwarded-tcpip"`` or
            ``"direct-tcpip"`` (ignored for other channel types)
        :param src_addr: the source address of this port forwarding, if
            ``kind`` is ``"forwarded-tcpip"``, ``"direct-tcpip"``, or ``"x11"``
        :param int window_size:
            optional window size for this session.
        :param int max_packet_size:
            optional max packet size for this session.
        :param float timeout:
            optional timeout opening a channel, default 3600s (1h)
    
        :return: a new `.Channel` on success
    
        :raises:
            `.SSHException` -- if the request is rejected, the session ends
            prematurely or there is a timeout openning a channel
    
        .. versionchanged:: 1.15
            Added the ``window_size`` and ``max_packet_size`` arguments.
        """
        if not self.active:
>           raise SSHException("SSH session not active")
E           paramiko.ssh_exception.SSHException: SSH session not active

/usr/local/lib/python3.5/dist-packages/paramiko/transport.py:896: SSHException
```

**Comment by chrisinmtown** [comment]
Arriving at this about 6 years late :/  Maybe the `exec_command` documentation should state that the session will be deactivated on completion, and this method should only be used when a single command needs to be run? Please comment, thanks in advance.

**Comment by bskinn** [comment]
> the `exec_command` documentation should state that the session will be deactivated on completion, and this method should only be used when a single command needs to be run?

@jun66j5 -- is this accurate regarding the behavior of `exec_command`, and the docs should note this?

**Comment by jun66j5** [comment]
> Arriving at this about 6 years late :/ Maybe the `exec_command` documentation should state that the session will be deactivated on completion, and this method should only be used when a single command needs to be run? Please comment, thanks in advance.

That is not right. `SSHClient.exec_command` can be invoked multiple times, not just once.

```pycon
>>> import paramiko
>>> paramiko.__version__
'3.1.0'
>>> def reader(f, buf):
...     while True:
...         data = f.read(256)
...         if not data:
...             return
...         buf.extend(data)
...

>>> def writer(channel, f, data):
...     chunk_size = 256
...     n = len(data)
...     pos = 0
...     while not channel.exit_status_ready():
...         chunk = data[pos:pos+chunk_size]
...         if not chunk:
...             break
...         pos += chunk_size
...     f.close()
...
>>> def run(cli, command, data=b''):
...     fin, fout, ferr = cli.exec_command(command)
...     channel = fout.channel
...     bufout = bytearray()
...     buferr = bytearray()
...     thin = threading.Thread(target=writer, args=(channel, fin, data))
...     thout = threading.Thread(target=reader, args=(fout, bufout))
...     therr = threading.Thread(target=reader, args=(ferr, buferr))
...     for th in (thin, thout, therr):
...         th.daemon = True
...         th.start()
...     while not channel.exit_status_ready():
...         time.sleep(0.125)
...     thin.join()
...     therr.join()
...     thout.join()
...     exit_status = channel.recv_exit_status()
...     return exit_status, bytes(bufout), bytes(buferr)
...
>>> cli = paramiko.SSHClient()
>>> cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> cli.connect('127.0.0.1', username='jun66j5', allow_agent=True, look_for_keys=False)
>>> result = run(cli, 'dd if=/dev/urandom bs=256 count=1')
>>> result[0]
0
>>> result[1]
b"b\xa8bqx}\xcd&\xfd>\x18\xcc\xf7=\x16l\xfbA\xba\xae\xcdQ\xd4G\x9d$]\xd4\xf7A6\xa1\xd9:\x02:T\xc3\x96\xa0\x17)*\xd4@\xadx@\xe0\x8c\xdc+)o\x1f\xbf\xd2\x01\xf8\x85q\x9e;\r\xc8+\xa5\x1b\xadN\xb84\x97\x1d6\xd4\xc1\xeb\xc03E:\xca~\x91\xf9+=\xff\x1c\x8fv=\xe2XF\xd9\x86\xcf\xcd\xd2\xe9\xb4m\xac\xcdupK\xfa\x03\xf7\xef|\xab\x17o\x1d\x9e\xcfQO\xfc'l\x14\x99`\x0f6Z~.aL!\xd1:\xe6\xed\xb9d\xa9\r\xe6\x94\xc4\x92\x03W\x11\xeae<G_x%\x1c\xd3=\x9a\xb8\x94\x1e\xfa\x85+Qi\xe4\xd6\x05\r^\x1f.R)F] \x04f\xf7\np\x1b\xd4\xd8v\x1f\x02\x9f\x87\x8fq^]\xe5\xb2\x16\xea\xef|2e\xbd\x8a\xfb,^q\x84\xffo\xe4\xbe\xdd\xcew\xd5(7\x0c\xcf\xb7!8\x8fK)\x07\t\xfd2\x97r7\x8cT\x0c[\xb8X\xd9\xed[d\xa9\x1e\xc5\xb1C\x1ba"
>>> result[2]
b'1+0 records in\n1+0 records out\n256 bytes copied, 2.0565e-05 s, 12.4 MB/s\n'
>>> len(result[1])
256
>>> run(cli, 'date -R')
(0, b'Tue, 25 Apr 2023 18:09:58 +0900\n', b'')
>>> run(cli, 'date -R')
(0, b'Tue, 25 Apr 2023 18:10:00 +0900\n', b'')
>>> run(cli, 'date -R')
(0, b'Tue, 25 Apr 2023 18:10:01 +0900\n', b'')
>>> run(cli, 'date -R')
(0, b'Tue, 25 Apr 2023 18:10:03 +0900\n', b'')
```

**Comment by bskinn** [comment]
Closing this ticket since it's for support and several years old.

If anyone is having similar difficulties, please open a new ticket instead of commenting on this one.

**Comment by MileanCo** [comment]
We are also experiencing this issue:

> Traceback (most recent call last):
   File "/nxtest/workspace/test/lib/sds/traffic/subprocess.py", line 981, in execute_raw_command
     _, stdout, stderr = self._client.exec_command(cmd, timeout=timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/paramiko/client.py", line 560, in exec_command
     chan = self._transport.open_session(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/paramiko/transport.py", line 959, in open_session
     return self.open_channel(
            ^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/paramiko/transport.py", line 1053, in open_channel
     raise SSHException("SSH session not active")
 paramiko.ssh_exception.SSHException: SSH session not active

This is how we create the client

`
        client = paramiko.SSHClient()

        client.set_missing_host_key_policy(paramiko.client.AutoAddPolicy())
        client.connect(hostname=hostname, port=22,
                       username=username, password=pwd, look_for_keys=False,
                       timeout=timeout, banner_timeout=timeout, auth_timeout=timeout,
                       allow_agent=False)
        return client`

How do you increase the ssh inactivity timeout? Im thinking that we get this error when its been some time since the last `exec_command` was issued. Otherwise this code works fine.
