### ISSUE TITLE
PKey from_private_key_file exception

### ISSUE THREAD

**Issue by Gerardwx** [paramiko/paramiko#938]
```#!/usr/bin/env python3
from paramiko import PKey

pk = PKey.from_private_key_file(filename="anon_rsa")
```
Traceback (most recent call last):
  File "./demo.py", line 4, in <module>
    pk = PKey.from_private_key_file(filename="anon_rsa")
  File "/usr/local/lib/python3.5/dist-packages/paramiko/pkey.py", line 196, in from_private_key_file
    key = cls(filename=filename, password=password)
TypeError: __init__() got an unexpected keyword argument 'filename'

**Comment by ploxiln** [comment]
http://docs.paramiko.org/en/2.1/api/keys.html#paramiko.pkey.PKey.from_private_key_file

> Through the magic of Python, this factory method will exist in all subclasses of PKey (such as RSAKey or DSSKey), but is useless on the abstract PKey class.

Try using the `RSAKey` class.
