### ISSUE TITLE
Segmentation fault while connecting to a host paramikoV2.1.2

### ISSUE THREAD

**Issue by HumbleFool006** [paramiko/paramiko#943]

**Comment by ploxiln** [comment]
This will require much *much* information to debug.

**Comment by psoracle2015** [comment]
I had the same problem. Everything is ok for my mac 10.12.6, python 3.5.2, but run error on centos 7.0 server. I found the problem from cryptography==2.0, get right to upgrade to 2.1.4.

**Comment by psoracle2015** [comment]
https://github.com/pyca/cryptography/issues?utf8=%E2%9C%93&q=Segmentation+fault
