### ISSUE TITLE
BadHostKeyException 

### ISSUE THREAD

**Issue by shehzi-khan** [paramiko/paramiko#948]
I'm trying to follow your demo as given below

```
import base64
import paramiko
key = paramiko.RSAKey.from_private_key_file('private.key')
client = paramiko.SSHClient()
client.get_host_keys().add('<servername>', 'ssh-rsa', key)
client.connect('<servername>', username='root')
```

Last statement throws BadHostKeyException as given below.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\paramiko\client.py", line 367, in connect
    raise BadHostKeyException(hostname, server_key, our_server_key)
paramiko.ssh_exception.BadHostKeyException: ('<servername>', <paramiko.rsakey.RSAKey object at 0x04075B70>, <paramiko.rsakey.RSAKey object at 0x03CB82F0>)

```

The key file is the same I have been using for a month now and I'm unable to understand what is the problem.

**Comment by ploxiln** [comment]
Can you please specify
  * which demo file you are trying to follow
  * what version of paramiko you are using
  * the size of the rsa host key

It's unusual for the client to have the host _private_ key, it typically has the host _public_ key ... is that your user authorization rsa key by any chance?

**Comment by bitprophet** [comment]
That sounds likely to me too @ploxiln.

Also, I don't see code like that snippet in our demos; is it an old demo? (Git history search didn't turn it up either, though.)

Going to close as "probably user error" but leaving discussion open.
