### ISSUE TITLE
How to deamon a process?

### ISSUE THREAD

**Issue by Samarpitr** [paramiko/paramiko#954]
I have used both nohup and appending & in the last of command but these ways are not working. I am getting out of exec_command() is not blocking but problem is that shell script executed on server is not longer. Shell script get stopped.

**Comment by SethMichaelLarson** [comment]
Have you tried using the process daemonizing features available on the host you're connecting to?

**Comment by Samarpitr** [comment]
No, I do not have any idea about it. Help will be appreciated.

**Comment by SethMichaelLarson** [comment]
If you're running a command on Linux I suggest reading [this StackOverflow answer](https://unix.stackexchange.com/questions/4004/how-can-i-close-a-terminal-without-killing-the-command-running-in-it). You should probably close this issue, this doesn't concern Paramiko.

In the future you should probably do some research on Google before opening issues.
