### ISSUE TITLE
python2.7 use paramiko to execute expect script in the remote server

### ISSUE THREAD

**Issue by zhangzheyuk** [paramiko/paramiko#960]
I used paramiko to connect to the server. then I tried to invoke one tcl/expect script.

below is the content of the script:
```
#!/usr/bin/expect
spawn icsconsole
expect ":"
send "2\r"
send " \r"
...
interact
exit
```

the script tried to handle a command line  tool - icsconsole.

I used paramiko like this 
```python
cmd = "sh /home/xxx/xxx.exp"
stdin, stdout, stderr = ssh.exec_command(cmd)
print stdout.read()
```

It seems that the script cannot be invoked by the python program. Could u pls help me about this?

**Comment by ploxiln** [comment]
Please learn to use fenced code blocks https://help.github.com/articles/creating-and-highlighting-code-blocks/

You wrote `sh /home/xxx/xxx.exp`. That won't work. You could do `expect /home/xxx/xxx.exp`, or just `/home/xxx/xxx.exp` if the script is marked executable.

Once you get the script actually running, "interact" won't work if you run it with `exec_command()` that way. But this is a more complicated topic...

**Comment by zhangzheyuk** [comment]
sorry for the mistake, I tried like this..

```python
ssh.connect(xx)
...
chan = ssh.invoke_shell()
chan.send("expect xxx/xxx.exp" + "\n")
print chan.recv(65535).decode('utf-8')
```
It only print the login message like this:
Last login: Thu xxxxxx  from xxxxxx

**Comment by ploxiln** [comment]
you're going to need to `.recv_stderr()` as well to see error messages printed by the command

**Comment by zhangzheyuk** [comment]
I want to change the solution to invoke the cmd line tool directly...Could you pls give me some advices? I had used lots of functions...but all of these didn't work...

**Comment by zhangzheyuk** [comment]
@ploxiln 
THX for your help, I had solved it...
Here is my solution:

```python
sshcmd = "~/xxx/icsconsole"
command_list  = ["2\n", "3\n", "\n" ....]
stdin, stdout, stderr = ssh.exec_command(sshcmd)
for each in comand_list:
    stdin.write(each)
    stdin.flush()
print '\n'.join(stdout.readlines())
```

**Comment by bitprophet** [comment]
@zhangzheyuk or check out http://fabfile.org which makes that a lot easier (especially its new `v2` branch)!

**Comment by kundansharmaindia** [comment]
cmd="ls"
stdin, stdout, stderr = ssh.exec_command(cmd)
Unable to execute this command and terminal not responding.
