### ISSUE TITLE
Upgrading from paramiko 1.7.7.1

### ISSUE THREAD

**Issue by UserName011** [paramiko/paramiko#966]
Hi,
we use paramiko 1.7.7.1 which is very old.
We use it for 2 different server.
We want to upgrade it to the latest version.

Where can we find information what should be installed on the server in order to work well with the new paramiko ? Currently we get errors:

> SSHException: Incompatible ssh peer (no acceptable kex algorithm)

We understand that upgrade the package can solve it but we didn't find any information of what the package expects to "have" on the server side? Which SSL or other issues?

**Comment by bitprophet** [comment]
(Going to close this as "no bug to fix" but conversation remains open.)

If by 'server' you mean the SSH target host, you should not need anything new for newer Paramiko versions.

If you mean the system Paramiko is installed on (the SSH client), the latest versions need OpenSSL and lib-ffi development headers - see [the install page](http://www.paramiko.org/installing.html), including its link to Cryptography's install page.

**Comment by UserName011** [comment]
@bitprophet  I'm connecting to servers which I'm not responsible of. I have no idea what is installed there and what is not. All I know is that it's working with paramiko 1.7.7.1 
I want to upgrade the paramiko package from my side.
All I do with it is connect with ssh 

Since I'm doing the upgrade from my side I need to tell the other server owners what they need to upgrade from their side. What do we need to check in the other servers to make sure that my paramiko update won't cause problems?

**Comment by bitprophet** [comment]
They should not need to upgrade anything, as far as I know! That would only be the case if we removed features (like removing support for an old algorithm), which so far, we have not.

**Comment by UserName011** [comment]
OK. Thx.

Where  can I read about the change log since this version?
Which version do you recommend update to?

**Comment by bitprophet** [comment]
Changelog is at http://www.paramiko.org/changelog.html.

I would try the latest version, 2.1.2. It needs a different crypto backend so make sure to read the [installation docs](http://www.paramiko.org/installing.html). If that is a pain for you, then use the latest 1.18.x version instead, it still uses PyCrypto but gets less feature support.

**Comment by UserName011** [comment]
@bitprophet  does it make scene that I don't have cryptography package installed?!
