### ISSUE TITLE
BufferedFile TypeError on write with buffer API objects

### ISSUE THREAD

**Issue by bz2** [paramiko/paramiko#967]
Unlike normal files, the paramiko `BufferedFile.write()` method throws a `TypeError` if passed an object that implements the [buffer API](https://docs.python.org/2/c-api/buffer.html), such as the builtin [`memoryview`](https://docs.python.org/2/library/stdtypes.html#memoryview) type.

Note this a Python 3 flavoured version of #285 from porting that code away from the old `buffer` type.

```
Traceback (most recent call last):
  ...
  File ".../osutils.py", line 753, in pump_string_file
    write(view[offset:offset+segment_size])
  File ".../paramiko/file.py", line 375, in write
    data = b(data)
  File ".../paramiko/py3compat.py", line 47, in b
    raise TypeError("Expected unicode or bytes, got %r" % s)
TypeError: Expected unicode or bytes, got <memory at 0x7f0ce4d08510>
```

Paramiko should not care about the types it is passed, provided they are `len`-able and can be written to the underlying (`BytesIO` here) object.

**Comment by bz2** [comment]
Missed the full path through `SFTPFIle` with the first pass fix, there's a secondary failure:
```
Traceback (most recent call last):
  ...
  File ".../breezy/osutils.py", line 753, in pump_string_file
    write(view[offset:offset+segment_size])
  File ".../paramiko/file.py", line 339, in write
    self._write_all(data)
  File ".../paramiko/file.py", line 456, in _write_all
    count = self._write(data)
  File ".../paramiko/sftp_file.py", line 176, in _write
    self._reqs.append(self.sftp._async_request(type(None), CMD_WRITE, self.handle, long(self._realpos), data[:chunk]))
  File ".../paramiko/sftp_client.py", line 748, in _async_request
    raise Exception('unknown type for %r type %r' % (item, type(item)))
Exception: unknown type for <memory at 0xb5613b70> type <type 'memoryview'>
```

Looks like _async_request should just try treat args as string by default.

**Comment by bitprophet** [comment]
Rolling into the final PR. Thanks!
