### ISSUE TITLE
Channel Exception on write with buffer API objects

### ISSUE THREAD

**Issue by bz2** [paramiko/paramiko#968]
Similar to #967, the paramiko socket-like `Channel.send()` method throws an `Exception` if passed an object that implements the [buffer API](https://docs.python.org/2/c-api/buffer.html), such as the builtin [`memoryview`](https://docs.python.org/2/library/stdtypes.html#memoryview) type.

From the `Channel` docstring:

> A Channel is meant to behave like a socket, and has an API that should be indistinguishable from the Python socket API.

```
Traceback (most recent call last):
  ...
  File ".../osutils.py", line 2181, in send_all
    sent = sock.send(view[sent_total:sent_total+MAX_SOCKET_CHUNK])
  File ".../paramiko/channel.py", line 715, in send
    return self._send(s, m)
  File ".../paramiko/channel.py", line 1080, in _send
    m.add_string(s[:size])
  File ".../paramiko/message.py", line 285, in add_string
    s = asbytes(s)
  File ".../paramiko/common.py", line 170, in asbytes
    raise Exception('Unknown type')
Exception: Unknown type
```

A native socket raises `TypeError` for send with non string or buffer types.

**Comment by bitprophet** [comment]
Rolling into the final PR. Thanks!
