### ISSUE TITLE
Paramiko is not sending proper output to cisco device

### ISSUE THREAD

**Issue by metro1234** [paramiko/paramiko#978]
I am using below script in that

 remote_conn.send("ping 10.10.10.1 vrf us-dc source 10.10.10.249\n")
is sending as

ping 10.10.10.1 vrf us-dc source 10.10.10.2$

I am wondering why it is sending $ at the end .

For other few IP's it is printing properly. example

ping 10.10.10.1 vrf us-dc source 10.10.100.255

I just printed before sending

 ping 172.16.34.48 vrf us-dc source 10.10.10.249 # printed before remote_conn.send so its properly printing.  

when i used with remote_conn.send it is not sending proper output

 ping 172.16.34.32 vrf us-dc source 10.10.10.2$

I dont know what I did wrong in below script or it might be bug

Note for security reasons. I have not pasted here actual used IP's

        
    import paramiko
    import re
    import time
    hostname = "10.10.10.1"
    net_username = ""
    net_password = ""
    remote_conn_pre = paramiko.SSHClient()
    remote_conn_pre.set_missing_host_key_policy(
        paramiko.AutoAddPolicy())
    remote_conn_pre.connect(hostname, username=net_username, 
    password=net_password,look_for_keys=False, allow_agent=False)
    remote_conn = remote_conn_pre.invoke_shell()
    buff = ''
    while not buff.endswith('#'):
        resp = remote_conn.recv(9999)
        buff += resp
        print(resp)
     remote_conn.send("\n")
     buff = ''
     while not buff.endswith('#'):
         resp = remote_conn.recv(9999)
         buff += resp
         print(resp)
        remote_conn.send("ping 10.10.10.1 vrf us-dc source 10.10.10.249\n")
        time.sleep(2)
         buff = ''
      while not buff.endswith('#'):
         resp = remote_conn.recv(9999)
         buff += resp
         print resp
      remote_conn.send("ping 10.10.10.10\n")
      buff = ''
      while not   buff.endswith('#'):
         resp = remote_conn.recv(9999)
         buff += resp
         print resp

**Comment by ploxiln** [comment]
The reason why you see the command strings you send, is that the remote shell echoes them back (which you get in "resp" and print). I think the `$` is not being sent, it's a reaction of the remote shell, after it has read "... source 10.10.10.2". Why, I don't know, sorry ...

**Comment by metro1234** [comment]
I used my code without using 


     buff = ''
     while not   buff.endswith('#'):
         resp = remote_conn.recv(9999)
         buff += resp
         print resp
Same error

**Comment by bitprophet** [comment]
Wondering if perhaps the $ is the remote end attempting to "display" the newline (thinking e.g. how $ is regex-speak for end-of-line). Wild guess though.

Paramiko definitely should not be injecting literal $ symbols in what you `send()`, so it's likely this is something to do with the remote end in some fashion. Assuming by "For other few IP's it is printing properly" you mean that the same Paramiko code is getting different results for different remote ends, that would definitely hint that this is the issue, to me.

Going to close as no-action but discussion remains open.
