### ISSUE TITLE
Add support for AES-GCM symmetric crypto

### ISSUE THREAD

**Issue by alex** [paramiko/paramiko#982]
https://tools.ietf.org/html/rfc5647 is the notional spec, but OpenSSH does a variant which I'm having trouble finding the spec for.

**Comment by ibygrave** [comment]
This is all I could find specifying the openssh gcm vendor mechanisms for AES GCM:

[PROTOCOL diff](https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/PROTOCOL.diff?r1=1.19&r2=1.20)

**Comment by bitprophet** [comment]
Paramiko 3.5 is now out with this feature.
