### ISSUE TITLE
unhashable type: 'Ed25519Key'

### ISSUE THREAD

**Issue by oprypin** [paramiko/paramiko#993]
Hi, after updating to Paramiko 2.2.0 some code that previously worked is now broken. I have minimized the reproduction code. Of course, I might have overly minimized it (removed the actual SSH key) because it can't work as is.

```python
import paramiko

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.load_system_host_keys()
ssh.connect('127.0.0.1')
```
```
Traceback (most recent call last):
  File "bis.py", line 6, in <module>
    ssh.connect('127.0.0.1')
  File "/tmp/paramiko/paramiko/client.py", line 377, in connect
    if our_key != server_key:
  File "/tmp/paramiko/paramiko/pkey.py", line 113, in __eq__
    return hash(self) == hash(other)
TypeError: unhashable type: 'Ed25519Key'
```

*known_hosts* (fake redacted hash):
```
127.0.0.1 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEZfTeFXnDtkVUYDWL0HiAL8+dXRpxuNpoNsYW1SkpRQ
```

Bisect:
> b395444062e82953d417a4da9157667c2e05d758 is the first bad commit

In older versions this code produces the following error:
```
paramiko.ssh_exception.SSHException: No authentication methods available
```

**Comment by ploxiln** [comment]
`ssh-ed25519` host keys in `known_hosts` were ignored before. It seems that actually comparing them was not tested.

Thanks for the report!

**Comment by oprypin** [comment]
OK, thanks for checking this!
In accordance to what you're saying, it appears that my *known_hosts* had 2 types of entries and one of them was ignored while the other one worked; now the first one causes a failure.

**Comment by bitprophet** [comment]
That sounds like the most likely explanation, yup; beforehand, I believe the known_hosts parsing would simply have skipped the ed25519 keys entirely; now it's able to create `PKey` instances for them, but they lacked hashability and thus failed the comparison step that came afterwards.

**Comment by bitprophet** [comment]
Let's close this as "closed by PR" and will note in changelog that this was the report, when we merge. Thanks!
