### ISSUE TITLE
Paramiko Socket closed Error

### ISSUE THREAD

**Issue by metro1234** [paramiko/paramiko#998]
Hi,

I am using Paramiko 2.1.2 and Python 2.7.

Some times it is failing with below error

Traceback (most recent call last):
  File "qa_check.py", line 202, in <module>
    ucs_sp.eth_check(ucs_username, ucs_password, ucsm_ip, tn,  TTN, sp_name, screen_shot, ts_file, error_log)
  File "/usr/lib/python2.7/site-packages/qaautomation/ucs_sp.py", line 491, in eth_check
    eth_get(ucs_username, ucs_password, login_ip, TTN, sp_name,  screen_shot,  ts_file, eth_num)
  File "/usr/lib/python2.7/site-packages/qaautomation/ucs_sp.py", line 349, in eth_get
    remote_conn.send("\n")
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 767, in send
    return self._send(s, m)
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 1134, in _send
    raise socket.error('Socket is closed')
socket.error: Socket is closed
Thanks

**Comment by prateekgarg** [comment]
Was there any resolution to this issue? I am facing the same problem and don't know what the root cause might be.

**Comment by BofengDuke** [comment]
I am facing the same problem when I send 'su root\n' to server.I have set timeout to 60 seconds, but it was not run.
The log:

2017-12-07 10:42:07 INFO    : Receive banner success.

'Command: su root\n'
2017-12-07 10:42:07 ERROR   :  Error: Socket is closed
Traceback (most recent call last):
  File "/root/python_src/2017/AssetHunter/assethunter/module/get_asset.py", line 142, in run
    hostinfo_handle(host[0],host[1],host[2],host[3],host[4],host[5])
  File "/root/python_src/2017/AssetHunter/assethunter/module/get_asset.py", line 108, in hostinfo_handle
    client = MySSHClient(host,port,username,password,rootpasswd)
  File "/root/python_src/2017/AssetHunter/assethunter/module/ssh_client.py", line 48, in __init__
    self._su_root()
  File "/root/python_src/2017/AssetHunter/assethunter/module/ssh_client.py", line 106, in _su_root
    success = self.change_user('root',self.rootpasswd)
  File "/root/python_src/2017/AssetHunter/assethunter/module/ssh_client.py", line 93, in change_user
    self.exec_command('su '+username,password,sleeptime=1)
  File "/root/python_src/2017/AssetHunter/assethunter/module/ssh_client.py", line 178, in exec_command
    self.send(command,sleeptime)
  File "/root/python_src/2017/AssetHunter/assethunter/module/ssh_client.py", line 122, in send
    self.channel.send(command + "\n")
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 785, in send
    return self._send(s, m)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/channel.py", line 1169, in _send
    raise socket.error('Socket is closed')
OSError: Socket is closed

**Comment by RahulShah9191** [comment]
I am also facing the same issue. Any workaround?

**Comment by mariabogatinovici** [comment]
Same problem, any workaround?

**Comment by kk348** [comment]
i am also facing same problem any though/comment to fix it?

**Comment by plwalsh** [comment]
Also facing this issue intermittently. My program makes an ssh connection, executes a command, and exits. Occasionally, after running the program several times in a row successfully, my next attempt will result in this error. Nothing about the program changes between runs; they are identical runs. I'm not sure the best way to debug this since it happens seemingly randomly.

I'm using Paramiko 2.7.1 and Python 3.6.9. Here is my version of the traceback:

```
Traceback (most recent call last):
  File "/home/code/<personal_file>.py", line 187, in patch
    stdin.write('%s\n' % password)
  File "/usr/python/env3/lib/python3.6/site-packages/paramiko/file.py", line 405, in write
    self._write_all(data)
  File "/usr/python/env3/lib/python3.6/site-packages/paramiko/file.py", line 522, in _write_all
    count = self._write(data)
  File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 1364, in _write
    self.channel.sendall(data)
  File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 846, in sendall
    sent = self.send(s)
  File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 801, in send
    return self._send(s, m)
  File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 1198, in _send
    raise socket.error("Socket is closed")
OSError: Socket is closed
```

This occurs after executing a `sudo` command and attempting to supply the password to the `stdin` object returned by `exec_command()`.

**Comment by zachliu** [comment]
@plwalsh having exactly the same issue, are you able to find out what caused the issue?

**Comment by plwalsh** [comment]
@zachliu unfortunately I have not found out the cause. I haven't seen it happen again in the recent weeks, but I also haven't been running the program as many times in quick succession as I was previously.

**Comment by zachliu** [comment]
perhaps the sftp server has some glitches?

**Comment by mariabogatinovici** [comment]
Hei, me too i haven’t seen again the problem... I have it on a script
running cli commands. I put the timeout bigger and now it s fine.

În mie., 24 iun. 2020 la 19:26 Zach Liu <notifications@github.com> a scris:

**Comment by barryjburns** [comment]
Offhand guess: the port is likely in TIME_WAIT status, aka 2MSL. Opening

**Comment by barryjburns** [comment]
Offhand guess: the port is likely in TIME_WAIT status, aka 2MSL. This is
specified in RFC 793 as being 2 minutes (Windows machines default to this
but can be modified via registry).

Opening the socket with SO_LINGER set to 0 abolishes this timeout. And the
practice of delaying invocations of the script to beat this only leads to
unnecessary delays or race conditions.

Hope this helps!

Luv, pluggo <3

**Comment by Denis-Alexeev** [comment]
Suffering the same issue from time to time. Flaky problem.

**Comment by dragoninsky** [comment]
> Also facing this issue intermittently. My program makes an ssh connection, executes a command, and exits. Occasionally, after running the program several times in a row successfully, my next attempt will result in this error. Nothing about the program changes between runs; they are identical runs. I'm not sure the best way to debug this since it happens seemingly randomly.
> 
> I'm using Paramiko 2.7.1 and Python 3.6.9. Here is my version of the traceback:
> 
> ```
> Traceback (most recent call last):
>   File "/home/code/<personal_file>.py", line 187, in patch
>     stdin.write('%s\n' % password)
>   File "/usr/python/env3/lib/python3.6/site-packages/paramiko/file.py", line 405, in write
>     self._write_all(data)
>   File "/usr/python/env3/lib/python3.6/site-packages/paramiko/file.py", line 522, in _write_all
>     count = self._write(data)
>   File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 1364, in _write
>     self.channel.sendall(data)
>   File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 846, in sendall
>     sent = self.send(s)
>   File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 801, in send
>     return self._send(s, m)
>   File "/usr/python/env3/lib/python3.6/site-packages/paramiko/channel.py", line 1198, in _send
>     raise socket.error("Socket is closed")
> OSError: Socket is closed
> ```
> 
> This occurs after executing a `sudo` command and attempting to supply the password to the `stdin` object returned by `exec_command()`.

Any new findings?   I have met the same problem on one customer environment.

**Comment by pjyan** [comment]
Is there any solution?

**Comment by morhook** [comment]
I had a similar problem to the OP (in my case the system uploaded many files in the middle of a process, so the `SFTP` was closed while the process was generating second file, etc), and started fixing problems by retrying twice each file like this:
```
try:
  sftp_tuple.sftp.put(chunk_filename, f"{self.dest_folder}/{chunk_filename_tmp}")
except socket.error as e:
  print("*** Exception trying to upload file: %s: %s" % (e.__class__, e))
  traceback.print_exc()
  print("Retrying by reconnecting and uploading to SFTP")
  sftp_tuple = sftp_connection_and_transport(self.sftp_conn_name)
  sftp_tuple.sftp.put(chunk_filename, f"{self.dest_folder}/{chunk_filename_tmp}")
```

**Comment by massibronto** [comment]
Hello, I just stumbled across this issue because I had the same problem.

Instead of 
```
stdin.write(pass_variable)
stdin.flush()
```

try the following:
```
# Create paramiko object
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
# Connect the object
client.connect(
            hostname=server, port=port, username=username, password=password
        )
# Open invoked shell
shell = client.invoke_shell()
# Go into superuser mode
sentbytes = shell.send('sudo su\n')
if sentbytes  > 0:
    print("Sudo command sent")
# Give username
sentbytes  = shell.send(user_variable)
if sentbytes  > 0:
    print("Username inserted")
```
On my side, this seems to work. When sentbytes returns anything, it means the shell has accepted the input.
